### ISSUE TITLE
Files window>rightclick >properties  wrong timestamp 

### ISSUE THREAD

**Issue by xal88** [thonny/thonny#1003]
looks like you using wrong startdate for embedded devices, when calculating modified date/time
Missing 30 years ( 1.1.1970 instead of 1.1.2000 )
Example from ESP8266
![grafik](https://user-images.githubusercontent.com/53332864/69484615-9ee3b480-0e35-11ea-8c3f-cb250fd6345f.png)

**Comment by aivarannamaa** [comment]
I'm just displaying what `os.stat()` reports for this file.

Are you saying it reports number of seconds from 1.1.2000 instead of Unix epoch time? Is there some documentation saying this?

**Comment by aivarannamaa** [comment]
Found it already: https://docs.micropython.org/en/latest/library/utime.html
Thank you for bringing my attention to this! 

You're welcome to add more information if you have it!

**Comment by xal88** [comment]
Hi,

dont have any more specific information than utime.html.

Thanks for the great program !

regards

Xal

 
 

Gesendet: Sonntag, 24. November 2019 um 15:41 Uhr
Von: "Aivar Annamaa" <notifications@github.com>
An: thonny/thonny <thonny@noreply.github.com>
Cc: Alf <xal@quantentunnel.de>, Author <author@noreply.github.com>
Betreff: Re: [thonny/thonny] Files window>rightclick >properties wrong timestamp (#1003)


Found it already: https://docs.micropython.org/en/latest/library/utime.html
Thank you for bringing my attention to this!

You're welcome to add more information if you have it!
