### ISSUE TITLE
Warn against running from a library directory

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1021]
See #1017

**Comment by hatlesshacker** [comment]
By "Library directories" are you referring to only the directory where the python packages are installed, or are there additional locations where Thonny should not be run?

**Comment by aivarannamaa** [comment]
I  mostly meant `site-packages` and `dist-packages` directories.

**Comment by hatlesshacker** [comment]
Ok, I'll try to submit a pull request

**Comment by aivarannamaa** [comment]
I guess the nice location for this warning would be "Assistant" view. If you agree, then see `thonny.plugins.misc_analyzers` for an example. I suppose the new warning can also go into same module.

**Comment by hatlesshacker** [comment]
See #1063 @aivarannamaa

**Comment by aivarannamaa** [comment]
This is actually non-issue.
