### ISSUE TITLE
if there are 2 python variables pointing to same complex number, would they be having the same id

### ISSUE THREAD

**Issue by muralee7it** [thonny/thonny#1022]
a=10+3j
b=10+3j
print(a is b) -->"thonny" saysthis is true
![thonny issue](https://user-images.githubusercontent.com/58697928/70448460-6810ce00-1ac6-11ea-8711-4f2eca5463b9.PNG)

print(id(a))
print(id(b))

**Comment by aivarannamaa** [comment]
This is not really specific to Thonny, but yes, two variables point to same object iff their `id`-s are equal.
