### ISSUE TITLE
Autocomplete error 3.2.4 MicroPython

### ISSUE THREAD

**Issue by cmdrdeliver** [thonny/thonny#1023]
Thonny 3.2.4 using Interpreter MicroPython 8266

Steps to reproduce:
- New File
- Save (junk.py)
- Type "imp" hit tab

Result: 
Dialog "Autocomplete Error" : "Autocomplete Error"

**Comment by aivarannamaa** [comment]
I can't reproduce this in Windows with Thonny 3.2.4.

Did you save the file locally or to the board?

Can you please post the stacktrace?

**Comment by cmdrdeliver** [comment]
Aivar,
I've attached a video showing process.  Not getting a stack trace.  Only occurs when the board is connected.  Had to zip video for supported attachment types.

Mike
[ThonnyAutocomplete3.2.4..mp4.zip](https://github.com/thonny/thonny/files/3968198/ThonnyAutocomplete3.2.4.mp4.zip)

**Comment by aivarannamaa** [comment]
Thanks! I was able to reproduce this in Linux
