### ISSUE TITLE
Draggable scrollbar minimum size in Raspberry Pi editor

### ISSUE THREAD

**Issue by mgagneur** [thonny/thonny#1027]
As the number of lines in my script grow ( Raspberry Pi) the vertical scrollbar draggable element becomes smaller and smaller until it's so small I cannot click on it and drag. I also have Thonny installed on my WIN 10 machine and its scrollbar draggable element is always the same size independent of script length.

Is there a way to set a minimum draggable element size so the vertical scrollbar is functional in all cases on the Raspberry Pi?

Thanks,

**Comment by aivarannamaa** [comment]
How many lines do you have in your script?
