### ISSUE TITLE
F5 not working - Lenovo T440/windows 8.1 Pro

### ISSUE THREAD

**Issue by matasejem** [thonny/thonny#1033]
Hi, when i want to run script by hitting F5 i has the following behavior 

1) Fn+F5 -> it does Save as 
2) F5 -> it lowers screen brigthness
3) Ctrl+ F5 -> it lowers screen brigthness

Pls advise how to resolve this issue. Thanks

**Comment by MatrixMike** [comment]
So is there an answer somewhere? I get the same issue : F5 lowers screen brightness -> my goal was to run the debugger as per https://thonny.org/    where Ctrl+F5 is suggested
