### ISSUE TITLE
Autocomple not working with pygame

### ISSUE THREAD

**Issue by bendavis78** [thonny/thonny#1038]
I'm not sure if this is an issue with Thonny or with some other component. When I type `pygame.display.`<kbd>Tab</kbd> I expect to see `.set_mode()` as an option, but this is what I get: 

![image](https://user-images.githubusercontent.com/324392/71527875-db765600-28a2-11ea-897c-76f4ae5d749e.png)

**Comment by aivarannamaa** [comment]
It looks like the autocompletion library (jedi) can't handle some tricks Pygame plays in this module. Here is a similar issue: https://github.com/davidhalter/jedi-vim/issues/146

It may get fixed in newer Jedi or Pygame versions, but most likely I can't do anything about it in Thonny.

**Comment by bendavis78** [comment]
Indeed this looks like an issue pygame needs to fix. It looks like it was fixed once before, but pygame had a major overhaul recently and the bug regressed. This issue seems to be the one to follow in case anyone else is interested: https://github.com/pygame/pygame/issues/1267

**Comment by Seraphli** [comment]
I searched for this issue on Google and found out the reason might be the `try-except` expression in the `pygame/__init__.py`.
