### ISSUE TITLE
files window does not show .gitignore 

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#1039]
in thonny 3.2.5 no hidden or dot-files are shown
.gitignore would be helpfull

**Comment by aivarannamaa** [comment]
I guess I need to add a configuration option for showing/hiding hidden files.

**Comment by kr-g** [comment]
in thonny 3.3.14 
this is available via file tab -> small (hamburger) menu -> show / hide hidden files

via file browser context menu could be an option too... (?)

**Comment by aivarannamaa** [comment]
Thanks for the suggestion! I agree it would be better like this.
