### ISSUE TITLE
support for open other file types 

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#1040]
editor does not open MD files

**Comment by aivarannamaa** [comment]
I can definitely allow editing MD files as simple text. Not sure if it makes sense to implement extra support (eg. syntax highlighting)

**Comment by kr-g** [comment]
syntax highlighting is not required.

**Comment by kr-g** [comment]
just tested it in thonny 3.3.0 
1. with right-click> open in thonny,
2. with right-click> configure 
tested both
:-)
