### ISSUE TITLE
save all button

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#1041]
save all button for saving all changed files, or in combination with F5 / Run, would be nice

**Comment by aivarannamaa** [comment]
I'd prefer not adding another button, but saving all files on F5 looks like a good idea!

**Comment by hatlesshacker** [comment]
I can do that. Mind if I submit a pull request?

**Comment by aivarannamaa** [comment]
@hatlesshacker, you are welcome!

**Comment by hatlesshacker** [comment]
see #1053, not #1052.
I had previously set Shift-Q as the Save-all keyboard shortcut, which closes the window on some systems.
