### ISSUE TITLE
Autocomplete for imported library

### ISSUE THREAD

**Issue by chezhj** [thonny/thonny#1046]
Hi.
Happy new year :-)
New to python I'm using Thonny to make a script that handles images based on exif information.
I am able to read the tags with the exifread package. https://github.com/ianare/exif-py
I've noticed the autocomplete (Jedi?) is not able to autocomplete object from the exifread package.

Is this an Jedi issue, or is something wrong with the package?
I found you can add packages to Jedi (https://stackoverflow.com/questions/46480237/is-jedi-able-to-autocomplete-custom-libraries). Can I add something similar to the Thonny config?

Just wondering..
Regards
ChezHJ
PS: just figured out I can try this in the console :-)
>>> import jedi
>>> jedi.Script('import exifread').goto_definitions()
[<Definition full_name='exifread', description='module exifread'>]
Now in the console autocomplete works!

**Comment by aivarannamaa** [comment]
Sorry for late reply!

Thonny doesn't have any means for tweaking jedi's work
