### ISSUE TITLE
Remove [BETA] from Greek Language

### ISSUE THREAD

**Issue by niplessa** [thonny/thonny#1051]
I have reviewed my Thonny translation and corrected some mistakes. It now is error - free (as possible). 
Please I would like the [Beta] Tag to be removed.

Thank you.

**Comment by aivarannamaa** [comment]
Will do. Thanks for your work!

**Comment by Hermann12** [comment]
I saw the German version is a mix-up English/German. How can I help? I am native German.

**Comment by aivarannamaa** [comment]
@Hermann12 , you are welcome to join translators here: https://poeditor.com/join/project/Gh188fdYH6 and add German translations to missing items

**Comment by Hermann12** [comment]
Done. See my post on German Update. Maybe this item is still closed sorry. I have tested as described. It doesn^t show all translations. In the POEditor I cańt find e.g. Run the script into the .mo file. Are not all menu labels for translation? How can I send you the .mo and .po files? Thanks.

**Comment by aivarannamaa** [comment]
@Hermann12, I made new issue for German: #1054

**Comment by Hermann12** [comment]
Updated and tested the .mo and .po. Looks good now in German. Please review my comments, if possible. I have also realized, that the item under Tools  | "Manage packages ..." and "Manage Plug-ins" are very similar. maybe this can be handeled by a filer or tab in the same Pop Up Window? Only a idea.

How do you get the translated file? I can't upload the files on github folder.
