### ISSUE TITLE
thonny-xxl-3.2.6 artifact contains `__pycache__` folder

### ISSUE THREAD

**Issue by stdedos** [thonny/thonny#1060]
I am not sure if it's a bug, or a feature:

I was trying to determine the differences of the released artifacts. I opened up the artifacts, and started comparing names and sizes.

I noticed that in `thonny\lib\python3.7`, there is an extra `__pycache__` folder

**Comment by aivarannamaa** [comment]
Thank you for noticing this! I'll add required cleaning commands to the build script

**Comment by thijstriemstra** [comment]
@aivarannamaa you should specify it in the manifest instead (or also), see https://github.com/rm-hull/luma.core/blob/master/MANIFEST.in for an example.

**Comment by aivarannamaa** [comment]
If I'm not mistaken, MANIFEST.in controls the list of files present in [tarball and wheel](https://pypi.org/project/thonny/#files). I suppose `__pycache__` is not present there

**Comment by thijstriemstra** [comment]
right, the place where @stdedos found the files.

**Comment by aivarannamaa** [comment]
Seems to be fixed in 3.3b2
