### ISSUE TITLE
Cant save files on ESP

### ISSUE THREAD

**Issue by KoljaL** [thonny/thonny#1068]
Hey there
I installed Thonny on W10 (with python already installed before).
Running Code works, but if i try to save a file on the ESP8266, tis error returns:
![Thonny save on device error](https://user-images.githubusercontent.com/55852574/72912567-1e113e00-3d3c-11ea-992d-c4c000c17a20.png)

**Comment by aivarannamaa** [comment]
Can you see the file list (View => Files)?

**Comment by KoljaL** [comment]
No, I couldn't.
But after reinstalling Thonny and Python it works both.
Sorry for the circumstances and thanks a lot for tis IDE :-)
