### ISSUE TITLE
Option to expand the view of lists, tuples, etc from top to bottom.

### ISSUE THREAD

**Issue by kawamaha** [thonny/thonny#1071]
Currently Thonny shows them only from left to right, which means they can't be completely examined if there are too many values.
![thonny_VS_variables](https://user-images.githubusercontent.com/60267630/73108407-890b7200-3f00-11ea-9103-a6794d707b1f.png)

**Comment by aivarannamaa** [comment]
Did you try Object inspector (View => Object inspector)?

**Comment by kawamaha** [comment]
Now I did, sorry.
Thank You!
