### ISSUE TITLE
debug does not work

### ISSUE THREAD

**Issue by datensysteme** [thonny/thonny#1077]
I would like to work with thonny. Editor looks good, Run works, but debug does not work. Klick on the bug symbol is like running the script, nothing is changing, no possible single step etc...

Dont know what to do

Walter

**Comment by aivarannamaa** [comment]
Do you have breakpoints in any of your open files?

**Comment by datensysteme** [comment]
Hi,

I tried everything concerning debug…

I want to debug only one single .py-file, which can be debugged within Pycharm, that means, nothing is wrong.

When I use debug in thonny, it starts with a yellow line at the beginning (that is ok) and steps through the code but dont step into funktions

Greetings
Walter

Von: Aivar Annamaa <notifications@github.com>
Gesendet: Samstag, 25. Jänner 2020 20:18
An: thonny/thonny <thonny@noreply.github.com>
Cc: Traunmüller KG - datensysteme.at <office@datensysteme.at>; Author <author@noreply.github.com>
Betreff: Re: [thonny/thonny] debug does not work (#1077)


Do you have breakpoints in any of your open files?

**Comment by aivarannamaa** [comment]
Are the functions defined in your own script or in a library? Thonny does not step into library functions, but this can be changed in Tools => Options => Run & Debug.

**Comment by datensysteme** [comment]
Functions are within my own script.

Structur is:
import…

import…

…

def start_script():


scan_input()

def scan_input():

def convert_to_jpg(parameter):

def delete_images():

…

def start():


start_script()

start()


This script loops like the “Server”-part of a client-server-software. I can debug it in pycharm, but in thonny I cannot enter into e.g. scan_input function.


Von: Aivar Annamaa <notifications@github.com>
Gesendet: Sonntag, 26. Jänner 2020 06:24
An: thonny/thonny <thonny@noreply.github.com>
Cc: Traunmüller KG - datensysteme.at <office@datensysteme.at>; Author <author@noreply.github.com>
Betreff: Re: [thonny/thonny] debug does not work (#1077)


Are the functions defined in your own script or in a library? Thonny does not step into library functions, but this can be changed in Tools => Options => Run & Debug.

**Comment by aivarannamaa** [comment]
Can you post the whole script? (eg. by attaching the script in GitHub, so that the indentation doesn't get lost)

**Comment by datensysteme** [comment]
Difficult…

You cannot run the script itself, there are a lot of configuration and installation around to use this system.

You might be used to make a complete testing environment.


Von: Aivar Annamaa <notifications@github.com>
Gesendet: Sonntag, 26. Jänner 2020 20:25
An: thonny/thonny <thonny@noreply.github.com>
Cc: Traunmüller KG - datensysteme.at <office@datensysteme.at>; Author <author@noreply.github.com>
Betreff: Re: [thonny/thonny] debug does not work (#1077)


Can you post the whole script? (eg. by attaching the script in GitHub, so that the indentation doesn't get lost)

**Comment by aivarannamaa** [comment]
Did you use breakpoints for debugging it?

**Comment by datensysteme** [comment]
Yes, I tried breakpoints, but thonny does not reakt on them, although the scrpt runs properly and does 100% what it should do

Greetings
Walter

Von: Aivar Annamaa <notifications@github.com>
Gesendet: Donnerstag, 27. Februar 2020 09:13
An: thonny/thonny <thonny@noreply.github.com>
Cc: Traunmüller KG - datensysteme.at <office@datensysteme.at>; Author <author@noreply.github.com>
Betreff: Re: [thonny/thonny] debug does not work (#1077)


Did you use breakpoints for debugging it?

**Comment by aivarannamaa** [comment]
Sorry, I can't start solving the problem if I can't reproduce it.

**Comment by RionDsouza** [comment]
Hello I just installed Thonny. I have to same problem. Trying to debug a Python Script but the debug options just seems to run the script. Can you help?

**Comment by aivarannamaa** [comment]
@RionDsouza, do you have your code in named or unnamed editor? I can't reproduce this problem when the code is in named (i.e. saved) editor, but I did notice debugger doesn't work properly if the editor is not saved (https://github.com/thonny/thonny/issues/2415).
