### ISSUE TITLE
Venv interpreter soft link gets resolved in macOS

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1079]

**Comment by kalhauge** [comment]
I second this :).  Alternatively, It would be nice with a choose virtual environment button instead of only being able to create a new one.

**Comment by aivarannamaa** [comment]
Thanks for your suggestion! Still, I'd prefer to keep virtual env selection as it is now -- by selecting its interpreter (not its root directory). Unfortunately macOS file chooser always resolves symbolic links, so it doesn't allow selecting venv interpreter. 

I added a warning about this and made it possible to bypass the file selection dialog and enter the interpreter path directly. This inconvenience appears only once per externally created venv -- next time you can already choose it from the list.

I also took the opportunity to refactor the UI of the configuration page.

**Comment by aivarannamaa** [comment]
Please reopen the issue, if you don't agree with my solution!

**Comment by kalhauge** [comment]
Works really well! Great job :)
