### ISSUE TITLE
Request: 'self' as keyword alike

### ISSUE THREAD

**Issue by bohbtone** [thonny/thonny#1080]
Would be nice, if word "self" is considered as keyword or so, and be colored in editor.
While it is not actually python keyword, it could be optionally added to special words because of heavy use. List of this kind of custom words in the -ini file perhaps.

**Comment by aivarannamaa** [comment]
Thanks for the suggestion!

It looks like VSCode and Pycharm display it as a keyword, so I guess it doesn't do any harm if I display it as keyword in Thonny as well.
