### ISSUE TITLE
Request: use the unix port of micropython as a backend

### ISSUE THREAD

**Issue by fstengel** [thonny/thonny#1081]
The title says all :-) Would it be possible to have the unix port of micropython as a (bundled) backend? That way, one would not be forced to plug a microcontroller in order to test micropython code

**Comment by aivarannamaa** [comment]
At the moment it would require quite a lot of extra code, because the Unix port doesn't support raw REPL, which Thonny relies on.

**Comment by fstengel** [comment]
I remember seeing that thread. Basically, I was hoping things had moved on that front. I was making the request more out of lazyness than anything else :-)

**Comment by aivarannamaa** [comment]
Done
