### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by fireday2** [thonny/thonny#1082]
Hi.
Win 10. 
first i install python 3.8.1. then i install Thonny 3.2.6 (14MB)
and get error. i reinstalled - the same. then i deleted python 3.8.1 and the PATH variable. 
After that i install thonny-xxl-3.2.6 and i got error too
and i change option-interpreter to "the same interpreter which runs Thonny (default)"
_when i installed first time i selected Russion lenguage. after error i change it to engl. it didn't help_
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 544, in _start_runner
>     self._runner.start()
>   File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 102, in start
>     self.restart_backend(False, True)
>   File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 557, in restart_backend
>     self._proxy = backend_class(clean)
>   File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 1232, in __init__
>     super().__init__(clean, get_interpreter_for_subprocess())
>   File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 1062, in __init__
>     super().__init__(clean, executable)
>   File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 771, in __init__
>     self._start_background_process(clean=clean)
>   File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 836, in _start_background_process
>     **extra_params
>   File "C:\Program Files (x86)\Thonny\lib\subprocess.py", line 800, in __init__
>     restore_signals, start_new_session)
>   File "C:\Program Files (x86)\Thonny\lib\subprocess.py", line 1207, in _execute_child
>     startupinfo)
> OSError: [WinError 87] Параметр задан неверно

**Comment by aivarannamaa** [comment]
Thank you for the report! I'll deal with this under #1000
