### ISSUE TITLE
Error when "file" "open" micropython, list is empty !!!

### ISSUE THREAD

**Issue by ChristianFrench** [thonny/thonny#1098]
![image](https://user-images.githubusercontent.com/60058707/75244467-21c93200-57cc-11ea-8fc7-bfcf36a3498d.png)

**Comment by ChristianFrench** [comment]
addendum:
 Appears when your stop/restart with the menu in "run" and you acces twice to "file" "open" ...

**Comment by aivarannamaa** [comment]
Why did you close the issue? Were you able to fix this somehow?

**Comment by ChristianFrench** [comment]
No, I must have done something wrong.

It happens after working with Thonny. Quite difficult to determine the context, following "CTRL x"? Following other actions?
No certainty except on the instability and the obligation to stop and restart Thonny.
