### ISSUE TITLE
thonny themes

### ISSUE THREAD

**Issue by PsychoLeo** [thonny/thonny#1100]
Hello everyone, 

I've been working on Thonny for about 2 years (school and mostly by myself and I've started getting lazy with the white shell. I've looked up how to change the shell and it says to go in Tools --> options --> font and themes. The issue is I don't have the themes and fonts, I only have Editor/ Font/ General/ Interpreter. Could someone please help me ?

PS : if this is important, I work on Ubuntu 18.04
Thank you very much,
Leo

**Comment by aivarannamaa** [comment]
Which Thonny version do you have?

**Comment by PsychoLeo** [comment]
I'm looking at the file in which it is installed and I believe it is "jedi_0.11.1"

**Comment by aivarannamaa** [comment]
Please open "Help" menu and select "About". Which version is displayed there?

Did you install Thonny with `apt` or with separately downloaded installer?

Do you see any errors when you run `thonny` from Terminal?

**Comment by PsychoLeo** [comment]
I have the 2.1.16 version of thonny

**Comment by PsychoLeo** [comment]
And it just says there is no such file in the terminal when I type in './thonny'

**Comment by aivarannamaa** [comment]
This is really old version and themes are not implemented in it. Visit https://thonny.org for latest versions.

**Comment by PsychoLeo** [comment]
ok thank you very much for your help !!
