### ISSUE TITLE
dbdown

### ISSUE THREAD

**Issue by dbdown** [thonny/thonny#1101]
Raspberry Pi, Thonny editor, Python 3.7
I've tried this in several editors with the same result.
Can anyone please help?

```
class Cats:
    def init(self, name):
        self.name = name

c = Cats("Suzy")        Error: Too many arguments for "Cats"
print(c)
```

**Comment by aivarannamaa** [comment]
The name for constructor should be `__init__`, not `init`.

BTW. This is not Thonny-specific question. In the future please post similar problems to other forums.
