### ISSUE TITLE
Harden MicroPython communication

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1103]

**Comment by AltoRetrato** [comment]
As always, thank you for your great work, Aivar! 😄 

I've been eagerly waiting for this, so I uninstalled v. 3.2.7 from my Windows PC and I tried [running from source](https://github.com/thonny/thonny/wiki/Running-from-the-source). Unfortunately I'm having this issue when I run it with Python 3.7.0:

`C:\Python37\python.exe: Error while finding module specification for 'thonny.__main__' (ImportError: cannot import name 'get_workbench' from 'thonny' (C:\Users\Ric\AppData\Local\Programs\Thonny\thonny\__init__.py))`

Any idea of the cause and/or solution?

Thanks!

**Comment by aivarannamaa** [comment]
Did you set PYTHONPATH environment variable?

You could also try overwriting the contents of `C:\Users\Ric\AppData\Local\Programs\Thonny\thonny` with newer version and start thonny from the shortcut

**Comment by AltoRetrato** [comment]
> Did you set PYTHONPATH environment variable?

Yes, I followed the instructions in [running from source](https://github.com/thonny/thonny/wiki/Running-from-the-source):

1. Downloaded https://github.com/thonny/thonny/archive/master.zip
2. Unpacked in `C:\Users\Ric\AppData\Local\Programs\Thonny`
3. Installed requirements: `pip3 install -r requirements.txt`
4. `set PYTHONPATH=C:\Users\Ric\AppData\Local\Programs\Thonny`
5. Run with `python3 -m thonny`

I also tried to `set PYTHONPATH=C:\Users\Ric\AppData\Local\Programs\Thonny\thonny`, but got the same result.

I guess I can't run Thonny from source on Windows... right?

> You could also try overwriting the contents of `C:\Users\Ric\AppData\Local\Programs\Thonny\thonny` with newer version and start thonny from the shortcut

First I downloaded `https://github.com/thonny/thonny/releases/download/v3.2.7/thonny-3.2.7-windows-portable.zip` and run the `thonny.exe`, which opened the editor just fine.

I closed the editor and copied the contents of folder `thonny` from the source (master.zip) to `C:\Users\Ric\AppData\Local\Programs\Thonny\Lib\site-packages\thonny`. Now, when I run `thonny.exe` I get the same error as before, but in a GUI dialog:

![Clipboard01](https://user-images.githubusercontent.com/22997468/91888221-4feb6b00-ec62-11ea-8e02-a1cc554675c9.png)

**Comment by AltoRetrato** [comment]
BTW, I tested the same code from https://github.com/thonny/thonny/archive/master.zip on Ubuntu, and the editor opened without any issues (but I had no time to test anything beyond that)...

**Comment by aivarannamaa** [comment]
I hope to publish first beta together with binaries tonight

**Comment by aivarannamaa** [comment]
@AltoRetrato , I have published Windows binaries for beta of the new version: https://github.com/thonny/thonny/releases/tag/v3.3.0b2.

It turned out the code indeed had a problem which was not apparent to me in Linux and Python 3.8
