### ISSUE TITLE
High resolution screen adaptation problem

### ISSUE THREAD

**Issue by Mark24Code** [thonny/thonny#1105]
ICONS don't fit well on high-resolution screens.

My Devices:
XPS 13-9350

Screen:
1920X1080

SystemSetting：
Scale： 150%

![屏幕截图(8)](https://user-images.githubusercontent.com/7592004/75945399-19ac7900-5ed5-11ea-8a5b-2909505f28ea.png)

**Comment by aivarannamaa** [comment]
Related to #1096 1113
