### ISSUE TITLE
Keypad movement keys don't work.

### ISSUE THREAD

**Issue by eliotb** [thonny/thonny#1106]
My laptop doesn't have dedicated Home, End, PgUp, PgDn keys - these are all on the numberpad.   As far as I can tell, Thonny doesn't recognise these keys.

They generate events prefixed with "KP_"  eg. KP_Prior.

(OS=Debian 10)

I'd be happy to implement and test a patch if someone would give me a tip about how mapping these keys should be done in Thonny.

**Comment by aivarannamaa** [comment]
TODO: Test in macOS and more Linuxes
