### ISSUE TITLE
thonny do something wrong?

### ISSUE THREAD

**Issue by GodLoveCoder** [thonny/thonny#1120]
![capture](https://user-images.githubusercontent.com/52340898/77026202-15508780-69ce-11ea-8ca5-6a410a07cdea.PNG)
why the al is not empty?
thonny must be do something wrong.

**Comment by aivarannamaa** [comment]
Thonny does not run your programs, Python does.

I'm not sure, but I assume Python's list iterator works by indices, ie. at first loop iteration it takes the element from index 0, next time from 1 and so on until the end of the list. I recommend printing out the list in the beginning of each iteration and counting the number of iterations -- this helps to see why it is working like this.

**Comment by GodLoveCoder** [comment]
alright,thanks for you tell me why python did that.
but how i to finish some work like that?

**Comment by aivarannamaa** [comment]
> but how i to finish some work like that?

What do you mean?

**Comment by GodLoveCoder** [comment]
thanks again, I remembered I can use copy module.
