### ISSUE TITLE
Buenos dias.

### ISSUE THREAD

**Issue by Madrigal88** [thonny/thonny#1123]
Te felicito por el Thonny IDE. Soy Docente de una escuela secundaria y enseño programación en Python, desde que vi este IDE me gustó porque tiene lo esencial para aquellas personas que están comenzando a programar. Me gustaría hacerte una donación económica, no será mucho pero espero sirva para el proyecto.

**Comment by aivarannamaa** [comment]
Thank you for your offer! I may set up donations in the future, but at the moment I get support from my employer. Your kind words are rewarding enough for me :)
