### ISSUE TITLE
Bad encoding when reading a csv file.

### ISSUE THREAD

**Issue by yalajules** [thonny/thonny#1128]
Hi,
When my lecturecsv.py program reads Préhistoire_Informatique.csv (encoding : UTF-8-BOM), bad print out.
When my lecturecsv.py program reads Préhistoire_Informatique1.csv (encoding : Ansi), it's good.

Where can we define the encoding in Thonny ?
Tx

[Préhistoire_Informatique.xlsx](https://github.com/thonny/thonny/files/4376921/Prehistoire_Informatique.xlsx)

#lecturecsv.py
#coding: utf-8
import csv
fichier=open('Préhistoire_Informatique.csv')
lecteur=list(csv.reader(fichier))
print(lecteur)
fichier.close()

**Comment by aivarannamaa** [comment]
This is not really a Thonny specific question, but here you go: https://docs.python.org/3/library/functions.html#open
