### ISSUE TITLE
"Unable to find a shell" from Tools/Open system shell

### ISSUE THREAD

**Issue by pebauer68** [thonny/thonny#1129]
Hello,
This seems to happen when x-terminal-emulator is configured as e.g. /usr/bin/terminator
bug seems to be in: def _get_linux_terminal_command():
Workaround on Ubuntu 18.04: use other x-terminal - you need to configure with 
`$sudo update-alternatives --config x-terminal-emulator`

example output:

```
  Selection    Path                             Priority   Status
------------------------------------------------------------
  0            /usr/bin/terminator               50        auto mode
  1            /usr/bin/gnome-terminal.wrapper   40        manual mode
  2            /usr/bin/koi8rxterm               20        manual mode
  3            /usr/bin/lxterm                   30        manual mode
* 4            /usr/bin/mate-terminal.wrapper    30        manual mode
  5            /usr/bin/terminator               50        manual mode
  6            /usr/bin/uxterm                   20        manual mode
  7            /usr/bin/xterm                    20        manual mode

```

**Comment by aivarannamaa** [comment]
Thank you for the report! I think I got it sorted out (tested also in Ubuntu 18.04). The fix will be in next release but you can also try applying the diff to your `thonny.terminal` module.

**Comment by aivarannamaa** [comment]
Sorry, the first commit missed one line.

**Comment by pebauer68** [comment]
Thank you, I really like Thonny -  because of good documentation in the source code.
