### ISSUE TITLE
Open a file from shell saved in Micropython device

### ISSUE THREAD

**Issue by TDB43** [thonny/thonny#1137]
It's possible open a file from shell?

Not  the file that is in the editor content (%Run -c $EDITOR_CONTENT)

Something like "%Run example.py" or "example.py" don't work..

**Comment by aivarannamaa** [comment]
Nope, this is not possible. Do you want to run a file without loading it in the editor first? Why?

**Comment by ttempe** [comment]
how different would that be from:
>>> import example
?

**Comment by aivarannamaa** [comment]
> how different would that be from `import example` ?

The main difference would be when you want to
