### ISSUE TITLE
Cant launch Thonny

### ISSUE THREAD

**Issue by AndrewBreyen** [thonny/thonny#1139]
After installing Thonny v 3.2.7, I get this error on launch:

![image](https://user-images.githubusercontent.com/7895581/78569754-ab1b4d80-77e9-11ea-9e6e-6c645741f5cf.png)

**Comment by aivarannamaa** [comment]
Seems to be related to #1126. Please check whether you can also fix it by rebooting!

**Comment by AndrewBreyen** [comment]
works now :P
