### ISSUE TITLE
Mistake in "File properties" 

### ISSUE THREAD

**Issue by TDB43** [thonny/thonny#1142]
When you ask the File properties in the field "Modified" it allways tell one hour more that it should be.

https://www.esploradores.com/wp-content/uploads/2020/04/Thonny_os_stat.jpg

**Comment by aivarannamaa** [comment]
Thank you for the report!

Did you manually set the real-time clock on your device? Thonny doesn't do it yet: #1004

**Comment by aivarannamaa** [comment]
Fixed under #1004
