### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ftriulzi** [thonny/thonny#1155]
except keyboardIterrupt:
    print ("\nCtrl-C pressed. Cleaning up and exiting...")
finally:
    np[0] = (0, 0, 0): #Turn off NeoPixel
    np.write()

After debug file
   print ("\nCtrl-C pressed. Cleaning up and exiting...")
finally:
    np[0] = (0, 0, 0): #Turn off NeoPixel
    np.write()
             ^
SyntaxError: EOF while scanning triple-quoted string literal

**Comment by aivarannamaa** [comment]
I don't understand. Did you get syntax error while trying to run this code? It seems to be incomplete code. Please post your whole code and mark it as code so that the indentation doesn't get lost (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
