### ISSUE TITLE
Dialogs may end up behind the main window

### ISSUE THREAD

**Issue by retrosnob** [thonny/thonny#1158]
Where can I find error logs?

**Comment by aivarannamaa** [comment]
The logs folder can be opened with "Tools => Open Thonny data folder". NB! The logs are currently overwritten each time you start Thonny.

I've seen that sometimes a dialog (eg. About) can end up behind the main window and this can effectively lock the UI. You can try whether you can reorder the windows by Alt-Tabbing to and away from Thonny.

**Comment by retrosnob** [comment]
That was the problem. It was appearing off-screen. Thank you.

**Comment by aivarannamaa** [comment]
Good to know! I'll leave it open, because this problem still needs a solution.

**Comment by aivarannamaa** [comment]
Somwhat related to #1133

**Comment by aivarannamaa** [comment]
Need to take #840 and https://bugs.python.org/issue34927 into account.
