### ISSUE TITLE
thonny startup error: no module named "pwd"

### ISSUE THREAD

**Issue by clarissa12193** [thonny/thonny#1159]
<img width="230" alt="k" src="https://user-images.githubusercontent.com/63707448/79314143-6c387680-7f12-11ea-9b71-403ae0738a67.PNG">

when i try to open thonny on my windows 10 laptop, i get the thonny startup error: no module named "pwd"
please help asap

**Comment by aivarannamaa** [comment]
Seems to be related to #1146

Please check whether restarting your computer cures this problem!

**Comment by clarissa12193** [comment]
it worked, thank you so much for the fast reply

**Comment by aivarannamaa** [comment]
Do you have any ideas what could have caused this situation (of `USERNAME` environment variable not being set)? Were you using a recently created account or did you install or update something before this problem occurred?

**Comment by clarissa12193** [comment]
No idea what had caused it, but I had bought a new laptop and installed
thonny on it, at first I could only open it if I ran the app as
administrator, but I couldn't open programs I'd have already made on thonny
as this error occurred, then I restarted it and now it opens as soon as I
click the app.
Thank you for your help
