### ISSUE TITLE
Connect to several ESP boards via WebREPL (MicroPython)

### ISSUE THREAD

**Issue by LDmicroGitHub** [thonny/thonny#1162]
There is possible to connect to several ESP  boards via REPL through serial ports (for example COM7, COM8, etc.)  
Every board is configured WebREPL on different IP addresses (for example '192.168.4.7', '192.168.4.8').
(Not default WebREPL IP address192.168.4.1)  
In this case, we need a text field to edit the target WebREPL IP address.  
![image](https://user-images.githubusercontent.com/48811061/79507011-a5bad000-803f-11ea-8fe0-b6ff0d6ab5ab.png)

**Comment by aivarannamaa** [comment]
When you select <WebREPL> the IP address and password entry boxes should appear below port combobox. You may need to resize the options window.

It looks like you don't have the newest Thonny version, because I've disabled WebREPL support for now because it is too unreliable.

**Comment by LDmicroGitHub** [comment]
I try to use latest master branche with 
    def allow_webrepl(self):
        return True

**Comment by LDmicroGitHub** [comment]
![image](https://user-images.githubusercontent.com/48811061/79554335-9622a200-80a6-11ea-9621-46b70bb4794f.png)  
After restarting the backend, an error occurs.  
AttributeError: 'function' object has no attribute 'put'  
![image](https://user-images.githubusercontent.com/48811061/79554627-016c7400-80a7-11ea-8999-a3ecac84ffb4.png)

**Comment by aivarannamaa** [comment]
I guess this commit is to be blamed: https://github.com/thonny/thonny/commit/9cc673373e3579c7374f3203d5dd9885132ece96#diff-bb25fa39cfa7e96bf57039b80f3ee8b4

You should revert the changes in webrepl_connection.py

**Comment by aivarannamaa** [comment]
... or better, just get rid of extra `.put`  on line 90

**Comment by LDmicroGitHub** [comment]
After the changes in webrepl_connection.py  
in line 90 and 180  
>          #self._make_output_available.put(data, block=False)  
>          self._read_queue.put(data, block=False)  
and in line 180  
>          #self._make_output_available(data)  
>          self._read_queue.put(data)  
I get a message in the Shell window:  
> WebREPL connected  
> raw REPL; CTRL-B to exit  
>  
MicroPython device files are displayed in their window. It's Ok.

But when I press the 'Run current script' button I get an error
[micropython-backend.log](https://github.com/thonny/thonny/files/4492572/micropython-backend.log)

**Comment by aivarannamaa** [comment]
I'll deal with it after I've finished with MicroPython communication refactoring (#1103).

**Comment by LDmicroGitHub** [comment]
Thanks. I am ready to test a pre-release.

**Comment by aivarannamaa** [comment]
Great! I'll let you know.

**Comment by laukejas** [comment]
Hey, @aivarannamaa , what is the status on WebREPL support? I have tried enabling it in the esp\__init__.py and micropython\__init__.py, but it returns an error `ModuleNotFoundError: No module named 'websockets'`. Is there a workaround or something? We need WebREPL support real bad.

**Comment by aivarannamaa** [comment]
@laukejas  Please try https://github.com/thonny/thonny/releases/tag/v3.3.0b2 There are some known problems, though.

If you run from source in a virtualenv, then you need to `pip install websockets`, because this is not a hard dependency.

**Comment by laukejas** [comment]
@aivarannamaa Thank you, this is looking really great so far. What import issues are there to keep an eye out for?

**Comment by aivarannamaa** [comment]
> What import issues are there to keep an eye out for?

No import issues (if you install `websockets`), but WebREPL has problems with long inputs (https://github.com/micropython/micropython/issues/2497). I have planned a work-around, but haven't got to it yet.

**Comment by aivarannamaa** [comment]
WebREPL support will be much better in the next beta
