### ISSUE TITLE
matplotlib

### ISSUE THREAD

**Issue by ThibaudTC** [thonny/thonny#1163]
when trying to use the matplotlib I get the following errors:

>>> %Run vb9.12matplotlib.py 1

Simulated Traceback (most recent call last):
  File "F:\Python\vb9.12matplotlib.py", line 1, in <module>
    import matplotlib
  File "P:\Thonny\lib\site-packages\thonny\backend.py", line 285, in _custom_import
    module = self._original_import(*args, **kw)
  File "C:\Users\Dagelijks\AppData\Roaming\Python\Python38\site-packages\matplotlib\__init__.py", line 207, in <module>
    _check_versions()
  File "C:\Users\Dagelijks\AppData\Roaming\Python\Python38\site-packages\matplotlib\__init__.py", line 192, in _check_versions
    from . import ft2font
ImportError: cannot import name 'ft2font' from partially initialized module 'matplotlib' (most likely due to a circular import) (C:\Users\Dagelijks\AppData\Roaming\Python\Python38\site-packages\matplotlib\__init__.py)

    Python exception:
        ImportError: cannot import name 'ft2font' from partially initialized module 'matplotlib' (most likely due to a circular import) (C:\Users\Dagelijks\AppData\Roaming\Python\Python38\site-packages\matplotlib\__init__.py)
        
    This exception indicates that a certain object could not
    be imported from a module or package. Most often, this is
    because the name of the object is not spelled correctly.
    
    Likely cause based on the information given by Python:
        The object that could not be imported is 'ft2font'.
        The module or package where it was 
        expected to be found is 'matplotlib'.
        
    Execution stopped on line 1 of file 'F:\Python\vb9.12matplotlib.py'.
    
    -->1: import matplotlib

    Exception raised on line 192 of file 'FRIENDLY:\matplotlib\__init__.py'.
    
       190:     # Quickfix to ensure Microsoft Visual C++ redistributable
       191:     # DLLs are loaded before importing kiwisolver
    -->192:     from . import ft2font

**Comment by aivarannamaa** [comment]
Sorry, I've somehow missed this issue.

Do you still have this problem?
