### ISSUE TITLE
pandas not working even though installed

### ISSUE THREAD

**Issue by clarissa12193** [thonny/thonny#1168]
when i try to run a pandas program, the following comes in the terminal
<img width="661" alt="Capture" src="https://user-images.githubusercontent.com/63707448/79726431-d595fc00-82fb-11ea-8b45-2830c3791b46.PNG">

this is the program
<img width="319" alt="2" src="https://user-images.githubusercontent.com/63707448/79726481-ee061680-82fb-11ea-8480-d75fb2d69f4d.PNG">

**Comment by aivarannamaa** [comment]
It seems to be problem with Windows build of latest Pandas: https://github.com/pandas-dev/pandas/issues/32857

As a workaround you should try going back to version 1.0.1. If you installed pandas with Thonny's pip GUI, then use "..." button for this:

![image](https://user-images.githubusercontent.com/1802/79761210-cfb70f80-8329-11ea-9442-b64689cad36e.png)

**Comment by clarissa12193** [comment]
it worked, thank you so much for your help
