### ISSUE TITLE
Best way to install packages remotely/silently

### ISSUE THREAD

**Issue by AndrewBreyen** [thonny/thonny#1172]
Hello,

I am struggling to figure out a way to remotely deploy Thonny and packages. 

I was able to get the EXE to install fine remotely/silently by using this CMD script:
`"\path\to\thonny-3.2.7.exe" /VERYSILENT /NORESTART /DIR="C:\Program Files\Thonny" /LOG="C:\logs\thonny3.2.7.log"`

but now the requesting professor wants packages to be installed. The professor wants these packages installed:
![Thonny_packages_on_my_campus_laptop](https://user-images.githubusercontent.com/7895581/80116458-9f4ebb80-854b-11ea-9fde-ab1c9526dc00.JPG)

Our network/user setup does not allow persistence in the user APPDATA directory, and we have tried having users manually install packages. This is tedious for our users, and doesn't work. 

Thonny must be installed to C:/Program Files in order to stay on the machines. 

Last year I believe there was a customize.py file that allowed us (very jankily) to point Thonny to the users network drive, where the user had previously copied the .thonny directory. This however appears to be missing from thonny v3. 

How should packages be remotely deployed silently, and across hundreds of computers?

Any suggestions?

Thank you.

**Comment by AndrewBreyen** [comment]
@aivarannamaa Any chance this is supported?

**Comment by Ivoz** [comment]
Have you exhausted all options in https://github.com/thonny/thonny/wiki/DeploymentOptions ?

It might also be possible with https://github.com/thonny/thonny/issues/755 method

**Comment by aivarannamaa** [comment]
@AndrewBreyen, as Ivoz said, there may be answer in https://github.com/thonny/thonny/wiki/DeploymentOptions

Let me know again if you get stuck.
