### ISSUE TITLE
Is there any way to add a grid inside my new created rectangle patch?

### ISSUE THREAD

**Issue by kosmas13** [thonny/thonny#1177]
import matplotlib.pyplot as plt
from PyQt5.QtGui import QPainter , QPen, QBrush, QPaintDevice
from PyQt5.QtWidgets import QMessageBox
import shapely.geometry
import pyproj

from PyQt5.QtCore import Qt

from matplotlib.patches import Rectangle
from matplotlib.patches import Circle
from caseswan import *
from app import *

class events:

    def __init__(self, cv, App):

        self.canvas = cv
        self.axes = self.canvas.axes
        self.App = App
        
        

        

        self.rect = Rectangle((0,0),1,1)
        self.point = (0,0)

        self.axes.add_patch(self.rect)

        self.x0 = None
        self.y0 = None
        self.x1 = None
        self.y1 = None

    def ComputationalDomain(self,x0,x1,y0,y1):

        self.x0 = x0
        self.y0 = y0
        self.x1 = x1
        self.y1 = y1
        

        self.rect.set_width(self.x1 - self.x0)
        self.rect.set_height(self.y1 - self.y0)
        self.rect.set_xy((self.x0, self.y0))
        self.rect.set_color('orange')
        self.axes.figure.canvas.draw()
        self.App.swancase.setComputationalDomain(self.x0,self.x1,self.y0,self.y1)

    def target_point(self,target_point):

        self.target_point = target_point

    def draw_point(self,x,y):
        painter = QtGui.QPainter()
        painter.drawPoint(x, y)
        painter.end()

        
        
    
    def connect_on_press(self):

        self.cidpress = self.axes.figure.canvas.mpl_connect('button_press_event', self.on_presstarget)
        
        

    def connect_on_release(self):

        self.cidpress = self.axes.figure.canvas.mpl_connect('button_press_event', self.on_press)
        self.cidrelease = self.axes.figure.canvas.mpl_connect('button_release_event', self.on_release)
    

    
        
    def on_presstarget(self, event):

        #QMessageBox.information(self, 'Information', 'Click to select target point')

        self.target_lon,self.target_lat = self.canvas.m(event.xdata,event.ydata, inverse=True)
        self.target_point = self.target_lon, self.target_lat

        self.App.swancase.setTarget_point(self.target_point)
    
        
        # self.swancase.settarget_point(self.target_point)
       
        #self.rect.set_xy((self.x0, self.y0))
        #self.rect.set_color('orange')

        #self.axes.figure.canvas.draw()
    def on_press(self, event):

        self.x0,self.y0 = self.canvas.m(event.xdata,event.ydata, inverse=True)
        

    def on_release(self, event):

        #QMessageBox.information(self, 'Information', 'Click to draw Computational Domain')
        self.x1 = event.xdata
        self.y1 = event.ydata
        #print(self.x1, self.y1)
        self.rect.set_width(self.x1 - self.x0)
        self.rect.set_height(self.y1 - self.y0)
        self.rect.set_xy((self.x0, self.y0))
        self.rect.set_color('orange')
        self.rect.set_edgecolor('black')
        

        
        

        
   

        
        
        
        self.axes.figure.canvas.draw()
        #self.App.ev.ComputationalDomain(self.x0,self.x1,self.y0,self.y1)
        #self.App.ui.doubleSpinBox_2.valueChanged(self.x0)

**Comment by aivarannamaa** [comment]
This is not a Thonny-specific issue. You should ask it elsewhere.
