### ISSUE TITLE
 Module Not Found

### ISSUE THREAD

**Issue by jkirkman41** [thonny/thonny#1181]
I am getting ModuleNotFoundError: "**No module named  'mysql'** " when I run the following code in Thonny 3.2.7.  

**Import mysql.connector**

The same command will run in Git Bash
.
Also, the command **"Import Tkinter as tk**" will run in both invoriments.

I do not understand why both of the statements don't fail or both run.

Thanks,
John

**Comment by aivarannamaa** [comment]
`Tkinter` is Python 2 module, Thonny uses Python 3.

If you run your script from command line it may be run with different Python interpreter, depending on how did you install Thonny.

What does `which python3` (when on Unix) or `where python` (on Windows) say when you run it on command line?
