### ISSUE TITLE
  from phue import Bridge ModuleNotFoundError: No module named 'phue'

### ISSUE THREAD

**Issue by soydepr** [thonny/thonny#1189]
someone help with this error 

have following script 
#!/usr/bin/python

from phue import Bridge
import logging
logging.basicConfig()

b = Bridge('192.168.1.3')

b.connect()

and get error above 

pi@lucas:~ $ echo $PYTHONPATH
/home/pi

pi@lucas:~ $ sudo pip install phue
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: phue in /usr/local/lib/python2.7/dist-packages (1.1)

**Comment by aivarannamaa** [comment]
Thonny uses Python 3, you installed it for Python 2. Try using `pip3` instead of `pip`.

**Comment by soydepr** [comment]
thank you above solved the issue
