### ISSUE TITLE
Poor UX with 3.2.7

### ISSUE THREAD

**Issue by pulkin** [thonny/thonny#1192]
1. You moved file upload as a boot/main script into a third-level menu. Previously I was able to just use a shortcut. This is a deal breaker for me: if I would be interested in such an obfuscated navigation I would just install KDE or even Windows.

2. Once you go all through that and press "Save" button a confirmation window should pop out. Not mentioning a strong attack of nostalgia from 90s, this dialog box does not acquire focus on my system Gnome / Fedora 32. I.e. it remains behind the file dialog which is ridiculous.

**Comment by pulkin** [comment]
Ah I think I got it: I am supposed to save the thing on the device and then to use Ctrl-s to upload it again and to never see those layers of dialog boxes. This partially invalidates p. 1.

**Comment by aivarannamaa** [comment]
Dialogs occasionally getting hidden behind other windows is a problem of Tk. I'll see whether I can find a workaround.

BTW. Issues written with pejorative tone automatically get lower priority. I believe it's the same with any open-source project.

**Comment by pulkin** [comment]
I am so sorry for that. Please do not consider it personal.

**Comment by aivarannamaa** [comment]
More ideas here: https://github.com/raspberrypi/thonny-pico/issues/12
