### ISSUE TITLE
Controlling the I beam (typing cursor) with Ctrl/Shift and arrow keys

### ISSUE THREAD

**Issue by CarterSnich** [thonny/thonny#1198]
I have this habit of using the keys (Ctrl and/or Shift combined with arrow keys), to move the typing cursor accurately instead of grabbing the mouse. The feature was most likely available on most IDEs and text editors. I hope that you can also add this feature.

**Comment by aivarannamaa** [comment]
Which OS are you using? I'm currently on Windows and Ctrl/Shift+arrow movements work fine. 
Are you using numpad arrows?
