### ISSUE TITLE
Changing editor-tab removes keyboard focus from editor

### ISSUE THREAD

**Issue by lurch** [thonny/thonny#1210]
If I have two or more files open, and I'm working on both of them, then when I click on the tab to switch which file I'm working on, the "tab button" then has keyboard focus, and I have to click back into the editor-window to give keyboard-focus back to the editor before I can carry on typing.

This is slightly annoying and it would be nice if I could switch between tabs, with the keyboard focus always being given back to the editor-part of the window.

**Comment by aivarannamaa** [comment]
I guess for now I can make it work as you describe it. I need to come back to this once I start preparing Thonny for blind users.

**Comment by aivarannamaa** [comment]
Fixed under #2737
