### ISSUE TITLE
Installed requests module not found

### ISSUE THREAD

**Issue by charlesglorioso** [thonny/thonny#1212]
Thonny 3.2.7 running on windows 10, interpreter set for ESP32 micropython.
I installed requests module using  manage plug-ins. 

![request installed](https://user-images.githubusercontent.com/8483659/82832740-d7119180-9e70-11ea-807d-7db3c8c274dc.jpg)

yet interpreter command line cannot find the module.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'requests'

Inserting "import requests" in main, and running it produces same result.
exact behavior occurs in two WIndows 10 machines.

**Comment by aivarannamaa** [comment]
I answered in the forum
