### ISSUE TITLE
Not able to run Plotly

### ISSUE THREAD

**Issue by urvir9** [thonny/thonny#1214]
Hello,

I am trying to create a treemap using below code but its not working and rather opens a web page with address http://127.0.0.1:53492/

Can you please advise

Code is like below:

import pandas as pd
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
df = pd.read_csv("C:\\Users\\xxx\\OneDrive\\Desktop\\connections.csv")
import datetime
def fun(date):    
  return datetime.datetime.strptime(date, "%d %b %Y").strftime("%Y-%m-%d")

df["Connected On"] = df["Connected On"].apply(fun)
df=df.sort_values(by="Connected On")
print(df.head(5))
df.reset_index(inplace=True)
df.reset_index(inplace=True)
df.drop(columns="index",inplace=True)
df.rename(columns={"level_0":"number"},inplace=True)
connections_line = px.line(df, x="Connected On", y="number", title='My Connections')
df.drop(columns='Email Address',inplace=True)
df=df.dropna()
Companies = df['Company']
df['My Network']= 'My Network'
position_tree_map = px.treemap(df, path=['My Network', 'Position', 'Company'], width=1000, height=1000)
position_tree_map.show()

**Comment by aivarannamaa** [comment]
Sorry, I somehow missed your issue. I'm afraid this is not Thonny-specific and I hope you already found a solution.
