### ISSUE TITLE
Images are missing on the InstallingPackages page on the wiki

### ISSUE THREAD

**Issue by martinohanlon** [thonny/thonny#1221]
It looks like the image links are broken.

![image](https://user-images.githubusercontent.com/2329501/83749286-5fefb080-a65b-11ea-83e8-cd1b70f7b256.png)

**Comment by aivarannamaa** [comment]
Thanks for noticing and reporting!

These were old pictures from the time when Thonny was living in Bitbucket and I forgot to update the links when moving to GitHub. Now the Bitbucket repo is deleted and the pictures are gone.

I just removed these for now.
