### ISSUE TITLE
A not important issue.

### ISSUE THREAD

**Issue by xcre** [thonny/thonny#1223]
could you please add my name to `CREDITS.rst`? I translated thonny to smplified chinese.😁

**Comment by aivarannamaa** [comment]
Sure! Do you want to be listed just as `xcre`?

**Comment by xcre** [comment]
No.My name is `丁向阳(Ding-XiangYang)`
thanks😁

**Comment by aivarannamaa** [comment]
Done: https://github.com/thonny/thonny/blob/master/CREDITS.rst
Thanks for your work!
