### ISSUE TITLE
Strange random behaviour of Thonny

### ISSUE THREAD

**Issue by pyforever** [thonny/thonny#1225]
Hi,
I found sometimes, after making a change to code and saved it to both pc and ESP8266, running the code executes the previous saved version of it (without the last changes).
I'm running Thonny 3.2.7 on Win 10 with 32GB RAM.
The strangest thing (to me) is that if I reload the code both from pc and board they HAVE the changes I made.
The problem persists after some resets and sometimes restarting Thonny IDE. Then suddenly, after one more board reset,  the correct code is executed and then at every board reset it never fails anymore.

**Comment by aivarannamaa** [comment]
Are you saving your code to main.py or another module which is imported from main.py?

**Comment by pyforever** [comment]
> 
> 
> Are you saving your code to main.py or another module which is imported from main.py?

I see this behaviour in both cases: changing code in main or/and in my imported module.

**Comment by aivarannamaa** [comment]
Currently I don't have any ideas of what may cause this. Please let me know if you find a way to reliably reproduce this!

**Comment by pyforever** [comment]
Ok, I'll try to write a small reproducible code so you can see this.

**Comment by aivarannamaa** [comment]
Please try Thonny 3.3 and reopen if you still see this behavior
