### ISSUE TITLE
%Run -c $EDITOR_CONTENT

### ISSUE THREAD

**Issue by MCASWA** [thonny/thonny#1227]
I'm new to programming. I am using Thonny 3.2.7. with micropython 1.12, on esp32. When I run my program there are no coding errors but I get this message in the shell; %Run -c $EDITOR_CONTENT. I cannot find the meaning of it. Also %lsdevice, %run, %cat return- unknown command.  Is there a Thonny users guide?

**Comment by aivarannamaa** [comment]
`%Run -c $EDITOR_CONTENT` is Thonny's internal command which also is meant to give indication in the Shell of what just happened. They are not documented currently and and some of them have been (and will be) changed between Thonny versions.

**Comment by pixster** [comment]
This was USELESS!!  How do you fix this!?!?
