### ISSUE TITLE
Thonny stops executing a program when executing a new one

### ISSUE THREAD

**Issue by acastan** [thonny/thonny#1242]
Thank you for your work and excuse my poor English,

I was practicing sockets with my students with Thonny. We left executing the server socket program, then we execute the client socket program, but we realized that when we execute the client , Thonny automatically stops the server.

You can check this behavior with more simple programs:
```
    import time
    while True:
        print('hello')
        time.sleep(1)
```

And then try to execute at the same time:
 ```
   import time
    while True:
        print('bye')
        time.sleep(1)
```

When you execute one program, the other one stops
Saludos des de Barcelona

Àlex

**Comment by aivarannamaa** [comment]
That's how Thonny works - current programm gets killed on new run.

Use 'Run -> run in terminal' to launch a paralleel process
