### ISSUE TITLE
from random import shuffle function

### ISSUE THREAD

**Issue by barakat99** [thonny/thonny#1249]
Bonjour je n'arrive pas à utiliser la fonction from random import shuffle pour remuer les élements de ma liste en fait dans l'interpréteur shell je fais comme çeci:
>>> from random import shuffle
>>> l1 = [1, 2, 3, 4]
mais rien se met en désordre.
Veuillez me résoudre ce problème s'il vous plaît.
Cordialement.
Mostafa Barakat.

**Comment by barakat99** [comment]
Bonjour je n'arrive pas à utiliser la fonction from random import shuffle pour remuer les élements de ma liste en fait dans l'interpréteur shell je fais comme çeci:

            from random import shuffle
            l1 = [1, 2, 3, 4]
            mais rien se met en désordre.
            Veuillez me résoudre ce problème s'il vous plaît.
            Cordialement.
            Mostafa Barakat.

**Comment by aivarannamaa** [comment]
Sorry, I don't speak French, but it looks like your question is not related to Thonny, so I recommend you ask it in a general Python forum.
