### ISSUE TITLE
Overwrite dialog opens in background

### ISSUE THREAD

**Issue by wnelis** [thonny/thonny#1250]
Using Thonny 3.2.7 on Linux Mint 19.3. When saving a modified  file back to an ESP8266, the "Overwrite" dialog opens but is invisible as it is hidden by the "Save to MicroPython device" dialog. This seems similar to issue #1133.

**Comment by aivarannamaa** [comment]
Thank you for reporting it!

Does it happen occasionally or always?

**Comment by wnelis** [comment]
It happened every time I saved a modified file on the ESP8266, thus far. Thus it basically happens always.

**Comment by aivarannamaa** [comment]
Duplicate of #1158
