### ISSUE TITLE
Device options gone

### ISSUE THREAD

**Issue by robertovega20** [thonny/thonny#1253]
when select Device, "Where are all the commands? message. Next this dialog appears but i can not upload my files to esp32
![image](https://user-images.githubusercontent.com/44219817/86126020-3c295a00-baa3-11ea-8cce-d7be4c7abc32.png)

**Comment by aivarannamaa** [comment]
In this version MicroPython features have been reorganized: https://github.com/thonny/thonny/wiki/MicroPython

**Comment by aivarannamaa** [comment]
In the next version I'll make the menu item open this help instead

**Comment by aivarannamaa** [comment]
I decided to get rid of this menu altogether.
