### ISSUE TITLE
Typo in pop-up menu 'File is gone'

### ISSUE THREAD

**Issue by wnelis** [thonny/thonny#1258]
Using Thonny 3.2.7 on Linux Mint 19.3, file main.py on the Linux laptop was renamed. Thonny presented a pop-up window with title "File is gone". The text in this window is "Looks like '/.../main.py' was deleted or moved outside if the editor." This line seems to contain a typo, "if" in stead of "of".

**Comment by ankith26** [comment]
I have put a PR to fix this issue.

**Comment by aivarannamaa** [comment]
Thanks! Closed in #1260
