### ISSUE TITLE
Save File icon bug?

### ISSUE THREAD

**Issue by DancingGuy** [thonny/thonny#1283]
This is a very minor issue but it still may confuse users.

When I left mouse click on the blue disk icon in the left upper corner to save changes, the asterisk on the file name goes away to suggest changes saved. Hitting F5 indeed shows the changes saved. However, the blue icon does NOT dim or change color. Clicking on the icon a 2nd time dims it. 

Using CNTL-S both saves the changes AND dims the icon on one try.

I was able to reproduce this behavior on two different Windows 10 computers.

I am running Thonny version 3.2.7

Thanks!

**Comment by aivarannamaa** [comment]
Thank you for the report! I can reproduce this. The fix will be in the next release.
