### ISSUE TITLE
thonny's file explore cant find some folders.

### ISSUE THREAD

**Issue by croku** [thonny/thonny#1288]
same as the title...see the picure below
![55ca7303dcb86e522a60064edcc4247](https://user-images.githubusercontent.com/52340898/88469424-179a9380-cf24-11ea-81be-3097db59c3c3.png)

**Comment by aivarannamaa** [comment]
It has different icon -- what kind of directory is this? Can you please post the output of following Python script when executed on your machine:

```
import os
print("listdir:", os.listdir("D:\\"))

path = "D:\\<insert the name of the problematic directory here>"
print("stat:", os.stat(path))

from ctypes import windll
print("atts:", windll.kernel32.GetFileAttributesW(path))
```

**Comment by croku** [comment]
just a normal directory with a special icon？？？I dont know.
![4c906cf28809114205c3ba6e3f6df2a](https://user-images.githubusercontent.com/52340898/88737713-a77e4e80-d16b-11ea-99fb-184ddaecb44e.png)

**Comment by aivarannamaa** [comment]
GetFileAttributesW shows that this is marked as a system directory. Thonny currently hides system and hidden files and directories. In a future version I'll add an option to show also these files #1292.

If you don't want this directory to be treated as a system directory, then open system command prompt and enter

```
attrib "D:\<name of your dir>" -s
```

**Comment by croku** [comment]
that directory isnt a system directory.it is create by a software and I copied it from another disk.
