### ISSUE TITLE
Cut a release featuring python 3.8?

### ISSUE THREAD

**Issue by Ivoz** [thonny/thonny#1289]
Wondering if it's possible to put something out there, 3.8 itself has had a few patches now. the `f"{var=}"` syntax is pretty cool new feature to be able to integrate.

What do you delineate between 3.2.x and 3.3?

**Comment by aivarannamaa** [comment]
I plan to release Thonny 3.3 still with Python 3.7, skip Python 3.8 and release Thonny 4.0 later with Python 3.9. There is a related discussion here: https://groups.google.com/g/thonny/c/3CyQLNZfzx8

**Comment by Ivoz** [comment]
I am really hanging out for walrus operator and f"{var=}" printing in Thonny! I guess I can set up an external python for now.
