### ISSUE TITLE
Problem with full screen and split screen views of thonny.

### ISSUE THREAD

**Issue by dulatemesgen** [thonny/thonny#1293]
Anytime I have thonny open side by side (on my macOs) with any other application in split screen mode, or in full screen, it doesn't really let me exit out of that view without having too completely closing thonny and restarting it.

**Comment by aivarannamaa** [comment]
Sorry for the late reply. I hope I can fix this with new Tk version used in Thonny 3.3

**Comment by aivarannamaa** [comment]
Fixed by upgrading to Tk 8.6.11. 

Experimental build available in https://github.com/thonny/thonny/releases/download/v3.3.5/thonny-3.3.5_alt.pkg (bundled with Universal 2 binaries of Python 3.9.2)
