### ISSUE TITLE
small toolbar icons

### ISSUE THREAD

**Issue by aryan-abdolahi** [thonny/thonny#1295]
hello, I'm using Thonny version 3.2.4 on windows 10 but I have a problem with the small icons on its toolbar. maybe that is because of resolution or sth else. please fix it.

**Comment by aivarannamaa** [comment]
Please try "Tools => Options => General => UI scaling factor => 2.0". Does this look better?

**Comment by aryan-abdolahi** [comment]
Yes it worked thank you so much!!!!

 
 
  On Sat, 8 Aug 2020 at 22:53, Aivar Annamaa<notifications@github.com> wrote:   


Please try "Tools => Options => General => UI scaling factor => 2.0". Does this look better?
