### ISSUE TITLE
Python code results in error just in Thonny only

### ISSUE THREAD

**Issue by vkmps** [thonny/thonny#1317]
```
>>> def foo(name, /, **kwds):
    return 'name' in kwds

  File "<pyshell>", line 1
    def foo(name, /, **kwds):
                  ^
SyntaxError: invalid syntax
>>> 
```

Where as this code returns no error in Python

**Comment by aivarannamaa** [comment]
I assume you are using Thonny with Python 3.7.

Positional-only arguments syntax requires Python 3.8 or later.

**Comment by vkmps** [comment]
Thank you very much. I realised this after I changed the compiler to Python 3.8. Thanks once again for the reply.
