### ISSUE TITLE
At the prompt

### ISSUE THREAD

**Issue by luizcarluz** [thonny/thonny#1318]
When I paste a a little piece of code at prompt
PROBLEM WITH THONNY'S BACK-END:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1245, in execute_source
    statements = compile(ast.Module(body=root.body[:-1]), filename, "exec")
TypeError: required field "type_ignores" missing from Module,

by the way, excellent job

**Comment by aivarannamaa** [comment]
Does your printed code contain serveral statements? And do you have Python 3.8 as a backend? If yes, then is fixed under #1138 and will be released in Thonny 3.3
