### ISSUE TITLE
Thonny plug-ins

### ISSUE THREAD

**Issue by mfreuden2** [thonny/thonny#1322]
MicroPython v1.12 on 2019-12-20; ESP32 module with ESP32

import astroid

Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
['', '/lib']
Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
ImportError: no module named 'astroid'

plug-in wir nicht gefunden

Die Verzeichnisse befinden sich wie folgt:
C:\Users\Manfred\AppData\Roaming\Python\Python37\site-packages
C:\Progs\Thonny\Lib\site-packages

Im Vorab vielen Dank!

**Comment by aivarannamaa** [comment]
Please also post the code you are trying to run. If your code is trying to import `astroid`, then you have a problem, because this package won't run on ESP
