### ISSUE TITLE
window size adjustment moves wrong direction

### ISSUE THREAD

**Issue by zxsq-cc** [thonny/thonny#1328]
OS: macOS mojave
Thonny version: 3.1.2
Dragging window edge from the left side moves the right side of the window in/out instead of the left side. Other sides work as expected.
(screen recording: https://vimeo.com/455811217)

**Comment by aivarannamaa** [comment]
Thank you for the report!

Could you please try [latest version (3.2.7)](https://github.com/thonny/thonny/releases/download/v3.2.7/thonny-3.2.7.pkg) or the [beta of 3.3.0](https://github.com/thonny/thonny/releases/download/v3.3.0b2/thonny-3.3.0b2.pkg)?

**Comment by zxsq-cc** [comment]
Still an issue in 3.2.7, and in 3.3.0 beta.

**Comment by aivarannamaa** [comment]
I can't reproduce this in Catalina and I don't have any ideas what may cause it. As it doesn't look like a serious issue, I'll leave it for now

**Comment by MotusPerpetuusSprocketus** [comment]
@aivarannamaa 
I hope this helps display the issue more throughly. I don't know if the requested improvements are even possible. Thanks for making an (otherwise) awesome program.

[Thonny vs Mac.m4v.zip](https://github.com/thonny/thonny/files/5320260/Thonny.vs.Mac.m4v.zip)

**Comment by aivarannamaa** [comment]
@MotusPerpetuusSprocketus , thank you for this video!

Regarding tiling and full screen -- this should be fixed in newest Tk, but unfortunately newest Pythons don't use this. I'll see what can be done.

**Comment by aivarannamaa** [comment]
Closing this for now, as I'm not able to reproduce. Hopefully will be fixed in Thonny 4.0
