### ISSUE TITLE
How to use visual studio to build the .exe file?

### ISSUE THREAD

**Issue by monsterkaka** [thonny/thonny#1329]
We are trying to build a windows installer, but we can't use visual studio to get the .exe file.
We have added the path of python37.dll to the project properities, but visual studio reports that it can't find python37.dll.
So We copy python37.dll to the dir of project, it seems to work. But when we try to run this project, it reports an error as follows:

![图片](https://user-images.githubusercontent.com/18423791/92500167-57e17700-f22f-11ea-9985-d3ffc9197823.png)

Could you help me to solve above problem? 
It would be appreciated that you can provide a readme file to show me how to build a windows installer.

**Comment by aivarannamaa** [comment]
Sorry, I'm not very good with VisualStudio myself and at the moment I don't have time for debugging this issue.

Can't you use thonny.exe which is present in the repository?
