### ISSUE TITLE
Packages cant install because of SSL 

### ISSUE THREAD

**Issue by nheyland** [thonny/thonny#1330]
Is there any way I can get around this? Been searching for hours cant seem to find anything that works? OS Big Sur if that helps at all? 

<img width="1052" alt="Screen Shot 2020-09-11 at 10 57 30 AM" src="https://user-images.githubusercontent.com/71138407/92940848-9c326a00-f41d-11ea-9cde-d81a40e90b7b.png">

**Comment by aivarannamaa** [comment]
"SSL certificate is not validated" is just a warning, the real problem lies elsewhere -- this package (`requests`) is meant for CPython, not MicroPython.

**Comment by aivarannamaa** [comment]
BTW, are you using Big Sur? My Mac is not compatible, so I haven't tested Thonny with it. Is everything else running smoothly?

**Comment by nheyland** [comment]
Ahh that's makes sense, new here just getting the hang of everything in micropython. Yes this is Big Sur. I had trouble opening the package manager in the previous version but now I am in the latest Thonny build, and so far no issues, let me know if you need me to try anything specific out for you for testing.

**Comment by tony1tf** [comment]
I’m having exactly the same problem with Thonny on Big Sur trying to add numpy to my RPi Pico. Did you find a solution?

**Comment by aivarannamaa** [comment]
@tony1tf, numpy doesn't work on MicroPython devices.

**Comment by tony1tf** [comment]
Wow! - thanks for that - that's a lot of head scratching finished.
Tony
