### ISSUE TITLE
update from Windows command line

### ISSUE THREAD

**Issue by DancingGuy** [thonny/thonny#1331]
I tried:

\AppData\Local\Programs\Python\Python38\Scripts>pip -vvv install -U thonnyapp

and got this:

 https://pypi.org:443 "GET /simple/thonnyapp/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/48/15/319977469d382c214b7b8ef8f36c189ed0e4fe33fa4a82fa88d91599bff7/thonnyapp-0.9.zip#sha256=be2b9f91201e021671ca44b80719af5d5ec85d918464c33cc6f17588825d544e (from https://pypi.org/simple/thonnyapp/), version: 0.9
  Found link https://files.pythonhosted.org/packages/7a/f7/7129a753583157dc6bc00dd2d69ce9dd98c9595b07cbe29942da74157670/thonnyapp-0.9.1.zip#sha256=bb73fee3d90e894248b7394999c8c7d460d07c40c5bdb9fc0bc24b28b720012e (from https://pypi.org/simple/thonnyapp/), version: 0.9.1
Given no hashes to check 2 links for project 'thonnyapp': discarding no candidates
Installed version (0.9.1) is most up-to-date (past versions: 0.9, 0.9.1)
Requirement already up-to-date: thonnyapp in c:\users\ebay_sandbox\appdata\local\programs\python\python38\lib\site-packages (0.9.1)
Requirement already satisfied, skipping upgrade: thonny in c:\users\ebay_sandbox\appdata\local\programs\python\python38\lib\site-packages (from thonnyapp) (3.2.7)

My desktop shortcut and program group from Start button still launch 3.2.7 although I see you are at 3.3.0b3 at GitHub.

I did get warning about not having the newest pip so I updated that then tried again with same result.

I originally installed from the downloaded 14 MB setup file to my local disk if that makes any difference.

Please advise.

Thanks.

John

**Comment by aivarannamaa** [comment]
3.3.0b3 is a pre-release, ie you should add `--pre` switch to `pip install` if you want this.
