### ISSUE TITLE
just three suggestions, not issues

### ISSUE THREAD

**Issue by DancingGuy** [thonny/thonny#1332]
1. I have difficulty clicking the line number column to set a breakpoint while in nicer debug mode. The mouse cursor has to be exactly in the right spot which seems to move around across sessions or lines. Is there a way to broaden out the click area to light up the red spot?

2. Would it be possible to add a search box for the optional heap window so I can find a hex address without scrolling manually to sight it?

3. In easy mode, I did not see a way to steer the algorithm at break points by changing variable values? 

Overall, this IDE has been very helpful to me, especially the Object Inspector and friendly-traceback. Great work and Many Thanks!

**Comment by aivarannamaa** [comment]
> I have difficulty clicking the line number column to set a breakpoint while in nicer debug mode

Just in case -- are you clicking or double clicking? In Thonny the breakpoints are meant to be set with a double-click.

> Would it be possible to add a search box for the optional heap window so I can find a hex address without scrolling manually to sight it?

You are using heap view for teaching, right? When I was teaching, I only demonstrated the heap view once per cohort, so IMO this scrolling is bearable. I'd rather not complicate the view with the search box.

> In easy mode, I did not see a way to steer the algorithm at break points by changing variable values?

I'm afraid I didn't understand this one.
