### ISSUE TITLE
Unconnected network drive shorcuts make Files explorer broken

### ISSUE THREAD

**Issue by codemee** [thonny/thonny#1333]
If theres's network drive shorcuts that cannot be connected on Windows, click the **This Computer** button in the **Files** explorer would raise the FileNotFoundError exception so that I cannot view files anymore.  

![圖片](https://user-images.githubusercontent.com/1037913/92992080-aede9900-f51a-11ea-971c-f1c430b7782b.png)

**Comment by aivarannamaa** [comment]
Thank you for the report! I'll fix it in the next beta of 3.3

You should be get out of this state when you enter following command into shell:

`%cd C:\`

**Comment by aivarannamaa** [comment]
Sorry, my previous suggestion doesn't work with MicroPython backend. Switch to Python 3, issue this command and then switch back to MicroPython.

**Comment by codemee** [comment]
Thanks, but the command should be %cd C:\\ to escape from '\'.
