### ISSUE TITLE
Make console dockable in right pane (same pane as assistant)

### ISSUE THREAD

**Issue by LowToneMoFo** [thonny/thonny#1348]
I'd like to request a feature. Currently the console is always below the code editor. Since most computers are wide-screen, that usually wastes a lot of screen real-estate.

It would be nice of the console could be docked in the right pane (where the helper is). Ideally by making all views draggable to different panes, but having an option in the UI settings would be fina as well.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion! It is actually quite popular request and in my TODO list already (#544).

A workaround is linked here: #932.
