### ISSUE TITLE
Device message ! MicroPython commands have been moved or replaced

### ISSUE THREAD

**Issue by FreddyBI** [thonny/thonny#1350]
![Screenshot 2020-09-23 102454](https://user-images.githubusercontent.com/71754323/93986864-23210400-fd87-11ea-9e66-6cf55d76dc44.png)

and shell
>>> %lsdevice
Unknown command: lsdevice

![Screenshot 2020-09-23 100415](https://user-images.githubusercontent.com/71754323/93985497-75f9bc00-fd85-11ea-855c-7db9a4ebadaa.png)
![Screenshot 2020-09-23 100742](https://user-images.githubusercontent.com/71754323/93985532-83af4180-fd85-11ea-8ad7-a247827a6668.png)
No problem to save, save as ... or run my scripts or open files from MicroPython device.
![Screenshot 2020-09-23 102237](https://user-images.githubusercontent.com/71754323/93986538-c3c2f400-fd86-11ea-8d31-680a2a159a83.png)

**Comment by aivarannamaa** [comment]
This Thonny version doesn't have `%lsdevice` command anymore. Use View => Files instead.

**Comment by FreddyBI** [comment]
Remove "Device" from menu bar "File Edit View ...." ?
Or remove Message on click Device ?

**Comment by aivarannamaa** [comment]
Sorry, I did not understand what is the problem.

**Comment by FreddyBI** [comment]
I use for the first time Thonny program.
When  I click to Device on the menu bar I receive info moved commando's.
This is good info for users that use already previously versions  Thonny, not for me.

**Comment by FreddyBI** [comment]
I use for the first time Thonny program.
When  I click to Device on the menu bar I receive info moved commando's.
This is good info for users that use already previously versions  Thonny, not for me.

**Comment by aivarannamaa** [comment]
> I use for the first time Thonny program.
> When I click to Device on the menu bar I receive info moved commando's.
> This is good info for users that use already previously versions Thonny, not for me.

I think it's quite common that some parts of a program are not useful for all users. Do you propose I should remove this menu?

**Comment by FreddyBI** [comment]
Yes.
(I like use Thonny, thanks)
