### ISSUE TITLE
Mysql connectivity

### ISSUE THREAD

**Issue by SSGowri** [thonny/thonny#1352]
Hi,
I can't do Mysql connectivity in  thonny. in manage packages mysql is not listing to install. Please tell me a solution . I reinstall both tonny and mysql also. then also connectivity is  not getting

**Comment by aivarannamaa** [comment]
If you want your code to be able to talk to a MySQL server, then you need to select a suitable Python library for this and install it (eg. via Thonny's package manager). The choice of the library is not Thonny-specific.

**Comment by SSGowri** [comment]
I tried to install mysql. but its not showing in manage packages. Screen shot is attached. 
Regards ,

Gowri S S

Screen shot    Save Paper ! Think Before You Print !!



 

    On Tuesday, September 29, 2020, 02:35:43 PM GMT+4, Aivar Annamaa <notifications@github.com> wrote:  
 
 


If you want your code to be able to talk to a MySQL server, then you need to select a suitable Python library for this and install it (eg. via Thonny's package manager). The choice of the library is not Thonny-specific.

**Comment by SSGowri** [comment]
I tried this way also(screen shot attached). but error msg only displaying
Regards ,

Gowri S S


    Save Paper ! Think Before You Print !!



 

    On Tuesday, September 29, 2020, 02:35:44 PM GMT+4, Aivar Annamaa <notifications@github.com> wrote:  
 
 


Closed #1352.

**Comment by aivarannamaa** [comment]
Attachments don't come through if you reply by e-mail. You can post screenshots only on GitHub interface. 

Are you sure you want `mysql` PyPI package? Or are you trying to install MySQL server via Thonny?

**Comment by SSGowri** [comment]
I tried to install Mysql via Thonny for doing connectivity. but i cant install mysql errors are coming. screen shot attached.
Please do the needful.
Regards ,

Gowri S S


    Save Paper ! Think Before You Print !!

**Comment by aivarannamaa** [comment]
As I told you, I don't see your screenshots if you are replying by e-mail.

**Comment by SSGowri** [comment]
**here also i included**
Please do the needfull

![Screenshot (128)](https://user-images.githubusercontent.com/71939242/94682208-ac12df00-0335-11eb-9d9f-ca703ec25744.png)
![Screenshot (129)](https://user-images.githubusercontent.com/71939242/94682220-ae753900-0335-11eb-918a-0e29039ba0e4.png)

**Comment by aivarannamaa** [comment]
Sorry, but this is not Thonny's problem. If you can install this package with plain `pip install`, but not with Thonny's package manager, then I'll investigate further.

**Comment by r0the** [comment]
According to PyPI, mysql is an alias for MySQL-python, which is Python 2.7 only. It will not work with Thonny and Python 3.

I'd use the official mySQL driver for Python: [mysql-connector-python](https://pypi.org/project/mysql-connector-python/). It installs nicely in Thonny.

**Comment by SSGowri** [comment]
i went through that page .i am not getting from where to install from that page

**Comment by SSGowri** [comment]
![Screenshot (130)](https://user-images.githubusercontent.com/71939242/94725331-a08eda80-036c-11eb-838d-62144dd0e3d0.png)

**Comment by SSGowri** [comment]
error is comming

**Comment by SSGowri** [comment]
can you please send me a video showing next steps

**Comment by aivarannamaa** [comment]
@SSGowri, I recommend you ask advice from a Python forum. Your problem is not specific to Thonny. Also, I recommend to postpone MySQL for now and learn basic Python programming first.

**Comment by SSGowri** [comment]
I know python programming. I am a teacher . my collegue told about Thonny. and i taught my students using tonny. next topic is connectivity. thats why i am trying this
