### ISSUE TITLE
Opening on the last file

### ISSUE THREAD

**Issue by laboiteaphysique** [thonny/thonny#1353]
Hi,
I let unchecked the option "Reopen all files from previous session", but Thonny allways open the last file used.
Could you add an other checkbox in these options tab like "Don't open the last file on start"
(I'm a teacher and my students use the same session. When opening Thonny, the next student see the file opened by the other one, and sometime reuse it...).
Best regards
Vincent Le Mieux

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

I'll consider changing the binary option to a choice between ["all", "last", "none"]

**Comment by laboiteaphysique** [comment]
Thank for your positive answer !
... waiting for a new release yet !
Best regards
Vincent Le Mieux

**Comment by eyleenk** [comment]
still having the same issue, I've overwritten my other files because of this

**Comment by aivarannamaa** [comment]
> I'll consider changing the binary option to a choice between ["all", "last", "none"]

I changed my mind. I introduced new option "Reopen files from previous session" instead of "Reopen **all** files from previous session". It is checked by default, but if it is unchecked, no files from previous session get opened automatically.

**Comment by amathenge** [comment]
Hi - the option does not seem to work on Thonny for Mac.
I installed Thonny via homebrew, and works excellent.

However, when I launch it, the old open files are always open even if I clear the checkbox for that option

<img width="928" alt="Screenshot 2024-11-26 at 3 53 45 PM" src="https://github.com/user-attachments/assets/6e745058-2af4-4fb5-afd6-1b7761dfefe3">

Thanks,
Andrew.

**Comment by aivarannamaa** [comment]
The new behavior will be published as Thonny 5.0
