### ISSUE TITLE
Thonny breaks when emojis are used

### ISSUE THREAD

**Issue by BioHazard1282** [thonny/thonny#1357]
I am making an example program in Python 3 for a video, but Thonny 3.2.7 breaks when any line has emojis in it:
`def _thet():`
`    return "I am his brother. He is a memer, I am a coder."`
`    return "Favorite Emojis: 🦅🐍🦎🐊🐉🐲`
`print(_thet())`

If you were to paste this in an editor, another "Favorite Emojis" text appears at the end but white outside of comments, and I have to force-quit when I do this. I am using MacOS Mojave.

If you try to edit the text where the emojis are, many things in Thonny become unresponsive.

**Comment by aivarannamaa** [comment]
Thank you for the report!

It is a known issue and I'm waiting for newer Tk to be bundled with Python: #32

**Comment by AgimaFR** [comment]
In the meantime, you can use one of the following workarounds for source code management in Thonny and **run the script in a terminal window**(not in Thonny).

1. Use the [Unicode code of emojis](https://unicode.org/emoji/charts/emoji-list.html)
```python
print("\U0001F1EC\U0001F1E7")
print("\U0001F923")
```
2.Use the library [emoji](https://pypi.org/project/emoji2/)
```python
import emoji
print(emoji.emojize(":grinning_face_with_big_eyes:"))
print(emoji.emojize(":winking_face_with_tongue:"))
print(emoji.emojize(":zipper-mouth_face:"))
```
