### ISSUE TITLE
Mac Thonny is not running pygame properly

### ISSUE THREAD

**Issue by mhighmore** [thonny/thonny#1359]
The pygame window appears but no output happens.
I am running big sur and thonny

**Comment by aivarannamaa** [comment]
Sorry for late reply. I somehow missed your post.

Please post your Pygame version and a minimal program that demonstrates your problem.

**Comment by illume** [comment]
This was a known problem with pygame 1.9.6 and some versions of python. pygame 2 should work on Mac properly.

**Comment by mhighmore** [comment]
Thanks for confirming yes it seems to work fine now!
