### ISSUE TITLE
Problem with Thonny

### ISSUE THREAD

**Issue by tomasdaureli** [thonny/thonny#1360]
Hi i'm Tomas. i had a problem with my Thonny. I think that I put the mode expert and now the screen looks very small and i can't see anything. Please i need help because i'm student. I don't know how fix it. 
![Captura de pantalla (6)](https://user-images.githubusercontent.com/72536433/95411397-c718bc80-08fc-11eb-88d3-c28a7a1e08b2.png)

**Comment by aivarannamaa** [comment]
Please go to "Tools => Options => General". What do you have in "UI scaling factor" box? Try larger values. You need to restart Thonny after changing this.

**Comment by aivarannamaa** [comment]
You may need to change "Font scaling" mode as well

**Comment by tomasdaureli** [comment]
I can’t find the option “UI scalling factor” box. The tools looks like this. I tried to change the font scalling too, but it doesn’t change the rest of the view.     From: Aivar AnnamaaSent: jueves, 8 de octubre de 2020 02:17To: thonny/thonnyCc: tomasdaureli; AuthorSubject: Re: [thonny/thonny] Problem with Thonny (#1360) Please go to "Tools => Options => General". What do you have in "UI scaling factor" box? Try larger values. You need to restart Thonny after changing this.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tomasdaureli** [comment]
I uninstall the application too, but the configuration is still the same and nothing is changed. Is there any way to restore the app to the original values, installing from zero? Thank you   From: Aivar AnnamaaSent: jueves, 8 de octubre de 2020 02:18To: thonny/thonnyCc: tomasdaureli; AuthorSubject: Re: [thonny/thonny] Problem with Thonny (#1360) You may need to change "Font scaling" mode as well—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aivarannamaa** [comment]
For resetting the configuration:

* Start Thonny
* Select "Tools => Open Thonny data folder"
* Close Thonny
* delete configuration.ini
* Start Thonny

**Comment by tomasdaureli** [comment]
Thank you very much!!!!! You just saved my life. Greetings.   From: Aivar AnnamaaSent: jueves, 8 de octubre de 2020 16:11To: thonny/thonnyCc: tomasdaureli; AuthorSubject: Re: [thonny/thonny] Problem with Thonny (#1360) For resetting the configuration:Start ThonnySelect "Tools => Open Thonny data folder"Close Thonnydelete configuration.iniStart Thonny—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Flaming-crossbow** [comment]
> * configuration.ini

Thank you soo frggn much,
