### ISSUE TITLE
ISR is not always cleared at 'Stop/Restart backend'

### ISSUE THREAD

**Issue by wnelis** [thonny/thonny#1361]
The use case is to measure the frequency of a pulse train, typically 50 [Hz], on an ESP8266 using micropython v1.12, developed with Thonny 3.2.7. In this program an ISR is used, which triggers on the rising edge of a pulse. During testing of this program, it crashes or needs to be terminated. In both cases, you'll end up in REPL.

Sometimes the pointer to the ISR seems to be active even after one or more 'Stop/Restart backend'-commands. If the source of the pulse train is still active and connected, it rusults in my case in a lot of Python errors per second, stating:
```
    Traceback (most recent call last):
      File "main.py", line 165, in isr
    NameError: name 'time' isn't defined

```

The source code of the ISR is:
```
class Frequency():
  def __init__( self, Pin, N ):
    self.pulses= N                      # Number of pulses per measurement
    self.puls  = 0                      # Number of pulses this measurement
    self.tofp  = time.ticks_us()        # Time of first pulse
    self.topp  = 0                      # Time of previous pulse
    self.lopt  = None                   # Length of pulse train

    self.refupd= self.update
    self.pin   = machine.Pin( Pin, machine.Pin.IN, None )
    self.pin.irq( self.isr, machine.Pin.IRQ_RISING )

 #
 # Method isr is an Interrupt Service Routine (ISR).
 #
  def isr( self, pin ):
    tocp      = time.ticks_us()         # Time of current pulse
    if time.ticks_diff( tocp, self.topp ) < _frequency_bnc:
      return                            # Ignore pulses during 0.75 of period
    self.topp = tocp                    # Update pulse statistics
    self.puls+= 1
    if self.puls < self.pulses:
      return                            # Wait till enough pulses seen

    self.lopt= time.ticks_diff( tocp, self.tofp )
    self.tofp= tocp                     # Set up for next measurement
    self.puls= 0
  #
    micropython.schedule( self.refupd, None )

  def update( self, _ ):
    print( "{:5.2f}".format(1000000.0*self.pulses/self.lopt) )

```

Line 165 is the line following the header of method Frequency.isr, thus the line containing `tocp = time.ticks_us()`.

Thus a fragment of Python code is still active, but it's environment has been cleared.

I do not know where the root cause of this issue is located, in Thonny, MicroPython or even "deeper" in the ESP8266. So my question is if Thonny should heave cleared the interrupt pointer too upon issuing the 'Stop/Restart backend'-command.

**Comment by aivarannamaa** [comment]
In Thonny 3.2.7 Stop/Restart only restarts the connection to the device and doesn't actually soft-reboot the device. Thonny 3.3 will (since beta 3, you can try it with `pip install --pre thonny`).

In the meanwhile you should order a soft-reboot explicitly with Ctrl+D.
