### ISSUE TITLE
import numpy in shell view puased at startup . (version 3.3.0b3)

### ISSUE THREAD

**Issue by beardad1975** [thonny/thonny#1363]
I  cloned thonny version 3.3.0b3 and found  a strange thing in shell view.

When I tried to import numpy in shell view, it will paused . 
I needed to press  an extra Enter key to get  it run .

My simple numpy program do  "Run in current Script"  will pause at startup and needs an an extra Enter.
But  the same program do "Run current script in terminal"  just normally.

By the way .   My laptop os is Win10 64bit. 

![thonny_issue](https://user-images.githubusercontent.com/13803312/95668239-c0f83980-0ba3-11eb-8c45-8fdbf8787d93.jpg)

**Comment by aivarannamaa** [comment]
Thank you for the report!

I was able to reproduce this. It looks like I have to revert a design decision because it distracts DLL loading machinery.

**Comment by aivarannamaa** [comment]
I think I was able to fix this problem. Please pull the updates and see if this works for you!

**Comment by beardad1975** [comment]
I tried the updates.  It worked  as usual .  Good job.
