### ISSUE TITLE
Show full path+name when mouse points(hovers) editor tab

### ISSUE THREAD

**Issue by IhorNehrutsa** [thonny/thonny#1364]
Feature request.
I lost some time when I opened one module from another drive.
The hint under the mouse cursor (see a picture) will help to resolve my misunderstanding.
Thanks a lot.
![image](https://user-images.githubusercontent.com/70886343/95720010-56b1c880-0c79-11eb-8c58-77e33ac8886f.png)

Thonny 3.3.0b2 used

**Comment by aivarannamaa** [comment]
I'll consider adding it, but did you notice that the title bar of Thonny's window has full path of the active file?

**Comment by IhorNehrutsa** [comment]
Not always.
![image](https://user-images.githubusercontent.com/70886343/96755965-0e627b00-13dc-11eb-85a4-9081a4b9bd45.png)

**Comment by aivarannamaa** [comment]
Oh, this is a bug and must be fixed.

**Comment by IhorNehrutsa** [comment]
Not the big bug, after F5(Run) correct full name is displayed.

**Comment by aivarannamaa** [comment]
Can't reproduce mismatching titlebar path in Linux. Will test in Windows later.

**Comment by aivarannamaa** [comment]
Will be reimplemented with new Notebook
