### ISSUE TITLE
starting thonny came with a 'installinng' window  (version: 3.3.0b3-dev)   

### ISSUE THREAD

**Issue by beardad1975** [thonny/thonny#1366]
Test thonny 3.3.0b3-dev. (os: win10 64Bit )

When I started thonny . There was a small 'installinng' window . 
It never finished untill I close it . Was it normal?

![thonny_issue2](https://user-images.githubusercontent.com/13803312/95873283-595c0d00-0da2-11eb-87bd-7112c0287170.jpg)

**Comment by Standaros** [comment]
I have this issue only when starting Thonny from other IDE like Idle for example. When running in OS using direct interpreter like python.exe or pythonw.exe it launches just fine

**Comment by aivarannamaa** [comment]
Sorry, it was an experiment which was committed by accident. Fixed now.
