### ISSUE TITLE
Next update?

### ISSUE THREAD

**Issue by speedy-10** [thonny/thonny#1371]
Hi together,
I'm curious, when the next update of thonny will be availbale?
System: Ubuntu 20.04

Kind Regards

**Comment by aivarannamaa** [comment]
I hope to release next beta of 3.3 this week.

**Comment by raenye** [comment]
It's still Py3.7 based, right?

**Comment by aivarannamaa** [comment]
Right, Thonny+Python bundles will come with Python 3.7
