### ISSUE TITLE
Getpass Module issue

### ISSUE THREAD

**Issue by ayylena** [thonny/thonny#1374]
When using the getpass module the getpass function does not prompt any input (same code works fine in terminal).

Eg code:
from getpass import getpass
username=input('Username: ')
password=getpass('Password: ')

Output using thonny:
%Run user_data.py
Username: `ayylena`

(no further prompt)

Output using Windows terminal:
Username: ayylena
Password: (hidden input which works as expected)

**Comment by aivarannamaa** [comment]
This is expected, as Thonny's shell is not a terminal emulator.

You need to run such programs in Terminal (eg. by invoking "Run => Run current script in terminal" in Thonny)
