### ISSUE TITLE
Thank you very much for a great editor for Python!

### ISSUE THREAD

**Issue by mrkaban** [thonny/thonny#1376]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D1%83/ide/thonny-%D1%81%D1%80%D0%B5%D0%B4%D0%B0-%D0%B4%D0%BB%D1%8F-python.html).

The project is interesting, so please don't abandon it!

**Comment by aivarannamaa** [comment]
Thank you for the kind words!
