### ISSUE TITLE
I can't install pandas

### ISSUE THREAD

**Issue by caroblees** [thonny/thonny#1378]
I need to install pandas, but I get this ad, which I already tried to solve but it did not work
![Captura de Pantalla 2020-10-19 a la(s) 18 49 23](https://user-images.githubusercontent.com/73145223/96523631-cefd2880-123b-11eb-8dac-adf41e25951a.png)

**Comment by aivarannamaa** [comment]
I see two problems:

* In terminal you are using Python 3.9, but it looks like Python 3.9 binary wheels for Pandas (and numpy) are not published yet to PyPI, and building such complex packages from source is error prone.
* If you manage to install Pandas to your Python 3.9, you need to make sure Thonny is using this interpreter (Run => Select interpreter). By default it is using bundled Python 3.7 (with its own packages).

**Comment by aivarannamaa** [comment]
It's quite common that binary wheels for new Python version don't get published before first bugfix release (eg. 3.9.1)
