### ISSUE TITLE
MatPlotLib Graphics

### ISSUE THREAD

**Issue by Quimel1** [thonny/thonny#1379]
Hi, I'm new with this, so I hope I explain myself correctly. 
I'm learning Python in my school, and we are using libraries as MatPlotLib. 
You'll know that when you visualize a graphic, it opens another window. So today I'm having a final presentation, but while I was testing my program just to check everything was in order I was just wandering trough the Thonny Options, and I have no idea of what I clicked-on, but now each time I try to visualize a Graphic the computer kind of resets. 
I use a MacBook Pro and Thonny to run my code. 
I will appreciate any help.

**Comment by aivarannamaa** [comment]
If you experience this crash again (or if you haven't started Thonny since last crash) then please check whether Thonny logged something: https://github.com/thonny/thonny/wiki/Troubleshooting#see-the-logs-macos

If there is anything, then please post them here.

Also, in the same directory as logs, there is a file configuration.ini, which may also be useful in debugging this situation.

**Comment by Quimel1** [comment]
I entered /Library/Thonny and inside the folder there are 6 files (as the image shows), but I only could upload one of them, because the page says the file is empty, and for the .ini file it says the page doesn't support this type of file (I am ommiting user_notes.txt)

 

![image](https://user-images.githubusercontent.com/73175693/96650936-61173680-12f9-11eb-8579-5af72a4c36af.png)

[frontend.log](https://github.com/thonny/thonny/files/5411978/frontend.log)

**Comment by aivarannamaa** [comment]
Unfortunately there was nothing useful in frontend.log.

Could you please make a copy of configuration.ini, rename it to have `.txt` suffix and then send it here?

**Comment by Quimel1** [comment]
[configuration.txt](https://github.com/thonny/thonny/files/5432395/configuration.txt)

Hi, this is configuration.ini converted to .txt

**Comment by aivarannamaa** [comment]
Unfortunately I couldn't spot anything suspicious in the configuration.ini

> now each time I try to visualize a Graphic the computer kind of resets

Can you please be more specific? Do you get logged out from your session?

There couple of more things to try:

- Close Thonny and delete your configuration.ini. After this your Thonny will open with default settings.
- Try the beta of the next version: https://github.com/thonny/thonny/releases/tag/v3.3.0b2

-

**Comment by aivarannamaa** [comment]
If none of these help, then please post an example program, which reproduces this problem for you.
