### ISSUE TITLE
esp32 incompatibility problem

### ISSUE THREAD

**Issue by gooyle** [thonny/thonny#1383]
sometimes thonny may lose connection with esp32，and error is about : `<thonny>{'/': {'boot.py': {'size': 139, 'kind': 'file', 'time': 946684800}, 'main.py': {'size': 200, 'kind': 'file', 'time': 946685163}}}</thonny>>`

**Comment by aivarannamaa** [comment]
Please try whether https://github.com/thonny/thonny/releases/tag/v3.3.0b2 works better for you!

**Comment by grubert** [comment]
On Thu, 22 Oct 2020 at 02:52, gooyle <notifications@github.com> wrote:

> sometimes thonny may lose connection with esp32，and error is about : <thonny>{'/':
> {'boot.py': {'size': 139, 'kind': 'file', 'time': 946684800}, 'main.py':
> {'size': 200, 'kind': 'file', 'time': 946685163}}}</thonny>>
>
i tried 3.2.7 on linux, macosx and several windows pcs.
linux and mac work but on windows the file list (see above) always ends up
in the python console
and not in the file view.

3.3.0b2 works on all systems
upgraded with pip install --pre thonny

**Comment by aivarannamaa** [comment]
@grubert, thanks, that's good to know!

Closing now. @gooyle, please reopen if the problem persists with version 3.3

**Comment by gooyle** [comment]
> Closing now. @gooyle, please reopen if the problem persists with version 3.3

thx，the 3.3 version works.
