### ISSUE TITLE
Micropython: another autocomplete issue (editor view)

### ISSUE THREAD

**Issue by adzierzanowski** [thonny/thonny#1410]
Autocompletions work fine in the terminal view but with micropython files there's no autocompletion at all for user-defined modules. Consider:

```python
# foo.py
def foo():
    print('bar')
```

```python
# bar.py
import foo

foo.#<TAB> hit here, nothing happens
```

Would it take much to implement autocompletions in the editor view? I suppose it would require loading the imported modules dynamically and would raise the issue of cluttering the board's communication port if there were many large modules used.

**Comment by aivarannamaa** [comment]
Do you edit your scripts on the device, or on the local machine? In the latter case it may require some tweaking in Thonny, but I don't have a good solution for the former.

**Comment by adzierzanowski** [comment]
On the device, unfortunately.

**Comment by aivarannamaa** [comment]
I could maintain a local shadow copy of each file from the device, if it has been opened in Thonny (in this case no extra data needs to be exchanged).

I don't have time to squeeze this into version 3.3, though.

**Comment by aivarannamaa** [comment]
Should be working in 4.0
