### ISSUE TITLE
Suggestion: remove support for Friendly-traceback

### ISSUE THREAD

**Issue by aroberge** [thonny/thonny#1416]
Suggestion: remove Thonny's built-in support for Friendly-traceback until version 1.0 is available.  I can do this in a pull request if desired.

Friendly-traceback (currently at version 0.1.11) can now be run from any editor, using a secondary file as a launcher. 
Here's a screen capture using Thonny:

![image](https://user-images.githubusercontent.com/629698/99146781-70b44180-2651-11eb-9cba-73609427666f.png)

As a result, built-in support for Thonny, while slightly more convenient (in theory) is no longer needed.  Removing code related to Friendly-traceback from within Thonny would ensure that no breakage would occur when changes to Friendly-traceback are made.

Once the API of Friendly-traceback is "frozen", the idea of adding direct support for Friendly-traceback within Thonny could be revisited.

**Comment by aivarannamaa** [comment]
Alright, I don't mind. I'll remove it before releasing final 3.3.0

**Comment by aroberge** [comment]
And I want to really thank you for the early support you gave to Friendly-traceback. I have been adding some features found in Thonny's assistant, mostly inspired by some comments you made a while ago on the design of Friendly-traceback.

**Comment by aivarannamaa** [comment]
I'm glad my comments have been useful! I wish you luck!
