### ISSUE TITLE
Thonny opens only last file opened whent restart application

### ISSUE THREAD

**Issue by Juarrox** [thonny/thonny#1433]
If I close Thonny with some files opened when I reopen again Thonny only opens last file opened last time. Just updated to 3.3.0 version in my RPi4, this problem did not appear in the previous version.

**Comment by aivarannamaa** [comment]
Reopeing all files is controlled by "Tools => option => General => Reopen all files from previous session".

Is it on or off?

**Comment by Juarrox** [comment]
You're right! It was off, just activated and works on. 

I don't know if in previous version it was on or off that option but every time that I started Thonny always opened the files that I didn't close.

Thank you and congrats, great app 👍

**Comment by aivarannamaa** [comment]
Thank you for the kind words!
