### ISSUE TITLE
Please add keyboard shortcut to menu: Run->Disconnect

### ISSUE THREAD

**Issue by IhorNehrutsa** [thonny/thonny#1438]
Possibly Shift + F2.
Thanks

**Comment by aivarannamaa** [comment]
Sorry for late reply!

I assume that you want the shortcut, because you need to disconnect often. Is it because you want to connect to same device from different program?

**Comment by IhorNehrutsa** [comment]
Yes, You are right. I am developing C modules for ESP32 MicroPython 
https://github.com/micropython/micropython/pulls/IhorNehrutsa
and I need to switch to esptool.py to write the firmware to the chip 
and then switch back to Thonny to run Python code.
Thanks.

**Comment by aivarannamaa** [comment]
I see. I think you are in a rather unusual situation, compared to other Thonny users. Therefore I'd rather not use up a shortcut key for this command, but you can add it yourself: https://github.com/thonny/thonny/wiki/Custom-shortcuts

**Comment by IhorNehrutsa** [comment]
I added 
```
[shortcuts]
disconnect = <Shift-F2>
```
to c:\Users\ < user >\AppData\Roaming\Thonny\configuration.ini 
and I have the shortcut and it works as expected
![image](https://user-images.githubusercontent.com/70886343/100856813-91272d00-3494-11eb-8452-d8a3501baca7.png)
Am I happy?
Not fully.
I need to do the same in 3 other places: in VirtualBox, in VMware Player, and on my notebook :(

**Comment by aivarannamaa** [comment]
Well, the choice is yours...
