### ISSUE TITLE
Writing to a file on microbit causes unwanted output

### ISSUE THREAD

**Issue by r0the** [thonny/thonny#1441]
When writing to a file on microbit, an output occurs in the shell. The output
seems to be the number of characters written to the file.

```
from microbit import *

with open("test.txt", "w") as file:
    file.write("Hello World")
    file.write("Test")
```

This behaviour is new in Thonny 3.3.0.

<img width="345" alt="Bildschirmfoto 2020-11-22 um 16 38 12" src="https://user-images.githubusercontent.com/1057839/99908271-fa16e400-2ce1-11eb-877c-084cc8a9a19e.png">

**Comment by aivarannamaa** [comment]
Thank you for the report! 

This will be fixed in 3.3.1
