### ISSUE TITLE
pixeld icon "stop" with 4k

### ISSUE THREAD

**Issue by speedy-10** [thonny/thonny#1445]
Hi, I discovered that the stop icon is unsharp with 4k monitor: UI scaling 4.0.
See picture
![Bildschirmfoto von 2020-11-26 16-02-45](https://user-images.githubusercontent.com/20227451/100368051-61df6e80-3003-11eb-853c-8eda8cdb310f.png)

Thonny 3.3.0  (ubuntu 20.04).

Regards
PS: Same with the "x" to close the tabs.

**Comment by aivarannamaa** [comment]
Thanks!

I'll keep it in the TODO list, but I don't know when will I find time for this.

If you want to get it faster, then you could create a 32x32 icon yourself.

**Comment by speedy-10** [comment]
No problem, I only want to help to improve this nice editor.

**Comment by speedy-10** [comment]
hi, will this issue be fixed with Thonny 4.0 :-) ?

**Comment by speedy-10** [comment]
this picture is offered with:  CC BY-NC 4.0 Licence
https://pngset.com/download-free-png-izmoz
So I reduced the size to 32x32 pixel, see attachement. 
Regards

![stop-1327126-transport-stopsign-road-sign-symbol-transparent-png-2322234_small](https://user-images.githubusercontent.com/20227451/151755844-75801015-2f84-477b-9589-72beaa0c17cc.png)

**Comment by aivarannamaa** [comment]
Thanks! This looks really nice! It will be in 4.0
