### ISSUE TITLE
Cannot select a virtual environment in dot directory

### ISSUE THREAD

**Issue by m4r35n357** [thonny/thonny#1448]
Dot folders are invisible to the file selector.  The virtualenvwrapper package on Raspberry Pi OS installs environments to ~/.virtualenvs, so they become invisible to the Thonny file selector.

I had to make a **symlink** to access mine, so this is not fatal, but is inconvenient and potentially frustrating to users attempting to use virtual environments for the first time.

**Comment by aivarannamaa** [comment]
Try right-clicking on the file selection dialog -- it should give you an option for showing hidden files.

**Comment by m4r35n357** [comment]
You are absolutely correct,  I am not used to the Pi file selector!  Sorry to trouble you with this.  BTW Thonny has taken over from my attempts to understand Spyder on the Pi ;)
