### ISSUE TITLE
About adding modules

### ISSUE THREAD

**Issue by asp65** [thonny/thonny#1456]
i don't know why i've added this module, but it doesn't work.
![1](https://user-images.githubusercontent.com/73155911/100691151-075b5f00-33c3-11eb-9cc2-6ea50d650d4a.png)
![2](https://user-images.githubusercontent.com/73155911/100691164-0d514000-33c3-11eb-835a-703255508a33.png)

**Comment by aivarannamaa** [comment]
In the screenshot you have installed it for Python 3 in your computer, but according to the package description it is meant for MicroPython, ie. it should be installed on the device.

Which MicroPython device are you using?

**Comment by asp65** [comment]
> In the screenshot you have installed it for Python 3 in your computer, but according to the package description it is meant for MicroPython, ie. it should be installed on the device.
> 
> Which MicroPython device are you using?

i didn't install it on my device. now,it is working. thank you guys for helping! my mircopython is esp32, other device isn't being sold in china.
