### ISSUE TITLE
ESP32: Run-Disconnect breaks the microcontroller program

### ISSUE THREAD

**Issue by IhorNehrutsa** [thonny/thonny#1462]
Latest Thonny, latest stable ESP32 port of MicroPython.
I connect ESP32 to my WIFI router.
When I try to disconnect, I suppose that the ESP32 still working, but it is not.
WebREPL lost the connection (reconnect not possible).
![image](https://user-images.githubusercontent.com/70886343/101151530-74bcf900-362a-11eb-8bca-62584b47a939.png)

There is no that effect in [EsPy IDE](https://github.com/jungervin/EsPy).
WebREPL connected to the ESP also works synchronously to the terminal inside IDE.
![image](https://user-images.githubusercontent.com/70886343/101152462-cb770280-362b-11eb-832e-0f0d6a47a993.png)

**Comment by aivarannamaa** [comment]
Thank you for the report! I wish all reports were so clearly presented!

Currently the "Disconnect" simply kills the back-end process, which is talking to the device.

I have noticed that when I'm opening connection to some of my devices with PySerial, the device resets. It looks like the same can happen on disconnect. I suspect that there is a difference in how PySerial connects to the device and how EsPy does.

I couldn't reproduce this behavior in Ubuntu with Sparkfun ESP32 thing. Will try Windows later.

**Comment by aivarannamaa** [comment]
Can you test whether the device reboots on disconnect from Thonny or only the webepl service disappears?
When you create a variable in REPL, disconnect, exit Thonny and start Thonny again, is the variable still present?

Note that you can't use Stop/Restart in this test because it does soft-reboot by design.

**Comment by IhorNehrutsa** [comment]
ESP32 flash is rewritten.
boot.py is default:
```
# This file is executed on every boot (including wake-boot from deepsleep)
#import esp
#esp.osdebug(None)
#import webrepl
#webrepl.start()
```
Open Thonny 1
![image](https://user-images.githubusercontent.com/70886343/101165536-7d6bfa00-363f-11eb-8cb5-0344f506ee51.png)
Close Thonny
Open Thonny 2
![image](https://user-images.githubusercontent.com/70886343/101165603-98d70500-363f-11eb-9ede-2aad7cad5aba.png)
Close Thonny
Open Thonny 3
![image](https://user-images.githubusercontent.com/70886343/101166023-48ac7280-3640-11eb-84a3-cf2bb6b1d97d.png)

ESP reboots are happening, sometimes it visible in Shell, sometimes not.

**Comment by IhorNehrutsa** [comment]
```
[ESP32]
dtr = False
rts = False
```
It seems that more convenient and right name of section in ini file is:
[USB_UART]
not
[ESP32]
because CP2102 used in Arduino/AVR, STM32 boards also.

And thanks for your work and time.

**Comment by aivarannamaa** [comment]
All MicroPython settings are grouped under respective back-end, ie. when you want to set dtr/rts for ESP32, then they must be under `[ESP32]`. If you need it for other kinds of devices as well, then you also need to set the same settings under other sections.

**Comment by IhorNehrutsa** [comment]
Ok, thanks for clarifying.

**Comment by IhorNehrutsa** [comment]
Tested in Thonny 3.3.1. All right.

**Comment by slabua** [comment]
Still needed to be added in 3.3.14.
