### ISSUE TITLE
"Unable to find a shell" from Tools/Open system shell

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#147]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/147) by Anonymous.**

----------------------------------------

Thonny 2.0.3
Ubuntu 16.04.1 LTS
Python 3.5.2
Tk 8.6.6

**Comment by pebauer68** [comment]
I also had this issue with Ubuntu 18.04 when x-terminal-emulator was set to use the "terminator" as the terminal application. There is a linux config option for this:

sudo update-alternatives --config x-terminal-emulator
There are 7 choices for the alternative x-terminal-emulator (providing /usr/bin/x-terminal-emulator).

  Selection    Path                             Priority   Status
------------------------------------------------------------
  0            /usr/bin/terminator               50        auto mode
  1            /usr/bin/gnome-terminal.wrapper   40        manual mode
  2            /usr/bin/koi8rxterm               20        manual mode
  3            /usr/bin/lxterm                   30        manual mode
* 4            /usr/bin/mate-terminal.wrapper    30        manual mode
  5            /usr/bin/terminator               50        manual mode
  6            /usr/bin/uxterm                   20        manual mode
  7            /usr/bin/xterm                    20        manual mode
