### ISSUE TITLE
paramiko.hostkeys.InvalidHostKey, Incorrect padding

### ISSUE THREAD

**Issue by rmarkscott** [thonny/thonny#1471]
I am having trouble getting this to work. The error is:

"File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/hostkeys.py", line 372, in from_line
    raise InvalidHostKey(line, e)
paramiko.hostkeys.InvalidHostKey: ('192.168.1.28 ecdsa-sha2-nistp256 ****************.', Error('Incorrect padding'))"

My server is 192.168.170.2, I have no idea where the 1.28 comes from.

Can you help?

**Comment by aivarannamaa** [comment]
Thank you for the report!

You are using public key authentication, right? With or without passphrase?

Unfortunately I don't know what is to blame. When I googled for your error message, I found https://github.com/3drobotics/solo-cli/issues/36, which offers a work-around. Maybe it works if you remove the known host and let Paramiko (Thonny's SSH library) add it back. Hopefully your other SSH client (which added it first) is happy with the one added by Paramiko.

**Comment by aivarannamaa** [comment]
> You are using public key authentication, right?

I don't know why I assumed this. The error is probably not related to authentication at all.

**Comment by aivarannamaa** [comment]
Have you had chance to try the suggested work-arounds?

**Comment by rmarkscott** [comment]
Yes, I never got it to work.


Mark Scott, M.S., Assistant Professor, GCIA
Cybersecurity Program Coordinator
Member - The FBI’s InfraGard Program
Freed-Hardeman University | 158 E. Main Street | Henderson, TN 38340
731.989.6779

http://www.fhu.edu/cybersecurity

**Comment by aivarannamaa** [comment]
> My server is 192.168.170.2, I have no idea where the 1.28 comes from.

I suppose the library is parsing the whole known_hosts file, and you have connected to 1.28 before.

Did you try removing this line from `~/.ssh/known_hosts` ?

**Comment by aivarannamaa** [comment]
Closing for now as I don't have ideas how to move forward.

**Comment by ollav** [comment]
> > My server is 192.168.170.2, I have no idea where the 1.28 comes from.
> 
> I suppose the library is parsing the whole known_hosts file, and you have connected to 1.28 before.
> 
> Did you try removing respective line from `~/.ssh/known_hosts` ?

I think you are right about known_hosts. I had the same issue with 'incorrect padding' and found I had a key from a very old version of ssh in ~/.ssh/known_hosts. When I removed the key the issue went away.

**Comment by plijnzaad** [comment]
I can attest that removing ~/.ssh/known_hosts works (which is weird because I had already removed all keys that looked even a bit like they could be the offending ones, based on name and type)
