### ISSUE TITLE
Documentation strings not accessible via REPL

### ISSUE THREAD

**Issue by raenye** [thonny/thonny#1481]
The following code behaves differently when typed in the REPL shell and when run from a script:
```python
def f():
    "doc string"
    pass
```

### REPL (Thonny)
```
>>> help(f)
Help on function f in module __main__:

f()
>>> f.__doc__ is None
True
```
### Script (Thonny)
```
>>> %Run scratch.py
>>> help(f)
Help on function f in module __main__:

f()
    doc string
>>> f.__doc__
'doc string'
```
### REPL (official CPython)
```
>>> help(f)
Help on function f in module __main__:

f(x)
    doc string
>>> f.__doc__
'doc string'
```

Is this intentional?

Thanks,
R.

**Comment by aivarannamaa** [comment]
Thank you for the report!

It was not intentional. I had made a mistake in emulating Python REPL, which prints the value of each "bare" expression (ie. ast.Expr node). I forgot, that the docstring is an exception to this.

Should be fixed now.
