### ISSUE TITLE
Add Persian/Farsi (فارسی) Translation in Thoony

### ISSUE THREAD

**Issue by Farshidmi** [thonny/thonny#1486]
Hi

I have just finished translating Thonny into Persian (Farsi). 
Kindly Add this translation to the next Thonny updates and name it "فارسی".

  Best Regards,
  Farshid  :)

**Comment by aivarannamaa** [comment]
Thank you! Will do.

**Comment by aivarannamaa** [comment]
Can you tell me the locale code for this language? Is it `fa_IR` (https://www.localeplanet.com/icu/fa-IR/index.html)?

**Comment by Farshidmi** [comment]
Yes,  the code is fa_IR.
