### ISSUE TITLE
feedback assistant popup is BEHIND the assistant UI

### ISSUE THREAD

**Issue by pleabargain** [thonny/thonny#1489]
https://i.imgur.com/bo5m62u.png

I had thought that Thonny had locked up after submitting feedback when in fact the confirmation dialog was BEHIND the assistant UI window.

suggestion:
push confirmation dialog to TOP of the UI.

I use Thonny daily :) 

thank you!

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Thonny version are you using? Some bugs like this were fixed in Thonny 3.3.
