### ISSUE TITLE
Thonny Python app loopt vast

### ISSUE THREAD

**Issue by Nilogisch** [thonny/thonny#1491]
Ik gebruik Thonny Python op mijn Raspberry PI, maar als ik hem nu wil gebruiken loopt hij direct vast. Ik heb de RPI opnieuw gestart en de app geupdate. Weet iemand wat ik hieraan kan doen?
groet van Nilo (10 jaar)

**Comment by aivarannamaa** [comment]
How does it crash? Do you get an error message?
