### ISSUE TITLE
ESP32: machine.reset() command & Thonny backend

### ISSUE THREAD

**Issue by IhorNehrutsa** [thonny/thonny#1492]
Hello, Aivar. Thanks for your time.
Is it possible to detect the machine.reset() command in Shell and restart the Thonny backend without manual manipulations, like the soft reboot?
Please remove "ManagementError" modal window  (a Shell message is sufficient).
![image](https://user-images.githubusercontent.com/70886343/102711288-24e46000-42c1-11eb-834c-66ea8ce7525f.png)
![image](https://user-images.githubusercontent.com/70886343/102711142-28c3b280-42c0-11eb-862e-c8327b29e4a4.png)
it is continue
![image](https://user-images.githubusercontent.com/70886343/102711134-1c3f5a00-42c0-11eb-8db8-80b0cb10d3ec.png)
I know that EsPy is simpler inside than Thonny.
![image](https://user-images.githubusercontent.com/70886343/102711104-f0bc6f80-42bf-11eb-9ba3-4ea7552aa16b.png)

Minimalist boot.py is
```
from machine import reset, reset_cause
print('reset_cause() =', reset_cause())
```
Thanks a lot.

**Comment by aivarannamaa** [comment]
Thank you for the report!

I could reproduce and fix. The fix will be in Thonny 3.3.2
