### ISSUE TITLE
Making Thonny default application for .py files in Windows

### ISSUE THREAD

**Issue by Ferro1945** [thonny/thonny#1495]
Hi!
When I began learning Python I found PyCharm development environment, and started using it. Very soon I noticed that it is too complex for a beginner. Then I found Thonny that seems to fit very well for me. So I would like to make Thonny my default application for .py files. When I go to Windows Settigns, it only gives the opportunities Notepad, PyCharm, and Look for an app in the Microsoft Store. Microsoft Store does not offer Thonny as a possibility. Please tell me how to proceed.

**Comment by aivarannamaa** [comment]
You should right-click on a py file in Windows explorer, select "Open with.. => Choose another app" and navigate to where you installed Thonny and select thonny.exe

This may help you https://www.digitaltrends.com/computing/how-to-change-file-associations/
