### ISSUE TITLE
Add support for jedi 0.18+

### ISSUE THREAD

**Issue by yossioo** [thonny/thonny#1497]
Pressing tab on `prin` should put `print` , but instead got this:
![image](https://user-images.githubusercontent.com/10714585/103220757-be4aec00-4929-11eb-8b8d-54c86b83cd40.png)

Thonny 3.3.1
Python 3.9.1 x64
Ubuntu 18.04
Tk 8.6.8

**Comment by aivarannamaa** [comment]
Thank you for the report!

I assume you installed Thonny with `pip`, is it right? Could you please check the version of `jedi` library your Thonny using? (Tools => Manage plug-ins => Select "jedi" from the list in the left)

**Comment by yossioo** [comment]
That is correct. I have a testing `venv` environment derived from system-wide python3.9 installed from sources.
In the said environment I have installed Thonny using `python3 -m pip install -U thonny` command.

The `jedi` version is 0.18.0
![image](https://user-images.githubusercontent.com/10714585/103221577-aa07ee80-492b-11eb-9bc9-6241fcf46167.png)

**Comment by aivarannamaa** [comment]
Please try downgrading jedi to 0.17 (either with pip or via Thonny's plugin-manager dialog)

**Comment by yossioo** [comment]
That seems to solve the problem!

**Comment by aivarannamaa** [comment]
Good to know. Thanks!
