### ISSUE TITLE
debug python 2.7 using Thonny

### ISSUE THREAD

**Issue by uglybugs** [thonny/thonny#1499]
using  Thonny v.3.3.0 how do i get the interpreter to recognise Python 2.7 files ?

**Comment by aivarannamaa** [comment]
Unfortunately you can't -- Thonny does not support Python 2.

**Comment by uglybugs** [comment]
do you know of an IDE that can support python 2.7 ?
i am trying to understand (using a trace feature like in Thonny)  why called methods are not returning.

**Comment by aivarannamaa** [comment]
You could try debugging in IDLE: https://realpython.com/python-idle/#how-to-debug-in-idle
or PyCharm, but this IDE may be more complicated to get started
