### ISSUE TITLE
How to add an interpreter to thonny

### ISSUE THREAD

**Issue by Quinniboi10** [thonny/thonny#1505]
Hello, I really like Thonny, but I want to add an interpreter so I can run python 2.7 files. Any help is welcome. 

Thanks,
Quinniboi10

**Comment by aivarannamaa** [comment]
You can add a Python 3 interpreter from "Run => Select interpreter => Custom Python ...", but Python 2 is not supported.

Out ouf curiosity -- why do you need Python 2?

**Comment by Quinniboi10** [comment]
To use the GMailAPI, if I use C:\Users\<MYUSERNAME>\anaconda3\ipython.exe, will I get to use all of the libraries that I installed when using Spyder (from anaconda3)?

**Comment by aivarannamaa** [comment]
> if I use C:\Users<MYUSERNAME>\anaconda3\ipython.exe, will I get to use all of the libraries that I installed when using Spyder (from anaconda3)?

That's right.

**Comment by aivarannamaa** [comment]
Oops, sorry, don't use `ipython.exe`. There should be `python.exe` in the same directory -- use this one instead
