### ISSUE TITLE
How to install keras in Thonny

### ISSUE THREAD

**Issue by Quinniboi10** [thonny/thonny#1510]
Hello, I really like using Thonny, and I want to install keras on it but it won't get me. Any help is welcome

Thanks,
Quinniboi10

**Comment by aivarannamaa** [comment]
>  but it won't get me

What do you mean exactly? Do you get an error message?

**Comment by Quinniboi10** [comment]
1. I met let not get
2.  It says:
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py which use PEP 517 and cannot be installed directly
Process returned with code 1

**Comment by aivarannamaa** [comment]
You may need to upgrade pip: https://stackoverflow.com/questions/61365790/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installe

pip is another package you should see in "Tools => Manage packages". Or you could use command line ("Tools => Open system shell")

**Comment by Quinniboi10** [comment]
Pip is at the latest version though.

**Comment by aivarannamaa** [comment]
In this case I'm afraid I can't help you.
