### ISSUE TITLE
M5Stack error when restarting a program.

### ISSUE THREAD

**Issue by fraramon** [thonny/thonny#1512]
The error occurs when the program is running and you try to run it again.

`WARNING:root:Unexpected echo. Expected b'%Run -c $EDITOR_CONTENT\r\n', got bytearray(b'MediaTrans/TimerCam ')`

It would be very good if before executing it a Ctrl-C was performed to cut it before and after its execution.
I use this example program:
```
from m5stack import *
from m5ui import *
from uiflow import *
while True:
      wait_ms(1000)
```

**Comment by aivarannamaa** [comment]
Thank you for the report! I'll consider your suggestion.

**Comment by fraramon** [comment]
Thanks to you, may everything be for a better product. Happy New Year.
