### ISSUE TITLE
Thonny on Macbook missing its Menu Bar

### ISSUE THREAD

**Issue by mainguyenjune** [thonny/thonny#1523]
Installed Thonny on Macbook but can't find the Menu Bar
- Thonny ver 3.3.1
- MacOS ver Big Sur 11.1
- Screenshot https://drive.google.com/file/d/1MowtyVdNAkGP3xepo430eLP8gQQCo4EK/view?usp=sharing

**Comment by aivarannamaa** [comment]
Thank you for the report!

On this screenshot I see only Thonny's window, but on Mac, menu bar is never attached to a window. When you open Thonny, what do you see in the uppermost edge on your screen?

**Comment by mainguyenjune** [comment]
Oh, my bad, I already see the menu bar on the uppermost edge on my screen. I am also a new Mac user, so thank you so much for that! 

Have you a nice day Aivar Annamaa!

**Comment by aivarannamaa** [comment]
You're welcome!
