### ISSUE TITLE
I have connect esp32 with usb cable to my raspberry Pi  it's shows device not connected

### ISSUE THREAD

**Issue by CoderLogy** [thonny/thonny#1525]
I connected device using thonny and thonny has also detected it but when I click open file from micropython device it shows me error
Pls help the esp32 is connected and have .bin installed on it

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please copy this error here. Also please tell me your ESP32 board name (model), MicroPython version and Thonny version.

**Comment by CoderLogy** [comment]
I will add u. Error some my board is esp3p2 generic module wroom 32 micropython version is esp32-idf3-20200902-v1.13.bin and thonny is latest

**Comment by aivarannamaa** [comment]
Unfortunately I can't reproduce this. Can you access the REPL with another tool (eg. screen, tio, minicom)?

**Comment by CoderLogy** [comment]
Yes now my problem fixed thnks for reaching me
