### ISSUE TITLE
ManagementError

### ISSUE THREAD

**Issue by ttadam** [thonny/thonny#1538]
I do long time testing with ESP32 (wesp32 board), micropython, So the repl is always runnig

Time-to-time I got a small error window with red cross. 
Title of the window is: Error querying global vari.... (It is a small window, so I don't see the text)
Text in the window is: ManagementError. 

If I click okay, the IDE froze. 
![screenshot1](https://user-images.githubusercontent.com/6552445/104439223-2be55200-5591-11eb-8d8b-d81656f3b1bf.jpg)

(I know that We have some issues with our management, but why does thonny remind me about it? :D )

**Comment by aivarannamaa** [comment]
Thank you for the report!

Unfortunately Thonny is not smart enough to diagnose your management :) The ManagementError means Thonny failed to execute on your board a hidden command for managing user experience (eg. querying variables or files)

Which Thonny version are you using? If anything less than 3.3.2, then you should upgrade and try again.

If you are having 3.3.2, then can you tell me which action precedes this error message? Restarting the device? Executing `machine.reset()`? Something else?
