### ISSUE TITLE
Internal error while using Outline View

### ISSUE THREAD

**Issue by rvreugde** [thonny/thonny#1543]
When I activate Outline in Thonny, I got sometimes an error:
- Activate Outline
- Choose one of my functions in the outline list
- Scroll upwards in the code window
- Try to save or edit
- Error pops up
![image](https://user-images.githubusercontent.com/38208623/104598369-ca97ae80-5676-11eb-9217-f2105c52b554.png)
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/usr/lib/python3/dist-packages/thonny/plugins/outline.py", line 126, in _on_select
    lineno = self.tree.item(self.tree.focus())["values"][0]
IndexError: string index out of range
```

I use Thonny 3.2.7 under Linux Mint 20.1 (Ubuntu 20.1).

**Comment by aivarannamaa** [comment]
Thank you for the report!

I could reproduce it. The fix will be in Thonny 3.3.3
