### ISSUE TITLE
Fonts with ligatures

### ISSUE THREAD

**Issue by cybarspace** [thonny/thonny#1546]
Is there any plan to support fonts with ligatures? Or is it already supported and I have to enable it somewhere in the configs?

I want to use JetBrains Mono, Fira Code or Cascadia Code with ligatures, as they are easier to understand (as they look natural) and save some horizontal space.

**Comment by aivarannamaa** [comment]
It looks like Tk's Text widget doesn't support ligatures. So it's not possible, at least not before Tk 8.7 (and I'm afraid it will be years before it gets released and integrated into Python)

**Comment by cybarspace** [comment]
Ah, ok. Thanks for letting me know. 😀
