### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by Boussari** [thonny/thonny#1552]
Bonjour.
Une fois installé, j'ai essayé de lancer un programme. Mais j'obtiens comme information :  import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

Pourriez-vous m'aider ?
Bien cordialement.

**Comment by aivarannamaa** [comment]
How did you install `matplotlib`? Note, that Thonny does not come with this module (unless you installed Thonny XXL)

**Comment by Boussari** [comment]
OK. Merci







Hakim BOUSSARI
 

    Le mardi 19 janvier 2021 à 11:54:45 UTC+1, Aivar Annamaa <notifications@github.com> a écrit :  
 
 


How did you install matplotlib? Note, that Thonny does not come with this module (unless you installed Thonny XXL)
