### ISSUE TITLE
"SyntaxError" when using positional-only arguments

### ISSUE THREAD

**Issue by vis4718** [thonny/thonny#1559]
pyshell as well as editor
<img width="960" alt="Screenshot 2021-01-20 191719" src="https://user-images.githubusercontent.com/77734572/105183403-291bcb80-5b54-11eb-8e23-5005aba913b3.png">

**Comment by aivarannamaa** [comment]
Positional only arguments are supported since Python 3.8, but you are using (bundled) Python 3.7
