### ISSUE TITLE
german localication error in save-dialog

### ISSUE THREAD

**Issue by speedy-10** [thonny/thonny#1568]
Hi, in Thonny 3.3.2 I discovered two missing translations (in German) in the save-dialogs, see pictures.

Furthermore in the top menu
- Datei > Save all files
- Move /Rename
- Bearbeiten > Replace tabs with spaces

: Regards Speedy-10
![Bildschirmfoto von 2021-01-23 15-56-36](https://user-images.githubusercontent.com/20227451/105597257-3626fd80-5d94-11eb-9a55-dd23b59757e9.png)
![Bildschirmfoto von 2021-01-23 15-56-19](https://user-images.githubusercontent.com/20227451/105597300-3921ee00-5d94-11eb-85d6-926a9c07aa86.png)

**Comment by aivarannamaa** [comment]
Thanks!

I made these strings translatable and will update the templates in POEditor soon.
