### ISSUE TITLE
Version 3.3.3 - Crash on Linux Mint if the last opened document contains a UTF-8 smiley

### ISSUE THREAD

**Issue by hubertmeier** [thonny/thonny#1569]
Hi,
i could paste an UTF-8 smiley (🤪) into the micropython source-code for an ESP8266 webserver, the character was not to see but used two spaces ... the code was working.
When i closed Thonny and reopened it, it crashed immediately. 
I corrected the file with geany and Thonny opened without problems.

I would be nice if the UTF-8 signs would work in Thonny like in geany (perhaps colored, at least visible ...).

Thank you

**Comment by aivarannamaa** [comment]
Thank you for the report!

Unfortunately, emojis are not properly supported by Thonny's UI toolkit (Tk).

See #32
