### ISSUE TITLE
Feature: Smart highlighter in the Editor

### ISSUE THREAD

**Issue by georgethemarmot** [thonny/thonny#1587]
Hi, 
it would be nice to get a notepad plus plus smart highlight feature.
If a word is selected, the other occurrences are highlighted. 
Currently it seems only variables and functions are highlighted if the cursor is on the word.
Thanks

**Comment by aivarannamaa** [comment]
Thank you for the suggestion, but I'm afraid it would be confusing. The variable highlighter is meant to highlight the occurrences of the same variable, not the same name. This means if you have used the same name on a local scope and on global scope, then these should not be highlighted together.

I understand that the behavior you suggest could be made optional, but given Thonny's target group I don't find it useful enough.

There may come some changes related to highlighting in future Thonny version, so I'll keep your wish in mind.
