### ISSUE TITLE
Raspberry Pi Pico can't transfer bmp, jpg files with Thonny

### ISSUE THREAD

**Issue by CaptainJackey** [thonny/thonny#1588]
Thonny IDE only can transfer py files to Pico, how to transfer other files just like bmp, jpg or others to Pico ?

**Comment by aivarannamaa** [comment]
Have you seen Thonny's file manager (View => Files)? (Note that if you are in simple mode, you need to switch to regular mode first).

In the local files pane navigate to source folder, right click on the file and select "Upload to ..."

**Comment by CaptainJackey** [comment]
Fink it , thanks

**Comment by davidamis** [comment]
Actually, the default behavior would not show a bmp or jpeg file, only .py files. You need to right-click in the file listing area and choose "Show hidden files".
