### ISSUE TITLE
Historic debugging?

### ISSUE THREAD

**Issue by amogorkon** [thonny/thonny#1590]
Hi,

I love Thonny so far for debugging simple scripts, but I'm wondering and hoping whether it is possible to also do reverse/historic debugging with it?

**Comment by aivarannamaa** [comment]
Hi!

With the "nicer" debugger it is possible to step back in time (Run => Step back). This is useful if you made a "Step over" by accident -- you can then rewind the presentation with "Step back" and go forward with "Step into".

See https://comserv.cs.ut.ee/home/files/leemet_informaatika_2018.pdf?study=ATILoputoo&reference=57D36B3D851E10E6FC750A19E3479D643D8A0FB7 for details.

**Comment by amogorkon** [comment]
Very cool, thank you!
