### ISSUE TITLE
why it doesn't works "cls"

### ISSUE THREAD

**Issue by profsamikaabar** [thonny/thonny#1596]
from random import*
import os
os.system("cls")
x=randint(0,9)
print(x)

**Comment by aivarannamaa** [comment]
Thonny's shell is not a proper terminal emulator. In particular, the subprocess you are calling with `os.system("cls")` has its own console, which is not related to Thonny's shell.

I don't have a Windows machine at hand, but I believe you can get the desired behavior if you use "Run => Run current script in terminal".

**Comment by profsamikaabar** [comment]
Le ven. 5 févr. 2021 à 18:09, Aivar Annamaa ***@***.***> a
écrit :
