### ISSUE TITLE
Feature Request - Add support for sys.stdin.read() and sys.stdin.readlines() method

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#160]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/160) by Anonymous.**

----------------------------------------

The recent version only support for sys.stdin.readline() method which is not sufficient for many purpose. It is painful to get multiline input from stdin without the read() or readline() method.

**Comment by Ivoz** [comment]
It would also be nice to be able to open a dialogue to paste in text to a "stdin file".

i.e; the text of this file/(maybe as a textarea dialog) would be piped to the python program when it is started. You could either have a separate "run with stdin" button, or perhaps a checkbox in the dialogue for whether it is piped or not.

The purpose being many example problems in coursework / assignments etc operate by the program being designed to run where it is fed its data to process via stdin. Such a dialog would allow one to enter sample data to test one's program reading from stdin.

I'm not sure if this feature request belongs here or possibly just a new issue.

**Comment by aivarannamaa** [comment]
Thank you for the idea! It's nice to have, but I'll postpone this for now.

**Comment by aivarannamaa** [comment]
Fixed under #219 

Multiline input text can be pasted to the shell and ended with Ctrl+D
