### ISSUE TITLE
The Debug icons are grayed out

### ISSUE THREAD

**Issue by simcha07** [thonny/thonny#1607]
I have Thonny installed on windows-10.
It is working well, except the debugger.
All debug icons are grayed out. 
How come?
(A  screenshot is attached.)
![Thonny without Debug icon](https://user-images.githubusercontent.com/29655817/107516994-77e5df80-6bad-11eb-88bc-7cd4d5fc7f5d.PNG)

**Comment by simcha07** [comment]
Found (the) (a) solution!
I installed the Thonny IDE again but now not in my own language but I chose for "English".
Now the debug icon(s) are available and not grayed out anymore.
Feel free to respond if there is a solution for an Thonny installation in my own language.
Thanks in advance.

**Comment by aivarannamaa** [comment]
From the screenshot I understand that you are using MicroPython back-end. Debugging is not supported in MicroPython.

**Comment by simcha07** [comment]
> From the screenshot I understand that you are using MicroPython back-end. Debugging is not supported in MicroPython.

That's a pity, thanks for responding!
