### ISSUE TITLE
People may choose "Raspberry Pi" initial settings without knowing it's trimmed

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1609]
https://www.bit-101.com/blog/2021/02/raspberry-pi-pico-what-ive-learned/

Maybe split Raspberry Pi settings into two, such that the options would be:

* "Raspberry Pi (simple)"
* "Raspberry Pi (full)"
* "Regular"

Also, make sure the "Switch to regular mode" is discoverable (at least not hidden as in the screenshot in the blog post linked above)

**Comment by crjase** [comment]
I thought it was to make it compatiable with a raspberrypi pico XD

**Comment by aivarannamaa** [comment]
Now the dialog says more clearly "Simplified, with Raspberry Pi theme and defaults".
