### ISSUE TITLE
module 'tabulate' not found

### ISSUE THREAD

**Issue by RNeuwirth** [thonny/thonny#1611]
In my python (version 3.9.1) application "from tabulate import tabulate" prompts" ModuleNotFoundError: No module named 'tabulate'". IDLE Shell 3.9.1 runs without a problem.

**Comment by aivarannamaa** [comment]
Most probably your IDLE and Thonny are using different Python interpreters, one of them having `tabulate` package and the other not. 

If you want to use it in Thonny then either make Thonny use the same interpreter as IDLE (Run => Select interpreter => Alternative Python 3 ...) or install `tabulate` for Thonny's interpreter as well (Tools => Manage packages).

**Comment by RNeuwirth** [comment]
Thank you.

----- Original Message -----
From: "thonny/thonny"
<reply@reply.github.com>
To:"thonny/thonny" <thonny@noreply.github.com>
Cc:"RNeuwirth" <rneuwirth@optusnet.com.au>, "Author"
<author@noreply.github.com>
Sent:Sat, 13 Feb 2021 22:48:23 -0800
Subject:Re: [thonny/thonny] module 'tabulate' not found (#1611)

	Most probably your IDLE and Thonny are using different Python
interpreters, one of them having tabulate package and the other not. 

	If you want to use it in Thonny then either make Thonny use the same
interpreter as IDLE (Run => Select interpreter => Alternative Python 3
...) or install tabulate for Thonny's interpreter as well (Tools =>
Manage packages). 

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2]. 
-------------------------
Email sent using Optus Webmail

Links:
------
[1]
https://github.com/thonny/thonny/issues/1611#issuecomment-778736769
[2]
