### ISSUE TITLE
Running multiple instances of Thonny

### ISSUE THREAD

**Issue by Venturer** [thonny/thonny#1616]
Is it possible to run more than one instance of Thonny?

I am developping MicroPython applications with two MCUs (ESP32 series) connected to each other. It would be convienient to connect to both of them at the same time during debugging.

Steve Baugh, Bracknell, England
steve@baugh.org.uk

**Comment by aivarannamaa** [comment]
Yes, Thonny can have multiple instances (find the checkbox under "Tools => Options => General"). Unfortunately this doesn't work properly on Mac, see #1554 for a work-around.

**Comment by Venturer** [comment]
Thank you, I've found the setting. Working fine here on Windows 10.
