### ISSUE TITLE
Maximizing a view should keep tabs visible

### ISSUE THREAD

**Issue by Venturer** [thonny/thonny#1617]
The help for expert mode says:

`Double clicking on the tab of an editor or view maximizes this editor or view. Unmaximize by double clicking the tab again.`

In fact once maximized there is nolonger a tab to double ckick to un maximize. One can press Escape or use the view menu to unmaximize. Thonny 3.3.3

A minor point!

**Comment by aivarannamaa** [comment]
Good point!

I should keep the documentation and change the behavior, so that Thonny is more like other IDE-s in this respect.

**Comment by aivarannamaa** [comment]
I decided to remove this feature altogether, because it made implementation messy.
