### ISSUE TITLE
UI To Large and I can't change it.

### ISSUE THREAD

**Issue by Stomiidae** [thonny/thonny#1620]
The general tabs and the run save new command etc are massive and unable to change the size because I can not scroll down is the genral tab because everything is way to large
[problem photos.pdf](https://github.com/thonny/thonny/files/5989737/problem.photos.pdf)

**Comment by aivarannamaa** [comment]
Did it get so large after you tweaked the scaling options? If yes, then

* close Thonny
* execute `rm ~/Library/Thonny/configuration.ini` on Terminal to get back to default settings.
* start Thonny

**Comment by Stomiidae** [comment]
Thanks you that worked!
