### ISSUE TITLE
Feature: Check for new versions

### ISSUE THREAD

**Issue by bsimmo** [thonny/thonny#1626]
Just a request to add the simple everyday feature to _check for new versions._

Provide the option for people who don't want to check for new version for whatever reason.
Provide the changelog so I can decide if it is useful.

Just one of the everyday niceties of computers I miss.

This is probably for the Windows (when not installed via the store as that's automatic, but you don't have a store version)
Mac, Linus distro's no idea.
RPi version, would be nice there too as apt checking isn't automatic.

Reason,
Most of my time I keep having to tell people to have a look for a new version, things change and improvements are made.  People do not naturally go looking. 

It's a feature of pretty much every other program I use.
Why do it manually when the computer can do it for you.

(unless I miss something and it's already there, but it's never alerted me to it.)

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

This has been been in my TODO list for some time now. I'll schedule it for Thonny 4.0 now.

Closing this in favor of #256.
