### ISSUE TITLE
ChatterBot

### ISSUE THREAD

**Issue by ahmet-soner** [thonny/thonny#1642]
![Screenshot_3](https://user-images.githubusercontent.com/79277444/108637526-b758d980-7493-11eb-9874-5c761eabbcd1.png)

**Comment by aivarannamaa** [comment]
I'm sorry, but I'm not here to help with general Python programming questions. Please reopen the issue if your code works properly outside of Thonny but fails in Thonny.

**Comment by ahmet-soner** [comment]
okey

Aivar Annamaa <notifications@github.com>, 22 Şub 2021 Pzt, 08:40 tarihinde
şunu yazdı:
