### ISSUE TITLE
Coronabot

### ISSUE THREAD

**Issue by ahmet-soner** [thonny/thonny#1643]
![Screenshot_4](https://user-images.githubusercontent.com/79277444/108637715-6d242800-7494-11eb-8bff-c681188a147c.png)

**Comment by ahmet-soner** [comment]
I found the solution to the problem
************************************
Or try changing ...
time_func = time.process_time ()
insted of .. time_func = time.clock in
C: \ Users \ Admin \ AppData \ Local \ Programs \ Python \ Python38 \ Lib
site-packages \ sqlalchemy \ util \ compat.py

**Comment by aivarannamaa** [comment]
I'm sorry, but I'm not here to help with general Python programming questions. Please reopen the issue if your code works properly outside of Thonny but fails in Thonny.

**Comment by ahmet-soner** [comment]
Okey

Aivar Annamaa <notifications@github.com>, 22 Şub 2021 Pzt, 08:40 tarihinde
şunu yazdı:
