### ISSUE TITLE
scroll bar uncommon behavior

### ISSUE THREAD

**Issue by dddjjj** [thonny/thonny#1652]
For other apps, when clicks the light gray area of the scrollbar, the window scrolls toward that direction and the dark gray bar moves to that direction too. However, thonny does not either in raspbian. Please fix it so it is easier to move around in the file.
![2021-02-25-202618_1024x768_scrot](https://user-images.githubusercontent.com/9594902/109241841-052d5480-77a8-11eb-8b73-fc78bd64be13.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

This seems to be an issue with themed scrollbars, which I don't know how to solve. Please see #1406 for a work-around.
