### ISSUE TITLE
PyAudio problem

### ISSUE THREAD

**Issue by ahmet-soner** [thonny/thonny#1654]
hi 
I am trying to install pyaudio module from package upload and from terminal, cannot be installed
Do you know why it cannot be installed

**Comment by aivarannamaa** [comment]
No, I don't know. I recommend to google your error message and `pyaudio`

**Comment by ahmet-soner** [comment]
Tamam teşekkürler.

Aivar Annamaa <notifications@github.com>, 26 Şub 2021 Cum, 20:29 tarihinde
şunu yazdı:
