### ISSUE TITLE
Feature Request: Move position of tab

### ISSUE THREAD

**Issue by Hermann12** [thonny/thonny#1666]
It would be nice, if the tab of open files can be moved vie drag&drop to a new position. I work often with a batch of python files and sometimes I need the file on another position to make clear how the program works. I closed than all files and open it again in the right order. Not reaky user friendly. In other programs the tab can by pushed to another position for better order, e.g. drag and drop tab 6 to position 2 and tab 2 to the right end. Maybe there is still a possiblility, what I not know?

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

This is currently not possible, but it has already added to the TODO list: #1156
