### ISSUE TITLE
Pgzero module is not found

### ISSUE THREAD

**Issue by AIzen159** [thonny/thonny#1669]
"Pgzero module not Found", please help.

Installed Thonny on the D: drive and made my first pygame program on it. I activated Pygame Zero Mode and Run the program but displayed an error message on the shell instead which was "...but pgzero module is not found".

Did missed something to install? Maybe a plug-in or something?

**Comment by aivarannamaa** [comment]
I assume you are the same who asked at Facebook and got your case solved.

**Comment by AIzen159** [comment]
Yes thanks. (^-^)/
