### ISSUE TITLE
ManagementError since Thonny 3.3.x

### ISSUE THREAD

**Issue by Crazyhackelkorn** [thonny/thonny#1674]
Hi,
i used Thonny 3.2.7 on macOS 11.2.2 with a Wio Terminal and an modified Ardupy. For Testing little code ideas.

Today i tried a newer Thony version 3.3.5, 3.3.5_alt, 3.3.2 and 3.3.0. All of these print a ManagementError, but the python code works fine

**Errormessage:**
![Bildschirmfoto 2021-03-03 um 17 44 34](https://user-images.githubusercontent.com/61194658/109840389-5cb83e00-7c48-11eb-9183-891d7b39d9b6.png)

**Python code:**
![Bildschirmfoto 2021-03-03 um 17 44 53](https://user-images.githubusercontent.com/61194658/109840395-5e820180-7c48-11eb-9c96-d8e25c70586d.png)
![Bildschirmfoto 2021-03-03 um 17 45 00](https://user-images.githubusercontent.com/61194658/109840396-5e820180-7c48-11eb-814a-e7e3dfc8c9a4.png)

Now I tried running nothing this works but if I but anything insite the editor like space, enter it throws the error.

I found my Problem I have for bigger projekt two files /lib/os.py and /lib/uos.py for a device cross compatibility. Because ArduPy only has ```import os``` and most micropython uses ```import uos```

**Comment by aivarannamaa** [comment]
Thank you for the report!

> Didn't found modul uos ...

I assume your code prints this. Please try what happens when you delete this print statement.

**Comment by Crazyhackelkorn** [comment]
Yes, this print is from my code.
You were right. If I comment this print in ```/lib/uos.py``` out, my compatibility-file work as intended and no more ManagementError.

Thank you for your fast help.
