### ISSUE TITLE
Thonny and RP Pico Lock Up When Code is Run From IDE

### ISSUE THREAD

**Issue by A-Krau** [thonny/thonny#1691]
When running the linked code, Thonny and RP Pico will freeze and require the RP Pico to be unplugged and plugged back in. After power cycle code will run fine.  Stopping and rerunning the same code with Thonny will cause the issue to return.

https://github.com/A-Krau/RaspberryPi_Pico_Pimoroni_Blink

Commenting out all lines after 43 in main.py eliminate the problem which leads me to believe it has to do with writing the json file which happens in the Class FileManage in Blinky.py.

Thonny 3.3.3
Windows 10 (64-bit)
Python 3.7.9 (32-bit)
Tk 8.6.9

pimoroni-pico-micropython.uf2 0.0.9
https://github.com/pimoroni/pimoroni-pico/releases

**Comment by aivarannamaa** [comment]
Thank you for the report!

Have you tried commenting out only the print-statement at line 45?

**Comment by A-Krau** [comment]
Good suggestion.

I just tried running it with link 45 commented out and it didn't seem to have an effect on the issue.  Commenting out lines 87 and 97 in Blinky.py also does not make a difference.

**Comment by aivarannamaa** [comment]
@A-Krau, please check, whether the same problem occurs with newer firmware: https://github.com/pimoroni/pimoroni-pico/releases/tag/v0.1.0

**Comment by aivarannamaa** [comment]
Closing, as Thonny and MicroPython have changed in the meanwhile
