### ISSUE TITLE
Unavailable for Mac OS in Split View

### ISSUE THREAD

**Issue by varna9000** [thonny/thonny#1699]
I tried to split the screen between the browser (Safari) and Thonny, but the OS doesn't allow me to do that for Thonny. It's not an essential feature, but I thought I need to report the issue.

Ps: Just realised that Full Screen also doesn't work for Thonny.

Mac OS: Big Sur
Thonny: 3.3.1

![Screenshot 2021-03-13 at 16 49 58](https://user-images.githubusercontent.com/39020101/111034019-6ac24780-841c-11eb-9528-a4641432b49b.png)

**Comment by aivarannamaa** [comment]
Please try https://github.com/thonny/thonny/releases/download/v3.3.6/thonny-3.3.6_alt.pkg -- this one uses newer Tk, which should support splitting (at least it does in Catalina)

**Comment by varna9000** [comment]
Yes, this version works in Split View on Big Sur. Thanks!
