### ISSUE TITLE
Thonny package install error - can not combine '--user' and '--target'

### ISSUE THREAD

**Issue by dandavies80** [thonny/thonny#1701]
When I try to install certain packages in Thonny, I get the following error

-----------------------------------------------
ERROR: Can not combine '--user' and '--target'

Process failed, return code: 1
-----------------------------------------------

This happens when I try to install PyGame, and Tweepy, but it works for most other modules.  Can anyone tell me what's going on and how I can fix this?

Thank you!

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which platform and Thonny version are you using? 

I can't reproduce this with Thonny 3.3.6 on Ubuntu 20.04 and Pygame 2.0.1

**Comment by dandavies80** [comment]
Hi, thank you for replying.

I'm using Thonny 3.3.6 on Mac OS Catalina v 10.15.7.

Were you able to reproduce it with Tweepy at all?

Thanks for your help.

Dan

**Comment by dandavies80** [comment]
> Thank you for the report!
> 
> Which platform and Thonny version are you using?
> 
> I can't reproduce this with Thonny 3.3.6 on Ubuntu 20.04 and Pygame 2.0.1

**Comment by dandavies80** [comment]
Any ideas?  Thanks!

**Comment by aivarannamaa** [comment]
Strange -- I could install both pygame and tweepy on Catalina with Thonny 3.3.6 without problems.

Are you using "Tools => Manage packages"? 

Are you using the default interpreter, ie. the one bundled with Thonny?

**Comment by dandavies80** [comment]
Yes, I'm using "Tools => Manage packages", and using the default interpreter, the same one that runs Thonny.  I wonder what's different about my setup.

**Comment by aivarannamaa** [comment]
It may be either a `PIP_*` environment variable or a global pip configuration file.

You can investigate environment variables like this:

```
import os
for key in os.environ:
    print("*", key, "=", os.environ[key])
```

See https://pip.pypa.io/en/stable/user_guide/#config-file for possible locations of pip config file.

**Comment by aivarannamaa** [comment]
Did you find a solution?

**Comment by dandavies80** [comment]
Hi Aivar,

No, I wasn't able to fix this issue.  Do you have any other ideas?

Dan

**Comment by aivarannamaa** [comment]
Does it mean you don't have any `PIP_*` environment variables nor pip configuration files?

**Comment by dandavies80** [comment]
Actually, I can't find those!  Do you know where they are on a Mac?  I'm
using Catalina v 10.15.7.

Dan

**Comment by dandavies80** [comment]
If I do, I don’t know where they are.  Do you know where I can look for them?

**Comment by aivarannamaa** [comment]
> If I do, I don’t know where they are. Do you know where I can look for them?

Please see the comment where I gave the snippet for examining environment variables and link about pip config files.

**Comment by aivarannamaa** [comment]
Please reopen if you're still stuck or you have more details to add!
