### ISSUE TITLE
Thonny startup error

### ISSUE THREAD

**Issue by p0960595** [thonny/thonny#1706]
Got this error message when try to run the Thonny, anyone can help to advise?
![Picture1](https://user-images.githubusercontent.com/80742168/111266480-95531100-8665-11eb-95e3-30d249ba74cd.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

This has been reported before, but I haven't been able to reproduce.

Have you been able to run Thonny on this machine before?

**Comment by aivarannamaa** [comment]
Closing as I can't progress with this information. Please reopen if you have more info.
