### ISSUE TITLE
Hide or structure `extras` when displaying the package

### ISSUE THREAD

**Issue by mristin** [thonny/thonny#1707]
Hi!
I am developing two plug-ins for Thonny to help with code testing and verification ([thonny-icontract-hypothesis] and [thonny-crosshair]). I noticed that when I want to install them over `Manage Plug-ins...` menu, the extra `dev` dependencies are displayed.

Here's the related screenshot from [thonny-icontract-hypothesis]:
![dependencies](https://raw.githubusercontent.com/mristin/thonny-icontract-hypothesis/main/readme/install.png)

Perhaps you want to either hide those (as you won't be installing them anyway) or somehow structure the information on the screen so that the user is not unnecessarily confused?

Would you like me to make a pull request for that?

[thonny-icontract-hypothesis]: https://github.com/mristin/thonny-icontract-hypothesis
[thonny-crosshair]: https://github.com/mristin/thonny-crosshair

**Comment by aivarannamaa** [comment]
Thank you for the report!

Good idea! I think it's better to hide them altogether. A PR would be great!

Also, thank you for the screenshot -- I've never seen this dialog with so big resolution, but now I see that I shouldn't measure margins in pixels (#1708).
