### ISSUE TITLE
cannot connect error 111 developing minecraft code in python

### ISSUE THREAD

**Issue by johnrogersavs** [thonny/thonny#1723]

**Comment by aivarannamaa** [comment]
Can't help you with so little information.

**Comment by johnrogersavs** [comment]
Thank you, I have posted details on a new thread with error note and the
commented python program.

The code is an example taken from raspberry pi for dummies ,which should
create a maze to be used in a Minecraft application.

From my experience of building the program in stages, it appears that the
block building function  that builds the maze walls cannot run.
In advance thanks
John

**Comment by aivarannamaa** [comment]
#1726
