### ISSUE TITLE
One Dark theme port for Thonny

### ISSUE THREAD

**Issue by ranelpadon** [thonny/thonny#1748]
**One Dark** is a very popular theme introduced by Atom, then ported to various apps. VS Code is the most popular text editor/IDE now in web development. And the **Top 1** and **Top 3** color schemes in VS Code are ports of One Dark, with a combined **5.5 million downloads**!

<img width="593" alt="Screen Shot 2021-04-03 at 1 29 59 AM" src="https://user-images.githubusercontent.com/4292088/113439058-5cb08700-941c-11eb-99a9-88e1485ff68a.png">

https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Installs

Personally, I love One Dark very much, and use it as my color scheme in all my programming-related apps: `Alacritty`, `Tmux`, `Vim`, `VS Code`, `PyCharm`, `Sublime Text`, `iTerm`, and `Kitty`. I work as a full-time software engineer, and part-time lecturer in a university. This year, I started using the **Thonny** IDE in our introductory programming class, my students like it as well since it's lightweight, has clean UI, has powerful program logic/variable inspector, etc. Although I kinda miss the One Dark color when using it. Eventually, I glimpsed about the **Dracula** theme in Thonny home page, and got the idea of implementing similar one for One Dark. So, here's the result:
<img width="706" alt="Screen Shot 2021-04-03 at 4 44 19 AM" src="https://user-images.githubusercontent.com/4292088/113453129-f9cce900-9437-11eb-85b6-dcfbf16d7d77.png">
 
It's already indexed in **PyPI** as `thonny-onedark`:
https://pypi.org/project/thonny-onedark/

and works as intended in my local when installing from PyPI:

<img width="923" alt="Screen Shot 2021-04-03 at 1 15 56 AM" src="https://user-images.githubusercontent.com/4292088/113439997-2c69e800-941e-11eb-9692-c1aa5f8b0d50.png">

GitHub repo:
https://github.com/ranelpadon/thonny-onedark

Special thanks also to @danspinola, got the idea of the implementation from https://github.com/thonny/thonny/issues/1304. Similarly, I filed this issue just to let you know, and hopefully will be included also in the **Thonny homepage** since One Dark is really popular nowadays. :)

**Comment by aivarannamaa** [comment]
That's great! I added the link to Thonny's homepage and mentioned it in Twitter: https://twitter.com/thonnyide/status/1378058229809348610

**Comment by ranelpadon** [comment]
@aivarannamaa Yay, I've seen it, you could also mention my handle (**`@_ranelpadon`**) in your Twitter post, since I've lost my `@ranelpadon` account years ago. Cheers :)

**Comment by ranelpadon** [comment]
Just realized that the docstrings' indention is not good, so I updated the screenshot:
<img width="706" alt="Screen Shot 2021-04-03 at 4 44 19 AM" src="https://user-images.githubusercontent.com/4292088/113453238-24b73d00-9438-11eb-9fcf-50275cbd4716.png">

I posted it also in Python's Reddit:
https://www.reddit.com/r/Python/comments/mist7k/one_dark_theme_for_thonny_ide/
