### ISSUE TITLE
Device is busy or does not respond

### ISSUE THREAD

**Issue by Keu99** [thonny/thonny#1750]
![](https://user-images.githubusercontent.com/54695818/113456414-7de88780-93ca-11eb-8849-2dc03be9d06e.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

Did you try the suggestions given in the message?

Do you have anything in your main.py?

**Comment by Keu99** [comment]
I try it even unistalling and install thony again, but only when I tried the interpreter for Raspberry Pi Pico, Thony can't detect the port for Raspberry

**Comment by aivarannamaa** [comment]
According to your screenshot, Thonny has connected to Pico, it's just that Pico doesn't answer. This can be because a script is running on your Pico.

Have you used MicroPython with this Pico before? If no, then have you installed MicroPython for it?

**Comment by Keu99** [comment]
I have not used MicroPython with this Pico, I mean even when Pico is disconnected Thony throw the same error.

**Comment by aivarannamaa** [comment]
To be sure, are you trying to use Thonny for MicroPython on Pico or for regular Python 3?

If you want't to use MicroPython, then you need to first install MicroPython on your Pico.

> even when Pico is disconnected Thony throw the same error.

When you disconnect Pico, the error is not supposed to go away. What were you trying to do with Thonny after you disconnected Pico?

**Comment by aivarannamaa** [comment]
Please reopen if you're still stuck and you have more details to add!

**Comment by zrl4836** [comment]
下载 闪存重置 文件 重新 烧录进去 即可解决 https://datasheets.raspberrypi.com/soft/flash_nuke.uf2
