### ISSUE TITLE
Make MP back-end advise Ctrl+C even if only whitespace characters get printed

### ISSUE THREAD

**Issue by bitboy85** [thonny/thonny#1755]
If the device is already executing code thonny does not show its files or some output in the commandline.
The os filemanager still allows editing the files on the device.

I think it would be helpful to print a line like "The device is currently running. Press CTRL + C to abort" or something like this in the comandline line.

Firmware: Adafruit CircuitPython 6.2.0-beta.3-178-gd2563c57d on 2021-03-13; Raspberry Pi Pico with rp2040

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

Did you get anything in the output when your device was running and you connected Thonny to it? Actually Thonny is supposed to print this information, but only if the device doesn't print anything in 2.5 seconds: https://github.com/thonny/thonny/blob/707e69ec3a567df5f82205c5a2ae0d79f186ed25/thonny/plugins/micropython/bare_metal_backend.py#L820

**Comment by bitboy85** [comment]
The Output is just an empty line.
Hitting Enter will give you an error message "WARNING:root:Unexpected echo. Expected b'\r\n', got b''"
![grafik](https://user-images.githubusercontent.com/6197580/113988698-03978780-9850-11eb-8ce6-5d7a89d9d969.png)

**Comment by aivarannamaa** [comment]
Ok, I should then consider only visible characters when deciding whether to print the advice or not.

**Comment by aivarannamaa** [comment]
Thonny 4.0 will print the "device is busy or doesn't respond" message when no visible chars appear after certain time after connection or when interrupt doesn't have an effect.
