### ISSUE TITLE
Error when importing Firebase.

### ISSUE THREAD

**Issue by J-Lennox10** [thonny/thonny#1772]
When I try to import firebase in Thonny I constantly get the error from 

```
Traceback (most recent call last):
  File "C:\Users\jackl\brhyu.py", line 1, in <module>
    import firebase
  File "C:\Users\jackl\AppData\Roaming\Python\Python37\site-packages\firebase\__init__.py", line 3
    from .async import process_pool
              ^
SyntaxError: invalid syntax
```

Any ideas what's wrong? My code is literally just: 

```python
import firebase
```

Any help is greatly appreciated, I need this for a big exam

**Comment by aivarannamaa** [comment]
It looks like this package is not suitable for recent Python versions. See https://stackoverflow.com/questions/52133031/receiving-async-error-when-trying-to-import-the-firebase-package
