### ISSUE TITLE
pi pico

### ISSUE THREAD

**Issue by jimbo95-beep** [thonny/thonny#1777]
when running blink.py /from pi pico book 
no module machine 
I look in search machine installed but still getting no module machine 
whats happening do i have to install a library

**Comment by aivarannamaa** [comment]
Thank you for the report!

Do you have MicroPython or CircuitPython on your Pico? CircuitPthon does not have `machine` module.

If you have MicroPython, then do you have MicroPython interpreter selected? See the lower-right corner of Thonny's window.

**Comment by aivarannamaa** [comment]
Please reopen if you still have this issue an can provide more information!
