### ISSUE TITLE
Not working in High Sierra

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1779]
> not working with my high sierra. before it worked well but suddenly it has stopped to working .. no functioning the button (commands of thonny)
> even alvarannamaa's copy also the same

**Comment by aivarannamaa** [comment]
@gurugr, I created a new issue for your problem.

Do I understand correctly, that you can start Thonny and see its window, but the buttons are not working?

Can you send me a screenshot of your Thonny window?

**Comment by gurugr** [comment]
[
![Screen Shot 2021-04-23 at 14 52 50](https://user-images.githubusercontent.com/65117842/115874085-fed3f580-a443-11eb-9348-a7fd96665dc2.png)
](url)

**Comment by gurugr** [comment]
it is like stuck. not running. when I move it , it's become completely black. i remove it many times restart the computer and reinstall the Tonney but it is the same. i can not understand why it is like this. before it worked  perfectly 
thank you so much for spending time for me.

**Comment by aivarannamaa** [comment]
Please post me your Thonny's configuration file:

Open finder, go to your home directory => Library => Thonny. There should be a file named configuration.ini. Please post it under this GitHub issue (either by copy-pasting or by attaching).

**Comment by gurugr** [comment]
Thank You so much for your effect. I don't know how, but thonny works now suddenly today. but I will attach to you that configuration.ini file here with a screenshot of my directory

 [@@](`[url]([url](url))`)
[general]
configuration_creation_timestamp = 2021-03-01T14:33:49.505761
language = en_US

[view]
full_screen = False
maximize_view = False
shellview.visible = True
assistantview.visible = True
astview.visible = False
stackview.visible = False
exceptionview.visible = False
filesview.visible = False
heapview.visible = False
helpview.visible = False
notesview.visible = False
objectinspector.visible = True
outlineview.visible = True
variablesview.visible = True
show_program_arguments = False
show_plotter = False

[file]
recent_files = ['/Users/imac/Desktop/wew.py', '/Users/imac/Desktop/python/Angela Lessons/first.py']
current_file = /Users/imac/Desktop/wew.py
open_files = ['/Users/imac/Desktop/wew.py']

[run]
working_directory = /Users/imac/Desktop
program_arguments = 
dock_user_windows = False
pgzero_mode = False

[layout]
zoomed = False
notebook_nw_visible_view = None
notebook_w_visible_view = None
notebook_sw_visible_view = None
notebook_s_visible_view = ShellView
notebook_ne_visible_view = VariablesView
notebook_e_visible_view = None
notebook_se_visible_view = ObjectInspector
width = 833
height = 663
left = 611
top = 435
west_pw_width = 255
east_pw_width = 381
nw_nb_height = 255
sw_nb_height = 255
s_nb_height = 285
se_nb_height = 255
ne_nb_height = 255


![Screen Shot 2021-04-26 at 09 30 24](https://user-images.githubusercontent.com/65117842/116046101-03cabc00-a673-11eb-8eca-3869b78fb35f.png)

**Comment by aivarannamaa** [comment]
I've never tried using emojis in my code. I know that earlier versions of Thonny's UI framework (Tk) did have problems with this.

Can you now use emojis without problems?

**Comment by gurugr** [comment]
I've copied a program to see an error with emoji. but the problem was I couldn't erase the code from Thonny. when I check it today thonny has reset (without any previous code) Now I check with a simple code. it worked as usual thank you so much. I guess I've got that error with emojis.
