### ISSUE TITLE
Thonny issue

### ISSUE THREAD

**Issue by Gautam-crypto** [thonny/thonny#1791]
When i am opening thonny it is showing startup error unsuccessful delegation plz reply

**Comment by aivarannamaa** [comment]
plz more inf

**Comment by Gautam-crypto** [comment]
when i am clickining  on thonny exe it is showing a pop up titeled as startup error and delegatuion error is written inside it

**Comment by aivarannamaa** [comment]
Please try the newest version https://github.com/thonny/thonny/releases/download/v3.3.7/thonny-3.3.7.exe

**Comment by Gautam-crypto** [comment]
thanks a lot it worked
