### ISSUE TITLE
Allow specifying SSH port

### ISSUE THREAD

**Issue by dk2jk** [thonny/thonny#1808]
Hello ,
is it possible to open SSH-connection with other port address than 22 ?
Tools -> Options->Interpreter-> remote Python3 SSH   : Hostaddress

**Comment by aivarannamaa** [comment]
Unfortunately, the port is not configurable at the moment. I'll add the possibility in the next version.

Until then your only option is to modify Thonny's souce code. Select "Tools => Open Thonny program folder", find this location: https://github.com/thonny/thonny/blob/40fbb4bd97a5dfb9d008e0519b73c7e9b85e0b4c/thonny/backend.py#L523 and add `port=...` parameter.

**Comment by dk2jk** [comment]
tnx , works

**Comment by ansobczak** [comment]
thanks, helps a lot!

**Comment by vinniec** [comment]
I can't connect even applying the code modification that is suggested here.
```
Can't connect to '10.0.0.2' with user 'u0_a281': Authentication failed.
Re-check your host, authentication method, password or keys.

Process ended with exit code 1.
```
However I realized that I can write the port in the Host field, for example in my case 10.0.0.2:8022
If it helps.
