### ISSUE TITLE
Thonny 'about' message

### ISSUE THREAD

**Issue by samtal** [thonny/thonny#1809]
Hi,
When help is being asked for or an error is reported, we always wish to add system information. 
In Thonny, such info is clearly available in the Help-About, but unfortunately it can not be copied to the clipboard.
It would be nice if you could enable copieng the info which contains all necessary information for reporting issues.
Tanks. 
![image](https://user-images.githubusercontent.com/743855/117303031-eec90680-ae84-11eb-8052-1e3b69ae614d.png)

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

Unfortunately Tkinter (Thonny's UI toolkit) doesn't have a good widget for this. Besides, for most issues, only Thonny version and OS brand is relevant, so there is not much data to be written by hand.

In Thonny 4.0 I'm planning to make it easier to find Thonny's log files, which contain more useful information.
