### ISSUE TITLE
Over-the-air feature

### ISSUE THREAD

**Issue by phme283** [thonny/thonny#1820]
Is it planned to add an over-the-air feature? So that you are able to flash your code via Wifi?

**Comment by aivarannamaa** [comment]
I assume you mean Thonny's MicroPython support and the ability to update py files on the device.

Updating files over WiFi is already possible if your device supports WebREPL.

Which device are you using?

**Comment by phme283** [comment]
@aivarannamaa: Thanks a lot for you quick answer!
Currently, I am starting with a first small home IoT project using an ESP32 and a Raspberry Pi as "server". 

I was not aware of WebREPL and will have a deeper look into it. Google always brought me to "over the air" with the Arduino IDE. So, thanks a lot for your helpful answer.
