### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by Geek-007** [thonny/thonny#1826]
![image](https://user-images.githubusercontent.com/25733662/118904816-2f2c8800-b94d-11eb-9ad6-28cf8a82b223.png)

Hello, what is the cause of this error prompt

**Comment by Geek-007** [comment]
![image](https://user-images.githubusercontent.com/25733662/118905590-972f9e00-b94e-11eb-9017-d3f25b867b1c.png)

anaconda，python3.7

**Comment by aivarannamaa** [comment]
Thank you for the report. I think it has to do with unexpected version of `jedi` (the library which powers Thonny's code completion). Please select "Tools => Manage packages" (while Anaconda back-end is selected) and check the version of `jedi` package.

**Comment by Geek-007** [comment]
update latest version of **jedi** ，solved。
