### ISSUE TITLE
Installing micropython-ssd1306 on Win 7 ends in Error

### ISSUE THREAD

**Issue by prototype-it-co-za** [thonny/thonny#1836]
On trying to install ssd1306 libraries using Thonny "manage packages......" on a Windows 7 machine,  I end up with this error :

Installing to temp directory
Error installing 'micropython-ssd1306': b'403'
Installing to: C:\Users\user\AppData\Local\Temp\tmpj1lsb5k3\

micropip returned with error code 1

Is there any way of overcoming this  ?. 
I did confirm the tmpk... directory was created but dont know what error code 1 means ?

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please try the latest version: https://github.com/thonny/thonny/releases/tag/v3.3.10

**Comment by prototype-it-co-za** [comment]
Hello Aivar

Thank you - it now does work.

rgd
cb
