### ISSUE TITLE
Version Control System embedded on Thonny?

### ISSUE THREAD

**Issue by smfrederico** [thonny/thonny#1844]
Is there a Version Control System embedded on Thonny, such as git is embedded on PyCharm, for exemple?

**Comment by aivarannamaa** [comment]
Sorry for the late reply, I somehow missed the notification.

No, Thonny doesn't have integrated version control.

**Comment by SilverNodashi** [comment]
Are there any plans to integration version control, or even just a history of edited files?

**Comment by aivarannamaa** [comment]
No, I don't think I'll add any kind of VC support any time soon.
