### ISSUE TITLE
Device is bussy

### ISSUE THREAD

**Issue by sekpona** [thonny/thonny#1848]

**Comment by sekpona** [comment]
> _Aucune description fournie._


Device is busy or does not respond. Your options:

  - wait until it completes current work;
  - use Ctrl+C to interrupt current work;
  - use Stop/Restart to interrupt more and enter REPL.
Good evening, every time I connect my ESP CAM IA THINKER card to my computer, I get this error in thonny's
 terminal. Who can help me?

**Comment by aivarannamaa** [comment]
Did you try Ctrl+C or Stop/Restart button?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
