### ISSUE TITLE
Problem with Save all files

### ISSUE THREAD

**Issue by Dan-Essin** [thonny/thonny#1849]
Why does Save all files (to computer) open a dialog to enter a file name.
All of the files have names already.
Save all should know this and just save them once you have selected a directory.

Perhaps there should be an option to overwrite all existing, but this cannot be addressed until "Save All" is made to function correctly.

Thank you

**Comment by aivarannamaa** [comment]
Thank you for the report!

I can't confirm this with Thonny 3.3.10 on Ubuntu. Which OS and Thonny version are you using? 

Does it happen both with shortcut and by selecting the menu item?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
