### ISSUE TITLE
Unable to install mediapipe

### ISSUE THREAD

**Issue by YisrealHung** [thonny/thonny#1850]
Unable to install mediapipe

ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
Process returned with code 1

**Comment by aivarannamaa** [comment]
I assume you are using Windows. It looks like mediapipe only provides wheels for 64-bit Python, but Thonny (by default) comes with 32-bit Python. I recommend installing separate 64-bit Python and configure Thonny to use it (Run => Select interpreter => Alternative Python 3...)

**Comment by YisrealHung** [comment]
Thank you very much for your reply.

**Comment by anonymousehacker818765** [comment]
wOw It worked broo

**Comment by YisrealHung** [comment]
Thank you very much for your reply, I will try it sometime.
