### ISSUE TITLE
problem with autocomplete in  Thonny 3.3.10 and before

### ISSUE THREAD

**Issue by BertrandSahel** [thonny/thonny#1852]
When i use an other version of python than the integrated one, the autocomplete don't work, and says:
Autocomplete error: Python version None is currently not supported

**Comment by aivarannamaa** [comment]
Thank you for the report!

Autocompletion will get a big overhaul in Thonny 4.0, and then I'll make sure your case gets fixed as well.

**Comment by aivarannamaa** [comment]
Should be fixed by now.
