### ISSUE TITLE
How to zoom back in??

### ISSUE THREAD

**Issue by Barry-03** [thonny/thonny#1853]
I can't zoom back in too see my code. what do I do or how do I fix this issue?

**Comment by aivarannamaa** [comment]
Do you mean you made the font size too small to be legible? Did you only change the font size, or UI scaling option?

In the first case you should be able to increase the font size by pressing `Ctrl` and `+` simultaneously.

In the second case you may need or delete the configuration file. For example, assuming you're using Windows, close Thonny, open Windows Explorer, paste `%APPDATA%\Thonny` to the "address bar" and delete configuration.ini.

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem!
