### ISSUE TITLE
Make download/upload commands in batch

### ISSUE THREAD

**Issue by IhorNehrutsa** [thonny/thonny#1867]
Is it possible to upload files to a new device (MicroPython on ESP32) in batch mode (ideally from the command line)?

**Comment by aivarannamaa** [comment]
Thonny doesn't offer this feature, but you could try https://github.com/dhylands/rshell

If you meant whether you can upload several files together, then yes, you just need to select several files (or directories) in the local files pane.

**Comment by IhorNehrutsa** [comment]
rshell doesn't copy a file from WINDOWS host to ESP32 device 
https://github.com/dhylands/rshell/issues/162

**Comment by IhorNehrutsa** [comment]
SOLVED: use mpremote
https://github.com/micropython/micropython/tree/master/tools/mpremote
