### ISSUE TITLE
Micropython v1.16

### ISSUE THREAD

**Issue by The-Bow-Hunter** [thonny/thonny#1869]
In my current version of Thonny (3.3.10) under Windows 10, 64bit using Python 3.7.9 32 bit i am unable to see the latest version of Micropython (1.16., came out yesterday) when im trying to update my Pi Pico via the interpeter selecter. It would be nice to change that

**Comment by aivarannamaa** [comment]
Thank you for the notice! I'll update the link (https://github.com/thonny/thonny/blob/master/data/rpi-pico-firmware.json) once I fix and publish #1868 (hopefully today).

**Comment by aivarannamaa** [comment]
Fixed now
