### ISSUE TITLE
Error in Thonny

### ISSUE THREAD

**Issue by jorgelucas-byte** [thonny/thonny#1881]
TypeError: 'NoneType' object isn't iterable

**Comment by jorgelucas-byte** [comment]
1 from machine import Pin, UART
2
3 led = Pin(25, Pin.OUT)
4 uart = UART(0, 9600)
5
6 while True:
7   command = uart.readline()
8    if "on" in command:
9        led(1)
10   elif "off" in command:
11        led(0)
12    elif "toggle" in command:
13        led.toggle()

The mssage is:  File "<stdin>", line 8, in <module>
TypeError: 'NoneType' object isn't iterable

**Comment by aivarannamaa** [comment]
Thank you for the report! 

It doesn't look like Thonny's fault, though. Does the same program outside of Thonny?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
