### ISSUE TITLE
Installing mail module erroe

### ISSUE THREAD

**Issue by narunkumark** [thonny/thonny#1882]
Getting bellow error while installing main module.

--compile --install-headers 'C:\Users\a_nataraj\AppData\Roaming\Python\Python37\Include\main' Check the logs for full command output.
Process returned with code 1

**Comment by aivarannamaa** [comment]
Is it this package: https://pypi.org/project/Mail/ ?

Considering the last release is from 2010, I don't find it likely that it works in Python 3

Python 3 standard library already has `email` module. Are you sure you need to install something extra?

**Comment by narunkumark** [comment]
sorry that was typo.. its main. corrected the mistake.

**Comment by aivarannamaa** [comment]
Do you really mean https://pypi.org/project/main/ ?

I suspect you actually meant something else than "installing main module", but I can't see what it is.

Can you tell me in more details what you were trying to achieve, what steps did you take and what happened?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
