### ISSUE TITLE
Large Int Object IDs not accurately represented

### ISSUE THREAD

**Issue by Andreilg** [thonny/thonny#1883]
It is my understanding that in python small Int objects ([-5:256]) are not garbage collected and new instances of Int objects of the same value in that range are never created, thus there is only one "5" Int object for example. 

However for numbers outside this range, python will create a new Int object every time an Int object is explicitly bound. This means that explicitly bound large Int Objects of the same value should have different IDs.

The issue I've noticed is that the heap view in Thonny is showing that the Int Object IDs are identical because only one Int object is being created:
![image](https://user-images.githubusercontent.com/52828703/123970104-d6f29800-d986-11eb-9158-7343507c2ec9.png)
While checking the IDs directly in the Python console shows they are different:
![image](https://user-images.githubusercontent.com/52828703/123970763-6a2bcd80-d987-11eb-9158-74fa363e84cf.png)

**Comment by aivarannamaa** [comment]
Did you try running the *script* of two `999999999` objects? According to my experiment, the id will be same.

I suppose Python's compiler optimises memory use when it sees two identical int literals in the source code and uses same runtime object for both. When you create two objects one by one as separate REPL inputs, Python also compiles the statements separately.

**Comment by Andreilg** [comment]
I just checked a script and you are correct. In retrospect it makes sense that a script would be more optimized in this respect.

Thank you for your time.
