### ISSUE TITLE
Device clock sync using UTC instead of Local Timezone on 3.3.11

### ISSUE THREAD

**Issue by lukeflima** [thonny/thonny#1886]
When upgrading from 3.3.10 to 3.3.11 the clock sync is using UTC instead of Local Timezone.
I didn't see any mention of that change anywhere, is it intentional?

**Comment by aivarannamaa** [comment]
Thank you for the report!

No, I did not intend to change this. Which device are you using?

**Comment by aivarannamaa** [comment]
Ouch, I now discovered that a last-minute update to Pico's backend indeed restored the old approach of syncing RTC to UTC. I'll fix this in 3.3.12
