### ISSUE TITLE
Import serial from pyserial issue

### ISSUE THREAD

**Issue by Nutakki2259** [thonny/thonny#1892]
Hi all,

I am just running this `Import serial` and obtaining this error `NameError: name 'IOError' isn't defined` when I connect Raspberry Pi Pico to the PC. I am unable to solve this issue. As the same format works fine in Spyder.

All suggestions are accepted.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Do you try to run `import serial` on your PC (for creating custom communication with a serial device) or on Pico (I don't know a library with module `serial` for MicroPython)?

Do you get this error on Pico or PC (ie. Python 3) ?

**Comment by Nutakki2259** [comment]
I got this error in Pico. I am just importing the serial library and running which shows this error in Pico but not in PC.

**Comment by aivarannamaa** [comment]
Could you give me the whole script you're trying to run on your Pico?

**Comment by Nutakki2259** [comment]
This is the whole code on Pico:

`#!/usr/bin/env python3
import serial
if __name__ == '__main__':
    ser = serial.Serial('COM8', 9600, timeout=1)
    ser.flush()
    while True:
        if ser.in_waiting > 0:
            line = ser.readline().decode('utf-8').rstrip()
            print(line)`

**Comment by aivarannamaa** [comment]
These pieces of code make sense in the Windows PC side, not on Pico, because `serial` is a library for CPython and COM-ports are Windows thing.

**Comment by Nutakki2259** [comment]
Yeah, I know but the `serial` library is working on Anaconda Spyder but not on Thonny with the same Pico.

**Comment by aivarannamaa** [comment]
I suspect I just misunderstood you and you actually want to run your script on CPython and have it talk to your Pico.

In this case, do you have Python 3 back-end selected in Thonny? Can you make a screenshot of your whole Thonny window, which shows the code, error message and the back-end descriptor in the lower-right corner of the window?

**Comment by Nutakki2259** [comment]
Here are the two program structure screenshots that show errors.

![full program](https://user-images.githubusercontent.com/51536760/125451959-2cb05133-9234-4959-8f08-7a9ca57b9658.PNG)


![serial](https://user-images.githubusercontent.com/51536760/125451938-9f56e15d-0456-4e18-b4cd-4b3d195cc0fa.PNG)

**Comment by aivarannamaa** [comment]
I see that you are trying to connect to a COM port on Pico, but that's not possible -- COM ports are a Windows thing, not Pico's MicroPython's. Also, it looks that you have installed PySerial on your Pico, but it won't work there -- it is meant to be run on a regular computer.

You probably want to switch Thonny's back-end to CPython (eg. "The same interpreter which runs Thonny") and then run your code from your local disk.

**Comment by Nutakki2259** [comment]
Thank you for your reply. Can I have an example to run the `pyserial` accessing the port that makes the Pico run the program?

**Comment by aivarannamaa** [comment]
I suggest to ask this at https://www.raspberrypi.org/forums/viewforum.php?f=146 or https://forum.micropython.org/viewforum.php?f=21
