### ISSUE TITLE
startup screen

### ISSUE THREAD

**Issue by sk8nfool** [thonny/thonny#1893]
I just installed Thonny (V3.3.?) and when I started it is popped up a window asking what language and initial settings I want. What is this??? I can't seem to find any mention of this anywhere! I'm running this on a laptop running Ubuntu 18.04. are the initial settings for the OS I'm running Thonny on or the platform I'm building an application for? The options (standard/Raspberry PI) are ambigous. I'm trying to develop an app for the RPi Pico. Here's a screenshot of this window (I hope)
![Screenshot from 2021-07-11 18-10-44](https://user-images.githubusercontent.com/12006794/125211492-c4c10580-e274-11eb-8b8c-938622ad36e0.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

You can develop for Pico with both settings. With Raspberry settings Thonny starts in simple mode, different theme and a couple of other tweaks Raspberry people chose for default settings on Raspberry Pi. I recommend choosing "Standard".

I'll try to make it more clear in the next version.

**Comment by sk8nfool** [comment]
Ah - this sets Thonny's host defaults not the target defaults. That's what needs to be a little more explicit. This is especially true for documentation.

**Comment by aivarannamaa** [comment]
Let's keep this open so I remember to make this dialog more clear.

**Comment by aivarannamaa** [comment]
The options are now:

* Regular
* Simplified
* Simplified, with Raspberry Pi theme and line-based debugger
