### ISSUE TITLE
I think I messed something up on Thonny

### ISSUE THREAD

**Issue by Vikingalchemist** [thonny/thonny#1894]
I am new to all of this and began taking a few courses. I barely touched base with Thonny when I found a program about creating a better way for Arduino to work. I copied what I thought they were saying and it ended up causing Thonny to not even recognize my Raspberry Pi. The following is what is said in the shell: 
Couldn't find the device automatically. 
Check the connection (making sure the device is not in bootloader mode) or choose
"Configure interpreter" in the interpreter menu (bottom-right corner of the window)
to select specific port or another interpreter.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Did you try the suggestion? Did you see any ports to select? If not, then you probably need to reinstall MicroPython.

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
