### ISSUE TITLE
Thonny doesn't see other PY files within a directory

### ISSUE THREAD

**Issue by DmitryMalishev** [thonny/thonny#1897]
I'm launching a Python project's files with Thonny, this one: https://github.com/jcamiloangarita/stocker/tree/master/stocker

Source file 'predict.py' is opened with Thonny, I push Run and get an error that other files of the project imported via project's name at the very top are not found (ModuleNotFoundError: No module named 'stocker').

The solution I found is changing 'from stocker.get_data import total' => 'from get_data import total'

When I open the same file with Python interpreter directly it manages to find other files in the folder and import them correctly without any changes.

**Comment by aivarannamaa** [comment]
Python sees your `stocker` package if it is in the `sys.path`. The easiest way to put a package into `sys.path`, is to execute a script, which is in the same directory as the package directory. 

> When I open the same file with Python interpreter directly it manages to find other files in the folder and import them correctly without any changes.

What do you exactly mean by opening the file? How do you run your file outside of Thonny?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
