### ISSUE TITLE
Thonny on the side of screen

### ISSUE THREAD

**Issue by PI922** [thonny/thonny#1898]
Whenever I enter Thonny, the first thing I'm greeted with is a you're being hacked page from Windows Defender, and then I see a Thonny on the side of the screen..

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Thonny version are you using? Which Windows? 7 or 10 or something else?

Can you give me the screenshot of the defender warning?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
