### ISSUE TITLE
Go to line number.

### ISSUE THREAD

**Issue by jrs69** [thonny/thonny#1903]
I'm new to Thonny, all good!, except I would love a shortcut to go to a specific line, e.g. ctrl+g or ctrl-l etc.

I'm a retired programmer just doing hobby stuff, but were I still working it would be a problem.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

This would be a nice and non-obtrusive addition. I'll add it into my TODO list.

Related to #1665

**Comment by neil9** [comment]
Hear hear. It would be VERY nice to be able to go directly to the line number rather than having to scroll through the whole code.

**Comment by bigrom26** [comment]
I try go to selected line but not work Ctrl-g and not in menu. 
How correct this problem ? 
I work on Win10.

**Comment by aivarannamaa** [comment]
@bigrom26, this feature isn't implemented yet.

**Comment by aivarannamaa** [comment]
Implemented in #2001
