### ISSUE TITLE
Backend terminated or disconnected. Use 'Stop/Restart' to restart on Raspberrry Pi

### ISSUE THREAD

**Issue by adesolasamuel** [thonny/thonny#1906]
I'm running an Optical Character Reading program on my raspberry pi 3 B+, after getting everything running, i decided to transfer to raspberry pi zero but start receiving "Backend terminated or disconnected. Use 'Stop/Restart' to restart" on running it. when i tried to run the code form the terminal, i received "Illegal Instruction"

**Comment by aivarannamaa** [comment]
Thank you for the report!

More details are required here. Which Thonny version are you using? Are you running Thonny on your zero or you are using Thonny's ssh back-end? Do you get this error right after starting Thonny or after running a script?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
