### ISSUE TITLE
Thonny Will Not Install for All Users

### ISSUE THREAD

**Issue by sanfordhelpdesk** [thonny/thonny#1909]
I have tried installing Thonny 3.3.11 as an administrator and it does not show up for other users. I am using a Windows 10 computer. Please advise. Thank you.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Just to confirm -- did you right click the installer and select "Run as administrator"? (It is not enough to run with double-click, even if you are administrator).

Did you see a screen like this: 

![image](https://user-images.githubusercontent.com/1802/126697419-01442924-e574-4928-b360-a39385b19f6a.png)

?

**Comment by sanfordhelpdesk** [comment]
Yes.

**Comment by aivarannamaa** [comment]
I could confirm the problem. Should be tackled together with #1119

**Comment by aivarannamaa** [comment]
The fix will be in Thonn 3.3.12
