### ISSUE TITLE
Issue with RPi.GPIO installation in Raspberry Pico

### ISSUE THREAD

**Issue by Nutakki2259** [thonny/thonny#1914]
Hi,

I have an issue in installing the package `RPi.GPIO` on Raspberry Pico connected to Thonny and I obtain the error as shown in the figure. So, please solve this issue.

All suggestions are accepted!

![GPIO](https://user-images.githubusercontent.com/51536760/126909895-aafa3287-213c-4df0-94e4-c20bbef901e1.PNG)

**Comment by aivarannamaa** [comment]
Thank you for the report!

I see that you are trying to install this package onto your Pico, but from the package description it looks like it's meant for the "big" Raspberry Pi and CPython (instead of MicroPython).
