### ISSUE TITLE
CircuitPython 7 Beta. Device not connecting?

### ISSUE THREAD

**Issue by bitboy85** [thonny/thonny#1921]
I'm currently playing around with CP 7 Beta and noticed, that thonny is not able to connect to the device. It outputs only a blank line on "Stop/restart". To get it working you must press CTRL + C

![image](https://user-images.githubusercontent.com/6197580/127744456-1a9c2277-9ce2-4928-a522-f68c69eceac9.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Thonny version are you using? On which platform? Did CP 6.3.0 work properly in the same Thonny installation?

**Comment by bitboy85** [comment]
Hi, i started again with another board and wasn't able to reproduce the issue.  Maybe the issue is caused by the connected hardware or used libraries on the other board.
So i close this issue.
