### ISSUE TITLE
Syntax theme

### ISSUE THREAD

**Issue by jrs69** [thonny/thonny#1936]
Are the syntax theme config files accessible?, I have trouble with my eyes and I would like to clone one and set the syntax background to "#F0E0B9" ~ "light chiffon".

**Comment by jrs69** [comment]
Found the files here:
/home/june/.local/lib/python3.8/site-packages/thonnycontrib
I had added 2 plug-in themes and they were stored here.

**Comment by aivarannamaa** [comment]
Do I understand correctly that you were able to solve your problem?
