### ISSUE TITLE
micropython. running globals() twice or locals() twice raises exception

### ISSUE THREAD

**Issue by fjcubi** [thonny/thonny#1938]
Same behaviour with nodeMCU and Pi Pico. Won't happen when using Putty.

See excerpt from REPL session below:

    MicroPython v1.16 on 2021-06-18; Raspberry Pi Pico with RP2040

    
    Type "help()" for more information.
    >>> globals()

    >>> globals()
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "<stdin>", line 16, in print_repl_value
    RuntimeError: maximum recursion depth exceeded

**Comment by aivarannamaa** [comment]
Thank you for the report!

I suppose it's caused by Thonny assigning the result of last expression to a global variable `_`. I'll see what can be done with this.
