### ISSUE TITLE
Thonny Crashed on Pico with Circuitpython

### ISSUE THREAD

**Issue by mrkprdo** [thonny/thonny#1940]
Mac OS (Big Sur)
MBP 2017 non-touchbar

I was testing some for loop from Thonny's terminal (that runs Circuitpython on Pico), and I have this code
```
>>> import time
>>> for _ in range(100) # <-- take note of this line
             time.sleep(0.5)
             print(_)
             print(time.monotonic())
```

I ran that code and worked fine, then i did this, on the line I mentioned to take note, I pressed Arrow Up to show previous code and place my cursor before `for` keyword and pressed Enter and boom Beach Volleyball of Death appeared. No other option but to kill the app.

Also weird thing I noticed, I was on my wireless headphones when this happened and It also started a buzzing sound, not sure if it was just Mac.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Can you reproduce this problem or was it a one-time glitch?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
