### ISSUE TITLE
Step in and Step out not working for windows10 installation of Thonny

### ISSUE THREAD

**Issue by AjaySinghPathania** [thonny/thonny#1944]
Hi
It is a wonderful IDE. 
I just loved it.
But when i am evaluating my code both step in and step out feature are shown disabled 
even when i am selecting the complete syntax of code.
Much love from India!!!!

Regards
Ajay Singh Pathania
ajay.pathania9@gmail.com

**Comment by aivarannamaa** [comment]
Thank you for the report!

By chance, are you using a MicroPython or CircuitPython back-end? The debugger is not implemented for these.

**Comment by Rashsaid** [comment]
Iam using pycharm, and step out is not working, what should i do?
