### ISSUE TITLE
Importing module is hit or miss.

### ISSUE THREAD

**Issue by icancwhatusay** [thonny/thonny#1945]
Writing the following in Notepadd++ works fine 

```
import pyautogui as py

py.typewrite("bunch of words")
```

Writing the exact same code in Thonny does not. I get :

![image](https://user-images.githubusercontent.com/6325219/130493565-ae52739a-2d32-441d-8769-22f4238498bf.png)

Even skipping the 'as py' part I get the same error.

In case the screen shot didn't stick, here's the error message:

```
>>> %Run 11.py
Traceback (most recent call last):
  File "C:\Users\************\11.py", line 1, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
>>> 
```

**Comment by aivarannamaa** [comment]
If you can import a module when running from Notepad++ and can't when running from Thonny, then you are using different Python interpreter in either case. 

I assume you installed Thonny via binary Thonny+Python bundle (eg. https://github.com/thonny/thonny/releases/download/v3.3.13/thonny-3.3.13.exe). In this case Thonny is running your programs in its own Python interpreter by default. You can either install required packages for this interpreter, or switch to an external interpreter (with the menu button in the lower-right corner of the main window)

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem!
