### ISSUE TITLE
Where to save to? popup off screen not visible

### ISSUE THREAD

**Issue by guser210** [thonny/thonny#1947]
Where to save to? popup does not appear when you have two displays with different resolutions in windows 10. I have my main display resolution at 3840 x 2400 and a 2nd display at 1080, when the Thonny is in the 2nd display either maximized or restore all popups appear off both screens, forcing me to use Alt + space and the arrow keys to move it back into view. this does not happen when Thonny is in the main screen.

Thonny 3.3.13
System: Windows 10 64bit
Python 3.7.9 32bit
Tk 8.6.9

**Comment by aivarannamaa** [comment]
Please try whether https://github.com/thonny/thonny/releases/tag/v4.0.0b1 works for you

**Comment by guser210** [comment]
Thank you, it fixed the issue.
