### ISSUE TITLE
run function malfunction(?)

### ISSUE THREAD

**Issue by estebon312** [thonny/thonny#1950]
When I click on the run button in Thonney 3.7 IDE, the Raspberry Pi 3B window file manager window opens. What is the setting for the IDE interpreter function?

**Comment by aivarannamaa** [comment]
Thank you for the report!

Have you saved your file? If not, then Thonny opens the save dialog, because currently it can only run saved files.

**Comment by estebon312** [comment]
Okay thanks I’ll make sure I save before running the file.
Sincerely,
Steve Spain
