### ISSUE TITLE
The app is wonderful, my favorite, as I am learning python BUT.... 

### ISSUE THREAD

**Issue by ElBuscador33624** [thonny/thonny#1951]
Hello,

Wonderful yes, but they more you use it, you get tired of fiddling with the windows, trying to adjust them so you can actually see the results that appear in them.
Or is it possible YOU ARE NOT AWARE OF IT?... I doubt it. 
So now I am wondering why would anyone go to the trouble of developing such a great app and not FINISH IT UP properly? Seems like you skipped the app's refining step completely out!

It is like like going to the toilet and having a good dump but not cleaning your ass...  follow me?...  does NOT make sense, does it.

NOTE: I would be glad to send you a link to a small video -via youtube- showing you what I am talking about.
em33624@gmail.com

**Comment by aivarannamaa** [comment]
> I would be glad to send you a link to a small video -via youtube- showing you what I am talking about.

Please do!

In return, I could send you recommendations about how to approach people if you are not happy with something.
