### ISSUE TITLE
Copy in Thonny does not work

### ISSUE THREAD

**Issue by stevio-stack** [thonny/thonny#1955]
I have tried numerous times to copy code from my source using Thonny then paste into a browser window. The copy / paste is not working and it is still pasting the previous content from the clipboard.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which platform and which Thonny version are you using? Did you copy with keyboard shortcut or with the menu? Did you copy from the shell or editor?

**Comment by aivarannamaa** [comment]
Please re-open if you have more details to add!
