### ISSUE TITLE
[suggestion] tooltip with function parameters in editor

### ISSUE THREAD

**Issue by atesin** [thonny/thonny#1960]
hi, thanks for this amazing ide... i am learning python, and this ide looks has the precise features to start being productive

when editing i often don't remember all the huge set of instructions and functions a language has, and have to go another documentation (online or local) for quering everytime, making it inefficient, slow and frustrating

some other ides+languages spawn tooltips in editor (or documentation panel) as we start to type something or click some keyword, showing the syntax/parameters list an instruction/function has, making up easy, speedy and fun

would be great if thonny would have some similar feature, or if it already has please tell me where to read more about it

**Comment by aivarannamaa** [comment]
Thank you for the kind words and sorry for the late reply!

Parameter tooltpis are planned for Thonny 4.0
