### ISSUE TITLE
[tutorial] add windows explorer context menu "edit with thonny" for .py files

### ISSUE THREAD

**Issue by atesin** [thonny/thonny#1962]
this feature could be useful if you code a lot of python files... i was searching for a tool for editing explorer context menus easily but none i tested worked me fine, until i realized doing it directly with regedit is easy and quick enough... here goes

disclaimer: modifying the windows registry could be dangerous for your computer, do it carefully or if unsure better don't

- open regedit, in left pane find HKEY_CLASSES_ROOT key
- search for '.py' subkey
- open and take note the default name at right pane, mine was "Python.File"
- copy the text below and paste in your favorite editor (notepad, madedit, geany, vim, etc)
```
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\Python.File\Shell\EditWithThonny]
"MUIVerb"="Edit with Thonny"
[HKEY_CLASSES_ROOT\Python.File\Shell\EditWithThonny\command]
@="\"C:\\Users\\YourLocalProfileName\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\thonny.exe\" -m thonny %*"
```
- modify "Python.File" and "YourLocalProfileName" to match yours
- note the '...thonny.exe' path should match your phython/thonny installation folder, could be 'C:\\Program files\\...' or anywhere, check it and edit before saving
- save the file somewhere with .reg extension, like 'somename.reg' and double click (read the advice and accept to continue)
- test right-clicking some .py file... if worked you can now safe delete de .reg file

**Comment by aivarannamaa** [comment]
Thank you!

I need to review Windows installer. I thought that it already does something like this.

**Comment by atesin** [comment]
hi...  you could also add a cascade style subbenu, what is actually what i did

![image](https://user-images.githubusercontent.com/8086106/133717802-0f420c4b-217e-494f-975f-037b0d99afdd.png)

as ain image speaks more than thousand words, this is a shot of my regedit

![image](https://user-images.githubusercontent.com/8086106/133720365-92676686-7b50-4fd4-95aa-667de1480cdc.png)

- there was already a 'edit39' key for 'edit with idle' cascade submenu entry, if your new subkey has a 'smaller' name it will appear before previous or with 'greater' name will appear after.... mine is 'edit29' so it appears before (see picture above)
- you can also even create another new additional cascade menu 'edithwithother' or whatever, following this same structure, which must have the string 'MUIVerb'='&Edit with'.... it seems the ampersand '&'tells explorer is a cascaded menu

**Comment by aivarannamaa** [comment]
@atesin , how did you install Thonny? As admin under Program Files or as regular user under home?

According to my experiments, latest Thonny installers still create "Edit with Thonny" context menu (just like early ones did).

**Comment by atesin** [comment]
i installed thonny in my laptop (windows), i am in my pc desktop right now

as i remember, i installed thonny with "pip install thonnyapp" from my normal cmd console window

**Comment by aivarannamaa** [comment]
Oh, in case you pip-installed it, then I can close this issue.
