### ISSUE TITLE
File not closed

### ISSUE THREAD

**Issue by AshDini** [thonny/thonny#1965]
**It seems when writing a file on an ESP32, and the file is closed, the Modified time does not get updated until Thonny is closed.**

I am using Thonny 3.3.13 

[testdir.txt](https://github.com/thonny/thonny/files/7149174/testdir.txt)

**Comment by aivarannamaa** [comment]
Thank you for the report! I assume you mean right-clicking on the file and selecting "Properties".

Please see whether "Refresh" works for you:

![Screenshot from 2021-09-12 10-28-37](https://user-images.githubusercontent.com/1802/132977818-e974b4e5-6226-4a0a-8efc-57a49caae5dc.png)

**Comment by AshDini** [comment]
It works if I issue a file.flush (No opening or closing bracket ?)

**Comment by AshDini** [comment]
This should not be necessary. When the file is closed, the directory
entries should be updated automatically.

Anyhow flush will achieve that. I just don't know why the brackets are not
needed.

While I am at it, what is the name of the configuration file for Thonny
running under Linux ? I have been unsuccessfully searching for it on my
Raspberry py.

Regards

Bob Stanton

**Comment by aivarannamaa** [comment]
> When the file is closed, the directory entries should be updated automatically.

I'm considering this, but it would mean refreshing the list after each run and after each REPL entry. It's not feasible to detect whether a piece of code will change filesystem or not.

> what is the name of the configuration file for Thonny running under Linux ?

It's called configuration.ini on all platforms. The directory can be found via "Tools => Open Thonny data folder"

**Comment by AshDini** [comment]
Thanks!
