### ISSUE TITLE
how to figure out solution for "looks like this file or folder is not writable"

### ISSUE THREAD

**Issue by hariprabhu08** [thonny/thonny#1966]

**Comment by aivarannamaa** [comment]
I take that you tried to save a file in Thonny and you received this error message. Where did you try to save?

**Comment by hariprabhu08** [comment]
Mahnn!! Tons of Thanks for your reply.. i was did in directly choose without folder, I meant i.e Pi, Document, Download,etc.. 

Now I had been chosen the document and tried to save , it works.. :)
