### ISSUE TITLE
New option in the files section

### ISSUE THREAD

**Issue by Pro100BooM** [thonny/thonny#1974]
Add the update function in the files section when working with micropython, which will update the list of files on the microcontroller

**Comment by aivarannamaa** [comment]
Do I understand correctly, that you want to refresh the list? This command is available under the "hamburger" menu:

![Screenshot from 2021-09-12 10-28-37](https://user-images.githubusercontent.com/1802/134683569-bbcfbdd8-9069-4a9b-a8a2-15cf8865af51.png)
