### ISSUE TITLE
[question] assistant: indentation warnings are driving me crazy, how to disable them?

### ISSUE THREAD

**Issue by atesin** [thonny/thonny#1978]
my assistant log are flooding with indentation warnings... i always use 2 spaces instead 4 for indents to prevent my code gets too
 W I D E

in the meantime this (hidden) option becomes available, i would like to disable related warnings, and learn **how to use the assistant** at the same time, because i couldn't find any documentation about it

thanks my prays are listened

**Comment by aivarannamaa** [comment]
Please go to "Tools => Options => Assistant", and paste `bad-indentation` to the big box.

**Comment by aivarannamaa** [comment]
You can check other Pylint message codes here: https://github.com/janjur/readable-pylint-messages

**Comment by aivarannamaa** [comment]
Hope my recommendation solved your problem

**Comment by atesin** [comment]
sorry to not had replied... surely it did, thanks for your answer
... could you add this link to thonny help file?

**Comment by aivarannamaa** [comment]
Added it to wiki: https://github.com/thonny/thonny/wiki/Assistant. Will create internal help page for Assistant later.

**Comment by atesin** [comment]
thanks...  sure this could help more people besides me

i was taking note some other ideas i will open suggestions now
