### ISSUE TITLE
thonny is not in the official repros of ubuntu 21.10

### ISSUE THREAD

**Issue by speedy-10** [thonny/thonny#1979]
Hi, I just can't install thonny by `sudo apt  install thonny` on 21.10. 
I know other installing methods, I just want to share the observation.

Regards

**Comment by Polosssatik** [comment]
Hello, can you tell about other methods?

**Comment by aivarannamaa** [comment]
@speedy-10, thank you for the notification! I asked for advice here: https://askubuntu.com/questions/1366211/how-to-find-out-why-a-debian-testing-package-is-missing-from-ubuntu

@Polosssatik, please see https://github.com/thonny/thonny/wiki/Linux

**Comment by TechCowboy** [comment]
This works on 21.10
bash <(wget -O - https://thonny.org/installer-for-linux)

**Comment by aivarannamaa** [comment]
Created a bug-report at Ubuntu: https://bugs.launchpad.net/ubuntu/+source/thonny/+bug/1950037

**Comment by aivarannamaa** [comment]
@TechCowboy, @speedy-10, @Polossatik, I created bug report at Ubuntu: 
https://bugs.launchpad.net/ubuntu/+source/thonny/+bug/1950037

You can raise the priority of this bug by marking that it affects you and/or subscribing to this bug.

**Comment by speedy-10** [comment]
I just tested the installation on ubuntu 22.04: thonny 3.3.14 can be installed by sudo apt install thonny, nice.
