### ISSUE TITLE
Autocomplete error

### ISSUE THREAD

**Issue by Melahen** [thonny/thonny#1984]
Hi, whenever i try to use the autocompletion, this pop up shows up saying :
Autocomplete error:__init__() takes from 1 to 2 positional arguments but 5 were given

Is there something I should do in order to fix it ?

Python 3.9.5

thanks

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Thonny version are you using? How did you install it?

**Comment by aivarannamaa** [comment]
Please re-open if you have more details to add!
