### ISSUE TITLE
Failure to install Thonny on Ubuntu 21.04 

### ISSUE THREAD

**Issue by TechCowboy** [thonny/thonny#1992]
suggested command is:
sudo apt install thonny

![image](https://user-images.githubusercontent.com/2847372/136632193-1b96fcbc-4153-4dcd-be0f-48e54eb1ac33.png)

I also tried
pip3 install thonny

Which appears to succeed but will not run thonny

![image](https://user-images.githubusercontent.com/2847372/136632435-100be0ab-b15f-4fe3-a89f-109e1bb5fbbb.png)

**Comment by TechCowboy** [comment]
Apparently this option does work:
bash <(wget -O - https://thonny.org/installer-for-linux)

**Comment by aivarannamaa** [comment]
To be handled under #1979
