### ISSUE TITLE
Shell appears to disappear and running programs fails to work.

### ISSUE THREAD

**Issue by avaguelyrabidduck** [thonny/thonny#1999]
I was trying out thonny while trying to get a raspberry pi pico to work, following [this](https://projects.raspberrypi.org/en/projects/getting-started-with-the-pico/7) specific tutorial. I copied and pasted the code into thonny, saved and ran the program, and got a message in shell: >>> %Run -c $EDITOR_CONTENT. after this, shell failed to respond (I could type in it but received no response), and closing and restarting thonny brought up this:
![image](https://user-images.githubusercontent.com/92543207/137372870-10f330d1-50d7-47f4-a0b9-226becc33940.png)

I have has this problem once before, trying the same code, but assumed it was a one-off and restarted my computer, which fixed the problem until i tried the same code again.

While this only affected me on this specific piece of code, it seems a strange error that I can't find anyone else mentioning.

**Comment by aivarannamaa** [comment]
Thank you for the report!

I assume the text "runnint the progam prints ..." comes from your main.py. Can you post this code?

**Comment by avaguelyrabidduck** [comment]
Sorry for the confusion: I meant to demonstrate that running a simple program such as `print('Hello')` would only print the horizontal line. The code I mentioned was just the `print('hello')` shown in the image.

**Comment by aivarannamaa** [comment]
Sorry for the late reply!

Were you able to solve your issue? 

Did you mean you can reproduce this problem only with `print('Hello')`? Do you have anything in your main.py?

**Comment by avaguelyrabidduck** [comment]
No, the code that caused the issue is located under the link in the first
issue report I submitted to github. The print command was simply to
demonstrate how the shell was not working.

**Comment by aivarannamaa** [comment]
MicroPython support will be refactored in Thonny 4.0, so I'll close this with the hope that your case will be solved by then.
