### ISSUE TITLE
Autocomplete error. Run in Python3.

### ISSUE THREAD

**Issue by chianjin** [thonny/thonny#2002]
![截图_thonny_20211017171450](https://user-images.githubusercontent.com/45473376/137620553-5509eee5-ad91-47cc-b138-375a3e630a75.png)
![截图_!aboutdialog_20211017171740](https://user-images.githubusercontent.com/45473376/137620643-ce90502b-a6ea-47ad-be9c-a0a82462e1e5.png)

Autocomplete error. Run in Python3.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Autocomplete will get a big refactor in Thonny 4.0, so I'm closing this, but the problem will be handled.

Your Thonny version is rather old. Did you install it with your distro's package manager? If it doesn't have 3.3, then I suggest uninstalling this and installing binary bundle instead by executing following command:

```
bash <(wget -O - https://thonny.org/installer-for-linux)
```
