### ISSUE TITLE
je n'arrive pas à trouver la solution exacte ...pouvez vous m'envoyer la correction svp

### ISSUE THREAD

**Issue by Six9one** [thonny/thonny#2009]
from random import*
x=randint(0,100)
i=0
while True :
    i=i+1
    y=int(input("donner un entier entre 0 et 100 : "))
    if (y>x):
     print("plus grand")
    elif (y<x):
     print("plus petit")
    if (i==5) or (x==y): break
     if (i==5) and (y!=x):
        print("tu as perdu x=",x)
     else:
        print("bravoo")

**Comment by aivarannamaa** [comment]
Sorry, I didn't understand what's the problem.

**Comment by Six9one** [comment]
> Sorry, I didn't understand what's the problem.

don't worry i find the problem.
