### ISSUE TITLE
How to use Waveshare Pico-Res-Touch-LCD-3.5 with Raspberry Pi Pico controller?

### ISSUE THREAD

**Issue by Roy-Ha** [thonny/thonny#2017]
I am using the Thonny IDE with my Raspberry Pi Pico and Waveshare Pico-Res-Touch-LCD-3.5. The only documentation I found was for pinout installation and C code example. On Waveshare site it says Micro-Python "To Do". Is my only choise C? Or is there a way to configure to use with Thonny?

**Comment by Roy-Ha** [comment]
I wrote enough code using SPI calls to implement some drawing functions, setPixel(), hLine(), vLine(), line(), fill_rect,() fill_triangle(). haven't tackled fonts or touch screen functions. I find serious limitations with what I have done so far. PI Pico does not allow arrays larger than about 10% of the display area, so can't display large images etc.

**Comment by aivarannamaa** [comment]
I see. As this issue is not really specific to Thonny, I'm closing it.

**Comment by CtrlAltFeck** [comment]
They have just added a basic micropython example in the wiki there's code for the 2.4inch  and 3.5inch versions
[https://www.waveshare.com/wiki/Pico-ResTouch-LCD-3.5](url)
