### ISSUE TITLE
Cannot activate step thru function

### ISSUE THREAD

**Issue by JohnS8631** [thonny/thonny#2023]
Hello,

I'm trying to use Thonny to see how my code is interpreted step-by-step. The step-over function, however, is grayed out. Any suggestions for fixing this?

**Comment by krish80552** [comment]
Im facing the same issue in mac Ive used the above Python 3, and ran the code in debug mode yet it is greyed out

**Comment by aivarannamaa** [comment]
@krish80552, did you save the code first? If not, then it is the issue #2415

**Comment by YogiBexar** [comment]
> 

It worked thanks!
