### ISSUE TITLE
Is it possible to modify keyboard shortcuts?

### ISSUE THREAD

**Issue by JourdanFleurus** [thonny/thonny#2028]
Hello,

I'm sorry if this isn't the place for this, I'm not sure.
I'd like to modify the autocomplete shortcut from `CTRL + SPACE` to `SHIFT + SPACE`. Or perhaps have autocomplete on at all time. Is this possible?

**Comment by aivarannamaa** [comment]
Currently changing shortcuts is only possible via directly modifying configuration file: https://github.com/thonny/thonny/wiki/Custom-shortcuts

Having autocomplete on at all time will be possible in Thonny 4.0
