### ISSUE TITLE
Losing track of cursor after switching editor windows - v.3.3.13

### ISSUE THREAD

**Issue by andrecgurgel** [thonny/thonny#2031]
When editing multiple files, cursor disappears after switching tabs.

On Windows10 x64 (En) 21H1 Build 19042.1288

**Comment by aivarannamaa** [comment]
Thanks for the report!

Do you mean you have to click on the editor text in order to get the cursor? In this case I agree it's tedious and I'm going to look for a solution.

**Comment by andrecgurgel** [comment]
That's correct. Even when I click back inside the window the editor doesn't
show the cursor in its previous position. That's enerving. ("Where was I?").

Anyway, thanks for your kind attention.

**Comment by aivarannamaa** [comment]
Fixed under #2737
