### ISSUE TITLE
How do I read library documentation

### ISSUE THREAD

**Issue by Roy-Ha** [thonny/thonny#2032]
I read somewhere that I could type help('modules') in thonny shell. This brings up a list of about 38 modules or libraries. Typing help(machine) gives a very cryptic list of functions for machine. **help(machine.WDT)** brings up:
"**object <class 'WDT'> is of type type
  feed -- <function**>"
Doesn't help me at all about what WDT is, what it does or even how to use it.
All other modules, help(anymodule) brings up an **Error: undefined**.

**Comment by aivarannamaa** [comment]
Because of size constraints, MicroPython doesn't include documentation for the built-in (frozen) code.

Thonny 4.0 will allow inspecting external documentation via code completion.

I assume, you already know https://docs.micropython.org/en/latest/library/machine.html
