### ISSUE TITLE
[suggestion enh] rename a variable/function/class everywhere in one place

### ISSUE THREAD

**Issue by atesin** [thonny/thonny#2034]
hi... i know something similar could be done in menu > find and replace dialog > replace all... but it just replaces "text" in the current file wherever it finds (similar variable names, comments, etc) sometimes screwing the code

while we are coding and our code grows often we need to change reference names for better or more intuitive ones, or to avoid name confussion/collision, even throught different library/module files, and the more big gets our code the more compicated it turns...

some ides like eclipse, netbeans, vscodium, etc, have a feature to change all variable/reference names everywhere at once (even throught different files)... this is extremely useful for shaping our code while we write and it grows, without losing the focus

i found this clear example on visual studio

![bulk rename variables in visual studio](https://blog.ndepend.com/wp-content/uploads/Visual-Studio-Rename-Variable.gif)

**Comment by aivarannamaa** [comment]
Thanks for the suggestion. I'll schedule this for 4.1

**Comment by chandantiwari1** [comment]
I will do it

**Comment by shivvamm** [comment]
i can also do it

**Comment by aivarannamaa** [comment]
Will be handled under #1653
