### ISSUE TITLE
[suggestion] ability to customize mouse operations (right-click to paste text)

### ISSUE THREAD

**Issue by atesin** [thonny/thonny#2036]
hi... surely there are many users like me that are accustomed to call a context floating menu by right clicking the text, and instead find the right-click to paste text feature annoying sometimes....

sometimes i blindly do this to change window focus and thonny inserts random text from clipboard in random places (usually from another application that i used 20 min ago, has nothing to do with python, and dont remember what it was) ... so i have to undo or carefully find the intrusive text to manually delete it .... (maybe you were inspired by putty consle)

my suggestion is to add some configurations to customize mouse operations, like add modifier keys or spawn right-click context menus (menu=rclick, paste=ctrl+rclick... usually ctrl is for copy/paste operations and shift is for move/cut)

or tell me if these configurations can already be set by editing the configuration file directly.... can you add this "configure thonny hidden options by editing configuration file" help page? ...  thanks again

**Comment by aivarannamaa** [comment]
Hmm, are you saying your Thonny pastes text simply by right-clicking? On Windows?  Actually, it's not supposed to do this on any platform.

Can you please give me the exact sequence of steps for reproducing this?

**Comment by atesin** [comment]
mh.. i am not able to reproduce now.... but sometimes it happened, maybe in certain conditions
i will be observant

**Comment by aivarannamaa** [comment]
Sorry for the late reply.

I wasn't aware of this middle-button paste feature. It seems to come from the UI toolkit (Tkinter).

As it works this way also in IDLE (which is also made with Tkinter), I'd leave it as is.
