### ISSUE TITLE
[request enh] ability to arrange tab windows

### ISSUE THREAD

**Issue by atesin** [thonny/thonny#2040]
hi.... in he case of editor window (or subwindow, area, view, pane, or whatever the official name is) tabs are arranged in the order they were opened and cannot be arranged/grouped

lets see i select a bunch of .py files and open all at once, they open in random order (i guess) and if i want to arrange hierarchical according imports or alphabetically, chronologic, whatever, i can't

this could be achieved by several ways, for example adding some options in tab context menu
![image](https://user-images.githubusercontent.com/8086106/141155194-8b209869-dbd4-49af-9edd-ab7b1d28cd33.png)
or/and by adding some buttons in tab bar to move selected tab
![image](https://user-images.githubusercontent.com/8086106/141156864-9efa0b65-3f34-418c-a35a-1f8349e9aea6.png)
or/and by dragging the tab with the mouse, the best (and maybe harder) option IMO, have even the chance to arrange tabs to other panes!... see for example my taskbar (courtesy of some taskbar/start menu configs and [open shell menu](https://open-shell.github.io/Open-Shell-Menu/) and [7 taskbar tweaker](https://tweaker.rammichael.com))
......
![Animation4](https://user-images.githubusercontent.com/8086106/141158538-2f344541-93b9-403a-8ec4-2ecfa96104ef.gif)

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

I think I'll aim for drag-and-drop first.

**Comment by aivarannamaa** [comment]
Fixed under #2737
