### ISSUE TITLE
Problem when deleting a file

### ISSUE THREAD

**Issue by AshDini** [thonny/thonny#2041]
It is difficult to explain so I provided some pictures:
![Image 1](https://user-images.githubusercontent.com/66854499/141275475-b85053a2-2967-44c5-8662-40b95f46fc0e.jpg)
![Image 2](https://user-images.githubusercontent.com/66854499/141275509-4548e980-2b55-4697-8375-2c847d1d67cd.jpg)
![Image 2 5](https://user-images.githubusercontent.com/66854499/141275530-fe06b25f-6c10-4cd0-8d0d-b44f2913a218.jpg)
![Image 3](https://user-images.githubusercontent.com/66854499/141275563-d9204034-85ae-4b6c-b81c-4aaab6d27478.jpg)
![Image 4](https://user-images.githubusercontent.com/66854499/141275590-45414175-c8d0-4684-98ba-ac07ca6b885e.jpg)

**Comment by aivarannamaa** [comment]
Thank you for the report!

Unfortunately I didn't understand how the deletion was related to the error. Also, the whole error message is not visible in the last screenshot. Please use "Copy to clipboard" button and post the error as text!

**Comment by aivarannamaa** [comment]
Deleting via file dialog will be handled (or disabled) at #2044. In the meanwhile delete via file browser view (View => Files)
