### ISSUE TITLE
turtle.py missing in Flatpak

### ISSUE THREAD

**Issue by Gabe1290** [thonny/thonny#2042]
Hello,
I am installing Thonny for schools in Geneva (Switzerland) and the 'turtle.py' module is missing in the Flatpak version of Thonny that we installed using the following command:

flatpak install org.thonny.Thonny

How can I install the missing module?

Thanks
Gabe

**Comment by aivarannamaa** [comment]
Thank you for the report!

Flatpak issues are handled by another project, so please report your issue here: https://github.com/flathub/org.thonny.Thonny/issues
