### ISSUE TITLE
MicroPython firmware lässt sich nicht auf Raspberry Pi Pico installieren

### ISSUE THREAD

**Issue by ChukoHund** [thonny/thonny#2047]
Bin totaler Anfänger und bekomme immer folgende Fehlermeldung:
" raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)> "

Wieso ist das Zertifikat  abgelaufe ? Ich habe doch Thonny neu installiert.

Ich komme nicht weiter und bitte um Hilfe.
Danke
Hänsel, K.-H.

**Comment by aivarannamaa** [comment]
Please see https://github.com/thonny/thonny/issues/1986
