### ISSUE TITLE
Python OSError: [WinError 6] The handle is invalid on Thonny Python Editor 

### ISSUE THREAD

**Issue by IliyasMomin77** [thonny/thonny#2061]
I am using below in my code
t_w=os.get_terminal_size().columns
when i run code in thonny editor i get below error
Python OSError: [WinError 6] The handle is invalid

But same code work if i run from CMD on windows machine

**Comment by aivarannamaa** [comment]
Thank you for the report!

Unfortunately this is not something I can (easily) fix -- Thonny's shell simply isn't a (proper) terminal emulator, so certain features simply won't work. Running your code via terminal (eg. "Run => Run current script in terminal") is your best option here.
