### ISSUE TITLE
Problem running a Flask program

### ISSUE THREAD

**Issue by DocObvious** [thonny/thonny#2062]
Hi

I am trying to run some code that works without issue on my pi 4 but when I try on a new PiZeroW2 with fresh sd card I get an error:

No module named thonny.plugins.cpython.app

**Comment by aivarannamaa** [comment]
Hi!

It looks like you have tried to post an image but it is not visible. Better copy paste the error text.

**Comment by DocObvious** [comment]
Apologies have updated the original post with the error. Thanks

**Comment by aivarannamaa** [comment]
Does the error message consist of this single line you sent me? No stack-trace?

**Comment by DocObvious** [comment]
I don't recall a full trace back but I will double check. Thanks

**Comment by DocObvious** [comment]
Really sorry I haven't updated this the full error is as follows:

 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/usr/bin/python3: No module named thonny.plugins.cpython.app

**Comment by yichenemma** [comment]
maybe try to run the program via terminal instead of Thonny?
