### ISSUE TITLE
Inserting a tab in editor is sometimes impossible.

### ISSUE THREAD

**Issue by WolleKette** [thonny/thonny#2069]
I use Thonny in the current version 3.3.13 on MacOS 12.0.1
Under some circumstances it is not possible to enter a tab character in the editor. I think it is related to the code completion.

We have the following line in the editor:   (**The Underscores represents Spaces**) 
>from modul1 ____  import *

If the cursor is directly behind the character "1", then nothing happens after the pressing the Tab key. 
If it is at any other position between modul1 and import, then the word import is doubled. Very strange.

Here the line before and after pressing the Tab key:
>from modul1 ____  import *
>from modul1 ____  import  import *

**Comment by aivarannamaa** [comment]
Thonny by default uses tab key for autocompletion, except in the beginning of the line. You can turn it off in "Tools => Options => Editor".
