### ISSUE TITLE
Consistent behaviour of the tab-key ?

### ISSUE THREAD

**Issue by speedy-10** [thonny/thonny#2070]
Thonny 3.3.13 on ubuntu 20.04.3.

I'm not sure if it's a bug, or I don't understand thonny in detail. 

If I press in thonny the "tab-key" in a new line, the cursor jumps 4 "spaces forward" as I assume.

But if I press the tab-key after a command, the cursor doesn't move forward and built-in commands are suggested as autofulfilment. In the typical IDLE pressing the tab-key makes the same as before: moving 4 spaces forward.
See pictures.

Regards

![Bildschirmfoto von 2021-12-08 14-15-41](https://user-images.githubusercontent.com/20227451/145231481-4f52df71-35fd-452b-b77e-90f5f6875730.png)

![Idle](https://user-images.githubusercontent.com/20227451/145231509-3c7c848b-3ccb-42d4-b352-589b3b02639d.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please see #2069 for explanation and solution
