### ISSUE TITLE
ESP32: How to hard reset ESP32 via the RTS pin of USB/COM converter CP2102?

### ISSUE THREAD

**Issue by IhorNehrutsa** [thonny/thonny#2071]
Sometimes I make mistakes in my code wich break REPL communication. 
Is Thonny has command for hardware reset of chip, like the **esptool**?

https://github.com/espressif/esptool/blob/master/esptool.py#L585-L588
```
            self._setRTS(True)   # EN=LOW, chip in reset
            time.sleep(0.1)
            self._setDTR(True)   # IO0=LOW
            self._setRTS(False)  # EN=HIGH, chip out of reset
```
Thank your.

**Comment by aivarannamaa** [comment]
Thank you for the request!

No, Thonny does not have such feature. Do you specifically want a command for hard reset or the ability to automatically reconnect after hard reset?

**Comment by IhorNehrutsa** [comment]
Yes I want a command(to make a keyboard shortcut) for hard reset the microcontroller and then automatically reconnect Thonny after hard reset.

Thank your very much.

**Comment by bnelsey** [comment]
for hard resetting the microcontroller, sending these two commands does the job:
```
import machine
machine.reset()
```
if we can get a shortcut to send those two commands so we don't have to type them out each time would be awesome

**Comment by IhorNehrutsa** [comment]
@bnelsey 
machine.reset() is not a hard reset, only a soft one. 
It will work when REPL can get and perform the command.
It does not work when the software is locked in an infinite loop or a blocking operation is in progress.

**Comment by aivarannamaa** [comment]
The problem is that different ESP-s on different platforms have different ways of invoking the hard reset. I'm afraid I don't have time for this feature.

**Comment by IhorNehrutsa** [comment]
I suggest moving this task to the 5.1... or 6.0... milestone.
Thanks.
