### ISSUE TITLE
Thonny

### ISSUE THREAD

**Issue by mikedabb6** [thonny/thonny#2110]
I am still having a lot of problems with Thonny. It seems a very flaking program as sometimes it works and other times it does not.

The Stop/Restart Backend does not always work with it just showing the lines as below when the button is clicked.

Is there a better program to use that will work with hub75 board and picodisplay2 in Python as I waste a lot of time using Thonny?

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by aivarannamaa** [comment]
Try Mu editor or various plugins for multipurpose IDE-s.
