### ISSUE TITLE
I cannot uninstall Thonny in MACBook

### ISSUE THREAD

**Issue by Cod3rror** [thonny/thonny#2111]
Hi, how to uninstall Thonny from Mac.. it prevents me from shutting down my laptop.
![269937857_1804689923061327_6229883056039746467_n](https://user-images.githubusercontent.com/97334701/148637854-f827a232-a271-48a5-9f5f-b5331af063eb.jpg)

https://user-images.githubusercontent.com/97334701/148637859-6eb6cce4-74a7-417c-b827-5b098b5b6456.mp4

**Comment by aivarannamaa** [comment]
Did you use pkg-installer? By default it installs under Applications, not desktop, so did you manually change the install location?

What happens, when you right-click Thonny and select "Send to trash"?

**Comment by aivarannamaa** [comment]
Please reopen if you have more information to add
