### ISSUE TITLE
 Unable to connect to COM5: port not found  Backend terminated or disconnected. Use 'Stop/Restart' to restart.

### ISSUE THREAD

**Issue by ocdarragh** [thonny/thonny#2116]
I keep getting this message on Thonny....any ideas?
It seems to be constantly running. When I hit stop it happens again.
I cannot run any file

**Comment by aivarannamaa** [comment]
Do you want to run MicroPython or Python 3 code?

**Comment by ocdarragh** [comment]
Python 3 code.

I was trying to connect a microbit through Thonny but now I am trying to run a simple Python file



Thanks,
Darragh
________________________________

**Comment by aivarannamaa** [comment]
In this case you need to switch back to Python3 mode. Click the button on the lower_right corner of the main window.

**Comment by ocdarragh** [comment]
That worked!
Thanks

________________________________
