### ISSUE TITLE
New ESP8266 based Wemos D1 mini pro with 16 MB requires extra step in firmware installation process.

### ISSUE THREAD

**Issue by JackV2020** [thonny/thonny#2119]
The Wemos D1 mini pro with 16 MB of memory needs something extra downloaded to the chip.
A working procedure is on https://www.jarutex.com/index.php/2020/09/20/119/
It boils down to 1 extra file which has to be sent by esptool.py in the same go.
Commands I used to install and test from lubuntu are :
- esptool.py --port /dev/ttyACM0 erase_flash
- esptool.py --port /dev/ttyACM0 --baud 460800 write_flash -fm dio -fs 16MB 0x0 esp8266-20200911-v1.13.bin 0xffc000 esp_init_data_default.bin
- minicom  --device /dev/ttyACM0
Now I can connect with Thonny :+1: 
They use firmware 20200911 v1.13 which also works fine for me, but there is a newer version available.
I tried the newer version but that does not work on my Wemos D1 mini pro's so I use the one they use.

Kind regards,
Jack Veraart

**Comment by aivarannamaa** [comment]
Thank you for this information!

I don't think I can use it in Thonny, though. There's a large number of ESP boards with several possible MicroPython variants so it's not feasible to account for all of these in Thonny.
