### ISSUE TITLE
celluloid not recognized 

### ISSUE THREAD

**Issue by f5exo** [thonny/thonny#2122]
ModuleNotFoundError: No module named 'celluloid'

from celluloid import Camera

The script run good in linux terminal, but not with thonny.

if you have any solution .

Thank's

Erick

**Comment by aivarannamaa** [comment]
If you installed Thonny+Python bundle, then the default interpreter does not use system's Python packages. In this case you either need to install `celluloid` for Thonny's Python as well (Tools => Manage packages) or make Thonny use system Python for running your programs (the button in the lower-right corner of the main window).

**Comment by f5exo** [comment]
Thank you for responding to my request for help.
Indeed, I was able to install the celluloid package from the tool manage package menu.
And so I can run the script without any problem.
A big thank you to you.

Erick 


On Sat, 15 Jan 2022 03:04:09 -0800
Aivar Annamaa ***@***.***> wrote:

> If you installed Thonny+Python bundle, then the default interpreter does not use system's Python packages. In this case you either need to install `celluloid` for Thonny's Python as well (Tools => Manage packages) or make Thonny use system Python for running your programs (the button in the lower-right corner of the main window).
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/thonny/thonny/issues/2122#issuecomment-1013662690
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


-- 
Liné Erick 
[Dept53 Laval]
***@***.***>

**Comment by aivarannamaa** [comment]
You're welcome!
