### ISSUE TITLE
[bug] 'preferences' screen unbound "tab" causing fault

### ISSUE THREAD

**Issue by SpudGunMan** [thonny/thonny#2127]
includes an additional tab that was not intended for production release. unbound and causes a fault also unbound. could inject code here etc. 

osx12 3.1.13

reproduce by opening preferences and clicking the "untitled tab", crash

**Comment by aivarannamaa** [comment]
Thanks for the report! I can't reproduce it, though. Can you post a screenshot?

**Comment by SpudGunMan** [comment]
also its not a fault I misspoke the windows seem to fly around when clicked

![image](https://user-images.githubusercontent.com/12676665/149997017-ce6b52b5-aa1b-49fc-be90-c8fce8b4545d.png)

**Comment by aivarannamaa** [comment]
I see. It looks like the same problem, which is mentioned for IDLE in https://bugs.python.org/issue34864 and https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/idlelib/macosx.py#L115

            'WARNING: The system preference "Prefer tabs when opening'
            ' documents" is set to "Always". This will cause various problems'
            ' with IDLE. For the best experience, change this setting when'
            ' running IDLE (via System Preferences -> Dock).'

Does changing this preference fix Thonny for you?

**Comment by aivarannamaa** [comment]
Probably related to #1721

**Comment by SpudGunMan** [comment]
check this out https://www.reddit.com/r/mac/comments/qp6t25/monterey_ignoring_prefer_tabs_always_when_opening/

anyway looks like its a mess, just never seen it till now!

**Comment by aivarannamaa** [comment]
Did you find a solution?
