### ISSUE TITLE
feature request: open binary containers mpy

### ISSUE THREAD

**Issue by SpudGunMan** [thonny/thonny#2128]
https://docs.micropython.org/en/latest/reference/mpyfiles.html

adding to the open encoded dialog

**Comment by aivarannamaa** [comment]
Do I understand properly that you want Thonny's editor to be able to show the bytecode in mpy files?

**Comment by aivarannamaa** [comment]
Sorry, but this doesn't sound useful enough for Thonny's target group (beginners).
