### ISSUE TITLE
Autocomplete error thonny 3.3.13

### ISSUE THREAD

**Issue by oz-y** [thonny/thonny#2130]
Hey, I have downloaded thonny 3.3.13 on ubuntu linux. I get this message:
Autocomplete error: __init__() takes from 1 to 2 positional arguments but 5 were given.
I like thonny a lot.

**Comment by aivarannamaa** [comment]
Thank you for the report! I suppose there's a confusion with the version of the library used for completing. Thonny 4.0 will have refactored library loading and completions, so I'll believe your case will be fixed as well.
