### ISSUE TITLE
Watch window needed

### ISSUE THREAD

**Issue by smblackledge** [thonny/thonny#2132]
1)Right now, the local variable display can be crowded, showing more information that is needed at that moment.  Other debuggers have a watch feature that shows one or more variables that you select along with their current values.

2)To be displayed at breakpoint or single-step.

3)This window would float.

4)If the variable is numeric, you can choose the base that it's value is displayed in (2, 10, 16?).

5)You can change the value of the variable by over-typing it's value field.

6a)Thonny shouldn't bring up the watch window when starting, but if selected, it should remember what variables were being previously watched. 6b)I suppose a "clear" option should exist to reset the watch window back to an empty state.

7)Variables being displayed should maintain the same order as when entered OR an option could exist that would display them in alphabetic order.

8)The variable type and location can be anything (display local, global, object, etc.). If the variable is out-of-scope, don't display anything.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion! I'll keep #2132 for this discussion. If I get to implementing it, I'll check this issue as well.
