### ISSUE TITLE
Pressing "Run" opens up my File Explorer instead of running code

### ISSUE THREAD

**Issue by sajiyoyo** [thonny/thonny#2133]
Hello,
I've recently attempted to put the "Shell" on the right-hand side by adding the line: **_shellview.location = ne_** under [view] in the configurations of Thonny's data folder. It caused problems, so I deleted the configuration.ini and reset Thonny back to normal.
However, ever since I've reset it, for some reason whenever I press on the green "run" button after writing a program, my File Explorer immediately opens up, instead of running the actual program.
 I wonder if there is a fix to this? Thank you!

**Comment by aivarannamaa** [comment]
Are you sure it's the file explorer and not file save dialog? If you run untitled editor, then Thonny first asks you to save the file.
