### ISSUE TITLE
feature request binary encoding type to hex

### ISSUE THREAD

**Issue by SpudGunMan** [thonny/thonny#2134]
adding binary as an option to open for loading and saving would be nice to move support files on and off connected devices and check readable assets in the binary

https://github.com/thonny/thonny/blob/a338f2892d10e9a9e50b4b4417ffd69d2d1837a5/thonny/editors.py#L198

this section here appears to look for and deny binary.. could something be added to read and write them into hex?

```
 >>> import binascii
 result = (binascii.hexlify(filename))
```

**Comment by aivarannamaa** [comment]
You can transfer any files via Files view (View => Files). Right-click on a file on the local (or device) pane and select "Upload ..." (or "Download ...")

**Comment by SpudGunMan** [comment]
oh snap, I feel like a fool. very nice.

**Comment by aivarannamaa** [comment]
You're not the first one who failed to discover this feature. I'll see whether I can do something about his.
