### ISSUE TITLE
So is there an answer somewhere? I get the same issue : F5 lowers screen brightness -> my goal was to run the debugger as per https://thonny.org/    where Ctrl+F5 is suggested

### ISSUE THREAD

**Issue by MatrixMike** [thonny/thonny#2135]
So is there an answer somewhere? I get the same issue : F5 lowers screen brightness -> my goal was to run the debugger as per https://thonny.org/    where Ctrl+F5 is suggested

_Originally posted by @MatrixMike in https://github.com/thonny/thonny/issues/1033#issuecomment-1019042614_

**Comment by aivarannamaa** [comment]
I suppose your laptops maps several virtual keys under single physical key. My Lenovo also has single key for both F5 and lowering screen brightness. If Fn Lock is on, the key, when pressed alone, reduces brightness and for F5 I need to press it together with Fn. If Fn Lock is off, it's vice-versa.

In my laptop I can toggle Fn Lock with Fn+Esc.
