### ISSUE TITLE
ManagementError installing packages

### ISSUE THREAD

**Issue by uliseswolo** [thonny/thonny#2145]
Installing to temp directory
D:\Programas\Thonny\python.exe -m thonny.plugins.micropython.minipip install --target C:\Users\uliwo\AppData\Local\Temp\tmpfwyel2o0 micropython-ssd1306
Processing 'micropython-ssd1306'
Querying package metadata from https://micropython.org/pi/micropython-ssd1306/json
Could not find 'micropython-ssd1306' from https://micropython.org/pi
Querying package metadata from https://pypi.org/pypi/micropython-ssd1306/json
Inspecting version 0.3
Extracting 'micropython-ssd1306' from https://files.pythonhosted.org/packages/01/d0/0841d47772962c80af3ab178ef062ed2cd524cb99eb38463e669428402a8/micropython-ssd1306-0.3.tar.gz to C:\Users\uliwo\AppData\Local\Temp\tmp4ojm48yo
Copying files to C:\Users\uliwo\AppData\Local\Temp\tmpfwyel2o0
Copying ssd1306.py
Copying to the device
C:\Users\uliwo\AppData\Local\Temp\tmpfwyel2o0\ssd1306.py (4740 bytes)

Could not write next block after having written 0 bytes to /lib/ssd1306.py

NB! Thonny could not execute 'upload'.

SCRIPT:
__W(b'# MicroPython SSD1306 OLED driver, I2C and SPI interfaces\r\n\r\nfrom micropython import const\r\nimport framebuf\r\n\r\n\r\n# register definitions\r\nSET_CONTRAST = const(0x81)\r\nSET_ENTIRE_ON = const(0xA4)\r\nSET_NORM_INV = const(0xA6)\r\nSET_DISP = const(0xAE)\r\nSET_MEM_ADDR = const(0x20)\r\nSET_COL_ADDR = const(0x21)\r\nSET_PAGE_ADDR = const(0x22)\r\nSET_DISP_START_LINE = const(0x40)\r\nSET_SEG_REMAP = const(0xA0)\r\nSET_MUX_RATIO = const(0xA8)\r\nSET_COM_OUT_DIR = const(0xC0)\r\nSET_DISP_OFFSET = const(0xD3)\r\nSET_COM_PIN_CFG = const(0xDA)\r\nSET_DISP_CLK_DIV = const(0xD5)\r\nSET_PRECHARGE = const(0xD9)\r\nSET_VCOM_DESEL = const(0xDB)\r\nSET_CHARGE_PUMP = const(0x8D)\r\n\r\n# Subclassing FrameBuffer provides support for graphics primitives\r\n# http://docs.micropython.org/en/latest/pyboard/library/framebuf.html\r\nclass SSD1306(framebuf.FrameBuffer):\r\n    def __init__(self, width, height, external_vcc):\r\n        self.width = width\r\n        self.height = height\r\n        self.external_vcc = external_vcc\r\n        self.pages = self.height // 8\r\n        self.')

STDOUT:

STDERR:
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "<stdin>", line 4, in __W

OSError: 28

You may need to reconnect, Stop/Restart or hard-reset your device.

Error ManagementError

**Comment by uliseswolo** [comment]
can´t manage to install any package, keep showing that error or [Errno 2] ENOENT (missing file as I looked it up)

**Comment by aivarannamaa** [comment]
Thank you for the report!

Do you have a `/lib` directory next to your `main.py` (ie. `/lib` or `/flash/lib`, depending on the device)?  If not then create it manually

![image](https://user-images.githubusercontent.com/1802/151798849-e69a7fc8-989e-4256-8ee4-7563ce4ffecb.png)

and try again.

If this helps, then please let me know!

**Comment by aivarannamaa** [comment]
The right folder name can be queried with:

```
import sys
print(sys.path)
```

**Comment by aivarannamaa** [comment]
Were you able to make it work after creating the directory manually? If not then please try https://github.com/thonny/thonny/releases/tag/v4.0.0b1

**Comment by Small-Wooden-Soul** [comment]
Hi, @aivarannamaa .  Firse, please forgive me my poor English. 
I have the similar problem.
I want to install **_micropython-mpu9250_** package. But I can't install package by Manage packages.

![mpu](https://user-images.githubusercontent.com/98692940/164284481-f69f2c2d-461c-4c08-90e3-6af339c2cd9a.jpg)

The error of minipip showed is same as @uliseswolo  .

I saw you said create `/lib` if we don't have this directory. 
But I'm not sure were you meant this?

![1650474087489](https://user-images.githubusercontent.com/98692940/164285048-ce967b3a-926d-4144-abb2-bd61e47bfaa4.jpg)


I thought I already have `/lib` directory. But I still can't install successful.
Am I misunderstand what you mean? Or I just missing something?
