### ISSUE TITLE
losing theme colors and bold after saving on Raspberry pico

### ISSUE THREAD

**Issue by Thomas-R-27** [thonny/thonny#2152]
Hi,
I am using Thonny 3.3.13 on Windows and as soon as I save some code on the Raspberry pico, all the theme colors and bold vanish. If I open a new window and paste the code, I get the theme, but is disappears again once saved. This does not happens if I save to my computer, only when I save to the nano. Any hints?

Many thanks!

Thomas

**Comment by aivarannamaa** [comment]
I suspect you didn't give `.py` extension to your filename. When saving to local disk, the `.py` extension will be added automatically if you don't provide another extension.

**Comment by Thomas-R-27** [comment]
You're right, thanks a lot!

Thomas
