### ISSUE TITLE
Ctrl+F5 is gray color, can't change to nice debug mode,

### ISSUE THREAD

**Issue by jmsbho** [thonny/thonny#2155]
Only F5 is active, All debug function is gray color, How to make them active? 
Version: 3.3.13 in Windows10
Thank you!

**Comment by aivarannamaa** [comment]
Are you using MicroPython back-end? Debugging is not implemented for MicroPython.

**Comment by jmsbho** [comment]
Yes, I connected a esp32 device, so debug function is disable. Thank you!
