### ISSUE TITLE
thonny does not detect RPi Pico device.

### ISSUE THREAD

**Issue by bret4811** [thonny/thonny#2156]
Thonny and the Pico are working OK on a Windows 10 pc.  On Ubuntu pc, Thonny is running but does not recognise that a Pico is connected.

Windows 10 installation - V3.3.13.
Ubuntu - V3.2.7. (I have both python 3.8.10, python 2.7(default))

I have attached a text log from the terminal of the installation.
Ubuntu installs up to V3.2.7.  From the forums it is known that V3.2.7 cannot detect a Pico.   I found a script that was intended to update the installation. You will see that the installation progresses without problems.  However, when I run Thonny the version displayed remains V3.2.7.  The shell window indicates that Ubuntu 3.8.10 is running, it does not report MycroPython v1.18 from the Pico like the windows version did. Applying Stop/Restart simply restarts Ubuntu python V3.8.10.

Best regards.

[install.txt](https://github.com/thonny/thonny/files/7996798/install.txt)

**Comment by aivarannamaa** [comment]
Can it be that you have also pip-installed Thonny? 

If you have apt-removed old Thonny version, then also try `python3.8 -m pip uninstall thonny` and try again running the binary bundle variant of Thonny.
