### ISSUE TITLE
Thonny has no useable titlebar

### ISSUE THREAD

**Issue by nathanbern** [thonny/thonny#2163]
Using Thonny 3.3.14 on my pi 3 A+ with the latest OS, it does not have a titlebar, or the titlebar has disappeared behind the system toolbar. I have seen mention of fixes to this issue in pull requests but it appears it is on going. Just an FYI. See attached screenshot.

**Comment by nathanbern** [comment]
![myimage](https://user-images.githubusercontent.com/92954139/153286536-0cddab5d-d0aa-40b6-bee4-30c3cbc80299.png)

**Comment by nathanbern** [comment]
Screenshot is blurry in preview but looks OK if you open it.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Can you temporarily reduce your RPi taskbar size so that you get to move Thonny's window.

**Comment by aivarannamaa** [comment]
Were you able to solve this issue?

**Comment by nathanbern** [comment]
Hi! Sorry, I've been dealing with a bunch of other stuff and haven't been
on the software side of my job for a few weeks. If I remember correctly the
workaround I had to use was move the pi's taskbar/menu bar to the *bottom*
of the screen. Not the cleanest but it worked.

Thanks for following up!

NB
