### ISSUE TITLE
Could not import jedi (autocomplete)

### ISSUE THREAD

**Issue by TravelTrader** [thonny/thonny#2165]
Same error for me as in #406.

I am using Ubuntu 18.04.
And I am using the default interpreter.
Just tried thonny the first day. No options changed.

**When pressing <ctrl+space> a message box opens, saying "Autocomplete error" and "Could not import jedi".**

Are there any solutions already?

**Comment by TravelTrader** [comment]
I installed thonny by `sudo apt install thonny` and had an old version. Now I used the installation for the latest build and autocomplete works. Thanks!

**Comment by abhx-x11** [comment]
thanks
