### ISSUE TITLE
How to read input() from a text file in Thonny?

### ISSUE THREAD

**Issue by memiarz** [thonny/thonny#2166]
Hi,

I'm new to Python, and I've just installed Thonny. I wrote a script that requires some input, and I want to test it. It looks like this:

`viariable = input()`

How do I import that input from a text file? In PyCharm I use a terminal with this command: `Get-Content xxx.txt | xxx.py` and it works.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

This is currently not supported, but it's in the TODO list: #1121

**Comment by memiarz** [comment]
Thank you! Can't wait :)
