### ISSUE TITLE
WIBNI:  Comments on Thonny in general - not issues, but ideas that will hopefully spark discussion

### ISSUE THREAD

**Issue by jharris1993** [thonny/thonny#2173]
Greetings!

("WIBNI" = "Wouldn't It Be Nice If. . . .")

I like Thonny.&nbsp; More accurately, I like Thonny a ***lot*** as it lets me do a lot with a small footprint that fits systems like the Raspberry Pi robot I'm working on.

Because of this there are a lot of things I'd like to try with Thonny - it's one of my two "go to" editors for working on my robot:
*  On my main system, (Windows), I'm using VS Code.
*  On my GoPiGo robot, I'm using Thonny as it's a lot like VS Code in its functionality.&nbsp; I can "hop on" Thonny on my 'bot for "quick-and-dirty" fixes to code without firing up the main system or VS Code.
* Other times, I do the entire project life-cycle in Thonny if it's not too big or I don't have to worry about pull requests.

In essence, it's a great smaller-scale IDE-like environment with a lot of good features that won't overwhelm the new programmer.

What I would like to see, if possible, is for Thonny to be able to "unfold" as it were.

That is, when someone is just getting started, it provides a set of features aimed for the beginning programmer. However, as they gain experience and confidence, they can "unfold", (enable), additional features to help them.
Eventually becoming a real "Kick-Butt!" IDE type environment that can run on smaller systems, (like the Raspberry Pi), without bogging it down like a full-blown VS Code install does.

Now, I understand that Thonny isn't, nor should it become, a replacement for VS Code, as it will become huge and difficult to maintain,  But I do think it can take the beginning programmer a long, long way towards expertise in Python.

What say ye?

**Comment by aivarannamaa** [comment]
The idea of unfolding is already present in Thonny, as one can open more views from the "View" menu.

Which features do you miss?

**Comment by aivarannamaa** [comment]
Please reopen if you have more information to add!
