### ISSUE TITLE
Thonny files option in multiple windows although "Allow only single Thonny instance" is set

### ISSUE THREAD

**Issue by cliverlong** [thonny/thonny#2176]
Windows 10, 64bit
Thonny: 3.2.3

I have the .py extension set in Windows to open Thonny.

I have an exiting thonny window open with python files in tabs that I opened in Thonny

When I click on a file <name>.py file in a file manager, say windows explorer, the Python file is opened in a new window rather than a tab in the existing Thonny instance.

In Thonny Tools > Options > General, the first option "Allow only single Thonny instance" is ticked.

I was expecting the Python file to open in a new tab in Thonny.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Can you reproduce this problem with the newest Thonny version -- 3.3.13 ?

**Comment by aivarannamaa** [comment]
... even better, try Thonny 4: https://github.com/thonny/thonny/releases

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem with Thonny 4.0.2
