### ISSUE TITLE
Pi pico output not displaying in shell but its working with "putty", and i also cant read from pi pico

### ISSUE THREAD

**Issue by OpGamer3000** [thonny/thonny#2178]
So i was writing my code as usual, after adding a while loop (which has no break), i can no longer upload the code or read my previous code from it
when i try it to do then i get this error:

Device is busy -- can't perform this action now.
Please wait or cancel the current work and try again!
![image](https://user-images.githubusercontent.com/88536432/154796317-bd905d88-9684-442f-8117-ba0fec3f1f3e.png)

there are no outputs, no shell stuff, etc
idk what to do now

any help will be greatly appreciated
and also suggest some precautions to take if possible...

**Comment by OpGamer3000** [comment]
so i managed to get the output from pi pico but stil cant access the dile system in pi pico

**Comment by OpGamer3000** [comment]
so i decided to nuke(reset) the flash instead, but this is a problem(or maybe i am doing something wrong). please fix this or suggest precautions.

**Comment by OpGamer3000** [comment]
so we can use rshell(linux or WSL) to do recover our files(worked for me!), stil if you guys have other sugestions then tell me

**Comment by aivarannamaa** [comment]
Thank you for the report!

Did you try interrupting your loop with Ctrl+C ?

**Comment by OpGamer3000** [comment]
> Thank you for the report!
> 
> Did you try interrupting your loop with Ctrl+C ?

yes i did but dint work

**Comment by OpGamer3000** [comment]
i'll just say that avoid using all the cores, if u have to do something forever then use the second core.
