### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bahaboutriga** [thonny/thonny#2179]
why "ValueError: invalid syntax for integer with base 10"?

**Comment by pasdechance** [comment]
This is a built in exception in Python https://docs.python.org/3/library/exceptions.html#ValueError you may need to review your code.

**Comment by aivarannamaa** [comment]
@bahaboutriga, if you got this error in the shell while running your script, then most likely you need to investigate your code, just as @pasdechance said.

If you believe it's Thonny's error, then you need to give more details -- what was the trigger of the error and where did it appear.
