### ISSUE TITLE
Add config to allow pip --trusted-host pypi.org  --trusted-host files.pythonhosted.org

### ISSUE THREAD

**Issue by jobartucz** [thonny/thonny#2184]
Would it be possible to allow a config where pip uses --trusted-host pypi.org  --trusted-host files.pythonhosted.org

In school environments, pip can fail with 

self-signed certificate in chain.

**Comment by aivarannamaa** [comment]
Nevermind, normal pip usage is not cocerned with micropython.org, whose certificate chain is the problem in #1986

**Comment by Givy** [comment]
Please see below Attached Error:
![Thonny Plug-ins-Error_Screenshot](https://user-images.githubusercontent.com/15314129/155851121-ecb82896-3c2c-470b-860c-489bfe81e089.png)

Thank you.

**Comment by Givy** [comment]
![Thonny Plug-ins-Error_Screenshot-2](https://user-images.githubusercontent.com/15314129/155851212-e54b3a6b-7ae1-4e47-8fa6-f3def07b7830.png)

**Comment by Givy** [comment]
Hi,
I hope these help:

![Thonny Plugins-PICO-Error_Screenshot](https://user-images.githubusercontent.com/15314129/155851949-c7e4a087-144c-4fb7-8fee-bcf456e88136.png)

Thank you.

**Comment by aivarannamaa** [comment]
@Givy, thonny-rpi.pico plugin is obsolete. In the future please create a separate issue for separate problems. This issue is not suitable for for discussing your problem.

**Comment by jobartucz** [comment]
> Have you tried specifying these options via environment variables (Tools => Options => General)? See https://pip.pypa.io/en/stable/topics/configuration/#environment-variables

but since the arguments are the same, how could I have two environment variables with the same name point to two different places?

PIP_TRUSTED_HOST="files.pythonhosted.org"
PIP_TRUSTED_HOST="pypi.org"

Is there a way to combine them?

**Comment by Givy** [comment]
Hi,
OK..  "thonny-rpi.pico plugin is obsolete.", thank you...But, what needs to replace it?  I have not modified anything in Thonny since I installed it!!  
I have opened a couple of new issues.  Please also see "Thonny 3.3.13 can't interpret #2187".
Thank you.

**Comment by aivarannamaa** [comment]
> Is there a way to combine them?

Did you try separating two values with space, as with PIP_FIND_LINKS example at https://pip.pypa.io/en/stable/topics/configuration/#environment-variables ?

**Comment by jobartucz** [comment]
It didn't work. :(


![Screenshot 2022-02-28 120226](https://user-images.githubusercontent.com/26631024/156035219-0e4688ad-7742-4d69-919f-8c930b95851f.png)

**Comment by KennyHarrer** [comment]
First and foremost its worth mentioning Dashes (``-``) have to be replaced with underscores (``_``) ([see this](https://pip.pypa.io/en/stable/topics/configuration/#environment-variables)). Secondly the secondly ``--trusted-host`` overwrites the first. I am on the same network as @jobartucz , adding ```PIP_TRUSTED_HOST="files.pythonhosted.org"``` did not fix the issue.

**Comment by aivarannamaa** [comment]
Please try without quotes. Thonny simply splits the line on `=` and sets the rightmost part as value of the variable

**Comment by KennyHarrer** [comment]
That solved the issue! Thank you. I will relay this information to @jobartucz .
