### ISSUE TITLE
Thonny showing Backend terminated

### ISSUE THREAD

**Issue by sahabitukur01** [thonny/thonny#2188]
My Thonny keeps on displaying "
Backend terminated or disconnected. Use 'Stop/Restart' to restart."
even after Stop/Restart,please Help !!

**Comment by aivarannamaa** [comment]
Which Thonny version are you using? Which OS? Which back-end (Python 3 or MicroPython)? Did it start displaying this error right after you launched Thonny for the first time or after you did something in Thonny?

**Comment by sahabitukur01** [comment]
I am using Thonny current version 3.3.13 on a windows 10 operating system and back-end is Python 3.It started showing errors  after using it for a while.

**Comment by aivarannamaa** [comment]
What do you have written on the lower-right corner of your Thonny's main window?

**Comment by aivarannamaa** [comment]
even better -- could you post the screenshot of your Thonny's main window, together with the error message?

**Comment by aivarannamaa** [comment]
Please reopen if you have more information to add
