### ISSUE TITLE
ModuleNotFoundError: No module named 'serial.tools'

### ISSUE THREAD

**Issue by Jawad-Alhamadah** [thonny/thonny#2189]
the issue started with thonny giving me an error  in the shell about not finding the serial module. After looking around, i did the only two suggested solutions: change any file that is named serial (i didn't have any), pip install serial.  After installing serial, thonny started giving me an error  in a window titled " error initializing backend": 
`ModuleNotFoundError: No module named 'serial'`

i tried installing serial using pip and that's when the issue changed to:
`ModuleNotFoundError: No module named 'serial.tools'`

 I have searched online for solutions and it seems that all the suggestions don't work. I ran all kinds of pip installs of serial and pyserial. 
this is what i tried so far in the terminal :
```
sudo pip install pyserial

sudo pip3  install pyserial --user

sudo pip  install serial --user

sudo apt-get install python3-serial

python -m pip install pyserial

pip3 install pyseria

pip install pyserial

pip install serial
```
Im unsure what to do to resolve this issue. I hope you guys can help. Thank you.

im using Raspberry pi 4.

**Comment by aivarannamaa** [comment]
`pip install serial` messes up things. Thonny needs distribution package `pyserial` (which contains Python module-packages `serial` and `serial.tools`.

So try uninstalling all other serial-like packages and keep only pyserial.

**Comment by aivarannamaa** [comment]
> the issue started with thonny giving me an error in the shell about not finding the serial module.

Did you try to `import serial` in your MicroPython code? AFAIK, there is no such module which would work with MicroPython. Pyserial is meant for CPython.

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add
