### ISSUE TITLE
file or folder not writable problem

### ISSUE THREAD

**Issue by plotzz** [thonny/thonny#2193]
i searched everywhere on youtube and other websites to no avail pls help

**Comment by aivarannamaa** [comment]
I don't know this problem. Can you elaborate?

**Comment by plotzz** [comment]
> I don't know this problem. Can you elaborate?

it goes like this when i use thonny i open it and try to use python i then try to save it and it a notification appears saying "this file or folder is not writable
![thonny error](https://user-images.githubusercontent.com/101086290/157290419-7ccd94f3-d0c2-4481-87b3-af2da041a94a.png)
"

**Comment by aivarannamaa** [comment]
Where are you trying to write the file? Under your home directory or somewhere else?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!

**Comment by JerichoTTV** [comment]
I am having this same problem, I'm currently trying to open the Clangen patrol rework through thonny but each time it gives me that same error message, I have all the requirements; Pygame, Pygame-gui, and ujson

**Comment by Youarenotblind** [comment]
> i searched everywhere on youtube and other websites to no avail pls help

去掉这个文件的“只读”属性就可以了

**Comment by Blank2275** [comment]
This happened to me, the solution was I had to change 'open(file, "r")' to 'open(file, "w")'
