### ISSUE TITLE
Webrepl not available on some installs for the same version

### ISSUE THREAD

**Issue by prgrobots** [thonny/thonny#2194]
Hello

I have the same version of Thonny installed on two different windows 10 PCs, one has the webrepl available where the port drop down box is and one doesn't?
![image](https://user-images.githubusercontent.com/91106994/157243025-30bdecc1-e1f2-462b-8675-c709c4124770.png)
I tried re-installing but its still not there and, kinda awesome to have a webrepl inside the IDE.

**Comment by prgrobots** [comment]
I have installed the latest, 3.3.1.3 but its only installed 3.2.1

![image](https://user-images.githubusercontent.com/91106994/157397211-74111560-154d-49e5-bffe-5950523be652.png)

My other machine is running 3.3.1.3 and has the webrepl

**Comment by aivarannamaa** [comment]
In this case you have an older instance of Thonny hiding the newer one.

Please go to "Tools => Manage plug-ins" and look for `thonny`. If it shows version 3.2.1, then uninstall it and restart Thonny.

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem
