### ISSUE TITLE
Thonny doesn't run on some Mac profiles

### ISSUE THREAD

**Issue by AndyRIC** [thonny/thonny#2195]
The issue is with some (not all) profiles, once Thonny is installed, on the "Let's Go" for the issue is for some profiles it will go no further, on the same machine a different profile will run it. Profiles have been wiped and reset, still same problem. Someone suggested it was a Rosetta issue.

**Comment by aivarannamaa** [comment]
Please try https://github.com/thonny/thonny/releases/download/v3.3.10/thonny-3.3.10-alt.pkg, which comes with universal build of Python 3.9

**Comment by aivarannamaa** [comment]
or try the new 4.0 https://github.com/thonny/thonny/releases
