### ISSUE TITLE
Thonny

### ISSUE THREAD

**Issue by amsimer** [thonny/thonny#2199]
I´m using thonny and suddenly it stopped working and it doesn´t let me run the programs, I've tried closing the program and restarting my computer and it still doesn´t work.

**Comment by aivarannamaa** [comment]
> it doesn´t let me run the programs

What does it precisely mean? Do you get an error message or simply nothing happens when you are selecting "Run => Run current script" ?

**Comment by Adfinem83** [comment]
Same problem I just stopped using crap from day one.

**Comment by aivarannamaa** [comment]
@amsimer, please reopen if you still have this problem in Thonny 4.0.2 and can provide more info
