### ISSUE TITLE
Thonny Mac for ARM64

### ISSUE THREAD

**Issue by below** [thonny/thonny#2201]
Hello,

are there any plans to bring Thonny to ARM64 for the Mac?

I did not really find about building Thonny for Mac from source, I might be able to help

**Comment by aivarannamaa** [comment]
I suppose you mean native support, as current build is reportedly working via Rosetta.

Thonny 4.0 will come with universal build of Python 3.10. Until then there is https://github.com/thonny/thonny/releases/download/v3.3.10/thonny-3.3.10-alt.pkg, which contains universal build of Python 3.9

**Comment by below** [comment]
Yes, it is working very well in Rosetta. 

And thank you, I will look at that!

**Comment by aivarannamaa** [comment]
Here is the first beta of 4.0 https://github.com/thonny/thonny/releases

**Comment by below** [comment]
Thank you! On my M1, Thonny 4 Beta still runs as "Intel". Am I doing it wrong?

**Comment by aivarannamaa** [comment]
Unfortunately I don't have a M1 to test with. I'll google for this problem later.

**Comment by below** [comment]
I have more information: If I start Thonny in Terminal (`% /Applications/Thonny.app/Contents/MacOS/thonny`) it launches as ARM64. If it is launched from the Finder (or, technically, `launchd`), it launches as x86_64.
So far I found no obvious setting in the Info.plist to say that the App is ARM64 compatible, I will continue to look for that …

**Comment by aivarannamaa** [comment]
@below, can you try this property https://developer.apple.com/documentation/bundleresources/information_property_list/lsrequiresnativeexecution ?

**Comment by below** [comment]
A good idea I did not think of before … but it seems to have no effect :( Still starts up as Intel if started from the Finder.

**Comment by aivarannamaa** [comment]
Are you willing to install a recent universal2 build from python.org (eg. https://www.python.org/ftp/python/3.10.4/python-3.10.4-macos11.pkg) and check how their IDLE runs? If you get an ARM64 process, then I should start comparing Thonny's and IDLE's approach.

**Comment by below** [comment]
This, oddly enough, starts up in ARM64! I see nothing in the Info.plist that looks like it is affecting this, and I am not knowledgeable about Python enough to see what could be different in the App "executable"

**Comment by aivarannamaa** [comment]
I got some ideas from the Pythonmac mailing list.

This is for me to try when building the next beta: https://mail.python.org/pipermail/pythonmac-sig/2022-March/024497.html

In the meanwhile you could check whether you can get native launch with this suggestion: https://mail.python.org/pipermail/pythonmac-sig/2022-March/024496.html

**Comment by below** [comment]
Cool! That suggestion fixed it for now! But why was "Open with Rosetta" ever active in the first place?

**Comment by aivarannamaa** [comment]
> But why was "Open with Rosetta" ever active in the first place?

Most likely it was caused by the x86_64 value in my Distribution.plist, which was given as input to installer builder. Therefore the installer must have marked the bundle as x86_64-only. I now changed it to `"arm64,x86_64"`, as Ned Deily suggested and hopefully the installer of the next beta doesn't set this flag anymore.

**Comment by aivarannamaa** [comment]
The new installer is now available: https://github.com/thonny/thonny/releases/tag/v4.0.0b2

**Comment by below** [comment]
Thank you! I can confirm it works. I will include Thonny in my documentation once you have a release
