### ISSUE TITLE
Thonny 2.1 does not startup under Windows XP

### ISSUE THREAD

**Issue by ReyZRX** [thonny/thonny#2209]
Howdy. Yes, I know, XP is old...but it is on my laptop and only used on trips; at home use Win 10 Pro w/Py 3.8 (64bit) & 3.9 (32 bit).
Last Oct 2021, installed Thonny 2.1 under PIP after Python 3.4X installed. It ran w/no issues.
On my move to Indiana, it now does not startup.  Attached is PNG of err msg displayed.
Appreciate any suggestions.
Thanks, Rey
![Thonny_startup_WinXP](https://user-images.githubusercontent.com/102242825/159742986-0c763735-47c8-4cf0-8a14-98568198972d.PNG)

**Comment by aivarannamaa** [comment]
Try the binary bundle, which has its own copies of suitable binaries: https://github.com/thonny/thonny/releases/download/v2.1.22/thonny-2.1.22.exe

**Comment by ReyZRX** [comment]
Thanks. Will uninstall and try the binary bundle suggested and update you
on results.

Rey

**Comment by deepeepee** [comment]
https://github.com/thonny/thonny/releases/download/v2.1.22/thonny-2.1.22.exe does not run in Windows XP!

**Comment by aivarannamaa** [comment]
Unfortunately I don't have time for debugging issues specific to XP.
