### ISSUE TITLE
Error: Interpreter 'Äm鋸o' does not exist. Please check the configuration!

### ISSUE THREAD

**Issue by Sushi2k6** [thonny/thonny#2214]
![image](https://user-images.githubusercontent.com/89247190/159975307-f87e37b0-abb6-46d6-9742-7fbcd732c284.png)
This error pops everytime I try to run or debug or any other function

**Comment by Sushi2k6** [comment]
I reinstalled the software as there was another problem. 
I am on 3.3.13
(It would be better if you ass the latest versions to the website)

**Comment by Sushi2k6** [comment]
I reinstalled the software and then this happened.
I am on version 3.3.13
(It would be better if you add the latest versions to the website)

**Comment by aivarannamaa** [comment]
what does it say in the lower-right corner of Thonny's main window?

**Comment by Sushi2k6** [comment]
@aivarannamaa I would like for you to fix this issue as soon as possible, please. I can't use other debugs, because it is confusing.

**Comment by TamilNeram** [comment]
Hi Shashidharan, 
              if you dont know the root cause of this issue. Try uninstalling and removing all files of Thonny from your system and then install again. 

For finding all files folder of Thonny,  use the "எல்லம்"(again Tamil Translation for this tool is from my team) from https://www.voidtools.com/.

**Comment by Sushi2k6** [comment]
@TamilNeram 
I tried it, but again the error occurred.

**Comment by aivarannamaa** [comment]
@Sushi2k6, please select "Tools => Open Thonny data folder" and send me your configuration.ini. It may contain clues for solving this problem.

**Comment by Sushi2k6** [comment]
I even tried installing older versions, still has the same problem.

**Comment by aivarannamaa** [comment]
@Sushi2k6, I requested access to your file in drive, but haven't received it

**Comment by Sushi2k6** [comment]
@aivarannamaa Try now

**Comment by aivarannamaa** [comment]
@Sushi2k6, thanks! Unfortunately I could not spot anything suspicious in the configuration file. Please try deleting this file (close Thonny first). After lauching Thonny again it should start with default settings. Does this make any difference?

**Comment by aivarannamaa** [comment]
In this case you could try https://github.com/thonny/thonny/releases/tag/v4.0.0b1

**Comment by Sushi2k6** [comment]
@aivarannamaa New issue, 
![image](https://user-images.githubusercontent.com/89247190/161390029-29da4269-d851-477e-869f-05321c8ad5f2.png)
This occurred when I uninstalled the old one and installed the new version, and opened it.....

**Comment by aivarannamaa** [comment]
@Sushi2k6, are you using Windows 7

**Comment by Sushi2k6** [comment]
yes, and I know that this version cannot support, but I saw this and I thought that it will support Win 7
![image](https://user-images.githubusercontent.com/89247190/161424384-b5fa16dc-11c6-4c5e-9589-6cd2f024b70e.png)

**Comment by aivarannamaa** [comment]
Please try https://github.com/thonny/thonny/releases/download/v4.0.0b2/thonny-32bit-py38-4.0.0b2.exe

**Comment by Sushi2k6** [comment]
but I have a 64bit os

**Comment by aivarannamaa** [comment]
> but I have a 64bit os

32-bit Python works in 64-bit Windows as well.

**Comment by aivarannamaa** [comment]
Did you try deleting the configuration.ini (while Thonny is closed) and then starting Thonny again?

**Comment by aivarannamaa** [comment]
> what should I do now?

Try deleting the configuration.ini (while Thonny is closed) and then starting Thonny again (if you haven't tried it yet).

**Comment by Sushi2k6** [comment]
I tried everything....

**Comment by Sushi2k6** [comment]
This happened.....
![image](https://user-images.githubusercontent.com/89247190/163402020-e02d55fa-3b2b-4090-a7ca-9b92d9e96b00.png)

**Comment by aivarannamaa** [comment]
> I tried everything....

Just to be sure -- did you try deleting the configuration file while Thonny was closed? Please note that uninstalling does not delete this file.

> Is there anyway you can get the interpreter in a way I can install it externally?

If you have Windows 7, then you could install separate Python 3.8 (https://www.python.org/downloads/release/python-3810/) and then use "Run => Select interpreter" in Thonny to locate python.exe in this external installation.

**Comment by Sushi2k6** [comment]
Yes, I tried that. I deleted the configuration.ini file while thonny was closed.

I don't get what you are trying to say, I should install python 3.8.10 ( I use that only ) and I should select it in the select interpreter?

**Comment by aivarannamaa** [comment]
> I should install python 3.8.10 ( I use that only ) and I should select it in the select interpreter?

That's right.

**Comment by Sushi2k6** [comment]
I tried it but a different error occurred. I meant to post this long back, I forgot

**Comment by aivarannamaa** [comment]
At the moment I don't know how to proceed with this issue. If you have more information to add, then please re-open this issue or create a new one.

**Comment by Sushi2k6** [comment]
Ok, if I did have any other info, I will inform you.
Thanks

**Comment by Sushi2k6** [comment]
Ok, if I did have any other info, I will inform you.
Thanks

**Comment by agorlach** [comment]
It is happen on my Win7 machine when I added api-ms-win-core-path-l1-1-0.dll  in hope to run the latest version of Thonny (4.1.4 x64 with Python 10).  I removed this version and tried to install x86 with Python 8. And then got this error. 

The error gone and Thonny start work when I removed api-ms-win-core-path-l1-1-0.dll from my machine.

**Comment by kb4oam** [comment]
Removing all instances of 'api-ms-win-core-path-l1-1-0.dll' did the trick!
I've been fighting the 'interpretter problem' for weeks.
A big thanks!

**Comment by h2457528767** [comment]
> Removing all instances of 'api-ms-win-core-path-l1-1-0.dll' did the trick!去除所有“'api-ms-win-core-path-l1-1-0.dll'的实例后，效果就解决了！ I've been fighting the 'interpretter problem' for weeks.我已经为“翻译问题”斗争了好几个星期。 A big thanks!  非常感谢！

This solution is worked on windows 7, thanks a lot!
