### ISSUE TITLE
Management Error. Trying to install digi-xbee module into Raspberry Pi Pico

### ISSUE THREAD

**Issue by cranfo** [thonny/thonny#2215]
![image](https://user-images.githubusercontent.com/29823172/160034705-66d8dc32-1411-463d-899d-4d8bbb34d349.png)

Tried with 2 different Raspberries, always the same error. Also tried cloning the module repository and uploading it directly into the Raspberry ('Upload to /' option).

**Comment by cranfo** [comment]
![image](https://user-images.githubusercontent.com/29823172/160046812-6a40c2f4-afa3-4d76-abf6-143a4c1fc859.png)

"Could not write next block after having written 146432 bytes to /lib/digi/xbee/firmware.py
Make sure your device's filesystem has enough free space. (When overwriting a file, the old content may occupy space until the end of the operation.)" 

Must be a free space issue.

**Comment by aivarannamaa** [comment]
It looks like https://pypi.org/project/digi-xbee is meant for CPython, not for MicroPython.
