### ISSUE TITLE
Import Pandas error

### ISSUE THREAD

**Issue by Mohsenaii** [thonny/thonny#2218]
I have got this issue
 from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject

**Comment by aivarannamaa** [comment]
It looks like you have `--user`-installed a pandas version which is incompatible with your numpy version. Did you install it via Thonny's package dialog? When you look at `numpy` in the same dialog, is it also installed to /home/pi/.local/lib/python3.9/site-packages ?
