### ISSUE TITLE
Device is busy or not response . please wait or cancel current work.

### ISSUE THREAD

**Issue by maheshahirwar** [thonny/thonny#2219]
How Can I solve this issue

**Comment by aivarannamaa** [comment]
Did you try to cancel the work?

**Comment by maheshahirwar** [comment]
No I try to run code in pico then I get this error . What should I do?

Mahesh

**Comment by aivarannamaa** [comment]
Is there something already running on your Pico? What does your main.py contain?

**Comment by aivarannamaa** [comment]
Please reopen if you have more information to add.
