### ISSUE TITLE
Open system shell does not work

### ISSUE THREAD

**Issue by git-aybo** [thonny/thonny#2222]
Hi
Thank you for your great work with Thonny. 
I use Thonny 3.3.13 on Windows 10. When I choose the interpreter "Remote Python 3 (SSH)" it works fine with my Rasperry Pi in the Python environment. But when I choose Tools->Open system shell... it gives the error "command ssh not found". I would expect that a remote terminal would appear. In a normal windows terminal ssh works fine.
![image](https://user-images.githubusercontent.com/40418811/161071518-a50b4554-1630-43ce-a649-28236f843aaf.png)
![image](https://user-images.githubusercontent.com/40418811/161071676-9ecea8cb-e144-47f2-a4f5-40cbf5161bdd.png)
![image](https://user-images.githubusercontent.com/40418811/161151635-f47f7951-3e98-4c61-8f77-a1bf869056cd.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

What do you get when you do `where ssh` in CMD?

**Comment by git-aybo** [comment]
Hi
Please have a look to the 3rd image. You can see the output from where in CMD and Python

**Comment by aivarannamaa** [comment]
Oh, sorry, I wasn't paying attention enough...

please try, whether giving the extensions helps:

```
>>> os.system("where ssh.exe")
>>> import shutil
>>> shutil.which("ssh.exe")
```

**Comment by git-aybo** [comment]
![image](https://user-images.githubusercontent.com/40418811/161219107-fb5cafac-8dbe-4348-a384-cd01bb2ec19a.png)

**Comment by aivarannamaa** [comment]
Please also investigate your PATHEXT evironment variable as described here: https://stackoverflow.com/questions/56399696/shutil-which-not-finding-programs-without-appending-file-extension

**Comment by git-aybo** [comment]
This variable is set:
![image](https://user-images.githubusercontent.com/40418811/161224016-eced8649-c6b7-4691-9789-c52cdbffc5a4.png)
i also tried .exe

**Comment by git-aybo** [comment]
The system shell from Thonny cannot reach the dircetory C:\Windows\System32\OpenSSH
![image](https://user-images.githubusercontent.com/40418811/161225988-ae9ee1c9-c541-42c1-8507-45462c369913.png)

**Comment by git-aybo** [comment]
I think this is a window problem with 32/64 Bit (https://github.com/PowerShell/PowerShell/issues/11774 or https://www.reddit.com/r/csharp/comments/i06zdq/cant_access_cwindowssystem32opensshsshexe_from_c/):
Workaround: 
I use a own ssh and set the path variable in Thonny. After restart it works fine. 

Thank you for your support and have a nice day.
