### ISSUE TITLE
plug-ins DHT

### ISSUE THREAD

**Issue by mecanospy** [thonny/thonny#2224]
Latest stable version: 0.1.0
Summary: Pure Python library for reading DHT11 sensor on Raspberry Pi
Author: Zoltán Szarvas
Homepage: https://github.com/szazo/DHT11_Python
PyPI page: https://pypi.org/project/dht11/
Requires: RPi.GPIO

unable to install all 'plug-ins'

**Comment by aivarannamaa** [comment]
> unable to install all 'plug-ins'

What do you mean precisely?
