### ISSUE TITLE
Can't find backend 'LocalCPython'. Please select another backend from options

### ISSUE THREAD

**Issue by sam-march-31** [thonny/thonny#2228]
Can't find backend 'LocalCPython'. Please select another backend from options
 i am using mac os monterey 12.2.1

i am unble to run  thonny application please help.

**Comment by aivarannamaa** [comment]
Thank you for the report!

You were trying Thonny 4.0.0b1 and then reverted to 3.3, right?

In this case you need to go to "Run => Select interpreter" and select another interpreter.

I'll make the error message more clear.

**Comment by sam-march-31** [comment]
this solved thanks
