### ISSUE TITLE
grammar correction on Support Ukraine page

### ISSUE THREAD

**Issue by slark** [thonny/thonny#2241]
[https://github.com/thonny/thonny/wiki/Support-Ukraine](https://github.com/thonny/thonny/wiki/Support-Ukraine) → 
2nd paragraph → 3rd sentence → 
replace "neither"
with "either"

see also attached screenshot from [https://quillbot.com/grammar-check](https://quillbot.com/grammar-check)

![QuillBot → Grammar Checker → screenshot](https://user-images.githubusercontent.com/138076/162860135-54a64cb7-cbd3-43ab-a0c0-0c39e7087662.png)

**Comment by coolapker** [comment]
fu*k you thonny!

**Comment by aivarannamaa** [comment]
@slark, thank you for the report! I fixed the wording now.
