### ISSUE TITLE
Feature Reuest: add code visulization

### ISSUE THREAD

**Issue by Free-Radical** [thonny/thonny#2242]
similar to https://pythontutor.com/visualize.html

otherwise excellent learning toool. Thank you.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

I don't have a time for re-implementing this visualization, though. But I added a command, which opens the code in the current editor at Python Tutor.

**Comment by Free-Radical** [comment]
Understandable. Thanks again.
