### ISSUE TITLE
Please upgrade the `.py` installation

### ISSUE THREAD

**Issue by reza-ghazi** [thonny/thonny#2244]
`pip install thonnyapp` will raise the following warning:
```python
DEPRECATION: thonnyapp was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```

Please upgrade the installation process.

**Comment by aivarannamaa** [comment]
I think I'll rather deprecate `thonnyapp` package, as it uses certain tricks for creating application shortcut, which doesn't fit into the preferred model of Python packages.

**Comment by aivarannamaa** [comment]
In the meawhile just use `pip install thonny` and manually create the shortcut to `thonny` executable.
