### ISSUE TITLE
Problem with Debugging

### ISSUE THREAD

**Issue by AshDini** [thonny/thonny#2245]
Pressed Ctrl+F5
![Image 2](https://user-images.githubusercontent.com/66854499/163131395-665c38ef-c805-40e7-93a6-d6cce4cda583.jpg)
Pressed Ctrl + F5
![Image 3](https://user-images.githubusercontent.com/66854499/163131505-bd33bc6f-bb02-4428-99f0-c75bbdd175e4.jpg)
Pressed Ctrl+F7
![Image 4](https://user-images.githubusercontent.com/66854499/163131584-c1618f64-e423-476c-a68f-5ff6f54f8c3f.jpg)
Pressed Ctrl + F6
![Image 5](https://user-images.githubusercontent.com/66854499/163131644-341dc5a4-fec6-4a79-8c08-4f80f3c035b4.jpg)
Pressed Ctrl + F6
![Image 6](https://user-images.githubusercontent.com/66854499/163131738-9377fe60-dd40-4926-81bb-1cc719c73524.jpg)
Pressed Ctrl + F6
![Image 7](https://user-images.githubusercontent.com/66854499/163131803-2967d22f-0cdb-419b-a484-815e843abe9e.jpg)

**Comment by aivarannamaa** [comment]
Thank you for the report! You are using 4.0.0b1, right? Please try https://github.com/thonny/thonny/releases/tag/v4.0.0b2

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem with version 4.0.2
