### ISSUE TITLE
Thonny locks up while editing

### ISSUE THREAD

**Issue by AshDini** [thonny/thonny#2247]
Thonny locks up while editing (using Thonny 4.0.0b2)
![Image88](https://user-images.githubusercontent.com/66854499/163276549-c500cb0b-d7e1-42fa-a960-403209a8ab48.jpg)

A little blue circle is circling, but it does not show on the screenshot.

**Comment by aivarannamaa** [comment]
Thank you for the report!

After you force-close Thonny, can you repeat this situation? Can you give me example code and steps for reproducing this?

**Comment by AshDini** [comment]
Hi Aivar,

It happened many times, but I could not find a common reason for it to
happen. Sorry I can not be more help.

Unfortunately, I had to switch back to the current (3.3.13) version

Regards,

Bob Stanton

**Comment by chicory-ru** [comment]
You can repeat it by opening a large enough code and dragging the scroll up and down many times.

**Comment by aivarannamaa** [comment]
I hope this issue was fixed in #2258, available since 4.0.0b3. Please reopen if you still get this error!

**Comment by AshDini** [comment]
It just happened during editing the source code...

**Comment by aivarannamaa** [comment]
@AshDini, with which version did it happen this time?

**Comment by AshDini** [comment]
That was version 13. 14 seem to be ok.

**Comment by aivarannamaa** [comment]
Assuming the issue is fixed in 4.0.1

**Comment by AshDini** [comment]
Yes, this issue have been fixed.
