### ISSUE TITLE
Strange REPL behavior in Micropython

### ISSUE THREAD

**Issue by jean-claudeF** [thonny/thonny#2250]
Yesterday when I wanted to demonstrate to some friends how easy it is to work with a Pico, I noticed something strange.

In normal Python on the PC, I was used to this:

>>> 3+5
8

The Pico did this:

MicroPython v1.18 on 2022-01-17; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> 3+5
0x11

This seems to be a Thonny bug, as it did not occur when connecting through a serial terminal.
The problem occured in version 3.3.14 under Linux Mint

**Comment by aivarannamaa** [comment]
Did you have the Heap pane (View => Heap) opened? In this case Thonny was in "heap mode", which is meant for explaining mutable objects (see https://youtu.be/nwIgxrXP-X4?t=247 for explanation)
