### ISSUE TITLE
Thonny not working with Python 3.10.4

### ISSUE THREAD

**Issue by electrosonics** [thonny/thonny#2254]
I am using Thonny 3.3.14 and after updating my Raspberry PI OS Python installation to version 3.10.4, Thonny no longer works. When I attempt to open Thonny, one gets an hour glass icon then nothing. If I change the link on the file /usr/bin/python3 back to python3.9 (`sudo ln -s /usr/bin/pythod3.9 python3`) then Thonny works again but then I cannot take advantage of Python 3.10 features.

I tested the installation of python 3.10.4 to verify tkinter was operating with the following command:

`python -m tkinter`

This command failed. I resolved the missing tkinter support by doing the following:

```
sudo apt update
sudo apt install -y build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev
```

Then I reran the command to rebuild python 3.10.4 from the python 3.10.4 installation folder:

`sudo make altinstall`

Afterwards, I was then able to verify tkinter was working correctly.

However, Thonny still does not work.

Is there a way to view Thonny start up logs to what is happening or is there a fix for this issue?

EDIT: I was able to solve my issue by allowing Thonny to run with Python 3.9 (/usr/bin/python3 linked to python3.9), then opened Thonny and from the menu bar selected _Tools/Options/Interpreter_ and then changed the interpreter to _Alternative Python 3 interpreter or virtual environment_ and then set the Python executable to: /usr/local/bin/python3.10

**Comment by aivarannamaa** [comment]
Thank you for the report! 

I'm glad you found the solution, as I'd rather not spend time for making Thonny 3.3 to be compatible with Python 3.10. The upcoming Thonny 4.0 does work with Python 3.10 on Linux (tested on Ubuntu, but I believe it would work on RPiOS as well)
