### ISSUE TITLE
VariablesHighlighter not Updated to OccurencesHighlighter

### ISSUE THREAD

**Issue by abrarwali** [thonny/thonny#2255]
I came across this import error : 

ImportError while importing test module '/home/abrarwali/rpmbuild/BUILD/thonny-4.0.0b2/thonny/test/plugins/test_name_highlighter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
thonny/test/plugins/test_name_highlighter.py:6: in <module>
    from thonny.plugins.highlight_names import VariablesHighlighter
E   ImportError: cannot import name 'VariablesHighlighter' from 'thonny.plugins.highlight_names' (/home/abrarwali/rpmbuild/BUILD/thonny-4.0.0b2/thonny/plugins/highlight_names.py)
======================================================================= short test summary info ========================================================================
ERROR thonny/test/plugins/test_name_highlighter.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================== 1 error in 0.61s ===========================================================================
error: Bad exit status from /var/tmp/rpm-tmp.6IZOLF (%check)

On  updating  the import with **OccurencesHighlighter** in thonny/plugins/highlight_names.py, fixed the import error.

**Comment by aivarannamaa** [comment]
Thank you for the report!

The fix will be in the next beta.
