### ISSUE TITLE
Not Recognizing Walrus Operator :=

### ISSUE THREAD

**Issue by ahowes83** [thonny/thonny#2259]
<img width="896" alt="Screen Shot 2022-04-25 at 4 33 35 PM" src="https://user-images.githubusercontent.com/1458422/165178862-a56aed4b-9495-4cc0-9947-cb5f5f4caa68.png">
Thonny is throwing an error when I try to use a := here. Same code works in VS and comes from the new CS50p video from Harvard.

`import re

url = input("URL: ").strip()

if matches := re.search("^(?:https?://)?(?:www\.)?twitter\.com/([a-z0-9_]+)", url, re.IGNORECASE):
    print(f"Username:", `matches.group(1))`

**Comment by aivarannamaa** [comment]
Thonny 3.3 is bundled with Python 3.7, which doesn't recognize the walrus operator (introduced in Python 3.8).

The solution is install separate Python 3.8 (or newer) and make Thonny use it (Run => Select interpreter) or use the beta of Thonny 4.0 (https://github.com/thonny/thonny/releases)

**Comment by ahowes83** [comment]
Ah, thanks very much -- I'm not too surprised it was my mistake and not a real issue -- Andy
