### ISSUE TITLE
File browser handling of links

### ISSUE THREAD

**Issue by dbuggz** [thonny/thonny#2260]
I see that under Windows, Thonny uses APDATA to open the default C:\Users\username and since I have a few devices I use Thonny with (MicroBit, pico, badger) I'd like to have a quick way of linking to my DATA drive (D:) and the directories I keep these different devices/projects in. I have tried creating a Thonny directory (C:\Users\username\Thony) with links to D:\Documents\Pimoroni\Badger etc. but when you click on that it opens Windows Explorer at that directory instead of following the link.

**Comment by aivarannamaa** [comment]
Thank you for the report!

For replicating it -- can you tell me precisely, how did you create the links? With `mklink`? (I've never used symlinks in Windows myself)

**Comment by aivarannamaa** [comment]
Please reopen if you're still interested in this problem and can add more information.

**Comment by dbuggz** [comment]
FYI this took a few attempts at WinDOZE stuff. Finally the command I used was :
_C:\Users\davew\Thonny>mklink /j PicoDir "D:\Documents\Raspberry Pi\Pico"
Junction created for PicoDir <<===>> D:\Documents\Raspberry Pi\Pico_
