### ISSUE TITLE
Intune validation string not reflecting version

### ISSUE THREAD

**Issue by TimButterworth** [thonny/thonny#2263]
Hi There,

I'd like to use Intune to manage Thonny on our pupil 1-to-1 devices, but there seems no obvious way for me to validate the installation according to software version. The File properties on the .exe are 1.0.0.1 rather than the version number, for example, so we won't be able to use that for the supersedence function for updates.

Any advice would be welcome,

Thanks!

Tim

**Comment by aivarannamaa** [comment]
thonny.exe is just the launcher, which does not change between versions, and I'd rather not change and re-sign it just for updating the version string.

Could you take the version string from `lib\site-packages\thonny\VERSION` ?

**Comment by TimButterworth** [comment]
Thanks for the reply - that should do the trick!

Kind regards,

Tim
