### ISSUE TITLE
Weird choice of pythonw vs python

### ISSUE THREAD

**Issue by isaacl** [thonny/thonny#2264]
4b2 user install on Windows 10.

On first run, I see pythonw selected as interpreter by default.  What is pythonw?  Why is it selected over "Thonny's python"?

![image](https://user-images.githubusercontent.com/1027886/166103657-c22d1d1b-224f-4a79-8848-1196255a2205.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

It's a bug (#2236) which will be fixed in the next beta.

**Comment by aivarannamaa** [comment]
Oh, pythonw.exe is almost the same as python.exe, but it doesn't allocate a console.
