### ISSUE TITLE
Some minor deviations to standard editors

### ISSUE THREAD

**Issue by street-grease-coder** [thonny/thonny#2265]
There are some annoyances with Thonny that, IMHO, keeps it from being absolutely amazing.

1) `[CTRL+SHIFT+Arrowkeys]` does not follow default behavior of notpad. E.g. in this example:
`def test(): can I write[1]?| ` with cursor at `|` and `[CTRL+SHIFT+ARROW LEFT]` unintuitively marks `1]?` (default windows notepad marks `[1]?`)
`def test():| can I write[1]?` with cursor at `|` and `[CTRL+SHIFT+ARROW LEFT]` unintuitively marks `test()` (default windows notepad marks `()?`)
for some text `[CTRL+BACKSPACE]` will delete more than one word, and will delete more than even more than the current line of code

2) if you open up the text search window and switch the tab, the search context still remains in the original tab, when it intuitively should focus on the currently open tab

3) sometimes Thonny crashes when longer commands are interrupted and with several mutliline commands, resulting in a never-ending error 'beep', that can only be resolved by killing the process. Will look for error log next time this happens.

**Comment by aivarannamaa** [comment]
Thank you for the suggestions! I'll fix the search thing before final 4.0.

Arrow key behavior is more tricky, as it's currently implemented inside the GUI toolkit.

In 3rd point, did you mean submitting multiline commands in the Shell pane?

**Comment by aivarannamaa** [comment]
Search is fixed in 4.0.2.

Caret movement is hard to fix, maybe sometime in the future...

Please open another issue for 3rd point if you experience it again and can provide the logs.
