### ISSUE TITLE
Open system shell is not working in Fedora 25 + KDE

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#227]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/227) by me.**

----------------------------------------

... because konsole is not supported at the moment and xterm is not installed

**Comment by EvansMike** [comment]
I just did this on Fedora32 and Konsole opens just fine.

**Comment by aivarannamaa** [comment]
Thank you! I guess I fixed something later and forgot this issue.
