### ISSUE TITLE
i found the 64bit installer for linux,where is the 64bit for win10 64bit？

### ISSUE THREAD

**Issue by better319** [thonny/thonny#2271]
i found the 64bit installer for linux,where is the 64bit for win10 64bit？THANK

**Comment by aivarannamaa** [comment]
For Thonny 3.3 there is none, use the 32-bit installer. For 4.0 the main Win installer is 64-bit

**Comment by aivarannamaa** [comment]
> how to change the python version to python 3.7 in 4.0?

If you mean changing the interpreter which runs your own programs in Thonny (and not Thonny's GUI), then install Python 3.7, go to "Run => Select interpreter => Local Python 3" and select python.exe of your 3.7 installation.

**Comment by better319** [comment]
> 

THK！！
