### ISSUE TITLE
Thonny is giving error and not booting - Please Help

### ISSUE THREAD

**Issue by wrmspatel** [thonny/thonny#2273]
![PXL_20220505_161226076](https://user-images.githubusercontent.com/89054330/167200145-6a0f4bf5-42cb-4dc3-95ba-9a560d9b2e18.jpg)
![PXL_20220505_161636133](https://user-images.githubusercontent.com/89054330/167200159-9eef3f4d-627c-4352-a81a-d9e407d039f4.jpg)

Thonny is giving error and not booting - Can you help?? Thank you.

**Comment by aivarannamaa** [comment]
Thank you for the report!

I assume you have you been able to use Thonny on this computer before. Do you have an idea what may have changed? Different screen resolution perhaps?

You could try deleting Thonny's configuration file and start Thonny again with default options. The configration.ini should be under `~/.config/Thonny`

Whis OS and which Thonny version is this?

**Comment by wrmspatel** [comment]
It is running on Raspberry Pi on a pi-top CEED.  Can't think of anything that might have changed. It was working fine on the CEED then started giving error.

**Comment by wrmspatel** [comment]
Can anyone help with this?

**Comment by aivarannamaa** [comment]
Did you try deleting the configuration file?
