### ISSUE TITLE
Backend terminated or disconnected. Use 'Stop/Restart' to restart in Thonny

### ISSUE THREAD

**Issue by helppython** [thonny/thonny#2275]

**Comment by aivarannamaa** [comment]
Can you be more precise about the problem? What did you do when you got this error?

**Comment by tabreturn** [comment]
Have you installed the thonny-py5mode plug-in? There are issues running this on Thonny 4, which may result in such an error.

**Comment by aivarannamaa** [comment]
@helppython, please reopen if you have more information to add.
