### ISSUE TITLE
clear shell

### ISSUE THREAD

**Issue by guess75** [thonny/thonny#2276]
how i can clear shell with a magic command like: %clear or %clear_shell

**Comment by aivarannamaa** [comment]
There's no magic command, but you can clear shell with Ctrl+L (on Windows and Linux) or Cmd+K (on macOS).

**Comment by 88cy** [comment]
Ah yo, just exit the IDE and reopen it, that works for me.

**Comment by commongeek** [comment]
Can I do this programmatically? Something like
```
from thonny import get_current_shell
shell = get_current_shell()
shell.clear_shell()
```
