### ISSUE TITLE
No error when running thonny from terminal, but when opened normally, no module named error

### ISSUE THREAD

**Issue by uchechi-ugo** [thonny/thonny#2277]
I am using a Raspberry Pi OS 64-bit to run a script that will capture an image. I have gone through installing the right packages for libcamera for this OS and can run libcamera apps using my terminal. I get the error: "no module named picamera2" whenever I try to run the script in the thonny ide.

However, I have set my pythonpath variable to "/home/pi/picamera2:/home/pi/libcamera/build/src/py:/home/pi/kmsxx/build/py:/home/pi/python-v4l2", 
and when I run the command "thonny" from my terminal, it opens up the ide and my script runs without an error

Please, how can I be able to run my scripts without having to go through this process?

**Comment by aivarannamaa** [comment]
If the modules are at a non-standard location, then setting PYTHONPATH is the best way.

You could try setting the same environment variable in Thonny's options dialog (Tools => Options => General), but depending on Thonny's version and the precise configuration, the variable may not make it to the backend process.
