### ISSUE TITLE
Trouble installing mfrc522

### ISSUE THREAD

**Issue by Nicolebendo** [thonny/thonny#2280]
When I try to install the library "mfrc522" on Thonny, it says that it requires Visual Studio (that I installed, as well as Visual Studio Build Tools 2022).

Now it gets me this error: error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\cl.exe' failed with exit status 2

Any kind of help would be apreciated

Thanks!

**Comment by aivarannamaa** [comment]
This issue is not specific to Thonny. It looks like the library depends on `spidev`, which seems to be Linux-only.
