### ISSUE TITLE
Vertical arrange in prefs dialog

### ISSUE THREAD

**Issue by juanfal** [thonny/thonny#2287]
This is not an issue, but a wish.  I find it quite useful to narrow the windows for editing and shell.  You usually don't write to left in those windows but downwards.  So I struggle a bit to find how to organise the panes in vertical, as I send in this screen shot.  But for students, they ask me all the time how to do it for themselves.  It could be great to have this vertical organisation of the the windows in Thonny Preferences dialog.
<img width="2305" alt="Captura de Pantalla 2022-05-17 a las 18 30 30" src="https://user-images.githubusercontent.com/895596/168872833-5d7e42ab-1439-4f9a-9acc-30ee3b8f9bb9.png">

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

This is actually already in my TODO list: #158

In Thonny 4.0 I still have some bugs to fix, but I hope to include this in 4.1
