### ISSUE TITLE
Thonny UI accessibility in terms of usage along with assisstive technology software

### ISSUE THREAD

**Issue by jacob-kruger-work** [thonny/thonny#2291]
I am a 100% blind web application developer, who's current focus area is python-django, etc. - but, have worked in lots of different platforms/frameworks. Anyway, came across Thonny and would have liked to try it out, but, it's UI seems incompatible with my current primary form of assisstive #technology, which is the NVDA screenreader, which itself is written in the python language: https://www.nvaccess.org/

Besides that, if you were not aware of blind/VI programmers, etc., here's a mailing list where we regularly discuss various topics relating to lots of different forms of programming, platforms, operating systems, environments, etc., etc.:
https://www.freelists.org/list/program-l

**Comment by aivarannamaa** [comment]
Thank you for the report!

I am aware of the needs of blind users, but unfortunately, the UI toolkit used in Thonny (Tk) does not support screen readers.

I've considered bolting on some support on Thonny's side, but it still requires a C programmer knowledgeable in accessibility API-s for Windows, macOS and Linux. Most likely I won't find time for becoming this programmer, but I'm ready to support anybody who wants to engage with this task.
