### ISSUE TITLE
Pygame showing 'Backend terminated or disconnected. Use 'Stop/Restart' to restart.'

### ISSUE THREAD

**Issue by Flufiku** [thonny/thonny#2297]
I'm using Thonny to make (pretty shitty) pygame scripts, and every time I use the pygame.quit() function to end the script, it shows 'Backend terminated or disconnected. Use 'Stop/Restart' to restart.'. It only happens in pygame (other scripts work fine) and it only happens after using the quit function. I'm using thonny since Autumn 2021 and this started happening ca. 2 weeks ago.
(Os: Windows 10; Python version 3.7.9)

Thanks in advance and sorry for any spelling errors.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Did you upgrade Thonny or Pygame 2 weeks ago? Did the `quit`-function work without this message before?

**Comment by Flufiku** [comment]
No, I didn't update it.

Yes, it worked before

**Comment by aivarannamaa** [comment]
Which Thonny version and which Pygame version are you using?
