### ISSUE TITLE
autocompletion

### ISSUE THREAD

**Issue by PapyFree** [thonny/thonny#2298]
Why on Ubuntu 20.4 in Thonny the ![CWhy on Ubuntu 20.4 in Thonny the ![Capture d’écran du 2022-05-24 10-18-01](https://user-images.githubusercontent.com/106153170/170012959-ba9d32c2-e7b8-4b2d-a165-831a4d19e1ee.png) does not work?
How to solve this problem?apture d’écran du 2022-05-24 10-18-01](https://user-images.githubusercontent.com/106153170/170012959-ba9d32c2-e7b8-4b2d-a165-831a4d19e1ee.png) does not work?
How to solve this problem?

**Comment by aivarannamaa** [comment]
I suspect Ubuntu has combined Thonny with unsuitable version of `jedi` (the library, which computes code completions). The solution is to `apt remove thonny` and install Python+Thonny binary bundle:

```
bash <(wget -O - https://thonny.org/installer-for-linux)
```

or (in case you want to try the newest beta of Thonny 4.0), then download https://github.com/thonny/thonny/releases/download/v4.0.0b3/thonny-4.0.0b3.bash and run it with `bash`.
