### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by ghost** [thonny/thonny#2300]
Installed the package simple calculator on Thonny IDE. However, when I adhered to the written codes to run simple calculator, I only get a runtime error saying that simple calculator was not found, or that it does not recognize the word from calculator.simple import SimpleCalculator because that is written in the example or source code for running Simple Calculator.

**Comment by aivarannamaa** [comment]
Do you mean this package: https://pypi.org/project/simplecalculator/ ?

Are you sure you installed it via Thonny's package manager and not via Plug-ins manager?

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem and can answer my question.
