### ISSUE TITLE
Bad Spanish traduction in package manager

### ISSUE THREAD

**Issue by javacasm** [thonny/thonny#2301]
When an installed packaged can be upgraded in Package Manager, the button for upgrade it show "Actualizado" ("Upgraded") instead of "Actualizar" ("Update")

Change propposed 

File thonny/locale/es_ES/LC_MESSAGES/thonny.po

line 371
#: thonny/plugins/pip_gui.py:76
msgid "Upgrade"
<<msgstr "Actualizar"
>>msgstr "Actualizado"

**Comment by aivarannamaa** [comment]
Thanks for noticing this!

You can fix this yourself after joining Thonny project in POEditor: https://poeditor.com/join/project/Gh188fdYH6

Before next release I'll update translation files from POEditor's current state.

**Comment by javacasm** [comment]
Done!! I made the change in poeditor
Thanks

**Comment by aivarannamaa** [comment]
Great, I'll use updated translation files before the next release.
