### ISSUE TITLE
Unable to see content in files window

### ISSUE THREAD

**Issue by nakeze** [thonny/thonny#2303]
Hello,
I am using Thonny 3.13.3 on a windows 10 (64-bits) system, with Python 3.7.9 (32bit) and Tk 8.6.9 .
I have an issue when I want to export files on the pi pico.
When I show the files tree from view->files, I can see all the files and directory on my computer.
As soon as I plug the Pi pico, it is recognized by Thonny. At that time I can see my computer, its files but not the pico on the files tree.
When I press the "Stop/Restart Backend", the tree shows the pico and the computer, but as empty directories.
It is impossible to upload a file on the pi pico.
Do you have a solution for this issue ?

Sincerely,
Cheron Nicolas

**Comment by aivarannamaa** [comment]
Thanks for the report!

Do you have files and/or folders on your Pico?

Can you use MicroPython REPL in Thonny? Could you post the screenshot of the whole Thonny window in the problematic state?

**Comment by nakeze** [comment]
I don't have file in  the pico (i have a blank result with the os.listDir() command).
Os.mkdir() is creating a folder that i can see in the files tree once I refresh.
I am having what I feel like a normal behavior for the micropython part.

![AfterPressingStop](https://user-images.githubusercontent.com/82804257/170987519-990dc9c2-4b4d-4b20-81ac-38488c2609f4.PNG)

**Comment by aivarannamaa** [comment]
So the problem is with the local files ("This computer") ?

What happens, when you drag the divider line between "This computer" and "Raspberry Pi Pico" downwards? Does the upper pane still remain empty?

**Comment by nakeze** [comment]
The problem was that "stupid". I thought to expand it on right but not to drag the line downwards. 
Thanks for your quick reply !
