### ISSUE TITLE
dehumanizing language included in latest release

### ISSUE THREAD

**Issue by andsat** [thonny/thonny#2308]
shocked to install this in my kids laptop for there to be a big message about "Russian Orcs" at the top. how is this acceptable? please remove this totally racist and inappropriate message from the project. thanks.

**Comment by andsat** [comment]
for clarification, referring to this
![IMG_5456](https://user-images.githubusercontent.com/2237417/171792341-d5c57c4f-300c-45bd-a626-b06e67dbf713.jpg)
.

**Comment by aivarannamaa** [comment]
Will remove after Russia stops its dehumanizing, racist and totally inappropriate actions.

**Comment by andsat** [comment]
"Orcs" is slang invented by Nazis in WW2 to imply that Russians weren't humans. If you really want to put Nazi propaganda in your software project, that's your call, but it violates the Github TOS you agreed to when you signed up. I'm just going to report to Github directly. Thanks.

**Comment by Pidbid** [comment]
For andsat, I agree with you!

**Comment by TOAGGA** [comment]
@andsat  It seems to have changed to "fighting the Russian Invasion".

**Comment by andsat** [comment]
> @andsat It seems to have changed to "fighting the Russian Invasion".

well, at least now it's just a silly political statement.

**Comment by TOAGGA** [comment]
How is it silly? Russia is doing all the stuff @aivarannamaa said in a previous comment, this statement should be there!

**Comment by andsat** [comment]
If your view of history in that region starts at 2022 then yes that is a correct statement. I'm done here so if you want to debate, please find somebody else.

**Comment by TOAGGA** [comment]
I agree, let’s not focus on politics and focus instead on Thonny :)

**Comment by gnull** [comment]
```
thonny.org###maincolumn > p:has-text(Ukraine)
thonny.org###maincolumn > p:has-text(Russia)
```

With µBlock Origin, you can use a filters like these to strip the page of political propaganda. I respect one's right to choose an opinion and advocate for it (even when I don't respect the opinion), but I also respect the right of users for agency in choosing what's being shoved in their face. And I absolutely respect the right of parents to be concerned with ideas their children are exposed to online by irresponsible strangers.
