### ISSUE TITLE
oversized

### ISSUE THREAD

**Issue by quakerpong** [thonny/thonny#2314]
for some reason, everything apart from the actual editor and shell of my thong application is so oversized that it won't fit on my laptop screen. I'm stuck looking at mediator and shell and just the top right portion of the thorny ui

update: sorry, I just looked through this thread and found so many people with the exact same issue, Ill try to fix it with their advice, comforting to know how many people are going through the same thing

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which OS and Thonny version are you using? Did it happen right after installing Thonny or after you had used it for a while?
