### ISSUE TITLE
Unable to connect to COM5: could not open port 'COM5': PermissionError(13, 'Access is denied.', None, 5)

### ISSUE THREAD

**Issue by Max510** [thonny/thonny#2315]
Whenever I install the MicroPython to my Raspberry Pi Pico, Thonny returns this message:
Unable to connect to COM5: could not open port 'COM5': PermissionError(13, 'Access is denied.', None, 5)

If you have serial connection to the device from another program, then disconnect it there first.

Backend terminated or disconnected. Use 'Stop/Restart' to restart.
What can i do?
![Untitled](https://user-images.githubusercontent.com/25057585/173126063-fb5a0bde-4a26-48bc-844d-7ca33bb11429.png)
This is the Info of the board: 
UF2 Bootloader v2.0
Model: Raspberry Pi RP2
Board-ID: RPI-RP2
Im also using Windows 10

**Comment by aivarannamaa** [comment]
What happens when you click the Stop/Restart button?

**Comment by Max510** [comment]
> What happens when you click the Stop/Restart button?

Same message

**Comment by aivarannamaa** [comment]
What other applications do you have open while receiving this error?

**Comment by Max510** [comment]
> What other applications do you have open while receiving this error?

I only got Google Chrome and Spotify

**Comment by aivarannamaa** [comment]
When you close Thonny, can you connect with Putty?

Did Thonny recommend COM5 port or did you select it yourself?

**Comment by Max510** [comment]
Yes thonny recommended COM5 but Im pretty sure i found the issue when NZXT CAM runs in the backroun thonny gives me the error message, when i close it from the task manager thonny connects to my raspberry pi pico.

**Comment by boskee** [comment]
@Max510 Thank you so much - confirmed to be caused by NZXT CAM - I just ran into the same issue. You're a lifesaver.

**Comment by kevinjwalters** [comment]
I was puzzling over same issue on `COM30` on Windows 10. I tried putty while Thonny was running and that was ok. After closing down putty, Thonny could then connect. Very puzzling...

**Comment by komsky** [comment]
For me, the blocking software was Ultimaker CURA slicer. Strange indeed.

**Comment by kroschenko** [comment]
> For me, the blocking software was Ultimaker CURA slicer. Strange indeed. So whoever is reading this, because Thonny 'could not open port', check what currently running software might blocking access to your COM port. This might not be an obvious one.

Thank you very much, it works

**Comment by eagl1** [comment]
On my `ESP32-3248S035C` board the solution is in this post:
[https://github.com/espressif/esptool/issues/682](url)

Which is to install old CH340 driver.

**Comment by PedroRuizCode** [comment]
> For me, the blocking software was Ultimaker CURA slicer. Strange indeed. So whoever is reading this, because Thonny 'could not open port', check what currently running software might blocking access to your COM port. This might not be an obvious one.

Thanks a lot. Closing Ultimaker CURA worked for me 👍
