### ISSUE TITLE
Thorny 3.3.14 micropython 3.18 Raspberry PI Pico

### ISSUE THREAD

**Issue by dharmor** [thonny/thonny#2317]
I am unable to install micropython v3.18 on a Raspberry PI pico. I get a certificate error when using Thorny. If I try to manually install v3.18 micro python v3.18 isn't recognized by the Pico. I tried going down the version list v3.17, 3.16 same issue Pico doesn't recognize it. Finally, v4.15 was installed without issue manually, but I can't access any of the packages in Thorny.
After searching I found others having the certificate errors with v4.18 in Thorny. Has anyone been able to resolve this?

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem and have more information to add.
