### ISSUE TITLE
Software freezes sometimes.

### ISSUE THREAD

**Issue by GodKode-Sensei** [thonny/thonny#2321]
Sometimes thonny freezes on MacBook Air m1. And it starts responding a bit strange while expanding it or squeezing it.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Thonny version are you using?

> Sometimes thonny freezes on MacBook Air m1.

Can you say what were you doing in Thonny before the freeze?

> And it starts responding a bit strange while expanding it or squeezing it.

What do you mean precisely

**Comment by aivarannamaa** [comment]
Sorry for the late reply! Please check whether https://github.com/thonny/thonny/releases/tag/v4.0.0b3 works better for you!

**Comment by aivarannamaa** [comment]
> which one to install on M1 Chip. There was not any arm64 build.

https://github.com/thonny/thonny/releases/download/v4.0.0b3/thonny-4.0.0b3.pkg is the universal build -- suitable for both Intel and arm64

**Comment by aivarannamaa** [comment]
Great!
