### ISSUE TITLE
Update to MicroPython 1.19

### ISSUE THREAD

**Issue by nikoskon2003** [thonny/thonny#2324]
MicroPython 1.19 has been released. When plugging in a device (Raspberry Pi Pico in my case), thonny continues to prompt to install 1.18 firmware.

MicroPython 1.19 release notes: [https://github.com/micropython/micropython/releases/tag/v1.19](https://github.com/micropython/micropython/releases/tag/v1.19)

**Comment by aivarannamaa** [comment]
Thanks for the suggestion!

I'll change the recommended version in couple of days after I've done some more testing.
