### ISSUE TITLE
Thonny not detecting Micro:Bit v2.2.1 for MicroPython install

### ISSUE THREAD

**Issue by dburck007** [thonny/thonny#2330]
New micro:bits (v2.2.1) do not appear in the `Install MicroPython for BBC micro:bit` - it appears to not detect the connected micro:bit (as below)
![image](https://user-images.githubusercontent.com/102138714/174923826-7adf910d-088a-4c96-8dab-c644cb03777e.png)

This appears to be the experience for an out-of-box retail device - or a device reset to factory defaults.

A micro:bit v2.0.0 will automatically detect and install MicroPython as usual.

**Comment by graham-mitchell-vcs** [comment]
@aivarannamaa - can confirm this is happening for us as well. We can get you some Micro:bit V2.21 boards if you don't have access to them.

**Comment by aivarannamaa** [comment]
Thank you for the report!

I assume you are using Thonny 3.3. The new micro:bit model is taken into account in Thonny 4.0, which is currently in pre-release status. The latest beta seems to be quite stable, though: https://github.com/thonny/thonny/releases/tag/v4.0.0b3

**Comment by aivarannamaa** [comment]
Please let me know if 4.0 works for you, as I don't own a micro:bit 2.2.1 myself.

**Comment by graham-mitchell-vcs** [comment]
@aivarannamaa thank you, we'll check it out!

**Comment by dburck007** [comment]
@aivarannamaa @graham-mitchell-vcs The new micro:bits (v2.2.1)  have connected with the beta Thonny 4.0

Thanks!
