### ISSUE TITLE
[Streamlit]Application doesn't work

### ISSUE THREAD

**Issue by mxlbb** [thonny/thonny#2334]
Streamlit can't run on python3.7.9

**Comment by aivarannamaa** [comment]
You can install a separate Python interpreter and configure Thonny to use it (Run => Select interpreter) or you could try the latest beta of Thonny 4.0, which comes with Python 3.10

**Comment by kcarnold** [comment]
I'm successfully using Streamlit on Thonny 4. After installing the package, go to Tools->Open System Shell and then type `streamlit hello` or whatever.

Note that, at least on Windows, interrupting the Streamlit process hangs for a long time unless you have the website open in the browser. Yes, strange, but it seems to be a known issue.

**Comment by aivarannamaa** [comment]
Thanks for the feedback! I guess I can close this issue now.
