### ISSUE TITLE
thonny meaning

### ISSUE THREAD

**Issue by TamilNeram** [thonny/thonny#2336]
What is the meaning of Thonny? Which language is the root word? What is the reason for choosing the word Thonny?

As a user of this IDE, I often wonder the meaning of the word "Thonny". So created this thread.

It will also help in proper translation in Tamil.

**Comment by aivarannamaa** [comment]
There is no meaning. The name comes from Py**THON** and the extra **NY** is for making it cuter.

Please leave the name "Thonny" as is, untranslated.

**Comment by carlosperate** [comment]
> The name comes from Py**THON** and the extra **NY** is for making it cuter.

Just a quick note to say that I was also curious about this. With most Python things called Py-something, I like this twist, and I think it resulted in a pretty cool name, I really like it!
