### ISSUE TITLE
Thonny 4 -- website install?

### ISSUE THREAD

**Issue by isaacl** [thonny/thonny#2339]
Hello! I am teaching in the fall and would like to use Thonny 4 (due to a variety of fixes).  The github releases page is a bit scary for new students...  Have you considered publishing a [thonny.org/beta](https://thonny.org/beta) page?

Pros:
- More installs = more feedback
- Easier / less scary place to install beta.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

I'd rather keep it as is, because I hope to complete the beta phase and switch the main download links to 4.0 soon.
