### ISSUE TITLE
Debug not functioning correctly. 

### ISSUE THREAD

**Issue by d3k4-k3rb3r0s** [thonny/thonny#2345]
Trying to follow a Python course and the step into function is not doing anything other than running my code, rather than going step by step the way it is demo'd by the instructor. is this a Pi issue?

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Thonny version are you using? On which OS? Can you share the code?

**Comment by Kuroojack** [comment]
I have same problem with newest thonny version in windows.

**Comment by aivarannamaa** [comment]
Do you have this problem only with untitled editors or also with editors having a file name?

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem and have more information to add.
