### ISSUE TITLE
Thonny installed correctly on Windows but RTC has only "datetime" function

### ISSUE THREAD

**Issue by BiancaPyF** [thonny/thonny#2351]
Hello, I am using Thonny IDE for a Raspberry Pi Pico with the RP2040 and I have to solve a problem in which I must use interruptions from the RTC class.
When, in the Shell window, I type "help(RTC)" to see what is the problem, I see that I only have the "datetime" function but I miss all the others.
Please, I strongly need the other functions such as setalarm and so, could anyone help me with this issue?
Is Thonny going to be the problem and I may have to change the IDE I am using?

**Comment by aivarannamaa** [comment]
Hi!

Thonny simply forwards there results provided by MicroPython on your device. If something doesn't look right, then I suggest asking in MicroPython forum (https://forum.micropython.org/).
