### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by AdamKaminski01** [thonny/thonny#2353]
MicroPython v1.19.1 on 2022-06-18; Raspberry Pi Pico with RP2040

Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 26, in <module>
ImportError: no module named 'imu'
>>> 

The necessary files are on the pi pico board and I don't know why Thony is generating this error. How to solve this problem.
![imoprt_error](https://user-images.githubusercontent.com/107132353/179472841-94f404ed-5f34-4687-80ae-6c3a0f185a78.png)

**Comment by aivarannamaa** [comment]
It looks like your files don't have `.py` suffix. That's why MicroPython doesn't treat them like Python modules.
