### ISSUE TITLE
[PROPOSAL] Ability to copy content of 'Assistant' tab to clipboard

### ISSUE THREAD

**Issue by ClaytonCurtis1947** [thonny/thonny#2355]
Users trying to take advantage of the 'Assistant' feature -- perhaps especially those relatively new to Python -- may want / need to have a way to persist the contents of the 'Assistant' tab so they can work through the items it contains.  For an example, please see the attached image.  Being able to copy the contents, with an option for expanding the items would make that possible.

Thanks in advance for your consideration!

![Thonny 'Assistant' tab content](https://user-images.githubusercontent.com/34657219/180234384-4ec56f7b-b80d-411d-930b-932039971fa9.JPG)

**Comment by aivarannamaa** [comment]
Have you tried selecting the text (either with mouse or Ctrl-A) and copying with Ctrl-C? I don't have a Windows machine at hand at the moment, but it works nicely in Linux.

**Comment by aivarannamaa** [comment]
Just checked -- copying Assistant text is possible in Windows as well
