### ISSUE TITLE
[PROPOSAL] Seed find/replace with currently-selected text

### ISSUE THREAD

**Issue by ClaytonCurtis1947** [thonny/thonny#2356]
Apologies in advance if I've missed something, in which education would be helpful.
I've found it both cumbersome and error-prone to get the desired text into the find/replace dialog.  Other than for short and simple strings into the dialog, direct entry of text is inefficient and prone to typographical errors. 

My current process is to select text, copy it, then paste it into the dialog, then do the find/replace. That is usually somewhat better than re-typing the text, but not much.

Seeding the find/replace text function with currently selected text is the approach taken by the majority of mainstream editors.  (Even IDLE, in the case of 'find'.) Enhancing the find/replace function in that manner would improve usability and reduce risk of error.

I hope you will consider this proposal.

**Comment by aivarannamaa** [comment]
Needs to be tested again with Ctrl-F shortcut on Linux
