### ISSUE TITLE
some turkish language letters types wrong

### ISSUE THREAD

**Issue by mu-us61** [thonny/thonny#2357]
![image](https://user-images.githubusercontent.com/73366454/180276113-edd32dd3-05c2-4830-95f7-cd85a240adf5.png)

hello some letters not working properly like ığş it types wrong like in the screen shot

**Comment by aivarannamaa** [comment]
Thank you for the report!

Does it only happen when typing? When you copy-paste the same letter into Thonny's editor, do they look right then?

**Comment by mu-us61** [comment]
Hello there , I tried and when I copy paste Turkish letters are fine, worked properly , the problem only exist when typing

**Comment by aivarannamaa** [comment]
Can you type some Turkish non-latin letters without problems? If yes, can you spot a pattern?

**Comment by mu-us61** [comment]
hello it seems the problem is with tkinter I reported the bug to python repo, thank you
![image](https://user-images.githubusercontent.com/73366454/180396442-eb837093-141f-45ca-b422-eee57b9fac1b.png)
