### ISSUE TITLE
Thonny crashed after pasteing an emoji

### ISSUE THREAD

**Issue by earhater** [thonny/thonny#2361]
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  6217
  Current serial number in output stream:  6222
![Screenshot from 2022-07-26 10-58-46](https://user-images.githubusercontent.com/109986940/180954743-0baa82dc-0f8e-48d5-a207-13346fbb71e8.png)

crashed with this code in terminal after pasteing an emoji from http://www.unicode.org/emoji/charts/full-emoji-list.html#1f4b8

**Comment by aivarannamaa** [comment]
Thank you for the report!

I assume your Thonny is installed with `apt` and therefore is using system's Tk, which in this version does have problems with emojis. I recommend installing a pre-built bundle instead, which comes with private Python 3.10 and newest Tk. You can do so by downloading and running the bash-file from https://github.com/thonny/thonny/releases/tag/v4.0.0b3
