### ISSUE TITLE
Thonny editor refuses to show contents of .csv file

### ISSUE THREAD

**Issue by lowfatcode** [thonny/thonny#2368]
CSV is pretty human readable so it would be nice if the editor would allow you to open in the same way it allows .txt files.

My use case is I'm working on a project where the device is logging data in CSV format - currently if I want to have a peek at the file contents I need to download the file from Thonny which isn't ideal.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Thonny version are you using? At least 3.3.12 and newer are supposed to show csv files as plain text.
