### ISSUE TITLE
failed to write file

### ISSUE THREAD

**Issue by HobCarm** [thonny/thonny#2373]
Using Raspberry Pi with senser hat I started a new file in Thonny.
When I tried to save it in default directory as directed I got:
Permission Error
Looks like this file or folder is not writable."

I was successful in opening a python file that was in default directory,

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which directory was it? Can you write into another directory?

**Comment by HobCarm** [comment]
The directory is pi/webapp.
The problem occurs when I try save a program I just wrote. It appears that I cannot write to a file that did not previously exist.
In another idle I got a error 13.

**Comment by aivarannamaa** [comment]
Perhaps you created this file with `sudo` or as another user? If you can't write this file with other applications as well, then you should check the file permissions.

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem and have more information to add.
