### ISSUE TITLE
key shortcut for menu "tools -> open system shell..."

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#2379]
can we have a key shortcut for menu "tools -> open system shell..." ???
e.g. Shift+Control+T

**Comment by aivarannamaa** [comment]
Thank you for the suggestion, but I'd rather not fix the use of this shortcut yet -- I may need it for another feature in the future.

But you can add it for yourself by editing Thonny's configuration file: https://github.com/thonny/thonny/wiki/Custom-shortcuts

**Comment by kr-g** [comment]
i think opening a shell is more or less on the same "level" as "run current script in terminal".
so i think it should come also directly out of the box.
but ... yes... if there is another option ...

**Comment by kr-g** [comment]
https://github.com/thonny/thonny/pull/2380#issuecomment-1209225221

i cleaned it from env related code.
sorry again for that.
i dont wanted to waste your time.

**Comment by kr-g** [comment]
https://github.com/thonny/thonny/compare/master...kr-g:thonny:kr-g-terminal-short-key?expand=1

**Comment by aivarannamaa** [comment]
In Thonny 4.1 I want to make it possible to add or change shortcuts in the options dialog (#306)
