### ISSUE TITLE
Git version of Thonny is broken... Work Dialog no way to get to Thonny

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [thonny/thonny#2382]
For a couple of days now when I run the Git version of Thonny I get "Work Dialog" and there is no way to get to Thonny. If I click cancel, the X, or even the install button I cannot get to Thonny. Everything fails and Thonny is never opened. Maybe this should be moved to another branch until it is stable.

Is there a workaround to fix this other than running the stable build?

**Comment by aivarannamaa** [comment]
Sorry, I forgot that someone else may be using the master branch and made Thonny to shortcut to the dialog I'm developing.

This is fixed now. 

You're also right about branches. I will probably continue in master for this feature, but try to be less lazy in the future.
