### ISSUE TITLE
Option for UTC / timezones

### ISSUE THREAD

**Issue by Skwarc** [thonny/thonny#2383]
Since I'm using pi pico which doest get his own timezone I noticed that pi pico registers PC's time as UTC which caused me many problems. I suggest some option would be added where you can pick whether the Thonny should pass the PC's time or not since Timezones are not exactly easiest to deal with especially because of summer/winter time

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

I'm assuming you are using Thonny 3.3. In Thonny 4.0, the MicroPython and CircuitPython configuration pages have these checkboxes:

![image](https://user-images.githubusercontent.com/1802/184063005-127dea41-9e83-41f1-a8e5-9d2716147bed.png)

If first is checked and other is not, then the device's RTC is synced to UTC.

**Comment by Skwarc** [comment]
Awesome!! Exactly what I needed :DD
Thank you!
