### ISSUE TITLE
How can I run mypy for static analysis of my code before runnning / executing the script?

### ISSUE THREAD

**Issue by ger-reyal** [thonny/thonny#2384]
Hi,
I have mypy installed on my windows, and I also see that mypy is an installed package in my Thonny environment as far as can see in the package manager.
I can also import 'typing' in my python code and it gives the proper type definitions.

What I am missing now, is the option to run only mypy for static code analysis without runing the code, to see results and only then run the code. Like god old C compiler.
How should I do it?
Eyal

**Comment by aivarannamaa** [comment]
Hi!

This is currently not possible -- there is no separate command for invoking code analysis.

I'll take some time to decide, whether I want to add such command or not.

**Comment by aivarannamaa** [comment]
To be handled under #2089
