### ISSUE TITLE
UI zoom factor is invalid

### ISSUE THREAD

**Issue by jiaoxiangyu05** [thonny/thonny#2392]
UI zoom factor is invalid，my version is 3.3.13

**Comment by aivarannamaa** [comment]
> UI zoom factor is invalid

What do you mean precisely?

**Comment by jiaoxiangyu05** [comment]
option——general——UI scaling factor (default)
option——general——UI scaling factor(2.0)

Both options have no change to toolbar icon size

**Comment by jiaoxiangyu05** [comment]
![图片](https://user-images.githubusercontent.com/61376513/186795926-0c9fe37f-ad3e-49a4-ae2b-eb6022ef8ad2.png)
![图片](https://user-images.githubusercontent.com/61376513/186795950-58a31e6a-4178-4460-afd5-beedbcaa2963.png)

**Comment by aivarannamaa** [comment]
Please note that changing the scaling factor only has effect after restarting Thonny. Evene then, If you have a hi-res display, the default scaling factor may be 2.0 or close to that. Scaling factor 1.0 is default only for 72dpi screens.

**Comment by jiaoxiangyu05** [comment]
I know to restart Thonny.The resolution is 1920*1080.
The same display , V3.3.10 scaling factor 2.0 icons are significantly larger.
I think it's a bug.
![图片](https://user-images.githubusercontent.com/61376513/186823869-17442fe4-2c58-4045-8ec0-f0aea2f90280.png)
![图片](https://user-images.githubusercontent.com/61376513/186823884-e13c017a-926e-4114-8c0d-a2bc32afc9fb.png)

**Comment by aivarannamaa** [comment]
Thonny 3.3.10 has different version of Tk, which may compute the default scaling differently.

Scaling the toolbar icons was changed in 4.0. Depending on the width of the main font, the increase of icon size (2x) happens somewhere around scaling factor 2.0 or higher.

**Comment by paradise321** [comment]
Previously I met the same issue with Thonny 4.0.x, after checking your discussion, and set UI scaling factor to 2.5x or 3.0x, it does work! All the icons on toolbar have been enlarged. 
![4 0 1-UI-scaling-factor-2 5x](https://user-images.githubusercontent.com/20944732/190854592-4005c6c5-38fb-4b80-b706-746c919689c8.png)

**Comment by aivarannamaa** [comment]
Will consider changes under #2457
