### ISSUE TITLE
auto proposal of completions in comments

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#2393]
when typing after a comment was introduced with # auto completion still makes proposals while typing.
also it causes sometimes a ui freeze.
i cant say if this really makes sense or not.
it is useful when documenting interfaces, but for the normal use-case somehow it should be not like that.

**Comment by aivarannamaa** [comment]
I agree, this can be confusing. That's how the jedi library works. I'll see if I can change this.

**Comment by kr-g** [comment]
it is also between single, double, or tripple quotes 
also => when inside of a string area

**Comment by aivarannamaa** [comment]
I turned automatic completions off for comments. 

In strings it seems to work quite OK -- according to my tests it only proposes paths in the current directory.
