### ISSUE TITLE
Speaking of translating Thonny to Vietnamese

### ISSUE THREAD

**Issue by bhuyquang1** [thonny/thonny#2396]
I am a Thonny translator and I am translating the software to Vietnamese.
(Not to say that I am the only Vietnamese translator alive)
Will you add my Vietnamese translation in the future versions?
P.S. I support Ukraine against Putin's evil intentions.
@aivarannamaa

**Comment by aivarannamaa** [comment]
Thank you and you're welcome!

Adding a new language is currently implemented in "self-service" style. Please see https://github.com/thonny/thonny/blob/master/docs/translate.md#short-story-for-translators for details.
