### ISSUE TITLE
wikipedia

### ISSUE THREAD

**Issue by valsha** [thonny/thonny#2397]
https://ru.wikipedia.org/wiki/Thonny

![image](https://user-images.githubusercontent.com/7966513/185784317-897ed336-e608-4e78-9ec3-878789632d95.png)

"In 2022, announced support for fascism in Europe."

**Comment by bhuyquang1** [comment]
> "In 2022, announced support for fascism in Europe."
That's a serious WP:NPOV violation.

**Comment by aivarannamaa** [comment]
Thank you for the notification!

I was able to revert this change. Let's hope it stays like this.
