### ISSUE TITLE
Offline Install

### ISSUE THREAD

**Issue by CFArmy** [thonny/thonny#2399]
I am attempting to install Thonny on a computer without access to the internet. Is there a way to manually install Thonny?

**Comment by aivarannamaa** [comment]
On which platform do you want to install it?

For example, on 64-bit Windows 10 or 11 you could download https://github.com/thonny/thonny/releases/download/v4.0.0/thonny-4.0.0.exe to a thumb drive and install it from there.

**Comment by CFArmy** [comment]
I am installing on 64-bit Windows 10. I have tried using the ThonnyRunner310 x64 application but it gives me the error python310.dll was not found. I have also tried to run create_installer.bat but it runs into several errors as well.

**Comment by aivarannamaa** [comment]
I don't know what is ThonnyRunner310.

> I have also tried to run create_installer.bat but it runs into several errors as well.

This is not meant for Thonny users. I am using it for creating the installers, which are available for download for the end users.

It looks like you have cloned or downloaded this repository, but you should do this only if you intend to develop Thonny IDE itself.

Did you try https://github.com/thonny/thonny/releases/download/v4.0.0/thonny-4.0.0.exe ?

**Comment by CFArmy** [comment]
I do not see a folder labeled releases under https://github.com/thonny/thonny. I found ThonnyRunner310 under https://github.com/thonny/thonny/tree/master/packaging/windows. I specifically tried to use https://github.com/thonny/thonny/tree/master/packaging/windows/ThonnyRunner310/x64/Release.

**Comment by aivarannamaa** [comment]
>  I specifically tried to use https://github.com/thonny/thonny/tree/master/packaging/windows/ThonnyRunner310/x64/Release.

This is not meant to be executed outside of special context.

Did you have success with https://github.com/thonny/thonny/releases/download/v4.0.0/thonny-4.0.0.exe ?

**Comment by CFArmy** [comment]
![image](https://user-images.githubusercontent.com/111885652/186244755-dbaf8343-24ea-4280-b564-f57a06062826.png)
I get this error when I try to follow that link.

**Comment by aivarannamaa** [comment]
I can't reproduce this. I suggest you try again with different browser and/or by tweaking your proxy settings.
