### ISSUE TITLE
Find function not highlighting selected result in block comments

### ISSUE THREAD

**Issue by brettjayp** [thonny/thonny#2407]
I'm seeing that while all results are still being underscored when searching with the Find & Replace tool, if the active selection is in a comment block, it will not be highlighted. I did not test this in the attached video, but the highlighting works as expected when the result is in an inline comment.

Environment where found is Thonny 3.3.13, Python file open, M1 MacBook Pro on MacOS 12.5.1

https://user-images.githubusercontent.com/53981534/187013394-105d7924-1f18-495d-bc8e-7f867047b78f.mov

**Comment by aivarannamaa** [comment]
Thank you for this nice report!

I was able to fix it. The fix will be in version 4.0.1
