### ISSUE TITLE
Thonny asks me for password for authentication

### ISSUE THREAD

**Issue by yakubszatkowski** [thonny/thonny#2411]
At first, I tried to use thonny so I can learn python and use step by step feature, which didn't work at all. I tried meddling in settings and now whenever I start Thonny it ask for password. Uninstalling and installing again doesn't solve anything.

**Comment by yakubszatkowski** [comment]
Already took care of it just downloaded portable version

**Comment by aivarannamaa** [comment]
Perhaps you had accidentally changed your interpreter mode to "Remote Python 3 (SSH)"? If you click on the lower-right corner of Thonny's main window, you can switch back to the default "Local Python 3", which is not supposed to ask any passwords.
