### ISSUE TITLE
AssertionError : RPM Packaging

### ISSUE THREAD

**Issue by abrarwali** [thonny/thonny#2413]
thonny/test/plugins/test_pip_gui.py:15: AssertionError

assert <re.Match object; span=(0, 34), match="extra == 'dev' and extra == 'dev1'"> is None
E            +  where <re.Match object; span=(0, 34), match="extra == 'dev' and extra == 'dev1'"> = <built-in method match of re.Pattern object at 0x7f776b7c5df0>("extra == 'dev' and extra == 'dev1'")
E            +    where <built-in method match of re.Pattern object at 0x7f776b7c5df0> = re.compile('^.*\\bextra\\s*==.+$').match

**Comment by aivarannamaa** [comment]
Thank you for the report! I'll fix this in the upcoming 4.0.1

**Comment by abrarwali** [comment]
Happy to be of help :)
