### ISSUE TITLE
Armenian support

### ISSUE THREAD

**Issue by narektigranyan** [thonny/thonny#2417]
Hello,

We are happy to use Thonny IDE, it is very usefull application. It is good and helpfull for children who learn CS and robatics as well.
In our country (Armenia) we use it a lot and there are many users staring use this in schools.
We have a big request to add Armenian language support in coding field as well, the UI is good for Armenian, but when we trying to put some Armenian letters, it shows just '????'. 
Please give some abilities to use Armenian as well or if there is already please give some instructions.

Thank you in advance!

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please investigate #2405 -- this deals with the same problem. Also, let's continue our discussion there.
