### ISSUE TITLE
Please add a Package as Snap in the Snapstore

### ISSUE THREAD

**Issue by CapeCrusader321** [thonny/thonny#2418]
I am using ubuntu 20.04.5, its not convenient to use the apt version since its ancient and the flatpak support for ubuntu is poor recently the official ppas are broken, But Snaps are working fine so taking in consideration Ubuntu users please add a Snap option making it easy to use latest thonny on ubuntu in a hassle-free manner

**Comment by aivarannamaa** [comment]
Thank you for the suggestion! Unfortunately I don't have time for learning how to create a snap package, but if someone else does it then I'm happy to help with answering questions about Thonny's ways.
