### ISSUE TITLE
Webrepl autocomplete does not work for variables

### ISSUE THREAD

**Issue by wohltat** [thonny/thonny#2419]
At first, i tried thonny and i like it as far as i've tried it. Very promising project.

Now to the issue.
Tab autocompletion does not work for variables although the variables are known to thonny since they appear in the 'Variables' panel on the right. 
Autocomplete seems to work for keywords though.

---------------
Version 4.0.0
OS: manjaro (arch)

**Comment by aivarannamaa** [comment]
Thank you for the report!

> Tab autocompletion does not work for variables although the variables are known to thonny since they appear in the 'Variables' panel on the right.

I assume you meant autocompletion in the Shell (because autocompletion in the editor only cares about variable definitions in the written code). Anyway, I've met similar problems both in the editor and shell and I'll try to fix them for the next release.

**Comment by wohltat** [comment]
Btw in the editor the tab completion does not work like in the Shell.
It just inserts a tab character. 

What about doing it like most other editors and interpreting the tab as completion key if there is text left of the cursor.

**Comment by aivarannamaa** [comment]
> What about doing it like most other editors and interpreting the tab as completion key if there is text left of the cursor.

This behavior can be turned on in "Tools => Options => Editor"

**Comment by wohltat** [comment]
Oh, must have missed it.
Awesome its implemented already.

I vote for making this default.

**Comment by aivarannamaa** [comment]
Let's keep it open until I've fixed the problem with completing the variables.

**Comment by wohltat** [comment]
Yeah right. I just confused it with the Tab-completion issue i mixed in, which is solved now.

**Comment by aivarannamaa** [comment]
Thonny 4.1 will support name completions in the MicroPython / CircuitPython shell (again).
