### ISSUE TITLE
After switching editor tabs in macOS, the new editor appears without text and scrollbar 

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#2425]
... only the gutter remains visible.

It looks like since Tk 8.6.11, the CodeView widgets, for some reason get grid_removed after creating new editor. The gutter will be re-added because of other events.

**Comment by aivarannamaa** [comment]
Could not find the reason. Added forced re-gridding of the widgets as a work-around.

**Comment by aivarannamaa** [comment]
@markmcgookin, please try version 4.0.2

**Comment by markmcgookin** [comment]
Just updated. Exact same thing on 4.0.2

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/1053345/216025098-1287e0a8-475c-4958-8eca-efcef173690b.png">

**Comment by aivarannamaa** [comment]
I could now reproduce this, but I still don't know why this happens. I extended my previous hack so that it should work better now. The fix will be in 4.0.3
