### ISSUE TITLE
Sometimes file in tab shows a blank page

### ISSUE THREAD

**Issue by beetlegigg** [thonny/thonny#2434]
Using 4.0.0 on a mac running Big Sur.  (its really great :-) )  When I have several files open in different tabs, sometimes when swapping to a different tab the files does not display and just a white screen is shown. (I use a dark screen 'Desert Sunset') Clicking on a different tab and then back to tab that showed the white screen is usually enough to provoke it to display the file properly.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Actually I think I discovered the same problem myself couple of days ago (#2425). Unfortunately I did not find the reason for this -- I haven't seen it happen on other platforms and it also doesn't happen on older versions of Tk on macOS. I implemented a work-around, which will be published in Thonny 4.0.1 (hopefully before the end of this week).

If you still meet this problem in 4.0.1 or later then please re-open #2425.
