### ISSUE TITLE
Install for all users silently

### ISSUE THREAD

**Issue by cjcm3** [thonny/thonny#2437]
I'm trying to install it silently for all users using a script but it keeps on installing only for the local user and it install in appdata. Do you have an MSI file that I could download? Maybe that can work?

**Comment by aivarannamaa** [comment]
You could try `/ALLUSERS` command line switch: https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

Possibly related issues: 

* https://github.com/thonny/thonny/issues?q=is%3Aissue+inno
* https://github.com/thonny/thonny/issues?q=is%3Aissue+silent
