### ISSUE TITLE
Can not open step through function in Windows

### ISSUE THREAD

**Issue by ckellum** [thonny/thonny#2443]
Step through function in debug mode does not work. It runs through the code without those buttons being highlighted. I downloaded the newest version this morning.

Thonny 4.0.0
Windows 10 64bit
Python 3.10.6 64bit
TK 8.6.12

**Comment by aivarannamaa** [comment]
Please check #2415. Does it match your issue?

**Comment by ckellum** [comment]
Hello Aivar,

Thank you for reaching out, this explanation and saving of the file do
work for me. I apologize I have used Thonny in the past and didn't research
different behavior.

Thank you for your time,
Curt
