### ISSUE TITLE
Using sys.exit creates a process that cannot be interrupted (need to click Stop before clicking Run again)

### ISSUE THREAD

**Issue by nikola-benes** [thonny/thonny#2447]
I have the following script:

    import sys
    sys.exit()

Steps to reproduce the issue and observed behaviour:

- Press the Run button. The script starts but doesn't finish. (The second `>>>` prompt doesn't appear in the shell window.)
- Press the Run button again. Nothing happens for a few seconds, and then the following message appears: “Could not interrupt current process. Please wait, try again or select Stop/Restart!”

Expected behaviour: The script should exit, and the following Runs should proceed as usual.

Version: Thony 4.0.0
OS: Linux

**Comment by aivarannamaa** [comment]
Thank you for the report!

I just fixed this under #2433 and release it as 4.0.1 tonight.
