### ISSUE TITLE
Can't interrupt the script if there are sleeps in the code

### ISSUE THREAD

**Issue by mastrolube** [thonny/thonny#2448]
Hi there, I have a problem with Thonny and ESP32.
I'm not able to stop the script (even from the `run - interrupt execution`) if there is a machine.sleep(t) inside.
I have a loop in the boot.py, for example:
```
from machine import sleep

for _ in range(100):
    print("hello!")
    sleep(500)
```
Is that a bug?
Thanks!

**Comment by mastrolube** [comment]
I've replaced the machine.sleep with time.sleep_ms and that solves the problem

**Comment by aivarannamaa** [comment]
Thank you for this information!

I'm afraid there's nothing else Thonny could do. It is unavoidable that a certain programs can't be interrupted.
