### ISSUE TITLE
AttributeError: 'UART' object has no attribute 'wait_tx_done'

### ISSUE THREAD

**Issue by diegorestrepo78** [thonny/thonny#2453]
I run a code for modbus serial master on raspberry pi pico and it shows me this message AttributeError: object 'UART' has no attribute 'wait_tx_done', UART library is not completed

What can I do?

**Comment by aivarannamaa** [comment]
Sorry, I'm not familiar with this library. I recommend asking in [MicroPython discussions](https://github.com/orgs/micropython/discussions)
