### ISSUE TITLE
Unable to scroll history in Thonny-4.0.0 after pressing stop

### ISSUE THREAD

**Issue by jakoai** [thonny/thonny#2456]
Thonny seems to reset the entire shell after pressing stop button. Is it a bug or a feature?

**Comment by aivarannamaa** [comment]
Thank you for the report!

It's a feature gone wrong. It should clear the shell before you run a script, but I forgot that one may want to see previous output after pressing Stop. I'll try to make it more sensible in this respect.

You can turn off this behavior from Tools => Options => Shell => First checkbox

**Comment by aivarannamaa** [comment]
The upcoming Thonny 4.0.2 won't clear the shell anymore if Stop/Restart is used for stopping the process.
