### ISSUE TITLE
Device is busy or does not respond.

### ISSUE THREAD

**Issue by JawadMezaal** [thonny/thonny#2460]
I have installed Thonny to work on ESP32-WROOM-32. I downloaded the firmware from Micropython, but all the time I got this message: Device is busy or does not respond. Your options:

  - wait until it completes current work;
  - use Ctrl+C to interrupt current work;
  - reset the device and try again;
  - check connection properties;
  - make sure the device has suitable MicroPython / CircuitPython / firmware;
  - make sure the device is not in bootloader mode. I tried to stop and run but all the time no response.
I connected to different computers and change the cable, but it still isn't working.
Please, do you have any Idea to solve this problem?

**Comment by aivarannamaa** [comment]
Thank you for the report!

Did you try Ctrl-C?

Can you get to REPL with some simpler tools (eg. Putty or tio)?

**Comment by JawadMezaal** [comment]
Thank you for replying,
I tried all the recommendations in the error message but got no response. I
did not try with putty or to. I think need to learn them and try them.
