### ISSUE TITLE
How to close the Find & Replace Dialog

### ISSUE THREAD

**Issue by microenh** [thonny/thonny#2461]
I don't see a way to close or hide the Find & Replace dialog in 4.0.1 on the Mac. In Version 3.3.14, the dialog window had a red button (standard Mac) in the title bar that could be used, but this button is missing in 4.0.1

**Comment by microenh** [comment]
Thanks. I didn’t try that.

Mark

**Comment by sdylewski** [comment]
I see the same problem.  Unable to close the window, so my scrolling doesn't work on the main window either.  need to restart the application.
