### ISSUE TITLE
Is there a way to view tab?

### ISSUE THREAD

**Issue by bearney74** [thonny/thonny#2475]
In a lot of editors, they differentiate spaces from tabs, but having a symbol such as -> for tabs.  Is there a way to enable this with thonny?

**Comment by aivarannamaa** [comment]
Please see "Tools => Options => Editor => Highlight tab characters".

**Comment by bearney74** [comment]
Thanks..   I had that selected, but didn't really notice the faint yellow
"block" until I really looked for it.  Now since I know what to look for,
its easier to see.

Thanks!
