### ISSUE TITLE
cannot install a library 

### ISSUE THREAD

**Issue by rusty-error** [thonny/thonny#2487]
I am trying to upload some libraries and i get this error. I tried couple of libraries and get the same error for most of them. Whats the problem?
![Screenshot from 2022-10-03 15-06-47](https://user-images.githubusercontent.com/114786953/193573328-d35b020f-d876-4231-a73c-124394950bb3.png)

**Comment by aivarannamaa** [comment]
According to the screenshot you used "Manage plug-ins", but you need to use "Manage packages". Please read the explanation at the top of the dialog on your screenshot.

**Comment by rstmsvk** [comment]
thanks :) I need to learn how to read sorry for that :)
