### ISSUE TITLE
thonny seems to fail in using the 'help' command at least from the shell.

### ISSUE THREAD

**Issue by mlytle0** [thonny/thonny#2496]
You can enter help() from the shell and it responds, but when you go deeper it won't provide any further specifics on classes or anything and freezes.  Hitting the 'stop sign' unfreezes it without having to exit the program.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Are you using version 4.0.0? A help-related bug was fixed in 4.0.1. 

If you are using 4.0.1, then please give me more precise instructions for reproducing the problem.

**Comment by mlytle0** [comment]
Yes, it's 4.0.0.  I'm running an arch derivative, so as soon as the new version shows up in the aur repo, I'll get the newer version. Perhaps it's already fixed then.
