### ISSUE TITLE
__file__ contains a relative path

### ISSUE THREAD

**Issue by nicolasdespres** [thonny/thonny#2497]
With Thonny version `v4.0.1-11-gf0fadb76`, the following program prints `test_file.py` when run from Thonny, whereas it prints the absolute path to the file when run using `python3 test_file.py` from the command line shell.

```py
print(__file__)
```

I expect it to print the absolute path.

**Comment by aivarannamaa** [comment]
Thanks for the report!

It looks like setting it an absolute path is the right thing to do. Will change this in 4.0.2.
