### ISSUE TITLE
Request: Improved Variable Explorer

### ISSUE THREAD

**Issue by mu-us61** [thonny/thonny#2503]
Hello it would be perfect if the variable explorer is detailed like "Spyder IDE" , especially for beginners , seeing types would be very helpful

![image](https://user-images.githubusercontent.com/73366454/195680307-6517b89f-4806-4118-a7d2-cec3aaa9e904.png)

**Comment by aivarannamaa** [comment]
Thank you for the suggestion!

I understand the benefit of having explicit type column in the Variables view, but it would make the initial impression of the UI more complex. Luckily, for simple values the type is easy to infer from the value's repr string.

Even if I added this column, I wouldn't put it before the value, before this could give the wrong impression, that type belongs to the variable (but this is not the case in Python). In my opinion, the principle, that a value has type, is nicely communicated by Thonny's Object inspector (View => Object inspector) -- it always shows a value (together with its type), even if the value is approached via a variable.

**Comment by mu-us61** [comment]
Ok thanks, I missed the Object inspector, that is very nice and far more detailed
