### ISSUE TITLE
How to automatically clean the log window

### ISSUE THREAD

**Issue by 0muyu0** [thonny/thonny#2510]
Running a python script in an infinite loop, the script will print the output using the print function. As the output increases, the Thonny execution will become slower and consume more and more computer memory. Is there a way for Thonny to automatically clean the log window? thank you!

**Comment by aivarannamaa** [comment]
By default Thonny is supposed to keep only last 1000 lines (see Tools => Options => Shell). Unfortunately it seems that there may be a memory leak. I'll deal with it under #2212
