### ISSUE TITLE
umqtt_simple install error

### ISSUE THREAD

**Issue by Ymoris** [thonny/thonny#2525]
Error during intallation

**Comment by aivarannamaa** [comment]
Can you install it with plain pip?

**Comment by bertolius-me** [comment]
Same error for me trying to use the "Manage packages..." feature.  I tried downloading the tar.gz file  and install from file, but still same error. However, mip.install('umqtt.simple') worked.

**Comment by aivarannamaa** [comment]
@Ymoris, the last comment gave me the idea that you may have used a MicroPython back-end in Thonny. Is this right?

I'll deal with this under #2524

**Comment by aivarannamaa** [comment]
Please try Thonny 4.0.2
