### ISSUE TITLE
SSL Certificate Issue

### ISSUE THREAD

**Issue by MOCS-BDobson** [thonny/thonny#2528]
To preface I am an IT Tech in a school:

**Collecting pygame
Could not fetch URL https://pypi.python.org/simple/pygame/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) - skipping Could not find a version that satisfies the requirement pygame (from versions: ) No matching distribution found for pygame
Return code:**

Admins can install modules without issues. Teachers couldn't until I gave the group full control over Thonny program/data folders. Students cannot even with control over the same folders as Teachers. I messed with groups a bit and Students not hitting as restrictive a firewall can install modules. I spoke to the people that manage the firewall and they are insisting it's a Thonny issue, and that nothing is being blocked.

Does anyone have anything I can try?

**Comment by aivarannamaa** [comment]
Does your issue look similar to #1986?

**Comment by MOCS-BDobson** [comment]
> Does your issue look similar to #1986?

Definitely a close match, only real difference is that I'm using the inbuilt Python interpreter rather than MicroPython. The point about Chrome saying the license is the same is true as well as I can manually navigate to pypi.org and download the correct module (if I know which is correct), just not use the inbuilt package installer or pip. I'll try installing the certificate you provided and see if it sorts my issue. Thank you!

**Comment by MOCS-BDobson** [comment]
> Does your issue look similar to #1986?

Do I need to basically get a certificate for pypi.org and get that on my test machine?

**Comment by aivarannamaa** [comment]
> Do I need to basically get a certificate for pypi.org and get that on my test machine?
 
I suppose. 

I just found a page, which may help you: https://jhooq.com/pip-install-connection-error/

**Comment by MOCS-BDobson** [comment]
> > Do I need to basically get a certificate for pypi.org and get that on my test machine?
> 
> I suppose.
> 
> I just found a page, which may help you: https://jhooq.com/pip-install-connection-error/

Step three on that one fixed it for me! Got a group policy creating the folder and ini file now for all students with Thonny and they can install packages just fine. Thank you so much for your help!
