### ISSUE TITLE
Issue BACK_END: Exception while handling 'get_globals' 

### ISSUE THREAD

**Issue by ONE1CHINA** [thonny/thonny#2530]
Hi,

my esp32 works well with Thonny 2 weeks already. But the problem occured just now.

Mac.OS
Info: >>> PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_globals' (thonny.plugins.micropython.mp_back.ManagementError: Management markers missing).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.

Process ended with exit code 1.

[backend.log](https://github.com/thonny/thonny/files/9921708/backend.log)

BR,

**Comment by aivarannamaa** [comment]
Thank you for the report!

It looks like MicroPython crashed on your device:

> Guru Meditation Error: Core  1 panic'ed (IntegerDivideByZero). Exception was unhandled.

Which MicroPython version are you using? Perhaps a newer version fixes this?

**Comment by ONE1CHINA** [comment]
Thank you for your reply! I do run the newest version of microPy. 
The problem has been solved: my main.py programm was wrong which was executing as the power is on....
