### ISSUE TITLE
macOS find and replace - can't close dialog box

### ISSUE THREAD

**Issue by eric-asu** [thonny/thonny#2531]
When opening find and replace on the macOS version of the app, you can't close/dismiss the dialog box.

<img width="1508" alt="Screenshot 2022-11-02 at 6 26 59 PM" src="https://user-images.githubusercontent.com/2099576/199632570-735bcfaf-7ccc-417c-9d5c-50fbef4fa9bc.png">

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please see #2461
