### ISSUE TITLE
unable to connect to com5: port not found

### ISSUE THREAD

**Issue by JMD-PyAreSquare** [thonny/thonny#2539]
I'm trying to connect my raspberry pi Pico W (with header pins) to thonny, but whenever I try to configure the interpreter to micropython for the pi pico, it keeps giving me this error:
===
Unable to connect to COM5: port not found

Process ended with exit code 1.
===
I also see that it has a yellow warning symbol in device manager with this following error:
===
This device cannot start. (Code 10)

A device which does not exist was specified.
===

**Comment by Brudehien** [comment]
Running into this same issue using Pico W. Removed a majority of peripherals and tested other USB ports with no luck. Tried to use a different board and got the same error.

**Comment by aivarannamaa** [comment]
Are you sure your Pico is on port COM5 ?

**Comment by JMD-PyAreSquare** [comment]
yep it is.

**Comment by JMD-PyAreSquare** [comment]
I checked in device manager

**Comment by JMD-PyAreSquare** [comment]
im also using windows 11

**Comment by aivarannamaa** [comment]
I'm afraid this issue is out of scope for Thonny. If you can connect to your device via another tool (eg. Putty) but can't connect with Thonny using the same port, then please re-open this issue.
