### ISSUE TITLE
cannot install any packages

### ISSUE THREAD

**Issue by MoonlightFlora** [thonny/thonny#2542]
I can't install any packages.
When I try to search up pygame (the package I want) nothing shows up. There is only an endless loading button
![image](https://user-images.githubusercontent.com/118339864/202115867-ed4e7e34-bfb4-4e02-86b7-3cb6d7290dfe.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

What happens when you select "Tools => Open system shell" and enter `pip install --user pygame`?

**Comment by aivarannamaa** [comment]
@kyubird, are you trying to run this script on a MicroPython device? Most of the packages containing setup.py are meant for CPython and there is no chance it could work with MicroPython.

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem and have more information to add.
