### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by BodyanB** [thonny/thonny#2545]
in ubunto do not work with resberry pico w

**Comment by brianlinuxing** [comment]
Forgive me, but it might help the Thonny developers  if you could explain:

1. The environment (operating system, version, hardware, etc ) involved:

2. What you have done.

3. What you expect to happen.

4. The precise error messages (screenshots):

5. What documentation you have studied to confirm this error.

And any other information that might assist their diagnosing of the problem.

[PS: I run Thonny (as a user) across 5+ different Linux environments and it certainly does work on Linux (including Ubuntu), although there are a few  minor gotchas, which are mostly Linux setup issues.]
