### ISSUE TITLE
Internal Error:  NameError: name 'logging' is not defined

### ISSUE THREAD

**Issue by Capt-Zeanie** [thonny/thonny#2548]
Thonny 4.0.1
Raspbian GNU/Linux 11 (bullseye)
Python 3.9.2 (32bit)
Tk 8.6.11
Device Raspberry Pi Zero 2

Using Threading code example

```
from time import sleep, perf_counter
from threading import Thread

def task():
    print('Starting a task...')
    sleep(1)
    print('done')

start_time = perf_counter()
# create two new threads
t1 = Thread(target=task)
t2 = Thread(target=task)
# start the threads
t1.start()
t2.start()
# wait for the threads to complete
t1.join()
t2.join()
end_time = perf_counter()
print(f'It took {end_time- start_time: 0.2f} second(s) to complete.')
```

Thonny produces an Internal Error Message Box with the following details.

> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
>     return self.func(*args)
>   File "/usr/lib/python3.9/tkinter/__init__.py", line 814, in callit
>     func(*args)
>   File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 2244, in poll
>     on_completion(proc, out_lines, err_lines)
>   File "/usr/lib/python3/dist-packages/thonny/plugins/mypy/__init__.py", line 110, in _parse_and_output_warnings
>     logging.error("Can't parse MyPy line: " + line.strip())
> NameError: name 'logging' is not defined

**Comment by aivarannamaa** [comment]
Thank you for the report!

This has been fixed in #2491 but not yet released. The work-around is to uncheck "Tools => Options => Assistant => Perform MyPy checks" for now.
