### ISSUE TITLE
Find / Replace search box, unexpected text and cannot edit while open

### ISSUE THREAD

**Issue by CosCal** [thonny/thonny#2550]
With the Linux version 4.0.1, I've noticed two more changes and issues related to the find & replace feature.

1) The ability to manually click, scroll, or edit code by hand, while using the find & replace box is open, is no longer unavailable.

2) When reopening the find/replace window with ctrl+F after a search, if any text is highlighted in the code (like for an upcoming copy/paste edit) it is appended to the last search query, mashing the searches together. This compounds the problem and makes it more difficult to re-open the find/replace window and repeat a search (which is necessary now due to the inability to edit manually code while the window is open).

I'm curious, what was the intended design idea? (the reason why find / replace was changed)

Would there be any issues if we consider restoring the original functions?

**Comment by aivarannamaa** [comment]
Thank you for the report!

Both cases look like a regression and should be fixed.
