### ISSUE TITLE
Thonny 4.0.1 'Manage packages' option greys out

### ISSUE THREAD

**Issue by Bold-engi** [thonny/thonny#2553]
Hi, I'm using thonny to programme my raspberry pi board to control a stepper motor. I want to do it by using RPi.GPIO but I can't open the 'Manage packages' to install the package. I tried using 'Manage plug-in' options but it just stuck on the installation process and never get to finish.

This below is the greys out 'Manage package' screenshot:
![屏幕截图 2022-11-23 130025](https://user-images.githubusercontent.com/60574298/203554049-7015a60e-48ed-482b-9396-daa060f0a706.png)

This below is the 'never-ending' installation screenshot:
![屏幕截图 2022-11-23 130614](https://user-images.githubusercontent.com/60574298/203554288-ea5a3c60-3869-4525-a8b6-92c7da39c73f.png)

Please don't mind the red text below, that's because I didn't connect any of my board to my laptop, it shouldn't be the reason why I can't get the package installed.

Many thanks

**Comment by aivarannamaa** [comment]
> Please don't mind the red text below, that's because I didn't connect any of my board to my laptop, it shouldn't be the reason why I can't get the package installed.

Well, this is exactly the reason you can't get the package installed, because the packages are supposed to end up on the board. Or do you want to install a Python 3 package? In this case you need to switch to Python 3 mode.

**Comment by Bold-engi** [comment]
Hi @aivarannamaa , thanks for poining out where my mistake is. It does because I didn't plug my board on. The problem solved after I make connection.
