### ISSUE TITLE
install via pip3 on Linux Mint uses coarse font

### ISSUE THREAD

**Issue by jbeale1** [thonny/thonny#2554]
Thonny 4.0.1 installed via "pip3 install thonny" on  Linux Mint:
"Linux john-fitlet2 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"
The program itself works OK, but the font is very coarse and not easy on the eyes (plain old-fashioned bitmap font, not anti-aliased). Is this unavoidable if I use pip3 to install, instead of the package manager on my OS?
![ThonnyWindow](https://user-images.githubusercontent.com/7452231/203595456-b2676064-179c-44a4-89db-a31c02914319.png)
![Thonny-About](https://user-images.githubusercontent.com/7452231/203596770-090f9a42-acc7-422f-b59e-3fbcb4f0e95c.png)

**Comment by aivarannamaa** [comment]
Thank you for the report and investigation!

I don't have Mint at hand and I'm hoping this problem only occurs in certain configuration. For this reason I'd prefer to leave this issue as is, until there arrive more reports about this problem.

You could try, whether you get better result with latest Python+Thonny bundle, which can be installed with following command:

```
bash <(wget -O - https://thonny.org/installer-for-linux)
```

**Comment by jbeale1** [comment]
Thank you for this suggestion. This bash command worked and now I have Thonny 4.0.1 installed and apparently working OK on my Linux Mint 20 system.  Toward the end of the install there were two messages indicating something went wrong, but apparently they were not fatal since everything I have tried in Thonny so far seems to work ok.
`Compiling Python files ............................................... Done!
kbuildsycoca5 running...
kf5.kservice.sycoca: Parse error in  "/home/john/.config/menus/applications-merged/xdg-desktop-menu-dummy.menu" , line  1 , col  1 :  "unexpected end of file"
kf5.kconfig.core: "KConfigIni: In file /usr/share/applications/screensavers/glitchpeg.desktop, line 7: " Invalid entry (missing '=')
Refreshing system menu ............................................... Done!`

**Comment by aivarannamaa** [comment]
I think you can ignore these messages. Glad you got Thonny working nicely!
