### ISSUE TITLE
step out,step into , step over

### ISSUE THREAD

**Issue by Nithin6524** [thonny/thonny#2556]
step over,step into,step out options are not working.

**Comment by aivarannamaa** [comment]
Are you using Thonny for MicroPython development? Debugging is only available for Python 3 back-end.

**Comment by Nithin6524** [comment]
then what should I do ? if I want those options work.

**Comment by aivarannamaa** [comment]
> then what should I do ? if I want those options work.

Currently your only option is to convince MicroPython developers to add some features, which enable building proper debugger and then implement or convince someone to implement MicroPython debugger for Thonny.
