### ISSUE TITLE
Outdated translations

### ISSUE THREAD

**Issue by MarieRoald** [thonny/thonny#2558]
I made some translations for Norwegian Bokmål and Norwegian Nynorsk earlier this year (#2157), but it seems like these are not included in the .po and .mo files. Is there anything I should do to update the po and mo files in the repo to include the translations in the next release?

**Comment by aivarannamaa** [comment]
Sorry, it looks like I've forgotton to include the po/mo files. I'll pay more attention before the next release.

But the translated help content seems to be available for "Norsk (Bokmål)" in Thonny 4.0.1

**Comment by aivarannamaa** [comment]
Fixed in 36ac8c63
