### ISSUE TITLE
print syntax with colored or colorama modules are not showing colours 

### ISSUE THREAD

**Issue by PhaniKumarDasika** [thonny/thonny#2567]
Hello Every One,
Environment : new to python, using python 3.7.4 in win 7 OS, below trials are not showing colour in python shell/terminal, 
  ** [ output:-] **
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
>>> 
 RESTART: C:\Users\admin\Desktop\23.py 
[48;5;131m[38;5;15mHello World !!![0m
[31mMy Text is Red

**[ Trial 1 ]**
from colored import fg, bg, attr
color = bg('indian_red_1a') + fg('white')
reset = attr('reset')
print(color + 'Hello World !!!' + reset)

**[ Trial 2 ]**
import os
from colorama import init,Fore
init()
print(Fore.RED + "My Text is Red")

please guide me. Thank you - phani

**Comment by aivarannamaa** [comment]
Which Thonny version are you using?

If you have the latest (4.0.1), then please make sure "Terminal emulation" is turned on at "Tools => Options => Shell"
