### ISSUE TITLE
No reponse to mouse clicks after opening a file

### ISSUE THREAD

**Issue by Rqml** [thonny/thonny#2569]
Sometimes you cannot edit an existing Python file when you open it. There is no response when you click the mouse. You need to restart the application or even the computer

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for the delayed response!

Could you be more specific? Does it happen just after the file gets opened in the editor or after you have edited it for a while?

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem and have more information to add.
