### ISSUE TITLE
Thonny freezes when print()

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#257]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/257) by Evgen (Bitbucket: [Evgenupd](https://bitbucket.org/Evgenupd)
 ).**

----------------------------------------

Hello, I am using Thonny 2.0.7, Darwin 15.5.0 (64-bit), Python 3.5.2(64-bit) and Tk 8.5.19 on 
MacBook Air (11-inch, Mid 2012) 1,7 GHz Intel Core i5

And when I run script: 

```
S='A\0B\nC'
print(S)
```

Thonny just freezes, it doesn't happen when I run code in terminal python (Python 2.7.10). 
Same thing happens in Debug mode, and only option is to restart application.
I have same thing with IDLE, so it might be not Thonny's fault, but I guess you should know. 

Unfortunately, I have no other systems to try this trick.

**Comment by chpurdy** [comment]
This seems to be resolved in 3.1.2.

**Comment by aivarannamaa** [comment]
Can't reproduce anymore
