### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED on multiple computers using Thonny and Micropython

### ISSUE THREAD

**Issue by EddieRadarHughes** [thonny/thonny#2571]
I have Thonny installed on 5 Windows 10 computers.   All are up-to-date with WIndows Updates.   I have various versions of Python up to 3.11 installed.    All are completely updated.    I have the latest versions of Thonny.   I tried reinstalling with the recommended version, with the portable versions and with the pip install thonny.  All give me the same error.   It doesn't matter if I install or run with Thonny as administrator or not. 

I have yet to be able to use any of the 8 Pico W computers I purchased.   I can code and save scripts on each of the Picos (saving as main.py), but I cannot import any modules.   I get the certificate error.   

I've searched GitHub for past posts on this same subject.   I don't understand how this topic is closed on those because there doesn't seem to be an answer given other than it's the os fault.   How is it that of the 64 to 577 programs I have installed on those Windows PC's, this program is the only one that gives me that error.  

I have also tried some of the other ideas.    I tried even the lets-encrypt-re.der program with no luck.

I did have have a Pico (without Pico W) to work for me back in 2021.   But that's been the only working Pico I've had.  That computer I used to program that Pico will not work with the Pico W I have now.   So I'm stuck with lots of boards an no working software.   I have put two full days into this.    I am going to boot up my Raspberry Pi 4B and try it from there next.
 
Any help on this issue would be greatly appreciated.  

UPDATE:   Worked the first time I tried it with Raspberry Pi OS.   Changed to expert UI and then followed the same procedure.   So that's my work around to trying to get it working from Windows installs.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please see if #1986 explains your case.
