### ISSUE TITLE
Indent Lines

### ISSUE THREAD

**Issue by jrs69** [thonny/thonny#2573]
Hi guys, a while ago I requested a "go to line" feature, duly implemented, thanks a bunch, makes life much easier.

A feature that other IDEs have is  "vertical indent lines", this would be very useful, I see it was requested back in 2020
- issue  #1078, any chance of bringing it back to life?

Cheers, jrs69

**Comment by aivarannamaa** [comment]
It is still in the TODO list, and if it gets implemented, you'll get notification under #1078.
