### ISSUE TITLE
Thonny 4.0.1 Windows 11 Micropytion No Debug

### ISSUE THREAD

**Issue by spencebs** [thonny/thonny#2574]
I am new to Thonny and using a Windows 11 PC. The buttons for debbugging are greyed out. Bottom right shows MicroPython (Raspberry PI Pico) COM3. I tried Save As and chose Raspberry PI Pico and This Computer. Neither work. The name of my program is main.py but I also tried test.py. 

I tried about the easiest program just to test funcationality. Below is my code:

from machine import Pin
from time import sleep

led = Pin(16, Pin.OUT)

while True:
    led.value(1)
    sleep(1)
    led.value(0)
    sleep(1)

**Comment by aivarannamaa** [comment]
Unfortunately debugging is not implemented for MicroPython.
