### ISSUE TITLE
Cannot see all of the micropython variants text - needs mouseover text

### ISSUE THREAD

**Issue by bsimmo** [thonny/thonny#2577]
Hello, I've just tried to use Thonny 4 .0.1 and select the micropython version for a PiPico.

When it comes to pick the version I need I cannot see all the text, see picture. 
Either the box needs to be bigger or the text needs to display in a mouseover/alt text popup showing the full text so I can see what is hidden.  
Should aid usability.  
Thankyou

![image](https://user-images.githubusercontent.com/11537335/208917442-21930443-5ebf-4ecf-aec7-5a09db63625d.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

I can suggest couple of work-arounds:

1) Resize the dialog
2) Make a selection and check the info url below the dropdown. If you did not select the right entry, try again.

I understand that there exist good solutions for this issue (your suggestion about mouseover text is a good idea), but there are lots of more pressing issues to solve first and I'm afraid this task will never reach the top of my work queue, so I'll close it right away,
