### ISSUE TITLE
Demand actions from your government.

### ISSUE THREAD

**Issue by doktorov** [thonny/thonny#2581]
_Demand actions from your government. If [thousands of Russians can speak up in spite of the big risk of being imprisoned](https://en.wikipedia.org/wiki/2022_anti-war_protests_in_Russia), you can do it as well._

Хохлы, почему я должен свергать своё правительство, если вы все ненавидите москалей? И вообще, почему вы решили, что я должен решать ваши проблемы?

**Comment by aivarannamaa** [comment]
It looks like you were not in the target group of the call you're referring to.

**Comment by doktorov** [comment]
> It looks like you were not in the target group of the call you're referring to.

Then mind your own business. This is a civil war between Russians.
