### ISSUE TITLE
Raspberry Pi Pico - First project problem

### ISSUE THREAD

**Issue by ThiNguyen3008** [thonny/thonny#2588]
Hello, I'm a beginner for Raspberry Pi Pico. I cannot run my first project and I don't know why. I'm using Thonny 4.0.1. Can you help me please? Thank you
This is from the book
![as](https://user-images.githubusercontent.com/114266186/210020405-06713d4c-2832-49bb-b5d1-a77ed699b72d.JPG)
This is a screenshot of my code
![ask](https://user-images.githubusercontent.com/114266186/210020474-8dadf3dc-7db0-4438-98db-909f8072f95b.JPG)

**Comment by samArtDev** [comment]
Did you set your interpreter in Thonny's options? "Local Python 3" is different than MicroPython.

![image](https://user-images.githubusercontent.com/114690398/210038386-e4baeedb-6129-4a26-b587-d671f3d4ebc4.png)

**Comment by aivarannamaa** [comment]
@ThiNguyen3008, you haven't paid attention to the indentation of the lines below `while`.

**Comment by samArtDev** [comment]
I completely didn't notice their mistake. Sorry. Just for clarification to new programmers, Python doesn't require semicolons ( ; ) the same way other programming languages do. The indents control the context for the code.

![image](https://user-images.githubusercontent.com/114690398/210043389-0b2fee92-28e3-4d0f-9419-07bec53c5923.png)
