### ISSUE TITLE
error when downloading packages 

### ISSUE THREAD

**Issue by goodbye2545** [thonny/thonny#2590]
Hello, I'm new and trying to do an oled display practice exercise for raspberry pi pico. i'm trying to download the SSD1306 package and after I search in Thonny and click on the package it diplays
 "Could not find the package info from PyPI. Error code: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>"
I'm in thonny version 4.0.2
I turned off my firewall and vpn if that matters 
Thanks

**Comment by aivarannamaa** [comment]
Please see #1986 and reopen this issue if you believe your case is different.
