### ISSUE TITLE
Why do I have to restart Thonny to get changes in a module?

### ISSUE THREAD

**Issue by armin-reichert** [thonny/thonny#2591]
If I edit a module and write some test code in the console below, I have to restart Thonny to get the changes. Just re-importing the module from the console seems not to work. Is this a bug or a feature?

**Comment by aivarannamaa** [comment]
> Just re-importing the module from the console seems not to work. Is this a bug or a feature?

That's how Python works. Re-importing during the same process will not make Python read the updated file from the disk.

Instead of restarting Thonny you could also press Stop/Restart button to restart the backend process.
