### ISSUE TITLE
Thonny crashses unexpectedly when command clicking import.

### ISSUE THREAD

**Issue by joyoforigami** [thonny/thonny#2594]
**Problem**  
Command click is supposed to get the definition of things, or throw "could not find definition" if it can’t find the definition.

If you command click import, it usually works correctly, throwing "couldn’t find definition". However, sometimes, python and thonny both crash without saving.

**How to reproduce**
1. Go to thonny
2. Type `import [insert some module here]`
3. Command click import
4. If it works correctly, command click the module name.
5. Look for the first import statement.
6. Go back to step three and repeat.

**My system**
I’m on a mac with Thonny 4.0.1, Darwin 26.6.0, and MacOS Monterrey.

**Edit** it seems that this does not apply to import only. It applies to everywhere on thonny, so to reproduce, randomly command click stuff until thonny crashes.
**Edit 2** the problem details and system configuration window that pops up can be found here: https://pastebin.com/45cg0jWN

**Comment by aivarannamaa** [comment]
Thank you for the report!

Unfortunately Python crashes like this are out of my scope. I'll bundle the next Thonny version with updated Python version. Let's hope this problem gets fixed by this.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Unfortunately Python crashes like this are out of my scope. I'll bundle the next Thonny version with updated Python version. Let's hope this problem gets fixed by this.
