### ISSUE TITLE
String formatting in print() messes up syntax highlighting

### ISSUE THREAD

**Issue by pitsi** [thonny/thonny#2599]
Hello and thank you for the great app. I started learning python ~2 months ago and thonny has helped me a lot as a beginner.

As mentioned in the title, when using the `f"` part inside print, thonny's syntax highlighting is messed, as seen here
![thonny](https://user-images.githubusercontent.com/5880037/211164703-17fdb726-76c7-48cd-a904-88d080112694.png)
Notice how everything inside the parentheses turns green as if it was just plain text, although it is not. The parts that are variables (katigoria, epityxies and kerdi above) should stay black because they are not text.

For comparison, this is how the same part of the code looks in sublime (I have no idea why "kerdi" is in green instead of cyan).
![sublime](https://user-images.githubusercontent.com/5880037/211164860-af509c3c-6a5a-4b52-8bf6-0501aad7b6da.png)

Is it something I am missing or I have configured it wrong?

**Comment by aivarannamaa** [comment]
Thank you for the report!

This kind of coloring isn't implemented in Thonny yet. I'll deal with this under #678.
