### ISSUE TITLE
Thonny feature request: enable drag-n-drop tab reordering in the IDE window

### ISSUE THREAD

**Issue by Zenmaster43** [thonny/thonny#2604]
I'm using Thonny 4.01 on my Raspberry Pi 4B via SSH and Thonny opens remotely in XQuartz on MacOS Ventura 13.1 on a 2022 MacBook Air.

When I try to drag a tab horizontally past another tab in the Thonny window, it doesn't move. It would be nice to be able to reorder the tabs by dragging the active (focussed) tab with the mouse and/or by using key combinations, such as command-<left arrow> and command-<right arrow> or option-<left arrow> and option-<right arrow>.

In MacOS Ventura 13.1, control-<left arrow> and control-<right arrow> are used to switch desktops, so these combinations are unavailable.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion! I'll deal with this topic under #2040.
