### ISSUE TITLE
tooltips - can I get rid of them

### ISSUE THREAD

**Issue by beetlegigg** [thonny/thonny#2607]
I use Thonny 4.01 on my mac and Thonny 3.3.14 on my raspberry pi.   On both of these Thonny versions a tool tip, such as the one for the 'run' button ( the tooltip 'run current script' pops up) and often these tooltips remain on the screen and are even visible over other windows such as the file manager.  The tooltip remains until I find the buried Thonny window and waft the mouse cursor over the buttons to make the tooltip disappear.  

This is rather annoying and it would be good if either they can be prevented from showing outside of the Thonny window or if there could be a way of turning them off completely.  

Thanks for your consideration of this issue.

**Comment by aivarannamaa** [comment]
Thank you for the report!

It's not currently possible to turn them off, but I'll see whether I can make the tooltips better.

**Comment by XexusUs** [comment]
Thanks for bring this up beetlegigg, I have the same issue running Thonny on Linux Mint/Cinnamon (using a resolution too big for my age only makes it worse).  Typically I'd see this issue on a webpage when I move the mouse too fast for the browser to note the focus change.

**Comment by KubaO** [comment]
A workaround to disabling the tooltips is to dynamically set them to None or "" for all controls.

**Comment by fiechr** [comment]
I have the same issue.

I'm running Manjaro Linux with KDE Plasma.

I know, it's only a small issue, but it's is really annoying. Maybe a framework problem. The tooltip even remains when I change virtual desktops. I wanted to make a screenshot but, of course, I didn't got stuck this time.

**Comment by aivarannamaa** [comment]
Should be now fixed in 4.1.2: https://github.com/thonny/thonny/releases/tag/v4.1.2

**Comment by mikedabb6** [comment]
Hi

I have the same issue with Thonny (tool tips remaining on the screen).

I am using Thonny version 4.0.1 on a Raspberry Pi 400. The system says it is the latest version installed.

Can you please tell me how to install version 4.1.2 on my Raspberry Pi 400.

Thanks in advance
Mike

**Comment by mikedabb6** [comment]
I seem to be having an issue with anything I write in Thonny, I get the following message:

PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_globals' (thonny.plugins.micropython.mp_back.ManagementError: Script produced errors).

**Comment by mikedabb6** [comment]
I also get this message:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 369, in execute_current
    self._wait_for_prompt(1)
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 438, in _wait_for_prompt
    raise TimeoutError("Backend did not respond in time")
TimeoutError: Backend did not respond in time

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 2027, in toolbar_handler
    handler(*args)
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 465, in cmd_run_current_script
    self.execute_current("Run")
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 375, in execute_current
    if self._proxy.stop_restart_kills_user_program():
AttributeError: 'NoneType' object has no attribute 'stop_restart_kills_user_program'
