### ISSUE TITLE
Wrong language name for Sl-Si

### ISSUE THREAD

**Issue by miharix** [thonny/thonny#2611]
Thonny 4.0.1
Windows 10 (64-bit)

In language selector is totally wrong display name for sl-si language.
"Slovène" is wrong
Correct is "Slovenščina" (don't lose the "š", because then is totally different country ! )
If naming must be in English, then correct would be "Slowenian"

I didn't fount wrong or right string in the poeditor.com .

Also on first run the correct language was not detected.
Is this related to wrong language display name ?

**Comment by aivarannamaa** [comment]
Thank you for the tip! 

I would have never thought two language names can be so similar...

The fix will be in the upcoming Thonny 4.0.2.

> Also on first run the correct language was not detected.

Thonny doesn't have automatic language selection, because some people always prefer English, and some translations are not good enough yet.
