### ISSUE TITLE
Tkinter pack labels

### ISSUE THREAD

**Issue by asad196030** [thonny/thonny#2615]
I am creating a booking system where one of the features is a retrieve function of all the bookings. The way this function works is by iterating though the bookings array and for each booking record it creates a label and packs it to the screen. The issue is that when there are too many bookings then the labels go below the screen. There is no cursor to view the labels at the bottom holding the booking information. I cannot seem to find a solution for this, can anyone guide me on it?

**Comment by aivarannamaa** [comment]
You'll get better answers to this question. from a Python forum, mailing list (https://mail.python.org/mailman/listinfo/tkinter-discuss) or Stackoverflow. This issue tracker is meant for discussing Thonny's problems.
