### ISSUE TITLE
Ensure Thonny's backends don't get confused by other installations

### ISSUE THREAD

**Issue by HeinzEgger** [thonny/thonny#2616]
This is a follow-up to closed issue: [#2610](https://github.com/thonny/thonny/issues/2610)
I followed the steps of issue [#2360](https://github.com/thonny/thonny/issues/2360) and had no success. Today I started my machine and removed Thonny, reinstalled it with your file thonny-4.0.1.bash and well, I can connect to the ESP8266. But there is always an error message:
_Traceback (most recent call last):
  File "/home/heinz/apps/thonny/lib/python3.10/site-packages/thonny/plugins/esp/esp_back.py", line 5, in <module>
    from thonny.plugins.micropython.bare_metal_backend import (
ModuleNotFoundError: No module named 'thonny.plugins.micropython.bare_metal_backend'

Process ended with exit code 1._
![Thonny-ModuleNotFoundError-2023-01-15 13-44-21](https://user-images.githubusercontent.com/122546107/212541385-bf3a2e31-e423-4642-823b-0540b74f9bb2.png)

I looked through all the mentioned paths in the error message, and did not find anything missing. See attached screenshot.
What is going wrong?

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please reproduce this issue and then, without doing anything else, select "Tools => Options => Open Thonny data folder" and post the backend.log you find in this folder.

**Comment by HeinzEgger** [comment]
I have done so. But the file backend.log does not show anything. There was an old file of the same name, dating back to the 12. December 2022 (attached). But I think this has no relevance. I created a new backend.log file but it stayed empty. The frontend.log contains some information (attached). Have I to change Thonny's settings? Mine are as shown in the screenshot (attached). Also the export of the protocol files does not show any results. The zip file is empty. 
![Thonny-Settings-HeinzEgger-Bildschirmfoto-2023-01-16 16-18-11](https://user-images.githubusercontent.com/122546107/212714945-809a749f-f87d-4175-a0f9-f1684fe94478.png)
[20221213-backend.log](https://github.com/thonny/thonny/files/10427234/20221213-backend.log)
[frontend.log](https://github.com/thonny/thonny/files/10427236/frontend.log)

**Comment by aivarannamaa** [comment]
I'm afraid you have both new and old Thonny versions in your system. 

Do you have `thonny` in `~/.local/lib/python3.10/site-packages` ? If yes, then please delete it from there and try again.

**Comment by HeinzEgger** [comment]
Many thanks! Yes, this was the problem. I removed the directory thonny in ~/.local/lib/python3.10/site-packages and the new Thonny-installation works perfektly! I am so happy! And it is a lot faster than under windows!

**Comment by aivarannamaa** [comment]
In the next Thonny version Thonny should not be confused by other installations anymore.

**Comment by aivarannamaa** [comment]
More conservative approach implemented in d2a96d04 because of #2851 and #2864.
