### ISSUE TITLE
Automatic syncing of clock is confusing

### ISSUE THREAD

**Issue by veebch** [thonny/thonny#2621]
This can lead to differing behaviour between code running via Thonny and code running automatically when connected to power.

I realise that this is for the purposed of timestamps on files etc, but because of it, it is easy to end up with code that works when run via thonny, and crashes when not initiated via thonny.

**Comment by aivarannamaa** [comment]
> I realise that this is for the purposed of timestamps on files etc

Yes, that's the main purpose

> because of it, it is easy to end up with code that works when run via thonny, and crashes when not initiated via thonny.

How so? I imagine, if a program depends on the correct time, then it shouldn't be a surprise when it acts erroneously when the time is not correct.

Did you know that you can turn off automatic syncing?

**Comment by veebch** [comment]
I know now :) 

My mental map assumed that Thonny would be a window into what happens when the code runs automatically on a pico. Turns out I was wrong....

Thanks!
