### ISSUE TITLE
Improve the object inspector view to update and stay in the selected tab

### ISSUE THREAD

**Issue by jrmoserbaltimore** [thonny/thonny#2622]
In the Variables view, I have globals, and I have `self` as `<__main__.DSVF object at 0xDEADBEEF>`, but I have no way to see what value is set to self._q, self._f, and so forth.

The object inspector is empty, and it took several days for me to figure out that if I go to Attributes and then double-click "self" it will actually open the variables in the object inspector.  The UI is clunky and non-obvious.  Perhaps populating it with a list of objects when no object is selected would help?

![image](https://user-images.githubusercontent.com/3127473/213884446-5345cec0-b640-4188-ab97-dbc7e6f6c3bf.png)

Also once the object is actually open, stepping through the program switches the tab to Stack.  Every time.  So it takes repeated tab switching to track what's happening anyway.  Then, it doesn't update, so you have to switch to something else in the inspector and switch back.  Stepping through one line takes 4 clicks in different parts of the screen.

**Comment by jrmoserbaltimore** [comment]
It seems the object inspector does in fact update if automatic stack view is disabled and you close the Stack tab.

**Comment by aivarannamaa** [comment]
Thanks for the notification!

I'll try to make the UX smoother.

**Comment by aivarannamaa** [comment]
In the upcoming Thonny 5.0 you can move the Stack pane above the Object Inspector, so they won't interfere with each-other.
