### ISSUE TITLE
Compiling translations for Thonny 4.0.2 fails for it_IT

### ISSUE THREAD

**Issue by befeleme** [thonny/thonny#2626]
There was a missing placeholder in the Italian translation: 
`error: thonny/locale/it_IT/LC_MESSAGES/thonny.po:1821: placeholders are incompatible`

I've added it in POEditor, all there's to do is update the translated strings in the repository.

**Comment by aivarannamaa** [comment]
Thanks! Will do it for 4.0.3

**Comment by tures43** [comment]
How to add CopyLineDown  in Ctrl+D?
