### ISSUE TITLE
Thonny seems redirect stdout to something different? 

### ISSUE THREAD

**Issue by codemee** [thonny/thonny#2629]
In Thonnys' shell, the sys.stdout.write() doesnt return the bytes count as shown bellow

```python
>>> import sys
>>> a = sys.stdout.write("hello")
hello
>>> a
>>> print(a)
None
>>> 
```
How is this happen?

Thanls.

**Comment by codemee** [comment]
I got it, it's  FakeOutputStream
https://github.com/thonny/thonny/blob/c4b5eb112e78bb53f745cb6eebf66add6464a2ac/thonny/plugins/cpython_backend/cp_back.py#L1020

**Comment by aivarannamaa** [comment]
Thank you for the report!

I'm surprised that this problem hasn't been reported until now. Luckily it was easy to fix. In Thonny 4.0.3 `sys.stdout.write` will return the number of written characters (not bytes).

**Comment by codemee** [comment]
Thanks.
