### ISSUE TITLE
B.C.N

### ISSUE THREAD

**Issue by Kavex71** [thonny/thonny#2631]
no entiendo casi nada de esto, yo solo quiero instalar aplicaciones y extenciones para abrir archivos.
[Visual-Studio-Marketplace-Publisher-Agreement.pdf](https://github.com/thonny/thonny/files/10528441/Visual-Studio-Marketplace-Publisher-Agreement.pdf)
[vscode-main (1).zip](https://github.com/thonny/thonny/files/10528443/vscode-main.1.zip)
[Anaconda-Starter-Guide.pdf](https://github.com/thonny/thonny/files/10528444/Anaconda-Starter-Guide.pdf)
[Installation — pandas 1.5.3 documentation.pdf](https://github.com/thonny/thonny/files/10528446/Installation.pandas.1.5.3.documentation.pdf)
[qrcode_code.visualstudio.com.zip](https://github.com/thonny/thonny/files/10528447/qrcode_code.visualstudio.com.zip)

**Comment by aivarannamaa** [comment]
This issue tracker is for a Python IDE. I guess you need ask somewhere else.
