### ISSUE TITLE
Back-end problem

### ISSUE THREAD

**Issue by elviine** [thonny/thonny#2632]
MacOS user here.

I decided to upgrade from Thonny 3.1.0 to Thonny 4.0.2 . I accidentally pressed decline when the program asked for my permission to access files and documents, and now it won't work at all and I don't know how to solve it.

PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_environment_info' (PermissionError: [Errno 1] Operation not permitted).
See Thonny's backend.log for more info.

Process ended with exit code 1.

How can I fix this?

**Comment by Honpyt** [comment]
Same problem on MacOS 13.1 even when the installation process was completed as intended.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please try adding "Full disk access" permission to Thonny:

* Go to System preferences => Security & privacy => Privacy
* Click on the padlock to allow changes
* Select "Full disk access"
* Click the "+" button and select Thonny (most likely under Applications).

**Comment by aivarannamaa** [comment]
@elviine and @Honpyt, did my suggestion solve your issue?

**Comment by elviine** [comment]
Yes it did! Thank you a lot.
