### ISSUE TITLE
esp32s3 save in microcontroller device problem

### ISSUE THREAD

**Issue by TGOA** [thonny/thonny#2643]
I am facing this annoying problem, when I open thonny IDE while my microcontroller is connected it gives me this error 

E (31) qio_mode: Failed to set QIE bit, not enabling QIO mode
Traceback (most recent call last):
  File "_boot.py", line 11, in <module>
  File "inisetup.py", line 34, in setup
  File "inisetup.py", line 7, in check_bootsec

 and every time I try to save the file on my microcontroller device it gives me this error:
 
PROBLEM IN THONNY'S BACK-END: Exception while handling 'write_file' (OSError: Could not open file /main.py for writing, output:
Traceback (most recent call last):

  File "<stdin>", line 4, in <module>

OSError: [Errno 19] ENODEV).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.

Process ended with exit code 1.

**Comment by aivarannamaa** [comment]
It doesn't look like Thonny-specific problem. I recommend asking for advice at MicroPython Discussions.
