### ISSUE TITLE
Plugin for Classroom Use 

### ISSUE THREAD

**Issue by graham-mitchell-vcs** [thonny/thonny#2658]
@aivarannamaa would you be interested in paid development of a plugin to enhance collaborative use in classrooms?

We have a decent budget (five figures) and would like the plugin to be publicly available for free afterwards. We can share wireframes and workflow via a Zoom call.

Just a reminder, we are the team @ Core Electronics.

**Comment by aivarannamaa** [comment]
Thanks for the proposal!

I'm not sure I can find time for this development, but I'd be interested to hear more. Lets arrange the call via e-mail. My e-mail address is aivar.annamaa@gmail.com

**Comment by graham-mitchell-vcs** [comment]
Thanks Aivar, I've sent you an email and will mark this issue as solved so it doesn't distract others :)

**Comment by aivarannamaa** [comment]
@graham-mitchell-vcs, I still haven't received your e-mail, neither in my inbox nor in the spam folder.

**Comment by graham-mitchell-vcs** [comment]
Interesting! Please send an email direct to support@coreelectronics.com.au if you can't see this one that was sent earlier today:

![image](https://user-images.githubusercontent.com/8654209/219074616-a9be3b65-1456-4221-8333-5a727f7e5b97.png)
