### ISSUE TITLE
utemplate plugin installer error

### ISSUE THREAD

**Issue by abreyu** [thonny/thonny#2663]
when I try to install utemplate plugin I get this error

`C:\Users\user\AppData\Local\Programs\Thonny\python.exe -m pip --disable-pip-version-check --no-color install --no-warn-script-location --user --user utemplate
Collecting utemplate
  Using cached utemplate-1.4.1.tar.gz (4.5 kB)
ERROR: utemplate from https://files.pythonhosted.org/packages/ba/93/5eca962e6d576b8f50bb11bc9506becc11ce4587a56b707095c3073bda06/utemplate-1.4.1.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Error: process returned with code 1
`

**Comment by aivarannamaa** [comment]
Are you sure you want to use as Plug-in or Package? Please see the text on top of the "Tools => Install plug-ins" dialog to learn the difference.

**Comment by abreyu** [comment]
ok thank you
