### ISSUE TITLE
REPL reporting issue in shell version 4.0.2

### ISSUE THREAD

**Issue by lreagan** [thonny/thonny#2668]
If "View" "Heap" option is checked,  simple REPL entries report object address instead of value
For example:
>>> 2 + 1
0x7

instead of  correct result:
>>> 2 + 1
3

**Comment by aivarannamaa** [comment]
That's the purpose of the heap view.

**Comment by lreagan** [comment]
Thank you Aivar.
I am using Thonny with ESP32.  I thought I had a Micropython issue.  I ran my board with a Putty terminal and noticed that the Thonny shell was reporting different than the Putty shell and traced it to the "Heap" option.  I still think this is confusing, but your comment agrees with documentation so I will close this. --L. Reagan
