### ISSUE TITLE
Started Creating and Maintaining Snap Package..

### ISSUE THREAD

**Issue by CapeCrusader321** [thonny/thonny#2675]
Hey there Community and People, i have started building and maintaining Thonny Snap at https://snapcraft.io/thonny-ide, please checkout and help me by reporting any issues at https://github.com/CapeCrusader321/Thonny-snap/issues.
<a href="https://snapcraft.io/thonny-ide">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

**Comment by CapeCrusader321** [comment]
Can i assume that at point in  future it will be declared an Official Package ?? @aivarannamaa

**Comment by CapeCrusader321** [comment]
You can check all the YAML etc., i can also help you to maintain and build it if needed..

**Comment by CapeCrusader321** [comment]
https://github.com/thonny/thonny/issues/2418[](url)

**Comment by CapeCrusader321** [comment]
#https://github.com/thonny/thonny/issues/2418

**Comment by CapeCrusader321** [comment]
Hello @aivarannamaa  not heard from  along time, are you busy ?? Please consider the request whenever possible, Thanks..

**Comment by aivarannamaa** [comment]
Thanks and sorry for the late reply! I have been really busy indeed.

> Please consider the request whenever possible

Do you mean mentioning this installation option at Thonny's homepage or something else?

I now added `sudo snap install thonny-ide` under Linux downloads at https://thonny.org/.

**Comment by CapeCrusader321** [comment]
> Thanks and sorry for the late reply! I have been really busy indeed.
> 
> > Please consider the request whenever possible
> 
> Do you mean mentioning this installation option at Thonny's homepage or something else?
> 
> I now added `sudo snap install thonny-ide` under Linux downloads at https://thonny.org/.

Thanks for taking out your time,yes, mentioning it at home page will raise more awareness about the snap package, it already has 122+ downloads in 7 days...

**Comment by aivarannamaa** [comment]
> I also have a doubt whether thonny uses dbus or not ??

Not at the moment, but please see https://github.com/thonny/thonny/pull/2683
