### ISSUE TITLE
OpenCV via Manage plug-ins option not accessable

### ISSUE THREAD

**Issue by Petros626** [thonny/thonny#2678]
Hey there,

I've seen that several people had the problem to install OpenCV and use it in the _Thonny_ IDE. So I just installed it by searching `opencv-python` atfer that I restarted the IDE, but 
```python
import cv2
```
doesn't help, I get still `ModuleNotFoundError: No module named 'cv2'`. What could be the reason for it? In the terminal the module is also not recognized by `python3`.

Thanks in advance

**Comment by aivarannamaa** [comment]
Did you use "Tools => Manage packages" or "Tools => Manage plug-ins" ?

**Comment by Petros626** [comment]
I wrongly used `Manage plug-ins` and not the right one M`anage packages` . By the way whats the difference? Plug-ins is for the installed dependencies of a package?

**Comment by Petros626** [comment]
So now I tried just to `import cv2 ` and the library (`picamera2`)  I'm using fails. Outcommented it's no problem, but I need OpenCV. The error message says the following:

![image](https://user-images.githubusercontent.com/62354721/221937310-226543e4-5625-4fc1-9d37-05420a22bb79.png)

**Comment by Petros626** [comment]
I solved it with `sudo pip install -y python3-opencv opencv-data`. In case you install OpenCV from source, use this helpful discussion (https://github.com/Qengineering/Install-OpenCV-Raspberry-Pi-64-bits/issues/3)
