### ISSUE TITLE
Console prompt up while turtle program is still running

### ISSUE THREAD

**Issue by nicolasdespres** [thonny/thonny#2688]
Hi,

I have noticed that when running an interactive program like the following using turtle the console prompt appear whereas the program is still running.

```python
from turtle import onkeypress, listen

def when_Up_pressed():
    print('Up arrow pressed')

onkeypress(when_Up_pressed, 'Up')
listen()
```

It leads to output like this, which is a bit confusing for beginners.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/614631/223451489-88e176d0-1328-4497-bed2-dfc0a592153c.png">

I don't know if there is an easy fix for this, since, I guess, it depends on the degree of integration of the turtle canvas.

Best regards,

**Comment by aivarannamaa** [comment]
I'm considering this as a feature, as you can continue commanding the turtle in the REPL after the script ends. If you don't need this kind of interactivity, then you can add `turtle.mainloop()` to the end of your script.

**Comment by nicolasdespres** [comment]
Ok fair enough. Thx for your quick reply.
