### ISSUE TITLE
Script containing PySide2 does not work when loaded from a file, but works if run from <untitled> page

### ISSUE THREAD

**Issue by AshDini** [thonny/thonny#2700]
![2023-03-12 14 04 40](https://user-images.githubusercontent.com/66854499/224521974-b6b0d0af-e18a-49d5-a36c-e49940850b4e.jpg)
![2023-03-12 14 05 51](https://user-images.githubusercontent.com/66854499/224521993-e483b7d1-e916-43a9-86f3-04524506052e.jpg)

**Comment by aivarannamaa** [comment]
Please add following two lines in both programs and see if they print different value:

```python
import os
print(os.getcwd())
```

**Comment by AshDini** [comment]
Hi Aivar,

Thank you for your prompt reply.

Something funny is going on here.

After receiving your email, I loaded the script from the file and tried it
out before inserting your suggestion. *And it worked perfectly !*

Since yesterday (when the problem occurred) I have not even loaded Thonny.
It seems that something happened yesterday with my several use of Thonny
that affected it.

However including your suggestion, it just printed the locality of the
file: "C:\ESP-Scripts\Keyboard" and continued working

Very strange !

Regards

Bob Stanton
