### ISSUE TITLE
Newbee question: can't get it run/no issue

### ISSUE THREAD

**Issue by ITServ-DE** [thonny/thonny#2723]
Hi all!
I hope that somebody here can help me with an issue I have with my ESP32-CAM-Devboard (ESP32-S, CH340 Serial-to-USB), 'cause I can't figure out where to start. First to say, camera function is currently out of scope. I simply get nothing to work. But I'm also a newbee to MicroPython and Thonny.

I cannot get Thonny (Windows) to open a shell to the board. I successfully flash micropython using https://bipes.net.br/flash/esp-web-tools/, and the web installer also can connect to the console of the ESP32. I can also later come back and open a console only. However - a software reset of the board is required, a hardware reset works too.

With Thonny, I _seem_ to be able to flash firmware (erasing flash, writing at 0xXXXXX), but I never get a console back and only the error message `Device is busy or does not respond. Your options: [...]` appears. Neither pushing the reset button on the board, nor pressing the Stop/Restart button in Thonny connects. Also, having the firmware installed with the web installer, Thonny cannot connect.

Can somebody please be so kind and help me out or point me in the right direction? What might be wrong with my setup so I cannot get Thonny to give me a command shell from the ESP32?

I might also mention, I also cannot connect to the board using Putty at 115200bd. Same issue.

Thank you very much!

**Comment by ITServ-DE** [comment]
I'd like to add, when I connect to the board via the https://bipes.net.br/flash/esp-web-tools/, I _always_ have to do a "reset device" sequence first to get the console running. This seems to send some magic bytes to the Dev board, I think ...

**Comment by ITServ-DE** [comment]
... and it looks as if the RESET via serial is done by lowering the DTR signal.

**Comment by aivarannamaa** [comment]
If you are able to get the REPL on this device via other means, then please see https://github.com/thonny/thonny/wiki/MicroPython#advanced-configuration and try adding `dtr = True` into `[ESP32]` section. Also search Thonny issues for DTR
