### ISSUE TITLE
Thonny crashes when changing interpreter (macOS 13.3)

### ISSUE THREAD

**Issue by lferette** [thonny/thonny#2724]
Bug: Thonny crashes when selecting another python interpreter - when clicking any other interpreter in the drop down
Expected behaviour: no crash, current interpreter changed
Environment: macOS 13.3, intel
Crash report attached
[thonny.crash.txt](https://github.com/thonny/thonny/files/11110245/thonny.crash.txt)

**Comment by lferette** [comment]
Forgot to add: Thonny version 4.0.2

**Comment by rememberlenny** [comment]
I experienced this too

**Comment by lferette** [comment]
The root cause is that the crash happens when MicroPython is not installed on the target device, or when the target device is not connected. Ideally, Thonny should report the error condition instead of crashing.

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for late reply.

Such crashes are out of my control, but I'll release the first beta of Thonny 4.1.0 soon, which comes with update Python and Tk. Let's hope this fixes the crashes.

**Comment by aivarannamaa** [comment]
The first beta of 4.1.0 is now available: https://github.com/thonny/thonny/releases/tag/v4.1.0b1

Please see, whether this fixes the problem.

**Comment by anselanza** [comment]
>The root cause is that the crash happens when MicroPython is not installed on the target device, or when the target device is not connected. 

So how does one fix this? Or even determine which of the above is the culprit in my particular case? I'm new MicroPython, and I thought Thonny was meant to be the _easiest_ way to get started.

> Ideally, Thonny should report the error condition instead of crashing.

Definitely!

**Comment by aivarannamaa** [comment]
Try https://github.com/thonny/thonny/releases/tag/v4.1.0
