### ISSUE TITLE
macOS: the keyboard shortcut to ZOOM IN text (Option Command +) doesn't work

### ISSUE THREAD

**Issue by andreaval** [thonny/thonny#2725]
Bug: when you press the key combination (Option Command +) to zoom in, the text size remains unchanged. You have to act through the menu. Instead, the key combination (Command -) to decrease the zoom works.
Computer: Macbook Air M2 macOS 13.3
Thonny: 4.0.2

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for late reply!

I don't remember why I didn't use Command + for the shortcut as most apps. I suppose it didn't work with older Tk version and now the Option Command + doesn't work.

In the next Thonny version the shortcut for increasing font size will be Command +.
