### ISSUE TITLE
Thonny import msvcrt error trying to get one char at a time without enter

### ISSUE THREAD

**Issue by johngthomas** [thonny/thonny#2736]
I'm a Python raw beginner trying to get a get set number of characters typed on the keyboard recorded and displayed on screen without using the enter key. I'm on a Windows 10 desktop. Here are some of the routines I've tried in Thonny.  Am I doing something wrong here? Any suggestions?

First Attempt
import msvcrt
input_str = ""
while len(input_str) < 6:
    if msvcrt.kbhit():  # checks if a key has been pressed
        char = msvcrt.getch().decode('utf-8')  # gets the character and decodes it from bytes to string
        input_str += char
        print(char, end='')  # prints the character on the same line

Error Message:
KeyboardInterrupt: Execution interrupted
cp_back.py, line 133
No specific suggestions for this error (yet).
![ThonnyPythonAttempt1](https://user-images.githubusercontent.com/4264692/230877904-1c320364-2d3d-4021-a002-ca914d1cc265.png)

Second Attempt
import msvcrt
# Prompt the user to enter six characters
print("Please enter six characters:")
# Read input from the keyboard
input_chars = []
while len(input_chars) < 6:
    if msvcrt.kbhit():
        input_chars.append(msvcrt.getch().decode('utf-8'))
# Concatenate the input characters and display on one line
input_string = ''.join(input_chars)
print("You entered:", input_string)

Error Message
KeyboardInterrupt: Execution interrupted
cp_back.py, line 133
No specific suggestions for this error (yet).
![ThonnyPythonAttempt2](https://user-images.githubusercontent.com/4264692/230878006-5c795453-4c16-4e8a-a029-ed324ba2ea0a.png)

Third Attmpt 
import msvcrt
digits = [] #trying digits this time
while len(digits) < 6:
    digit = msvcrt.getch()
    if digit.isdigit():
        digits.append(digit)
        print(digit.decode(), end='')

Error Message
KeyboardInterrupt: Execution interrupted
cp_back.py, line 133
No specific suggestions for this error (yet).
![ThonnyPythonAttempt3](https://user-images.githubusercontent.com/4264692/230878062-41ffc8f3-f51c-497d-9913-647b417a2bac.png)

**Comment by aivarannamaa** [comment]
You can't do this in Thonny's Shell, as it is not a proper terminal emulator. For this kind of program you need to use "Run => Run current script in Terminal".

**Comment by johngthomas** [comment]
> You can't do this in Thonny's Shell, as it is not a proper terminal emulator. For this kind of program you need to use "Run => Run current script in Terminal".

Thanks. What IDE would be 'a proper terminal emulator' suitable for a beginner like me?

**Comment by johngthomas** [comment]
Thankyou
