### ISSUE TITLE
Can't change installation path

### ISSUE THREAD

**Issue by SilentHealer584** [thonny/thonny#2738]
I don't know if it's a big issue but i can't change my installation path for Thonny. I've already installed it once on my computer. When i try to install it again, i'm prompted with a widnow at a certain point there it says: Destination location, and then a path to where i once installed Thonny. So it's basically trying to install Thonny into the same path it already is in, and i can't change the install location. Can anyone help ?

**Comment by aivarannamaa** [comment]
I assume you're using Windows. The installer for Windows allows selecting new path after you've uninstalled the previous installation.
