### ISSUE TITLE
The shell only outputs %Run -c $EDITOR_CONTENT

### ISSUE THREAD

**Issue by ohomatt** [thonny/thonny#2741]
![WX20230413-123120@2x](https://user-images.githubusercontent.com/130422408/231654761-641ef7cb-3ea8-45ca-8937-d0242bf3b09d.png)
I used the sample code of micropython, as follows:
import network
wlan = network.WLAN(network.STA_IF)
wlan. active(True)
wlan. scan()
But I only get %Run -c $EDITOR_CONTENT
But if I use: print(wlan.scan()) I get the correct output,
I tried a lot of mcu or changed the version of micropython, and it was the same. I also tried to use the Windows computer version of Thonny, and it was the same. I am not sure if it is the reason of Thonny, please forgive me if it is my reason.

**Comment by ohomatt** [comment]
It should output all the wifi signals it can currently search for，like this：

**Comment by ohomatt** [comment]
It should output all the wifi signals it can currently search for，like this：
<img width="793" alt="截屏2023-04-15 17 14 09" src="https://user-images.githubusercontent.com/130422408/232203409-f81ba7ef-f1a7-46bb-bc39-6c2f50dd30cd.png">
This is what I print via print().

**Comment by ohomatt** [comment]
Micropython is used here, and the esp8266 is controlled through the serial port to run the code

**Comment by aivarannamaa** [comment]
I still don't understand what is the problem.
