### ISSUE TITLE
Thonny IDE cant detect the board

### ISSUE THREAD

**Issue by wael-ejkhidem** [thonny/thonny#2747]
hello, 
im using esp32 with cp2102, before 3 days i was able to work with the board but today i cant, i tried the board on other laptops and it works. but in my laptop it dosent. (the port is working i use it for the mouse). 
it shows the following msg :"
Couldn't find the device automatically. 
Check the connection (making sure the device is not in bootloader mode) or choose
"Configure interpreter" in the interpreter menu (bottom-right corner of the window)
to select specific port or another interpreter.

Process ended with exit code None"
thank you.

**Comment by aivarannamaa** [comment]
Did you try selecting specific port?

Which OS are you using?

**Comment by wael-ejkhidem** [comment]
On my laptop I just have only one port, Windows 11.

**Comment by aivarannamaa** [comment]
Does this one port correspond to your ESP? What happens when you select this port?

**Comment by wael-ejkhidem** [comment]
I've tried to connect arduino uno on the port and its working normally.
but when i connect ESP32 the option ports doesn't appear on device manager list.

**Comment by aivarannamaa** [comment]
> but when i connect ESP32 the option ports doesn't appear on device manager list.

I think in this case the problem lies outside of Thonny.

**Comment by wael-ejkhidem** [comment]
ok thank you, i solved the problem. but i have a problem with thonny this time. 
whenever i create a class i cant import it.
