### ISSUE TITLE
Formatting and Indentation Error in Thonny (works in IDLE)

### ISSUE THREAD

**Issue by Welding-Torch** [thonny/thonny#2751]
Hi Thonny Devs!

So I was writing a program that does some basic text alignment  when I realised that Thonny acts kind of weird when printing out aligned text. In the below example, I have tried to output text that is **right-aligned** in Thonny, only to find that it prints the output incorrectly. At first, I thought my code was wrong. But then I tried running it in a different interpreter(Python IDLE) on the command line and found that the output there was perfect. So I've opened this issue to bring this error in basic functionality to your attention.

I have attached the code that can be used to recreate this problem and images that showcase this problem below.

**Code:**
```python
names = ['Mark', 'Kevin', 'Paul','Leo','Knuth']
marks = [56,43,46,24,66]
for j in range(0,len(names)):
    print(f"{names[j]:>12}{marks[j]:>12}")
```

**Here's what the output is:**

![image](https://user-images.githubusercontent.com/46340124/232797624-eb7dc7e2-00fc-47e9-9ad5-1eb5b0e1fcc8.png)

Notice the improperly aligned names and numbers in this image.

**Here's what the output *should be:***

![image](https://user-images.githubusercontent.com/46340124/232797847-9e48c7f9-40ed-4292-83a8-54edfcd3874c.png)

Hope this issue can be solved soon!
_Thank you for Thonny, my favourite Python IDE._

**Comment by 44yu5h** [comment]
Hi, What is your version of Thonny?

![Screenshot from 2023-04-19 04-09-32](https://user-images.githubusercontent.com/130254793/232920493-edc5aaf2-ec12-4a94-81b7-533379207ed5.png)

(btw don't hate me for using light theme)

**Comment by Welding-Torch** [comment]
Oh, understood. Thank you for letting me know 👍
