### ISSUE TITLE
Missing Interpreter tab in 4.1.0b1 Mac build

### ISSUE THREAD

**Issue by rtideas** [thonny/thonny#2763]
Trying to use my ESP32-S2 with the latest beta 4.1.0b1 and using the lower right menu (or Preferences) and the Interpreter tab has disappeared. 

Accessing the menu in 4.1.0b1:
<img width="1280" alt="Screen Shot 2023-04-26 at 9 47 40 AM" src="https://user-images.githubusercontent.com/4334269/234603700-bb1cb12a-f53b-4693-a57b-823adf61dbd1.png">

Where's the Interpreter tab?
<img width="752" alt="Screen Shot 2023-04-26 at 9 48 17 AM" src="https://user-images.githubusercontent.com/4334269/234604725-435bc3e3-098d-4d12-a017-2d6c1e6b0baf.png">

Installed back and forth a few times between 4.1.0b1 and 4.0.2 with same issue. **Had to revert to 4.0.2 to still use my ESPs.**
<img width="1021" alt="Screen Shot 2023-04-26 at 9 51 45 AM" src="https://user-images.githubusercontent.com/4334269/234605815-f456753b-bd65-477d-ae8c-ab6fd4b0521a.png">

**Comment by aivarannamaa** [comment]
Thank you for the report!

Actually I've already noticed and fixed it (115ab502) but haven't been able to make a new release yet. I'll do it soon.

**Comment by wohltat** [comment]
I can replicate the bug on linux also. It is solved in the current git version.

**Comment by aivarannamaa** [comment]
Fix released now: https://github.com/thonny/thonny/releases/tag/v4.1.0
