### ISSUE TITLE
Verify Thonny Flatpak on Flathub

### ISSUE THREAD

**Issue by jwillikers** [thonny/thonny#2774]
There's a new Flathub website where it is possible mark apps as verified. This is described in the new [About](https://flathub.org/about) page. @aivarannamaa, if you login to the Flathub website with your GitHub account, it should automatically associate the Thonny Flatpak with your account. You can then follow the instructions in the [Developer Settings](https://flathub.org/apps/manage/org.thonny.Thonny) page for Thonny to perform Website verification.

**Comment by aivarannamaa** [comment]
Thanks for proposing this!

It's now done.
