### ISSUE TITLE
Mac Simple Mode Shortcut  Cmd-W closes App, not current Tab

### ISSUE THREAD

**Issue by martin-guddat** [thonny/thonny#2781]
Expected: Using the shortcut Cmd-W the current Tab is close.

Is: When the UI is set to simple, the whole Thonny App is closed.

Steps to reproduce: Open Thonny with UI mode simple. Press Cmd-W. App is closed immediately. Even when you open an additional tab before. This is different (and as expected) in UI mode regular.

Additional: When the UI is set to regular, it works as expected. This issue might have as similar reason as #2729 having issues with localisation 

Thonny 4.0.2, Mac Ventura 13.3.1. (a)

**Comment by aivarannamaa** [comment]
Thank you for the report!

> This issue might have as similar reason as #2729 having issues with localisation

You're right -- this issue was fixed together with #2729. I'll publish the next beta of 4.1.0 ... soon :)
