### ISSUE TITLE
esp32 webrepl not working 

### ISSUE THREAD

**Issue by Shafikulachalil** [thonny/thonny#2785]
Can't import `websockets`. You can install it via 'Tools => Manage plug-ins'.

Process ended with exit code 1.

**Comment by aivarannamaa** [comment]
Did you try installing websockets?

**Comment by Shafikulachalil** [comment]
its worked after re flashing micropython

**Comment by akomakom** [comment]
For anyone finding this with the same problem, this thread may be helpful:
https://forums.raspberrypi.com/viewtopic.php?t=348865

In Ubuntu, I was able to resolve this by uninstalling the websockets plugin from thonny, then installing it via pip3 as root:
`sudo pip3 install websockets`.

There is most likely a bug in thonny:
1. Tools -> Open System Shell
2. Run
 ```
import sys
print(sys.path)
```

Note that path of websockets plugin (shown in Plug-In Manager) isn't in this list.
