### ISSUE TITLE
Will not respond

### ISSUE THREAD

**Issue by GitKia1392** [thonny/thonny#2799]
When I write a program related to pygame(A python library), It doesn't respond; Don't think I have a bad pc, Because my pc has:
15.6" Full HD display
HD Webcam and Dual microphone
USB Type-C
64 bit intel core

**Comment by aivarannamaa** [comment]
This forum is for issues with Thonny IDE. Do you think your program is OK but it doesn't work because of Thonny?

**Comment by GitKia1392** [comment]
No, no issues, the problem was that I tried to use pygame(the library) and
Thonny cannot handle modules like this in python so yeah.

Kind regards
Kiamehr
