### ISSUE TITLE
Update Snap Listing

### ISSUE THREAD

**Issue by CapeCrusader321** [thonny/thonny#2800]
@aivarannamaa  Sorry for this, but when free please take out time to update the snap listing, i have changed the thonny package name to thonny from thonny-ide, (sudo snap install thonny). Thanks

<a href="https://snapcraft.io/thonny">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

**Comment by aivarannamaa** [comment]
Thanks, and sorry for late reply!

Done now.
