### ISSUE TITLE
Wiki: update links

### ISSUE THREAD

**Issue by rootsmusic** [thonny/thonny#2819]
The wiki's following pages should update links to the latest version.
- [x] [_Assistant_](https://github.com/thonny/thonny/wiki/Assistant) should update  [warning messages](https://pylint.pycqa.org/en/latest/user_guide/messages/messages_overview.html).
- [x] [_Friendly Traceback_](https://github.com/thonny/thonny/wiki/Friendly-traceback) should update https://friendly-traceback.github.io/docs/

**Comment by aivarannamaa** [comment]
Thanks for the suggestion! Fixed now. I kept the original link for Pylint messages, because it is not easy to search by message from the page you suggested.
