### ISSUE TITLE
version conflict with python 3.11

### ISSUE THREAD

**Issue by bcm23** [thonny/thonny#2820]
After upgrading from pytho 3.8 to 3.11 existing Thonny installation did not start;
New Thonny 4.1.1 does also not start with giving following reason:
 
pkg_resources.VersionConflict: (thonny 4.1.1 (/home/pi/.local/lib/python3.11/site-packages), Requirement.parse('thonny==3.3.10'))

**Comment by aivarannamaa** [comment]
Did you try removing and reinstalling Thonny? How did you install Thonny? With `apt` or `pip`?

**Comment by bcm23** [comment]
I tried removing, installing with apt , removing installing with pip3: I observed no differences in the final result

**Comment by aivarannamaa** [comment]
If you're still getting error with `Requirement.parse('thonny==3.3.10'))`, then it means there are leftovers from old thonny somewhere. Perhaps it's the executable script `/usr/bin/thonny` ?

Try launching Thonny with `python3 -m thonny`.

**Comment by bcm23** [comment]
you are right, the de-installation of the older thonny version went wrong.
