### ISSUE TITLE
update thonnyapp

### ISSUE THREAD

**Issue by rootsmusic** [thonny/thonny#2824]
Please update [thonnyapp](https://pypi.org/project/thonnyapp/).

**Comment by aivarannamaa** [comment]
Do you mean you wan't `pip install thonnyapp` to install latest `thonny` package? It should, if you don't have it installed yet. If you already have `thonny` package, then you need to do `pip install -U thonnyapp` (or `pip install -U thonny`).

**Comment by rootsmusic** [comment]
@aivarannamaa  `pip install thonnyapp` installed thonny into an environment with Python 3.7.7.  Then I tried `pip install --upgrade thonny`, but it says: thonny in c:\program files\python37\thonny\lib\site-packages (3.3.14).  Should thonny update to a newer version?  Thanks.

**Comment by aivarannamaa** [comment]
Thonny runs with the Python that you are using for installing it. The `thonny` package does not contain a Python interpreter.

**Comment by rootsmusic** [comment]
Yes @aivarannamaa, my environment was created by Python 3.7.7.  Since Pypi has [version 4.1.1](https://pypi.org/project/thonny/), shouldn't `pip install --upgrade thonny` update it from version 3.3.14?

**Comment by aivarannamaa** [comment]
> shouldn't `pip install --upgrade thonny` update it from version 3.3.14?

Yes, this should update `thonny` to latest version. If it looks otherwise then perhaps you have upgraded thonny in one environment (or for one interpreter) and tested it in another?

**Comment by aivarannamaa** [comment]
Which version does `pip show thonny` show?

**Comment by rootsmusic** [comment]
Package           Version
----------------- -------
astroid           2.15.5
asttokens         2.2.1
colorama          0.4.6
dill              0.3.6
docutils          0.20.1
isort             5.11.5
jedi              0.18.2
lazy-object-proxy 1.9.0
mccabe            0.7.0
mypy              1.3.0
mypy-extensions   1.0.0
parso             0.8.3
pip               23.1.2
platformdirs      3.6.0
pylint            2.17.4
pyserial          3.5
Send2Trash        1.8.2
setuptools        41.2.0
six               1.16.0
thonny            3.3.14
thonnyapp         0.9.1
tomli             2.0.1
tomlkit           0.11.8
typed-ast         1.5.4
typing_extensions 4.6.3
wrapt             1.15.0

Python 3.7.7 (I assume that thonny's version is constrained by thonnyapp's version.)

**Comment by aivarannamaa** [comment]
When I create a new venv and install `thonnyapp`, then it nicely downloads `thonny==4.1.1`.

**Comment by rootsmusic** [comment]
@aivaranamaa  I assume that your Python is a newer version.  I believe that thonny didn't update because my Python version is 3.7.7, which was last supported by [thonny 3.3.14](https://github.com/thonny/thonny/releases/tag/v3.3.14).  It'd be helpful, though, if pip's message is clearer than simply "Requirement already satisfied".
