### ISSUE TITLE
macOS close unsaved File and answer no to save loses focus on Thonny

### ISSUE THREAD

**Issue by martin-guddat** [thonny/thonny#2828]
When closing an unsaved file  with File>Close (CMD W), focus does not jump to another open file (severity low)

Steps to reproduce:
- Open Thonny
- Empty, unnamed file1 is open initially
- Enter some text
- Create an empty new file2, again enter some text
- Close file2 with CMD-W
- Request whether to save data before close comes up
- Select no as answer
- File is closed without save
Expected:
- Focus gets to tab and file1
- Another CMD-W would try to close file1
As-Is:
- Focus is not on any file, CMD-W does not work

Thonny 4.1.0, macOS 13.4.1

**Comment by aivarannamaa** [comment]
Thanks for the report! Thonny 5.0 will have new Notebook component (#2737), and I'll deal with this issue after Notebook issue gets worked out.

**Comment by aivarannamaa** [comment]
Fixed under #2737
