### ISSUE TITLE
If main.py is loaded in pico, thonny does not communicate with it

### ISSUE THREAD

**Issue by DanSkareda** [thonny/thonny#2843]
Hello. I'm using the latest version of thonny (4.1.1) and micropython for raspberry pico w (from https://micropython.org/download/rp2-pico-w/). When I load main.py into pico and disconnect-connect power, pico does not respond to thonny commands (as long as main.py exists). I can only help myself by quickly pressing STOP several times immediately when the pico is connected, only then does the main.py program stop and I can load another program or delete main.py. Older versions supposedly can stop the main.py program at any time (someone on the net says so, I haven't tried it). Can you fix this?

**Comment by aivarannamaa** [comment]
Thank you for the report! I suppose it is related to #2836. I'll see what needs to be done.

**Comment by aivarannamaa** [comment]
Will be fixed under #2843

**Comment by tenapier** [comment]
Hi, I'm having problems with this issue, losing communication with PicoW once I have a main.py program in it. Any outlook on when this might be fixed. Thank you, Tim
