### ISSUE TITLE
Not able to install packages in Thonny ide

### ISSUE THREAD

**Issue by arbbaza** [thonny/thonny#2848]
I am beginner to RP2040 and Circuit python using Thonny IDE.I have tried installing packages using the 'manage packages option' but it does not display any package available.I will share the screenshot below.I tried even installing files manually , but it again displays an error.I am not able to understand what is wrong.
![Screenshot 2023-07-05 095520](https://github.com/thonny/thonny/assets/138644472/e50d94a1-a990-49c2-90ff-62aeb7710c1f)
![Screenshot 2023-07-05 094819](https://github.com/thonny/thonny/assets/138644472/628de802-2d49-428e-8bf8-0937ed937f02)

**Comment by aivarannamaa** [comment]
Usually "an error" is not specific enough to start solving the problem -- it is necessary to include as much detail about the error as possible.

Luckily in the first picture the end of the error message suffices. It looks like you are trying to install the package called `pillow`, but this is not meant for MicroPython.

**Comment by arbbaza** [comment]
thank you for the clarification.

**Comment by arbbaza** [comment]
thank you

**Comment by arbbaza** [comment]
Another problems i am facing.When i search for any package using the manage packages option,it shows this error.I am unable to find any package or search it.the package i require is adafruit_imageload.Though i have the package downloaded from the circuitPython bundle.I am unable to add it manually ('it says pico write mode disabled' and through manage packages it does not show the avaialble packages at all.
![Screenshot 2023-07-05 170714](https://github.com/thonny/thonny/assets/138644472/0599ca1c-4703-47de-8a5d-bcc7b8ba8769)
![Screenshot 2023-07-05 171059](https://github.com/thonny/thonny/assets/138644472/a6788d71-eaee-41ac-9e34-7e1c00c0febd)
