### ISSUE TITLE
pyperclip not working

### ISSUE THREAD

**Issue by Fewoiz** [thonny/thonny#2852]
I did both a PIP Install pyperclip and used the Thonny addin module installation but I still get a ModuleNotFoundError: No module named 'pyperclip' 
I'm using pyperclip3 instead of pyperclip because it works.

**Comment by aivarannamaa** [comment]
Did you install it from "Tools => Manage packages" or "Tools => Manage plug-ins"?

**Comment by Fewoiz** [comment]
Yes, I did.

 

I installed pyperclip3 using the same method and it works fine.
