### ISSUE TITLE
thonny-py38-4.1.1.exe中文界面汉化有问题

### ISSUE THREAD

**Issue by ggtiancai** [thonny/thonny#2855]
thonny-py38-4.1.1.exe中文界面汉化有问题，很多都没被汉化成中文。

**Comment by aivarannamaa** [comment]
Sorry, I don't speak this language.

**Comment by 19e2k67** [comment]
![Screenshot 2023-07-08 213925](https://github.com/thonny/thonny/assets/102461738/f0e527c4-7d62-4fc6-af89-e0931e32736d)
Thonny4.1.1 Some parts of English were not successfully translated into Chinese

**Comment by aivarannamaa** [comment]
Please see #2856
