### ISSUE TITLE
esp32 upload error

### ISSUE THREAD

**Issue by iBigDane** [thonny/thonny#2864]
![1689315277255](https://github.com/thonny/thonny/assets/18596143/f2fe2831-f858-4008-a3bc-3093e678fbe2)
I kept getting stuck in this screen when I uploaded the file
I observed the indicator light of the serial port, and at this time the serial port has stopped working
my micropython version is 1.19.1
thonny version is 4.1.1
If I change to version 4.0.2 of thonny, the upload is normal

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which ESP device are you using? Does the same happen with MicroPython 1.20?

**Comment by iBigDane** [comment]
I use  ESP-WROVER-KIT_V4.1 board, the board use ESP-WROVER-E module。

**Comment by aivarannamaa** [comment]
This seems similar to #2851. I'll try to reproduce it later.

**Comment by aivarannamaa** [comment]
Please test https://github.com/thonny/thonny/releases/tag/v4.1.2
