### ISSUE TITLE
The position of the command line ...

### ISSUE THREAD

**Issue by boa2145** [thonny/thonny#2865]
Hello, Is it possible to change the position of the command line inside Thonny's IDE? I don't like the command line at the bottom, but I prefer to use the command line on right side, that I can code on the left. Would appreciate feedback! Regards ... Gregor

**Comment by SimUKdev** [comment]
You can adjust the layout following the [Custom Layout](https://github.com/thonny/thonny/wiki/Custom-layout) guide in the Wiki.

If you use `shellview.location = e` that will make the Shell (command line) appear on the right hand side.

Some others that I use to customise my Thonny layout are:

```
variablesview.location = ne
outlineview.location = ne
assistantview.location = e
helpview.location = se
todoview.location = se
stackview.location = s
filesview.location = s
notesview.location = s
eventsview.location = s
astview.location = s
objectinspector.location = s
```

**Comment by boa2145** [comment]
Thanks for your reply, SimUKdev. I changed Thonny's configuration file and it works now. I see the command line on the right. That's much better than at the bottom. Regards ... Gregor
