### ISSUE TITLE
Clear the window of the command line while the program is running ...

### ISSUE THREAD

**Issue by boa2145** [thonny/thonny#2866]
Hi, I'm looking for a way to delete resp. clear the window of the command line while a program is running. I know that the window of the command line can be deleted with STRG + L, but that's not what I'm looking for. Can I use a method in my code to clear the  window of the command line? In BASIC this used to be done with CLS, but inside Thonny's IDE I don't know how to do that. Regards ... Gregor

**Comment by aivarannamaa** [comment]
Currently there is no such method implemented, but it's in the TODO list: #1697
