### ISSUE TITLE
Thonny: certificate verify failed: certificate has expired (_ssl.c:1007)>

### ISSUE THREAD

**Issue by EdwardPalaci** [thonny/thonny#2872]
Error Trying to install ssd1306, from tools/manage packages:
Could not fetch search results:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)>

**Comment by petra20** [comment]
I am also getting this error when trying to install picozero

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)>

**Comment by aivarannamaa** [comment]
Please see https://github.com/thonny/thonny/issues/1986

**Comment by petra20** [comment]
So I have read #1986 and downloaded lets-encrypt-r3.der, which I agree does not sound like the best way to fix this problem, but needs must.
But, what do I need to do now I have it, I have tried google, but !!!!!

**Comment by petra20** [comment]
Woohoo!!!
Followed: 
https://support.securly.com/hc/en-us/articles/360026808753-How-do-I-manually-install-the-Securly-SSL-certificate-on-Windows
And now I can flash the LED.
Happy dayz 😎

**Comment by EdwardPalaci** [comment]
Glad, it worked for you,I have windows 11 and the menu sequence is
different. Thanks!
