### ISSUE TITLE
Wiki: update Python version required for thonny

### ISSUE THREAD

**Issue by rootsmusic** [thonny/thonny#2874]
The instructions for [SeparateInstall](https://github.com/thonny/thonny/wiki/SeparateInstall) on non-Windows platforms need to be updated, because versions [4.0.0](https://github.com/thonny/thonny/releases/tag/v4.0.0) and newer don't support Python 3.7.

**Comment by aivarannamaa** [comment]
Thanks for the suggestion! Updated now.
