### ISSUE TITLE
enhancement: shell auto-scroll disabling

### ISSUE THREAD

**Issue by nesergen** [thonny/thonny#2878]
Good day!
My programm is printing a lot of information to the shell-window. Some times there may appear an exception catch. But I can`t stop the scrolling data. It would be nice to implement the possibility to stop the scrolling and  examine the data.

I just read the post https://github.com/thonny/thonny/issues/1988#issuecomment-1624804323

It seems to be what I need. But this feature has not been implemented yet, as I see.

**Comment by aivarannamaa** [comment]
No, it is not implemented yet.

**Comment by SheepBetter** [comment]
I'm having this problem too, I wish I could add an option to stop scrolling to the bottom as I want to see the history logs otherwise it's a pain in the ass every time. It would be great if this could be set now.

**Comment by aivarannamaa** [comment]
This is implemented under #1988 and will be available in Thonny 5.0
