### ISSUE TITLE
can't find numpy in thonny

### ISSUE THREAD

**Issue by rickpeters112233** [thonny/thonny#2879]
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python311\Scripts\cofusion.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by capecrusader-121** [comment]
Do you have numpy installed to path ?
Also try installing numpy from within thonny.

**Comment by aivarannamaa** [comment]
@rickpeters112233 , please re-open if you have installed numpy via "Tools => Manage packages" and still have this problem

**Comment by rickpeters112233** [comment]
Installed and problem went away.  I thought since I already had Python installed it would run off of that. Now I have 2 of every package.
