### ISSUE TITLE
Support Ukraine - Double standard

### ISSUE THREAD

**Issue by iamahmedtahar** [thonny/thonny#2894]
![image](https://github.com/thonny/thonny/assets/9547879/26e2b5a2-07b5-4d6e-a5ba-8260879589eb)

**Comment by Pernat1y** [comment]
First of all, it is [whataboutism](https://en.wikipedia.org/wiki/Whataboutism).
The second thing is that started way before "12 days ago".
Read about [Holodomor](https://en.m.wikipedia.org/wiki/Holodomor) in 1932-1933 as an example, where 3.5 to 5 mil Ukrainians were killed (that's, like, 60~90% of current Palestine population) by USSR/russia. Also, there was no support in 2014 and, as result, Ukraine lost a piece of its territory and occupant got another springboard for full-fledged attack.
I am not saying that you (or anyone else, who can and is willing to) should stop supporting other countries, nations, ethnicities and so on, who need help. Just don't do such a comparisons. That's inappropriate.

**Comment by rosesonfire** [comment]
Free free Palestine! End Zionist occupation of Palestine! IDF is a terrorist organization. SPEAK UP FOR THE FREEDOM OF PALESTINIANS FROM ZIONISTS.
