### ISSUE TITLE
CTRL + SPACE suggestions / autocomplete not working

### ISSUE THREAD

**Issue by MarioPL98** [thonny/thonny#2895]
![obraz](https://github.com/thonny/thonny/assets/16231640/5fb34ebe-e0a8-4ef7-97b9-d8e9846fb213)
In this example when I press CTRL and SPACE, nothing happens. I assume it should show possible methods or properties.

Thonny 4.1.1 with RP2040 board.

**Comment by aivarannamaa** [comment]
Do you have Power Toys installed on this machine? If yes, then please see https://answers.microsoft.com/en-us/windows/forum/all/ctrl-space-not-working-while-pressed-together/f6ef4fae-5403-429a-8c8d-484095feee45

**Comment by MarioPL98** [comment]
No, it's not installed. Ctrl-space works in pycharm, vscode, visual studio code, etc.

**Comment by aivarannamaa** [comment]
I found the reason -- I had mostly tested in development environment, but the packaged variant of Thonny is missing one set of MicroPython typing stubs. 

Will fix this in Thonny 4.1.2.

**Comment by aivarannamaa** [comment]
Please test https://github.com/thonny/thonny/releases/tag/v4.1.2
