### ISSUE TITLE
cant upgrade or uninstall packages in thonny 4.1.2

### ISSUE THREAD

**Issue by ktrinko** [thonny/thonny#2902]
Dear sir,
after installing the latest portable version 4.1.2 on a windows 10 machine I cant upgrade or unistall packages becaus I am missing the buttons:
![shot](https://github.com/thonny/thonny/assets/110204960/0741ee3a-c77b-4f4f-9081-51ba41353432)

**Comment by ktrinko** [comment]
Installed on an other windows10-machine the non-portable version of thonny , which shows the same behaviour: no buttons for upgrade and uninstall appear

**Comment by aivarannamaa** [comment]
Thank you for the report!

I found the bug and the fix will be in Thonny 4.1.3.

**Comment by ktrinko** [comment]
Dear Sir,

thanks for your kind support!

Am Do., 17. Aug. 2023 um 07:17 Uhr schrieb Aivar Annamaa <
***@***.***>:
