### ISSUE TITLE
toolbar icon too small

### ISSUE THREAD

**Issue by kjm1102** [thonny/thonny#2903]
Installed the latest thonny on  windows10 & the run, stop, etc icons in the tool bar along the top a tiny but fonts in other windows are OK. Can't figure out how to increase the size of just the icons?

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please try setting "UI scaling factor" to 2.0 or more at "Tools => Options => General".

If this works then please tell me which factor did you choose and what is your screen resolution.

**Comment by kjm1102** [comment]
2 doesn't seem to make any difference to the icon size. 2.5 gives a reasonably sized icon but the font is now bigger than I'd like. 
![image](https://github.com/thonny/thonny/assets/92007731/d42b1197-2d9f-4213-8a9f-4eb8ded7f54a)

**Comment by aivarannamaa** [comment]
You can control editor font size separately in the "Editor" tab of the configuration dialog.

**Comment by kjm1102** [comment]
I'm off topic now but is it possible to change the default indent to 2 spaces instead of 4?

**Comment by aivarannamaa** [comment]
> I'm off topic now but is it possible to change the default indent to 2 spaces instead of 4?

Nope, see #1963
