### ISSUE TITLE
GUI Layout - Window and Panels Not Retained After Quitting

### ISSUE THREAD

**Issue by farTooOld** [thonny/thonny#2911]
Re:  v4.1.2  (and, 4.0.2)
Mac 12.6.3 Monterey

Issue: After Quitting, Thonny does Not retain the Window/GUI layout (size of the various panels/Sidebars/etc).
I have to Resize/Re-Arrange it everytime (a PITA).

This has become my Favorite Python IDE - has ~almost everything needed without all the extra/clutter... THANK YOU!!!

**Comment by aivarannamaa** [comment]
Thanks for the report!

I can't reproduce this in my mac, but I have plans to refactor Thonny's layout components in version 5.0 and most likely this will fix your issue.

**Comment by farTooOld** [comment]
If it helps, attached images shows my arrangement and how Thonny looks after quitting and restart...
<img width="600" alt="Screen Shot 2023-09-02 at 09 28 16" src="https://github.com/thonny/thonny/assets/23279806/1b39848a-f4b6-46b5-9db0-b1ae2e5c7fd9">
<img width="600" alt="Screen Shot 2023-09-02 at 09 28 57" src="https://github.com/thonny/thonny/assets/23279806/b6054dd9-3acf-405d-99f5-2bf78e0ca084">
