### ISSUE TITLE
pyserial-asyncio gives a syntax error when it's a valid addon

### ISSUE THREAD

**Issue by wyzarddoc** [thonny/thonny#2915]
pyserial-asyncio gives syntax error due to the - in the label when used as a **import pyserial-asyncio** statement in a program.

**Comment by aivarannamaa** [comment]
I guess you need to look up the documentation for the proper module name for import statement.

**Comment by wyzarddoc** [comment]
I guess you are a rookie programmer and not in the US otherwise you'd know that pyserial-asyncio is a valid python module. Or I guess if you can use Google you could learn something before trying a chatbot answer. You need to get smarter before answering questions or at least do a web-search thanks for wasting my time with a wrong answer
Web-design, Woodworking, 3D-Art 

    On Wednesday, August 30, 2023 at 06:01:48 AM MDT, Aivar Annamaa ***@***.***> wrote:  
 
 


I guess you need to look up the documentation for the proper module name for import statement.
