### ISSUE TITLE
Errors with python-cs50 package.

### ISSUE THREAD

**Issue by mangefx** [thonny/thonny#2924]
from cs50 import get_string

s = get_string("Enter something: ")
print("You entered:", s)

            SHELL
Error in sys.excepthook:

Original exception was:

Process ended with exit code 120.

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for the late reply! 

There is a trick used in `cs50` package, which conflicts with a trick used in Thonny. I proposed a work-around at https://github.com/cs50/python-cs50/pull/175

On Thonny's side the work-around is to use "Run => Run current script in terminal"
