### ISSUE TITLE
Unable to install new package using thonny windows

### ISSUE THREAD

**Issue by OscarW27** [thonny/thonny#2928]
When searching for packages I get this error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)>. I am not able to find a solution. Is anyone willing to help?

**Comment by rootsmusic** [comment]
Opened in #2881

**Comment by rootsmusic** [comment]
Try solutions in #1986
