### ISSUE TITLE
error 'import cv2'

### ISSUE THREAD

**Issue by Seojin1112** [thonny/thonny#2934]
import socket
import time
import struct

import cv2
import numpy as np

from tensorflow.keras.models import load_model
from PIL import Image, ImageOps

cap = cv2.VideoCapture('http://192.168.4.1:81/stream')

CAM_IP = '192.168.4.1'
MOT_PORT = 82
MOT_ADDR = (CAM_IP, MOT_PORT)

mot_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

t_now = time.time()
t_prev = time.time()
cnt_frame = 0

model = load_model('keras_model.h5')

data= np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

names = ['_0_forward', '_1_right', '_2_left', '_3_stop']

while True:

    # 영상 받기
    ret, frame = cap.read()

    # 영상 출력
    frame = cv2.rotate(frame,cv2.ROTATE_180)
    cv2.imshow('frame', frame)

    frame = cv2.resize(frame, (160, 120)) 

    image = Image.fromarray(frame)

    size = (224, 224)
    image = ImageOps.fit(image, size, Image.ANTIALIAS)

    #turn the image into a numpy array
    image_array = np.asarray(image)
    # Normalize the image
    normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
    # Load the image into the array
    data[0] = normalized_image_array

    # run the inference
    y_predict = model.predict(data)

    y_predict = np.argmax(y_predict,axis=1)
    print(names[y_predict[0]], y_predict[0])

    # send y_predict
    cmd = y_predict[0].item()
    cmd = struct.pack('B', cmd)
    mot_socket.sendto(cmd, MOT_ADDR)

    key = cv2.waitKey(1)
    if key == 27:
        break

    cnt_frame += 1
    t_now = time.time()
    if t_now - t_prev > 1.0 :
        t_prev = t_now
        print("frame count : %f" %cnt_frame)
        cnt_frame = 0

mot_socket.close()

I'm a  student in high school.
This code is related to self-driving car program and I wrote this code.
And there are some errors  that nobody in my school (including teachers) know why these errors appeared
I already installed the Tenserflow , opencv, etc.. 

the errors are 
  File "C:\Users\YNA\Desktop\소스_230425_HTTP\03_tm_ai_driving.py", line 5, in <module>
    import cv2
  File "C:\Users\YNA\AppData\Local\Programs\Thonny\lib\site-packages\cv2\__init__.py", line 11, in <module>
    import numpy
  File "C:\Users\YNA\AppData\Local\Programs\Thonny\lib\site-packages\numpy\__init__.py", line 139, in <module>
    from . import core
  File "C:\Users\YNA\AppData\Local\Programs\Thonny\lib\site-packages\numpy\core\__init__.py", line 73, in <module>
    from . import numeric
  File "C:\Users\YNA\AppData\Local\Programs\Thonny\lib\site-packages\numpy\core\numeric.py", line 2521, in <module>
    from . import _asarray
  File "C:\Users\YNA\AppData\Local\Programs\Thonny\lib\site-packages\numpy\core\_asarray.py", line 138, in <module>
    require_with_like = array_function_dispatch(
TypeError: array_function_dispatch() got an unexpected keyword argument 'use_like'

I want to know how I can solve it

**Comment by aivarannamaa** [comment]
This doesn't look like Thonny's issue. I guess you'll find the answer more likely if you ask this question in a numpy or OpenCV forum.
