### ISSUE TITLE
tooltips - can I get rid of them

### ISSUE THREAD

**Issue by mikedabb6** [thonny/thonny#2935]
I have the same issue as others with the tool tips not going away.

I have Thonny version 4.0.1. installed.

Can you please tell me how to install Version 4.1.2 on my Raspberry Pi 400.

Thanks in advance

**Comment by aivarannamaa** [comment]
You can either `apt remove thonny` and then `pip install thonny` or you can wait until RPi people update their repositories.

I have plans to release 4.1.3 during this weekend and after this I could poke RPi package managers to make the update.

**Comment by mikedabb6** [comment]
Hi Thanks for the quick reply.I will look into apt remove and reinstall and see if that works.Thanks for poking the RPi people if that doesn’t work.RegardsMikeSent from my iPhoneOn 21 Sep 2023, at 14:37, Aivar Annamaa ***@***.***> wrote:﻿
You can either apt remove thonny and then pip install thonny or you can wait until RPi people update their repositories.
I have plans to release 4.1.3 during this weekend and after this I could poke RPi package managers to make the update.
