### ISSUE TITLE
Open System Shell command closes pi peco connection

### ISSUE THREAD

**Issue by rvwilliams88** [thonny/thonny#2940]
I'm running Thonny 4.1.2 on Windows 11.  I want to install a package using pip.  When I click on the 'Open system shell' command it closes the connection to my pi peco w and gives me a Windows prompt. The two screenshots show before the command and after it.
![after](https://github.com/thonny/thonny/assets/112261322/083a2ac8-d12e-4ad7-ae59-ca58e9442bd6)
![before](https://github.com/thonny/thonny/assets/112261322/ce1590a4-9ebe-437a-9315-10197e6258c5)

**Comment by aivarannamaa** [comment]
Thank you for the report!

The command name "Open system shell" is probably misleading in MicroPython mode. In this context the word "system" represents the MicroPython runtime and this command closes the serial connection in Thonny and reopens it in a serial command line program. The connection must be closed in Thonny, because only one process can have serial connection to a device at a time.

**Comment by aivarannamaa** [comment]
If you want to install a MicroPython package on your device, then you could use "Tools => Manage packages", which re-uses Thonny's serial connection to the device.

**Comment by rvwilliams88** [comment]
Hi Aivar

Thanks for the response.  I couldn't use the package manager because of the expired certificate issue.  I was following the instructions in the Thonny help :

1. From "Tools" menu select "Open system shell...". You should get a new terminal window stating the correct name of pip command (usually pip or pip3). In the following I've assumed the command name is pip.
2. Enter pip install <package name> (eg. pip install pygame) and press ENTER. You should see pip downloading and installing the package and printing a success message.
3. Close the terminal (optional).
4. Return to Thonny.

How is the above meant to work on a Windows-based PC?

Regards

Richard Williams.

****************************************************
Richard Williams
email: ***@***.******@***.***>
mobile: 07981 734697
****************************************************

**Comment by aivarannamaa** [comment]
These instructions are for installing packages for CPython, not for MicroPython.

As a work-around, you could download the required package manually with a web-browser, uncompress and transfer the files to your MicroPython device's `/lib` folder using Thonny's file browser (View => Files).

**Comment by rvwilliams88** [comment]
Hi Aivar, thanks for the explanation. Pity that isn't clearer in the Help.
Regards
Richard Williams

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
