### ISSUE TITLE
Error when opening

### ISSUE THREAD

**Issue by MontWAsHere** [thonny/thonny#2946]
![image](https://github.com/thonny/thonny/assets/146595865/472d366f-3378-4cde-8778-d0df62f7a300)

This error is displayed when opening thonny

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Windows version is this? Which Thonny variant did you download?

**Comment by MontWAsHere** [comment]
Is windows 7 and is thony 4.1.3. The variant is : installer with 32 bits and phyton 3.8. :)

**Comment by aivarannamaa** [comment]
Sorry for the late reply! I don't have a Windows 7 machine available anymore and I'd rather not spend time on supporting this platform anymore.

If you can't upgrade to Windows 10, then you could try an older Thonny version (eg. 3.3)
