### ISSUE TITLE
Playsound errors after playing the sound with mp3 but not wav unless full path is used

### ISSUE THREAD

**Issue by JaredKreft** [thonny/thonny#2954]
Using playsound 1.3

Thonny 4.0.2 Win 10 (64-bit), Python 3.10.9 (64 bit)

(See attached code):

STR: 
Use playsound to play a wave file using a relative path (works)
Use playsound to play an mp3 file using an absolute path (works)
Use playsound to play an mp3 file using a relative path

Actual result: plays the sound, but the code errors out with an MCI device not ready error.

Expected result: Third example consistent with the first two.

Note: Using relative vs. absolute path should not cause a device not ready error in the sound driver. The behavior should be the same for wav and mp3.

**Comment by aivarannamaa** [comment]
I'm afraid this issue is not specific to Thonny. Please reopen if your program works outside of Thonny and doesn't work in Thonny.
