### ISSUE TITLE
 If you do not support the Ukrainian regime

### ISSUE THREAD

**Issue by ArduinoGo** [thonny/thonny#2955]
Version 4 includes support for Ukrainian regime (Zelensky's corrupt regime) in the menu bar.

![Скриншот 07-10-2023 000918](https://github.com/thonny/thonny/assets/1401505/c1d1813a-b580-48d8-9765-52ae0d532fce)

Like me, many people do not support him.

To remove support, you need to find the workbench.py ​​file and comment out lines (697-706).

This way you will save billions of tax dollars and stop the war.

--

C:\Users\Username\AppData\Local\Programs\Thonny\Lib\site-packages\thonny\workbench.py

![Скриншот 07-10-2023 000712](https://github.com/thonny/thonny/assets/1401505/a51a9f07-e877-4933-a421-13c62283b2c1)

**Comment by aivarannamaa** [comment]
This is open-source software and you are free to change it to your liking. If this makes Russians go home and stop the war, the better. In fact, in this case I'd be happy to remove the button from the next version of Thonny.

**Comment by wanwusangzhigit** [comment]
I think this makes many people will not use thonny as longer
