### ISSUE TITLE
add theme for Thonny like zynaddsubfx

### ISSUE THREAD

**Issue by theavege** [thonny/thonny#2966]
Hello.

Please add a theme for Thonny like [zynaddsubfx](https://zynaddsubfx.sourceforge.io).

Sincerely,
Artem

**Comment by aivarannamaa** [comment]
Unfortunately I don't have time for this. You could try doing it yourself, though. See https://github.com/thonny/thonny/wiki/Theming for instructions.

**Comment by theavege** [comment]
Thanks. I will try.
