### ISSUE TITLE
RasPiOS Bookworm. Is there an option to create virtual environment with --system-site-packages argument?

### ISSUE THREAD

**Issue by DeeJay** [thonny/thonny#2981]
Using Thonny 4.1.3 under RasPiOS Bookworm on RPi hardware.

Configure Interpreter -> New virtual environment

For some purposes it is necessary to create a virtual environment with the --system-site-packages option enabled. For convenience, is it possible/necessary to give Thonny an option to include this parameter?

The workaround at present is to use the system shell (cli) to create a virtual environment with this option and then configure Thonny to use that existing venv as its current python interpreter.

The **gpiozero** python library, recommended by Raspberry Pi for control of GPIO pins, is one such site-wide library that is not accessible from a Thonny-generated venv by default.

_{EdIt: added subsequently - }_

It seems that the line **include-system-site-packages = [ true | false ]** in the file **pyvenv.cfg** in the venv 'wrapper' folder may be the point where this feature is implemented and controlled.

**Comment by aivarannamaa** [comment]
Thanks for the suggestion and sorry for the late reply!

I'm considering refactoring the virtual environment creation in Thonny 5.0 and most likely I'll include a checkbox for inheriting system site packages.

**Comment by aivarannamaa** [comment]
Handled under #2974
