### ISSUE TITLE
Quite wierd bug while using the serial

### ISSUE THREAD

**Issue by mirkokral** [thonny/thonny#2983]
(I checked, it does not happen in PuTTY. The python code just errors like normal and no duplicate errors.)
Board: micro-bit
Firmware: Adafruit CircuitPython 8.2.6 (Installed through thonny's built in installer)

How to reproduce:
Run a long string of stuff e. "aa aaaaaaaa aaaaaaaa" (invalid stuff, if you see 2 different errors, and a wierd char with >OK then you have succeeded)
Run a short string e. "a"
It should crash with a hard fault and a memory access or instruction error.

Console:
```
>>> aa aaaaaaaa aaaaaaaa
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
>OKTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'aaaaaa' is not defined
>>> a
Serial console setup

Auto-reload is off.
Running in safe mode! Not running saved code.

You are in safe mode because:
CircuitPython core code crashed hard. Whoops!
Hard fault: memory access or instruction error.
```

As i am new in circuitpython, i don't really know what is happening and why is it happening.

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for the late reply!

Which OS and which Thonny version are you using? Can you reproduce this with CP 8.2.7? I cannot in macOS.

**Comment by mirkokral** [comment]
> Thank you for the report and sorry for the late reply!
> 
> Which OS and which Thonny version are you using? Can you reproduce this with CP 8.2.7? I cannot in macOS.

Sorry for very late reply but i was using arch linux. Forgot the thonny version.

**Comment by aivarannamaa** [comment]
> CircuitPython core code crashed hard

I'm afraid this is out of my reach. Most likely this is fixed in newer CircuitPython versions
