### ISSUE TITLE
Update pattern for Pololu 3pi+ and add new Zumo 2040 robot

### ISSUE THREAD

**Issue by pdg137** [thonny/thonny#3002]
Hello, regarding the Pololu firmware variant entry here:

https://github.com/thonny/thonny/blob/master/data/update_micropython_variants.py#L237

Could you update it to match our latest release?

https://github.com/pololu/micropython-build/releases/

There should now be two entries, like this:

```python
pololu_variants = [
    {
        "_id": "pololu-3pi-2040-robot",
        "model": "3pi+ 2040 Robot",
    },
    {
        "_id": "pololu-zumo-2040-robot",
        "model": "Zumo 2040 Robot",
    },
]
```

and the version string needs to be updated to work with multiple MicroPython versions (right now it looks like it's hard-coded to 1.20.0).  I think you could just extend the version-matching part so that the version looks like `v1.22.0-preview-231113` if that works for you.

**Comment by aivarannamaa** [comment]
I decided it's easier if in the update script I simply list the desired Pololu items as they should appear in the data file. Done now.

**Comment by pdg137** [comment]
Thanks!

Is there something else we could do to make our releases work better with Thonny? I think the only reason we're publishing them on GitHub is to support these automatic updates. It would be nice to have new ones show up automatically and maybe also to see more of the old ones, too.

**Comment by aivarannamaa** [comment]
You could also make a pull request for the Pololu section of the update script: https://github.com/thonny/thonny/blob/b3c3b8d2f63558eeed8ed378cf5e86b03508741a/data/update_micropython_variants.py#L224

This way I can put it online faster.

**Comment by pdg137** [comment]
Okay! I'll do that if necessary, but please let me know if there's something we can do to fix the automatic updates. I thought you'd just be able to use a pattern like

```python
"_download_url_pattern": "https://github.com/pololu/micropython-build/releases/download/{version}/micropython-{id}-v{version}.uf2",
```

and then it would be easier for you since you wouldn't ever have to manually update anything.

**Comment by pdg137** [comment]
Oh! Looking at the URL, maybe I can see the problem. Would it be easier for you if we named the releases like `v1.22.0-preview-231113` instead of just `231113`?

**Comment by aivarannamaa** [comment]
Would the `preview` make sense for next releases as well? I proposed PR-s because then you wouldn't need to create GitHub releases but could upload each release wherever and name it whatever.

**Comment by pdg137** [comment]
`v1.22.0-preview` is the current version name used on the MicroPython master branch so we just started our name with that. Not sure when we'll have a next release but I suppose that after `v1.22.0` is released they will immediately update the name to `v1.23.0-preview`. So we'll probably always have a "preview" in our names unless we happen to branch off the exact point of one of the official releases.
