### ISSUE TITLE
clear varibales command

### ISSUE THREAD

**Issue by oasis4cns** [thonny/thonny#3012]
I think Thonny has possibility to clear variables. So it is very useful to add a menu command and a keyboard shortcut for that
best regards

**Comment by aivarannamaa** [comment]
If you could tell me more about this wish, I could offer a solution. I which situation do you want to clear variables?

**Comment by oasis4cns** [comment]
hi,
for example while teaching, I use variables sidebar to show to students how
variables are changed. But when I start a new shell example, I clear shell
(ctrl+L) but I couldn't clear variables so we don't like to show variables
from the old example with variables of the new example. It is like when
working on Matlab environment.

**Comment by aivarannamaa** [comment]
In this case you could press "Stop / Restart" button (or the same command from the Tools menu).

**Comment by oasis4cns** [comment]
thanx! stop/restart combine clear shell and clear variables. but it is not
easy to discover that

**Comment by aivarannamaa** [comment]
> it is not easy to discover that

As I see it, clearing variables is just a side effect of restarting the interpreter. I don't see why someone would want the former without the latter. Therefore I'd leave current command name as it is.
