### ISSUE TITLE
Unable to install packages from local file

### ISSUE THREAD

**Issue by tazr42** [thonny/thonny#3026]
When installing a package from Tools->Manage Packages-> Install from local file it fails.

The command it tries to run is:
install install --user H:/Downloads/pip_system_certs-4.0-py2.py3-none-any.whl

And then it errors at trying to install the package "install".

The specific installation we have is behind a firewall, hence installing pip system certs, so the error messages we get are the firewall blocking the search for the package install.

ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install
Process returned with code 1

Managed to work around by editing pip_gui.py and removing "install" from the args array on line 898. No idea what else this impacts though.

**Comment by aivarannamaa** [comment]
Thank you for the report!

The bug appeared because I forgot to test installing from file after a refactoring. Your fix is spot on. I'll include similar fix in Thonny 5.0.
