### ISSUE TITLE
Problem with Thonny “save” 

### ISSUE THREAD

**Issue by JoKesCode** [thonny/thonny#3033]
| I am a new user and have a new Raspberrry Pi 5 and runnig it on my Mac with TigerVNC. Now I try to work with Thonny (4.1.4). But it is not possible to save files. When I select „save“ or "save as ..“ there is no possibility to give a name. I only see the folders of my raspberry and no possibility to save the file. I then only can close the folder window by pressing „esc“. What can I do to solve this problem?
-- | --

**Comment by aivarannamaa** [comment]
Can you post a screenshot describing your problem?

**Comment by JoKesCode** [comment]
> Thank you very much for the quick response. 
> 
> Attached I send some screenshots. It is not possible to save one file or open another. There is no way to enter a file name. Even the immediately opened file manager does not allow saving. Here I can only come back with the "ESC" key. Hope you have a solution for me. 
> 
> Best regards, Jochen Kempkens
> 
> 
> 
￼
> 
> 
￼
> 
> 
￼
> 
> 
￼

**Comment by aivarannamaa** [comment]
Unfortunately the images didn't come through. It looks GitHub doesn't support images via email. Please post them via web browser.

**Comment by JoKesCode** [comment]
![image](https://github.com/thonny/thonny/assets/153101755/b44119d4-0328-4f28-98c4-dfd545a91ed2)

![image](https://github.com/thonny/thonny/assets/153101755/aacd5173-605c-4033-9e31-c92b9de176d7)![image](https://github.com/thonny/thonny/assets/153101755/f56e6f33-f825-4a9a-84f3-d104d3dd49c8)
![image](https://github.com/thonny/thonny/assets/153101755/bc091989-4256-4f11-bbfd-21e5d0a840fd)
![image](https://github.com/thonny/thonny/assets/153101755/64c6b7fa-b577-4e8e-9d12-a92de82e7718)

**Comment by aivarannamaa** [comment]
Thanks! Now I understand.

It looks like the file selection app (zenity) by default creates too large windows for your resolution. You could try resizing it (press Alt, click anywhere on the window and drag until you see a corner of the window).

**Comment by aivarannamaa** [comment]
If this doesn't help, then in Thonny go to "Tools => Options => General" and select "Use Tk file dialogs instead of Zenity"

**Comment by aivarannamaa** [comment]
> Both options work. The second is more convenient. 😄

According to my tests, Zenity remembers the desired window size after you have resized it once.
