### ISSUE TITLE
ESP32: Thonny's backend output in Micropython WebREPL.

### ISSUE THREAD

**Issue by IhorNehrutsa** [thonny/thonny#3038]
There is Thonny's backend output in Micropython WebREPL when the ESP32 is connected to Thonny and WebREPL at the **same time**.
Please hide it.
Thank you.
![image](https://github.com/thonny/thonny/assets/70886343/c5d972b0-5791-461e-a582-314c5683eb26)

**Comment by aivarannamaa** [comment]
There is no way to hide it if you want to use two clients at the same time. MicroPython reuses same REPL for both serial and WebREPL connections. Actually I'm surprised that you can even use two connections at the same time. Most likely you will meet problems at some point.

**Comment by IhorNehrutsa** [comment]
If REPL output is raw, there are no restrictions to use two clients at the same time.
![image](https://github.com/thonny/thonny/assets/70886343/fdfeef7d-20aa-4998-9714-24b8d141baf4)
![image](https://github.com/thonny/thonny/assets/70886343/0be8bf7b-eba4-491d-8f6f-95a2fdc65f8d)
