### ISSUE TITLE
esp32 to thonny:PROBLEM IN THONNY'S BACK-END: Internal error (serial.serialutil.SerialTimeoutException: Write timeout). See Thonny's backend.log for more info. You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.   Process ended with exit code 0.

### ISSUE THREAD

**Issue by isbcoo** [thonny/thonny#3050]
how to solve

**Comment by isbcoo** [comment]
it is ok on other computer,but it is not good on my computer.

**Comment by aivarannamaa** [comment]
The difference between computers may be caused by different device drivers installed.

**Comment by dcmcshan** [comment]
I get this as well with ESP32 on OSX, wondering if it is a timing problem.  Is there a timeout that I can adjust?
