### ISSUE TITLE
WARNING: Secure coding is not enabled for restorable state! 

### ISSUE THREAD

**Issue by caseminario** [thonny/thonny#3058]
I get this warning using turtle ..
2024-01-06 12:32:08.079 Python[13643:1383350] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

Here's my code causing the error ..
import turtle
turtle.forward(50)

macOS Sonoma Version 14.2.1
MacBook Pro 2.3 GHz 8-Core Intel Core i9
Thonny 4.1.4, Python 3.10.11, Tk 8.6.13

**Comment by aivarannamaa** [comment]
You can ignore this warning. Next Thonny version comes with newer Python with this problem fixed.

**Comment by caseminario** [comment]
> You can ignore this warning. Next Thonny version comes with newer Python with this problem fixed.

Thanks Aivar! Any idea when the next Thonny version will be shipped? I have a Python course starting on Jan 16 and we start using Turtle heavily; if the new code isn't out yet, I will create a workaround.

**Comment by aivarannamaa** [comment]
By 16th of January I may be able to release the first beta of the next version but you shouldn't count on this.

**Comment by caseminario** [comment]
Ok, thanks for letting me know!

**Comment by Jedikoops** [comment]
welp.

**Comment by Zubair-codes1** [comment]
i cant ignore this issue its causing my code not to run
