### ISSUE TITLE
No more "Maximize View" option...

### ISSUE THREAD

**Issue by Charpy** [thonny/thonny#3066]
Hi,

I often need to display code only, without distraction, to my students. But the "**View/Maximise View**" features is now missing in recent versions of Thonny. Is there a way to have it back ?

[screenshot](https://i.imgur.com/zK67PsL.png)

**Comment by aivarannamaa** [comment]
This is available in "expert" UI mode. See "Tools / Options /General". You need to restart Thonny after changing this option.

**Comment by Charpy** [comment]
Oh thanks, perfect !
