### ISSUE TITLE
Multicursor for Thonny

### ISSUE THREAD

**Issue by Denisov21** [thonny/thonny#3067]
HI,
I would like it if in your program Thonny, you could add the functionality of: multicursor. Let me explain better: by holding down the CTRL+ key and clicking with the left mouse button on Windows, a cursor is created for each click made; so I can edit the code simultaneously. An example that uses this function is Notepad++

Thank you

**Comment by aivarannamaa** [comment]
Thanks for the suggestion, but I'm afraid this task would remain in the TODO list indefinitely, because there are already too many issues, which are more important for beginners (Thonny's main target group). Therefore I'm closing this issue.
