### ISSUE TITLE
Allow custom syntax colors / color schemes

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#307]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/307) by me.**

----------------------------------------

**Comment by cybarspace** [comment]
@aivarannamaa So... how to add custom syntax highlighting ?

Also, is there any way to add syntax highlighting for other languages ? I want to be able to use Thonny for editing Ren'py scripts too. Is that possible ?

**Comment by aivarannamaa** [comment]
@cybarspace 

> So... how to add custom syntax highlighting

Here you go => https://github.com/thonny/thonny/wiki/Theming

> Also, is there any way to add syntax highlighting for other languages ? I want to be able to use Thonny for editing Ren'py scripts too. Is that possible ?

Currently not.
