### ISSUE TITLE
Thonny locks up

### ISSUE THREAD

**Issue by AshDini** [thonny/thonny#3071]
If you don't press "Stop" after a syntax error, correct the error and press 'Run' Thonny will lock up

**Comment by aivarannamaa** [comment]
What do you precisely mean by locking up? No click or keypress does anything? Can you send me a screenshot of this state?

**Comment by AshDini** [comment]
Here  is the screen BEFORE:

[image: 2024-01-17 15 15 15.jpg]

and AFTER, takes no input from keyboard:

[image: 2024-01-17 15 09 12.jpg]

**Comment by AshDini** [comment]
This also happens if the source is being edited while it is running.

**Comment by aivarannamaa** [comment]
The pictures don't come through when sent via e-mail. Please post them at GitHub

**Comment by AshDini** [comment]
![2024-01-17 15 15 15](https://github.com/thonny/thonny/assets/66854499/9b625274-f6c2-491e-a6ed-2b1daa8a5031)
![2024-01-17 15 09 12](https://github.com/thonny/thonny/assets/66854499/4c7e79da-5f08-4136-b2a1-5cbf2d1e46fd)

I am using Thonny 4.1.4 under Win 10.
I was debugging a Python web server and while it was still running, I made some code changes, without pressing the Stop button.
In this case Thonny becomes unresposive, and has to be deleted and reloaded.
