### ISSUE TITLE
Thonnet error message

### ISSUE THREAD

**Issue by eugenerod33** [thonny/thonny#3107]
When attempting to run some code, I got the following message:

PROBLEM WITH THONNY'S BACK-END:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1245, in execute_source
    statements = compile(ast.Module(body=root.body[:-1]), filename, "exec")
TypeError: required field "type_ignores" missing from Module

**Comment by aivarannamaa** [comment]
Duplicate of #2992
