### ISSUE TITLE
Thonny fails to boot when /usr/bin/activate exists (conda)

### ISSUE THREAD

**Issue by scottfp** [thonny/thonny#3110]
Thonny fails to boot when /usr/bin/activate exists (conda)
---
May be a continuation of https://github.com/thonny/thonny/issues/2516.

## Description

After Thonny checks for `THONNY_USER_DIR`, and portable mode, it checks if a virtual environment is executable without actually checking if it's in a virtual environment. This makes Thonny set the user dir to `/usr/.thonny` on my system, which is not writeable by normal users. 

On the latest version (v4.1.4), there is a [function for this](https://github.com/thonny/thonny/blob/v4.1.4/thonny/common.py#L802-L808) but it's not actually being run. My local version (v4.0.2) does not have this function at all. Setting `THONNY_USER_DIR` dodged this issue, pinpointing it to `_compute_thonny_user_dir()` pretty quickly.

## Proposed solution

I tested the following approaches successfully by modifying site-packages locally, and I plan to prepare a PR when time permits. I personally prefer Option 1, as it's a more precise fix to this specific issue.

**Option 1 - Call `running_in_virtual_environment()` from `__init__.py` ([Ref](https://github.com/thonny/thonny/blob/v4.1.4/thonny/__init__.py#L87C10-L87C31))**

```diff
def _compute_thonny_user_dir():
    if os.environ.get("THONNY_USER_DIR", ""):
        return os.path.expanduser(os.environ["THONNY_USER_DIR"])
    elif is_portable():
        if sys.platform == "win32":
            root_dir = os.path.dirname(sys.executable)
        elif sys.platform == "darwin":
            root_dir = os.path.join(
                os.path.dirname(sys.executable), "..", "..", "..", "..", "..", ".."
            )
        else:
            root_dir = os.path.join(os.path.dirname(sys.executable), "..")
        return os.path.normpath(os.path.abspath(os.path.join(root_dir, "user_data")))
-   elif is_virtual_executable(sys.executable) and not is_private_python(sys.executable):
+   elif (
+       running_in_virtual_environment()
+       and is_virtual_executable(sys.executable)
+       and not is_private_python(sys.executable)
+   ):
        return os.path.join(sys.prefix, ".thonny")
    elif sys.platform == "win32":
        return os.path.join(_get_roaming_appdata_dir(), "Thonny")
    elif sys.platform == "darwin":
        return os.path.expanduser("~/Library/Thonny")
    else:
        # https://specifications.freedesktop.org/basedir-spec/latest/ar01s02.html
        data_home = os.environ.get(
            "XDG_CONFIG_HOME", os.path.expanduser(os.path.join("~", ".config"))
        )
        return os.path.join(data_home, "Thonny")
```

**Option 2 - Call `running_in_virtual_environment` from `is_virtual_executable` ([Ref](https://github.com/thonny/thonny/blob/v4.1.4/thonny/common.py#L789-L793))**

```diff
def is_virtual_executable(executable):
+   if not running_in_virtual_environment():
+       # probably add some log msg here
+       return False
    exe_dir = os.path.dirname(executable)
    return os.path.exists(os.path.join(exe_dir, "activate")) or os.path.exists(
        os.path.join(exe_dir, "activate.bat")
    )
```

## How to reproduce
I ran into this on Fedora 38, but I suspect it will be reproducible on any Linux distro.
Note: I suggest doing this in a VM because conda creates lots of little files that uninstallers do not clean up.

1. Install thonny through package manager
    ```
    sudo dnf install thonny
    ```
2. Confirm Thonny boots
    ```
    thonny
    ```
3. Install conda through package manager. Other installation methods will probably have the same result, but this is what I did.
    ```
    sudo dnf install conda
    ```
4. Init conda as root. This is probably the wrong way to use conda, but apparently it's what I did when I spent 20m messing with it last year.
    ```
    sudo conda init
    ```
5. Confirm /usr/bin/activate is present and is related to conda
    ```
    ls /usr/bin/activate
    cat /usr/bin/activate
    ````
    Output:
    ```
    #!/usr/bin/python3
    # -*- coding: utf-8 -*-
    import sys
    # Before any more imports, leave cwd out of sys.path for internal 'conda shell.*' commands.
    # see https://github.com/conda/conda/issues/6549
    if len(sys.argv) > 1 and sys.argv[1].startswith('shell.') and sys.path and sys.path[0] == '':
        # The standard first entry in sys.path is an empty string,
        # and os.path.abspath('') expands to os.getcwd().
        del sys.path[0]
    
    if __name__ == '__main__':
        from conda.cli import main
        sys.exit(main())
    ```
6. Try to launch Thonny again, it should fail
    ```
    thonny
    ```
    Output:
    ```
    Traceback (most recent call last):
      File "/usr/bin/thonny", line 8, in <module>
        sys.exit(launch())
                 ^^^^^^^^
      File "/usr/lib/python3.11/site-packages/thonny/__init__.py", line 234, in launch
        prepare_thonny_user_dir()
      File "/usr/lib/python3.11/site-packages/thonny/__init__.py", line 280, in prepare_thonny_user_dir
        os.makedirs(THONNY_USER_DIR, mode=0o700, exist_ok=True)
      File "<frozen os>", line 225, in makedirs
    PermissionError: [Errno 13] Permission denied: '/usr/.thonny'
    ```
7. Delete /usr/bin/activate
    ```
    sudo rm /usr/bin/activate
    ```
8. Queue [ocean breeze sounds](https://youtu.be/vPhg6sc1Mk4) and launch Thonny successfully
    ```
    thonny
    ```
    Output:
    ```
    13:48:38.543 INFO    thonny: Thonny version: 4.0.2
    13:48:38.543 INFO    thonny: cwd: /usr/bin
    13:48:38.543 INFO    thonny: original argv: ['/usr/bin/python3', '-sP', '/usr/bin/thonny']
    13:48:38.543 INFO    thonny: sys.executable: /usr/bin/python3
    13:48:38.543 INFO    thonny: sys.argv: ['/usr/bin/thonny']
    13:48:38.543 INFO    thonny: sys.path: ['/usr/lib64/python311.zip', '/usr/lib64/python3.11', '/usr/lib64/python3.11/lib-dynload', '/usr/lib64/python3.11/site-packages', '/usr/lib/python3.11/site-packages']
    13:48:38.543 INFO    thonny: sys.flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=1, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0, dev_mode=False, utf8_mode=0, warn_default_encoding=0, safe_path=True, int_max_str_digits=-1)
    ```

## Thank you!

Thanks to @aivarannamaa, the community and all the contributors for this great tool. It's my go to suggestion for newbies, and my personal choice for micropython development on microcontrollers. The ease of getting started, as well as the integrated WebREPL are really top notch.

**Comment by scottfp** [comment]
As an aside, [`is_virtual_environment()`](https://github.com/thonny/thonny/blob/v4.1.4/thonny/common.py#L789-L793) may not be that useful of a check overall. I don't know the history of this, and I don't think I have enough free time to dig into it, but according to [How venvs work](https://docs.python.org/3/library/venv.html#how-venvs-work), comparing prefixes should be all that's required to detect a venv.

**Comment by aivarannamaa** [comment]
Thanks! I now tweaked and merged your PR.

> As an aside, [`is_virtual_environment()`](https://github.com/thonny/thonny/blob/v4.1.4/thonny/common.py#L789-L793) may not be that useful of a check overall. I don't know the history of this, and I don't think I have enough free time to dig into it, but according to [How venvs work](https://docs.python.org/3/library/venv.html#how-venvs-work), comparing prefixes should be all that's required to detect a venv.

Comparing prefixes may be good enough for venv-s, but that helper function is also supposed to cover virtualenv-s, which used different layout in different versions.
