### ISSUE TITLE
pico w micropython - running machine.bootloader() causes error loop

### ISSUE THREAD

**Issue by ctimmer** [thonny/thonny#3116]
When manually loading new firmware, the following shell command line is run:
`>>> machine.bootloader ()`

Thonny gets into an error loop (trying to connect?) that can only be stopped by shutting down Thonny.

Thonny: 4.0.1
Micropython:
`MicroPython v1.22.1 on 2024-01-05; Raspberry Pi Pico W with RP2040`

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please try the newest Thonny version! I am not able to reproduce it with Thonny 4.1.4 on macOS. Which OS are you using?

**Comment by ctimmer** [comment]
Thonny 4.1.4 has fixed the problem on bookworm.
Curt

**Comment by aivarannamaa** [comment]
Great!
