### ISSUE TITLE
Please put "Support Pandas" next to "Support Ukraine"

### ISSUE THREAD

**Issue by webdeb** [thonny/thonny#3122]
There is an existential threat to panda bears, and because Thonny offers a platform to strengten political and social engagement, I think this is a good case which a lot of users will welcome.

Just add a small Panda Icon and put this link into the button:
https://wwf.panda.org/discover/knowledge_hub/endangered_species/giant_panda/whatyoucando/

WWF press and marketing department also likes this initiative.

Thank you!

**Comment by webdeb** [comment]
Also we should rename the software into **PoliThonny**

**Comment by aivarannamaa** [comment]
Answered under #3123.
