### ISSUE TITLE
Ukraine flag in software is a No Goal by the FOSS CoC

### ISSUE THREAD

**Issue by webdeb** [thonny/thonny#3123]
If you don't remove the Ukraine flag, you just don't respect the Free and Open Source Code of Conduct.
https://hub.fosstodon.org/coc/

Would you be fine when your phone would suddenly start to tell you a political message, when you look at it?
This is a no-go. Just keep your political views out of software, it sucks!

**Comment by aivarannamaa** [comment]
This kind of arrogant trolling (including #3122, https://github.com/thonny/thonny/issues/2967#issuecomment-1961827183 and https://github.com/thonny/thonny/issues/3010#issuecomment-1961823804) won't help you, especially in the world of open source software.

**Comment by webdeb** [comment]
You are an arrogant troll, you abuse your repository superpower to provide your own political opinions, which do not belong into software per-se.
