### ISSUE TITLE
thonny does not support 3.12.2

### ISSUE THREAD

**Issue by angelfish0808** [thonny/thonny#3127]
When I install thonny with pip, when I click on the thonny program, there is always no response. When I use python -m thonny, ModuleNotFoundError: No module named 'tkinter' is always displayed.

**Comment by aivarannamaa** [comment]
I assume you are using Linux. In this case you need to install tkinter. Depending on the distro the required package may be called `python3-tk`, `python3-tkinter` or (for Arch) just `tk`.

**Comment by angelfish0808** [comment]
@aivarannamaa I have found the reason. It is because I installed the embedded version of python and it lacks the tkinter library. I just paste the tkinter related files from the regular version of python into it.
