### ISSUE TITLE
Support ukraine button

### ISSUE THREAD

**Issue by Matvey00OO** [thonny/thonny#3128]
DELETE THIS SHIT FROM WIKI, MAIN PAGE AND PROGRAN(BUTTON)!!
GLORY TO RUSSIA!

**Comment by vpnpro** [comment]
If they don’t respond, then there will be complaints to GitHub, and to the GNU/Linux community in general, to remove this software from the packages altogether

**Comment by aivarannamaa** [comment]
Can't see any glory from where I stand.

The response is "no".
