### ISSUE TITLE
Feature: vscode base keyboard layout

### ISSUE THREAD

**Issue by amaxcz** [thonny/thonny#3133]
Could you please add option to use some std hotkeys from vscode?

Comment line: ctrl + /
Cut or Delete line: Ctrl + x

**Comment by mathias-ted** [comment]
To comment out line,highlight the code or text, then press ctrl + 3.

**Comment by amaxcz** [comment]
isnt acceptible and isnt comfortable. almost all python web editors and  vscode uses ctrl+/ and ctrl+x
so its hard to use ctrl+3

**Comment by aivarannamaa** [comment]
I have plans for implementing customs shortcuts (#306), then everyone can assign their favourite shortcuts to commands.
