### ISSUE TITLE
error in installing dlib eventhough I have an updated python and I already install cmake. I am using thonny in raspberry pi 4 and on my windows 11. Both are not working

### ISSUE THREAD

**Issue by mntnnc3058** [thonny/thonny#3134]
![Screenshot 2024-03-12 201047](https://github.com/thonny/thonny/assets/134205684/70f5b5c4-5e25-4b3e-8563-886ee2142518)
It is showing this kind of error when Im installing dlib. I already installed the cmake and I have updated python verision.

**Comment by aivarannamaa** [comment]
dlib seems to be written in C++. Are you sure you have all the required components in place for building the library from source?

**Comment by mntnnc3058** [comment]
Hello @aivarannamaa! I think yes I already have all required components. But just incase, may I know all required components for me to check, thank you!

**Comment by aivarannamaa** [comment]
I've never used dlib. I guess you should ask in a dlib forum. I'm willing to investigate, if you are able to install dlib outside of Thonny but not with Thonny's package manager.
