### ISSUE TITLE
WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### ISSUE THREAD

**Issue by DanHuntlyCollege** [thonny/thonny#3139]
Still have this issue with Thonny 4.1.4 
Mac OS Sonoma
Updated to Python 13.12.1 but I think waiting for Thonny V5.0?
How is that coming along? Other issue logs pointed to a Jan / Feb 2024 release, but they have been closed.
Thanks, Dan

**Comment by aivarannamaa** [comment]
According to my tests, this warning doesn't show up in Python 3.12.2

**Comment by DanHuntlyCollege** [comment]
Thanks for replying Annamaa! So if I update python, Thonny uses that in the background, and will fix the issue...? I very much appreciate your quick response! Wonderful work, and this great app for my students.Best regards, DanOn 17/03/2024, at 11:18 pm, Aivar Annamaa ***@***.***> wrote:﻿
According to my tests, this warning doesn't show up in Python 3.12.2

**Comment by DanHuntlyCollege** [comment]
Hi there Aivar (sorry got you name wrong... )
I have had a look at how I can upgrade Python, outside of Thonny, and gave
this a try.
I also had a look at all the Thonny versions to see if any are bundled with
python 3.12.2, but they are all older versions and come with just python
3.10.
Is there a way to make Thonny use the version of Python, or is there a beta
of thonny with the new version bundled?

Thanks for your help, Dan Howard


# Gui Learning Program
# import the Gui code library we want to use
from tkinter import *

# this code creates a first window. The 'mainloop' part stops the program
from ending

# Function for the Quit button
def quit():
    main_window.destroy()

def hello():
    print('Hello')

#function to use the main window to add a button
def main():
    main_window = Tk()
    Button(main_window, text='Quit',command=quit) .grid()
    Button(main_window, text='Enter Data', command=hello) .grid()
    main_window.mainloop()

# run the main window function
main()

On Mon, 18 Mar 2024 at 06:37, Dan Howard ***@***.***>
wrote:

> Thanks for replying Annamaa!
> So if I update python, Thonny uses that in the background, and will fix
> the issue...? I very much appreciate your quick response! Wonderful work,
> and this great app for my students.
> Best regards, Dan
>
> On 17/03/2024, at 11:18 pm, Aivar Annamaa ***@***.***>
> wrote:
>
> ﻿
>
> According to my tests, this warning doesn't show up in Python 3.12.2
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_thonny_thonny_issues_3139-23issuecomment-2D2002394810&d=DwMCaQ&c=_Zm2Kb9yJrso4r0-N78Ezl-a6DfgMbIISn5tZXXqWk4&r=dA6cVfbEBZIsqsqoz538-0swhS4LC1xoIQzgHmCd38E&m=Hkytp7WSf03hHAMN0DELCMGyfB1YpFFHaIj1-GdpziEiqOPa97Ilmzb0ZCcybed0&s=xtJwXYiP2C30fl_3TXcRk4jg_MkOYWGZamQ9SUGPloQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BFPZG4TUX447BAE3NZZBITTYYVUY7AVCNFSM6AAAAABEYTISJ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBSGM4TIOBRGA&d=DwMCaQ&c=_Zm2Kb9yJrso4r0-N78Ezl-a6DfgMbIISn5tZXXqWk4&r=dA6cVfbEBZIsqsqoz538-0swhS4LC1xoIQzgHmCd38E&m=Hkytp7WSf03hHAMN0DELCMGyfB1YpFFHaIj1-GdpziEiqOPa97Ilmzb0ZCcybed0&s=slV3xlQEKD1Rg3cI-8HqBoZSnBcClinHWq-eCHrKNzI&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
>

-- 
Dan Howard

e: ***@***.***

**Comment by aivarannamaa** [comment]
> Is there a way to make Thonny use the version of Python, or is there a beta of thonny with the new version bundled?

The beta is still in works, but you can install Pytho 3.12 separately and make Thonny use it (Tools => Options => Interpreter).

Please note that the warning you are talking about is just a warning. It is totally OK to simply ignore it for now.

**Comment by DanHuntlyCollege** [comment]
Thank you! On 24/03/2024, at 7:42 pm, Aivar Annamaa ***@***.***> wrote:﻿

Is there a way to make Thonny use the version of Python, or is there a beta of thonny with the new version bundled?

The beta is still in works, but you can install Pytho 3.12 separately and make Thonny use it (Tools => Options => Interpreter).
Please note that the warning you are talking about is just a warning. It is totally OK to simply ignore it for now.
