### ISSUE TITLE
建议增加的功能

### ISSUE THREAD

**Issue by Ioubipgxe** [thonny/thonny#3165]
I'm a Chinese user of Thonny IDE, it's the best Python IDE I've ever used. 

However, I've found that this integrated development environment doesn't support the code folding feature, which can bring great convenience to programmers. I hope the developers can add the code folding function to it.
Additionally, there is a typo in the Chinese interface of the "Interpreter Configuration" section. It mistakenly wrote "程序奔溃" instead of "程序崩溃". I hope this can be corrected.
I'll be appreciate if you can take my advice into consideration. 
Thanks!

**Comment by aivarannamaa** [comment]
Thank you for the suggestion! Code folding is already in the TODO list (#1090).

Regarding translation mistakes -- please go to https://poeditor.com/join/project/Gh188fdYH6 and fix it yourself.
