### ISSUE TITLE
thonny not opening file explorer (nautilus) on ubuntu 24.04

### ISSUE THREAD

**Issue by Giuseppe7887** [thonny/thonny#3173]
Zenity 4.0.1 not opening file selection on Ubuntu 24.04 because of --class and --name args, i created i fork "zenit-args" tò fix it

**Comment by aivarannamaa** [comment]
Commented under #3176

**Comment by sanchosk** [comment]
Same on Debian with 4.0.1 Thonny.

**Comment by sanchosk** [comment]
Temporary fix:
commented out line 2100
```
        # args = ["zenity", "--name=Thonny", "--class=Thonny"] + args
```
and instead inserted one below
```
        # args = ["zenity", "--name=Thonny", "--class=Thonny"] + args
        args = ["zenity"] + args
```

Works like that.

**Comment by Giuseppe7887** [comment]
They fixed It, install It from thonny website, not from apt
