### ISSUE TITLE
A crash destroys Thonny logs

### ISSUE THREAD

**Issue by Meogwyn** [thonny/thonny#3182]
Currently Thonny only saves log files upon closing gracefully, which means that a crash has the ability to destroy those logs completely. I have recently experienced such a log-destroying crash when using Thonny to complete an exam. 

I think this could be mitigated by periodically writing to the log file over the course of Thonny's operation, so that in the event of a crash, one could at least partially recover the logs.

Steps to reproduce:

1. Launch Thonny with logging enabled
2. Cause Thonny to close non-gracefully

**Comment by aivarannamaa** [comment]
Thank you for the report!

Thonny manages 2 types of logs -- diagnostic logs and logs of user actions. I assume you are talking about the latter. In Thonny 5 user action logging will be completely reworked (#2999) and the saving occurs just like you described.
