### ISSUE TITLE
!!!Remove support for nazis UA!!!!

### ISSUE THREAD

**Issue by vpnpro** [thonny/thonny#3192]

**Comment by coffandro** [comment]
What?

**Comment by aivarannamaa** [comment]
@vpnpro, it looks like we have different understanding of which country is currently acting like Nazi Germany.

**Comment by zeleniychupakeps** [comment]
Русский?

**Comment by zeleniychupakeps** [comment]
by Nazis he meant Ukraine

**Comment by vpnpro** [comment]
> @vpnproПохоже, у нас разное понимание того, какая страна сейчас действует как нацистская Германия.
Похоже ты не знаешь что такое UA,где она находиться,и кто за нее воюет.
А если ты такой патриот,то шел бы на ВОЙНУ,и не здесь свою поддержку объявлял бы,а там.

**Comment by coffandro** [comment]
L bozo

**Comment by rosesonfire** [comment]
@aivarannamaa do you fear your country will be invaded next by Russian, and is that why you put up that icon in the app?
