### ISSUE TITLE
Thonny OSError 84

### ISSUE THREAD

**Issue by pethyPesche** [thonny/thonny#3196]
On ubuntu 22.04.4 in Thonny 3.3.14 an connect Raso Pico W report in Thonny: Error 84 Could not write next block after having written 0 bytes to /t ERROR thonny.backend: PROBLEM WITH THONNYS'S BACK-END , Error Problem with a management command To do something??? Thanks 16.05.2024 Peter

**Comment by aivarannamaa** [comment]
Do you have free space left on your device?

**Comment by pethyPesche** [comment]
Thank you. I will check it. Be away until 27.05.2024
#
