### ISSUE TITLE
Pasting bad Unicode data to editor kills the process

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#32]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/32) by me.**

----------------------------------------

and Tk.report_callback_exception is not called

```
Traceback (most recent call last):
  File "D:\workspaces\python_stuff\thonny\src\launch.py", line 12, in <module>
    main.Thonny().mainloop()    
  File "C:\Python34\lib\tkinter\__init__.py", line 1069, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 50: invalid continuation byte

```

**Comment by Ivoz** [comment]
Hi @aivarannamaa maybe I found a way to replicate this :D

I went to https://rushter.com/blog/python-strings-and-memory/ and tried to paste exactly '🐍' .

Pasting just the snake does nothing. Pasting the two quotes with the snake inside raises this error. Both shell and file editor. Thonny 3.2.1 on Windows

**Comment by aivarannamaa** [comment]
Thank you! 

I guess I need to add a guard to paste and load operations and present a warning/confirmation dialog when unsupported characters are found in the input.

**Comment by aivarannamaa** [comment]
Needs to be tested with Python 3.7.6. Hopefully it got fixed by https://github.com/python/cpython/pull/16581

**Comment by aivarannamaa** [comment]
It still doesn't work in macOS catalina with official Python 3.7.6 (using Tk 8.6.8). Probably need to wait until Python gets built with newer Tk on macOS.

**Comment by kcarnold** [comment]
Another, probably related, Unicode bug: paste any emoji (e.g., 💬) into an empty editor. My editor then looks like 

💬💬

It gets worse: go to the beginning of the line and press Delete. Thonny hangs.

My guess is that the rebuild will fix this one too.

**Comment by aivarannamaa** [comment]
Unfortunately there is nothing I can do about it. Let's hope next Tk version to be included in Python fixes this.

**Comment by lurch** [comment]
> Unfortunately there is nothing I can do about it.

Understood, but in case it's useful, here's another way to reproduce this:
1. Use Thonny's manage-plugins window to install `black`
1. In the Shell window, type `!black myfile.py`
1. Boom, Thonny crashes with
```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  10827
  Current serial number in output stream:  10837
```

**Comment by lurch** [comment]
As a workaround I wondered if there was a way to turn off the emojis in the `black` output, but it seems that's something the `black` developers are stubbornly resistant too :confounded: https://github.com/psf/black/pull/1270

**Comment by aivarannamaa** [comment]
I hope they will bundle Tk 8.6.10 with Python 3.9. If this doesn't help, then I have to preprocess the output before reaching the shell.

**Comment by aivarannamaa** [comment]
Closing, as things are much better with Tcl/Tk 8.6.12 (to be bundled with Thonny 4.0)
