### ISSUE TITLE
Deleting within Thonny Shell

### ISSUE THREAD

**Issue by zino113** [thonny/thonny#3211]
Have tried package 'unprint' 
(https://pypi.org/project/unprint/) .

Works fine in 
- Windows Command Prompt and
- Windows Power Shell .

Unfortunately, same script doesn't properly work in Thonny shell.

This the code:
```
# Testing the 'unprint' package

from unprint import unprint as rubout

print('this line is fine ...');
print('this line looks buggy -- oops ...')
rubout(1,delay=3)
print('no sweat -- it\'s erased.')
```
'unprint' seems to be recognized alright (as the delay does work as expected).
But no text lines are deleted.

Thanks.

**Comment by aivarannamaa** [comment]
Sorry for the late reply.

Unfortunately, Thonny's Shell is not a complete terminal emulator, so unprint can not work. The work-around is to use "Run => Run current script in terminal".
