### ISSUE TITLE
Calliope mini V3 does not connect

### ISSUE THREAD

**Issue by StMaHa** [thonny/thonny#3219]
thonny 5.0.0b1-dev (master branch) shell shows:

```
INTERNAL ERROR, got '' instead of 'OK'
---
Traceback (most recent call last):
  File "D:\workspace\thonny\thonny\plugins\micropython\bare_metal_backend.py", line 31, in <module>
    from thonny.plugins.micropython.connection import MicroPythonConnection
  File "D:\workspace\thonny\thonny\plugins\micropython\__init__.py", line 5, in <module>
    from thonny.plugins.micropython.mp_front import (
  File "D:\workspace\thonny\thonny\plugins\micropython\mp_front.py", line 11, in <module>
    from packaging.utils import canonicalize_name
ModuleNotFoundError: No module named 'packaging.utils'

Process ended with exit code 1.
```

How I setup and start thonny from master branch:
---
git clone https://github.com/thonny/thonny.git
cd thonny
pip3 install -r .\requirements.txt
set PYTHONPATH=D:\workspace\thonny
python -m thonny

Thonny options -> Interpreter shows "MicroPython (generic)" and Port "Calliope mini V3 CMSIS-DAP @ COM21"
Always returns to "MicroPython (generic)" after switching to "MicroPython (Calliope mini)"

**Comment by aivarannamaa** [comment]
Sorry for the late reply. It turns out package `packaging` was accidentally left out from the requirements.txt. This is fixed by now.
