### ISSUE TITLE
Thonny Open, Save, Save To ,... don't work

### ISSUE THREAD

**Issue by RSMs007** [thonny/thonny#3241]
Hi I'm use Ubuntu 24.04 LTS with Thonny 4.0.1

When creating a program in Thonny, I cannot save it!!
Same for Save To, Save, Open, .... buttons
At least those buttons are lit.

Thanks

**Comment by aivarannamaa** [comment]
Sorry for the late reply!

It can be that the file dialog has gone behind Thonny window. Try force-closing Thonny and then switching off Zenity dialogs in Tools => Options => General

**Comment by digizun** [comment]
Yes turning off Zenity worked for me.
Otherwise the error reads: 
WARNING thonny.ui_utils: Zenity returned code 255 and stderr  ...
Ubunty 24.04 currently uses zenity/noble,now 4.0.1-1build3 and thonny/noble,noble,now 4.0.1-1 
Maybe one of these needs to be upgraded
