### ISSUE TITLE
Annoyance -> Line ??? : Bad indentation. Found 1 spaces, expected 4

### ISSUE THREAD

**Issue by AnonymouZEE** [thonny/thonny#3245]
2024.07.08
dudes...
	ERROR -> Line ??? : Bad indentation. Found 1 spaces, expected 4
	It looks like the unexpected number of indentation tabulations or spaces has been found.

this error should be disabled when 
Tools->Options->Indent with tab... 
is selected

or provide a 
Tools->Options->Indent spaces = ?
(this will also "kill another bird")
so we can set it to 1 (or set it auto)
when Tools->Options->Indent with tab... is checked

PS: no animals were harmed during this comment...

ZEE

**Comment by aivarannamaa** [comment]
Preferred indent width can be set in the upcoming Thonny 5
