### ISSUE TITLE
Can't upgrade or uninstall packages on Thonny 4.1.4

### ISSUE THREAD

**Issue by Spaghettatron** [thonny/thonny#3247]
Using Thonny 4.1.4 64bit on Windows 10, I can't upgrade or uninstall any plugins or packages.

![image](https://github.com/thonny/thonny/assets/68418332/0591700e-2fa4-4ac3-9121-fdfc19627ced)

**Comment by Hermann12** [comment]
> Using Thonny 4.1.4 64bit on Windows 10, I can't upgrade or uninstall any plugins or packages.
> 
> 
> 
> ![image](https://github.com/thonny/thonny/assets/68418332/0591700e-2fa4-4ac3-9121-fdfc19627ced)

You can go to __Tools__ | __Open system shell..__ than

`$ pip install --upgrade <package-name>
$ pip install -U <package-name>`

or 

`$ pip uninstall <package-name>`

**Comment by aivarannamaa** [comment]
Package management will be greatly refactored in Thonny 5. Please reopen if the problem remains.
