### ISSUE TITLE
Compile error in Thonny with Inventr Python example 1

### ISSUE THREAD

**Issue by ChipOfM** [thonny/thonny#3252]
import machine
import time

led = machine.Pin('LED', machine.Pin.OUT)

while True:
    led.value(True)
    time.sleep(1)
    led.value(False)
    time.sleep(1)

ModuleNotFoundError: No module named 'machine'
cp_back.py, line 353
No specific suggestions for this error (yet).
Let Thonny developers know

**Comment by selmen2004** [comment]
You are running local Python, connect your card , choose micropython backend and retry

**Comment by ChipOfM** [comment]
Will try that. Thanks!
