### ISSUE TITLE
Cannot determine SOC peripheral base address (ISSUE/ERROR)

### ISSUE THREAD

**Issue by Haswanth3714** [thonny/thonny#3256]
raspberry pi 5 thonny Basic LED python code (which is used in raspberry pi 4) so i give same code for raspberry pi 5 
code:

```python
import RPi.GPIO as AA
import time
AA.setwarnings(False)
AA.setmode(AA.BCM)
AA.setup(14,AA.OUT)
while True:
    AA.output(14,True)
    time.sleep(2)
    AA.output(14,False)
    time.sleep(2)
```

then it is showing ""Cannot determine SOC peripheral base address""

i have used another code which is i got from google search for raspberry pi 5
code:

```python
import gpiod
import time
LED_PIN = 14
chip = gpiod.Chip('gpiochip4')
led_line = chip.get_line(LED_PIN)
led_line.request(consumer="LED", type=gpiod.LINE_REQ_DIR_OUT)
try:
   while True:
       led_line.set_value(1)
       time.sleep(1)
       led_line.set_value(0)
       time.sleep(1)
finally:
   led_line.release()
```

this code has no issue at all thonny showing that code is running, but raspberry pi not working as code and not sending any output sessions

plz kindly tell me a solution for it.

**Comment by aivarannamaa** [comment]
I believe this problem is not specific to Thonny. You have better chance of getting useful replies in a MicroPython or RPi forum.
