### ISSUE TITLE
MPY CALCULATING TERMINAL PROBLEM IN THONNY'S BACK-END: Exception while handling 'Run' (thonny.plugins.micropython.mp_back.ProtocolError: Could not enter raw prompt).

### ISSUE THREAD

**Issue by FBDev64** [thonny/thonny#3257]
## Describe the bug
When I execute my code, it exits with a bug
![Shot-2024-07-22-193906](https://github.com/user-attachments/assets/87e21e37-c5fa-4a2c-ab00-7965518df5e0)

## Priority
P2 Critical
[Reference - Google Issue tracker priority levels](https://developers.google.com/issue-tracker/concepts/issues#priority)

## Desktop
 - OS: Arch Linux

## Additional context
I was using a Rapsberry PI Pico, and [this](https://gist.github.com/FBDev64/ecd0b115ca1aed45feace2d9ebe35204) is my code.
I think line 42 is faulty, because when I change the >>> it doesn't bug.

**Comment by aivarannamaa** [comment]
Sorry for the late reply! When Thonny sees `>>> `, it assumes MicroPython code has completed. Better use some other prompt in your code.
