### ISSUE TITLE
Not respecting "Interrupt working program on connect"

### ISSUE THREAD

**Issue by dcmcshan** [thonny/thonny#3261]
Seems to always soft reset on connect even when checkbox is unchecked...

Talking to ESP32-S3 USB CDC on MacOS.

**Comment by Hermann12** [comment]
Could be operating system problem too.

**Comment by aivarannamaa** [comment]
Some devices disconnect when they detect new connection. Thonny 5.0 will allow you to play with DTR and RTS values and this may help.

**Comment by dcmcshan** [comment]
I do not have DTR/RTS on this system - it's connected directly to the ESP32S3's USB port.
