### ISSUE TITLE
Adding a simple "view in file system" button

### ISSUE THREAD

**Issue by Futuray-pgm** [thonny/thonny#3265]
Just a new button next to the already-existing "_save_" button to switch quickly between Thonny and the folder that contains the current file.

**Comment by aivarannamaa** [comment]
Thanks for the suggestion, but I think not many users need such button, so I won't add this.

As alternative, you can open Thonny's file browser (View => Files) and use its hamburger menu to open system file browser:

<img width="483" alt="image" src="https://github.com/user-attachments/assets/fa10cb75-23a6-45d1-8371-ee110c4d92be">
