### ISSUE TITLE
Thonny won't detect some Picos on COM3: "port not found"

### ISSUE THREAD

**Issue by Noram-27** [thonny/thonny#3269]
I have 3 Rasberry Pi Picos and only 1 connects to Thonny on my PC. The others give the error message "Unable to connect to COM3: port not found".  They all connect to Thonny on my laptop.
Both laptop and PC run the latest Windows 10 and the latest Thonny.  
I have tried all USB ports and cables.  _Once_ I made them all connect (separately) but that has not happened again :-(
There are a mouse, keyboard and WiFi adapter plugged into the PC's USB ports.  They were all in use when the Picos all connected.
Perplexing.

**Comment by aivarannamaa** [comment]
I think you could get better answers in a MicroPython or RPi forum.
