### ISSUE TITLE
"Run current script" thing stays popped up even after taking cursor off

### ISSUE THREAD

**Issue by asherevan** [thonny/thonny#3291]
After you run a script by pressing "Run current script", and it saves, the popup thing that shows what the button does, stays, even after I take the mouse cursor off of the button, or even go to another window!

I am on Ubuntu 24.04.

![image](https://github.com/user-attachments/assets/74fc63af-8a6a-47ee-ac61-7ecbc41578fa)

**Comment by aivarannamaa** [comment]
I suspect you have older Thonny version. This should be fixed in 4.1.4

**Comment by asherevan** [comment]
What version of python does 4.1.4 require?

**Comment by aivarannamaa** [comment]
Thonny 4.1.4 requires at least Python 3.8.

**Comment by asherevan** [comment]
Thanks.

I was installing it from the apt repositories so it was a old version. I
will try installing it differently now.
