### ISSUE TITLE
nbre primaire

### ISSUE THREAD

**Issue by rouma228** [thonny/thonny#3295]
from PyQt5.uic import loadUi
from PyQt5.QtWidgets import QApplication
from numpy import*
def play():
    ch1=fen.nb1.text()
    ch2=fen.nb2.text()
    if verif(ch1,ch2)==False:
        fen.res.setText("veuillez respecter: 10<=N<=50 et N<M<=200")
    else:
        N=int(ch1)
        M=int(ch2)
        res=chercher(N,M)
        fen.res.setText(res)
def chercher(N,M):
    res=""
    for i in range(N,M+1):
        if verifier(i):
            res=res+str(i)+"-"
    res=res[:len(res)-1]
    return res
def verifier(p):
    n=0
    t=array([int()]*p)
    for i in range(1,p//2+1):
        if p%i==0:
            t[n]=i
            n+=1
    test=False
    i=0
    while test==False and i<n:
        test=premier(t[i]) and divide(t[i],p)
        i+=1
    return test
def divide(x,p):
    test=True
    while test and p!=0:
        p=p//x
        test=p%x==0
    return test

def premier(x):
    test=True
    if x==1:
        test=False
    elif x>3:
        k=2
        while test and k<=x//2:
            if x%k==0:
                test=False
            else:
                k+=1
        return test
    
def verif(ch1,ch2):
    ok=len(ch1)!=0 and len(ch2)!=0 and ch1.isdecimal() and ch2.isdecimal() and 10<=int(ch1)<=50 and int(ch1)<int(ch2)<=200
    return ok

app=QApplication([])
fen=loadUi("InterfacePrimaire.ui")
fen.show()
fen.bt.clicked.connect(play)
app.exec_()

**Comment by aivarannamaa** [comment]
Don't understand the problem
