### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by taqi59a** [thonny/thonny#3308]
Thonny is crashing on Mac after new update in Mac OS

**Comment by aivarannamaa** [comment]
Duplicate of #3283. Please try https://github.com/thonny/thonny/releases/download/v4.1.6/thonny-4.1.6.pkg

**Comment by impenz** [comment]
> Duplicate of #3283. Please try https://github.com/thonny/thonny/releases/download/v4.1.6/thonny-4.1.6.pkg

it works. Thanks.
