### ISSUE TITLE
version 4.1.4 32 bit not started under 32bit windows 7

### ISSUE THREAD

**Issue by hurae** [thonny/thonny#3309]
<img width="335" alt="截屏2024-09-10 15 29 06" src="https://github.com/user-attachments/assets/d80dc131-0b12-461e-aec4-464ab49ca5e6">

As shown in the screen shot, there is a "Invalid Argument" error shown of dll loading procedure.

My Windows version: Windows 7 Enterprise Service Pack 1 x86.

**Comment by aivarannamaa** [comment]
Sorry, but you are out of luck with this one, unless another Thonny user can help you. I don't have time for investigating Windows 7 issues anymore.
