### ISSUE TITLE
Open (or save) dialog does not work

### ISSUE THREAD

**Issue by asherevan** [thonny/thonny#3323]
Whenever I try to save or open a file to or from my computer, nothing happens.
When I ran it from the command line I got this message:

`
WARNING thonny.ui_utils: Zenity returned code 255 and stderr 'This option is not available. Please see --help for all possible usages.\n'
`

I am on Ubuntu 24

**Comment by aivarannamaa** [comment]
Sorry for the late reply!

The work-around is to turn off Zenity dialogs in Tools => Options => General. Upgrading to Thonny 4.1.4 should help as well

**Comment by asherevan** [comment]
Thank you. It worked.
