### ISSUE TITLE
'editor_autocomplete' error

### ISSUE THREAD

**Issue by AuntArctic** [thonny/thonny#3328]
Encountered this whilst attempting to run some exercise code in Python (beginner level). Code refused to run citing 'editor_autocomplete' EOFError:Ran out of input. Backend log attached.
[backend.log](https://github.com/user-attachments/files/17131938/backend.log)

Running Thonny 4.1.4 (Python 3.10.11) on Windows 11.

**Comment by aivarannamaa** [comment]
Seems to be a duplicate of #3321
