### ISSUE TITLE
11

### ISSUE THREAD

**Issue by P-Zhu** [thonny/thonny#3344]

**Comment by aivarannamaa** [comment]
?

**Comment by P-Zhu** [comment]
如何打包的 可执行安装程序 

https://github.com/thonny/thonny/releases/download/v4.1.6/thonny-4.1.6.exe

**Comment by P-Zhu** [comment]
我使用 原有的打包脚本 重新制作生成thonny-5.0.0a2-windows-portable.zip，结果  生成的程序界面并没有变化 我删除 或修改的代码内容 没有生效，我已经删除了的代码，仍然被使用 了，生成了对应的功能按键（我已经删除的代码仍然在生效）。
D:\Git\thonny-4.1.6\packaging\windows\create_installer.bat

**Comment by P-Zhu** [comment]
ThonnyRunner310\x64\Release\thonny.exe  我 在自己的电脑上如何 制作
