### ISSUE TITLE
Still missing ESP32-C6 Support?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [thonny/thonny#3363]
Still missing ESP32-C6 Support?  Version 4.1.6... no support for flashing ESP32-C6?

**Comment by maxacode** [comment]
@Jibun-no-Kage  Any updates on this, you figured it out yet?

**Comment by aivarannamaa** [comment]
Fixed in https://github.com/thonny/thonny/releases/tag/v4.1.7
