### ISSUE TITLE
Search Results Not showing in package manger

### ISSUE THREAD

**Issue by turkeycat666** [thonny/thonny#3396]
Fresh install of thonny on a fresh install of windows 10 pro and thonnys package manager wont show any search results, even when searching for known python packages like numpy.
![image](https://github.com/user-attachments/assets/2fc78562-09e0-4cfa-95f2-8c6a3f62cbfe)

**Comment by matteius** [comment]
I am having this issue and need to ship a board out today with my package https://pypi.org/project/growmax/ but ran into this issue and not sure how to proceed.

**Comment by aivarannamaa** [comment]
Please see #3401

**Comment by aivarannamaa** [comment]
Please try https://github.com/thonny/thonny/releases/tag/v4.1.7
