### ISSUE TITLE
Manage Packages and Manage Plugins failing 

### ISSUE THREAD

**Issue by TomasJMurphy** [thonny/thonny#3400]
I can no longer add packages or plug ins as the search finds nothing. I tried reinstalling but it has not solved the problem.

**Comment by aivarannamaa** [comment]
Please see #3401

**Comment by aivarannamaa** [comment]
Please try https://github.com/thonny/thonny/releases/tag/v4.1.7

**Comment by TomasJMurphy** [comment]
Thank You, worked well.

**Comment by mblasee** [comment]
I updated my version to 4.1.7 and its still not working for me (win11)
![image](https://github.com/user-attachments/assets/6f425f20-d1fa-4eca-9c93-b1fe323aa838)
it just stays like this for indefinitely. Other packages are not working either. 
Is there any log or output I can attach for you?
