### ISSUE TITLE
Can't find packages on PyPI

### ISSUE THREAD

**Issue by jhggit** [thonny/thonny#3413]
Uninstalled and installed latest Thonny. Using Windows 10, Thonny 4.1.6.
Opened Manage Packages, searched "matplotlib", results were blank. Searched "numpy", results were blank.
![image](https://github.com/user-attachments/assets/65da6280-5f1e-45ff-9a9c-dbd731c75120)

**Comment by aivarannamaa** [comment]
Please try 4.1.7
