### ISSUE TITLE
Feel a bit lost

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#350]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/350) by Anonymous.**

----------------------------------------

Well, yet I've worked with Tcl/Tk, Ruby and Python in Apple OSX, and have managed GitHub, I feel a bit lost with what it's the Thonny sources…  I don't know where to start from.  Any reference?

**Comment by mMerlin** [comment]
This should be be put in the readme or wiki someplace.  Took quite a lot of digging before I found the needed detail.  About how to run directly from the repository for testing.

**Comment by aivarannamaa** [comment]
Agreed!

**Comment by aivarannamaa** [comment]
https://github.com/thonny/thonny/wiki/Running-from-the-source
