### ISSUE TITLE
Let Thonny detect when the user accidentally shadows library modules ...

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#384]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/384) by me.**

----------------------------------------

... by creating something like "random.py" or "turtle.py" in their current directory.

**Comment by aivarannamaa** [comment]
It should work better: see #1277, #1243

**Comment by kcarnold** [comment]
It looks like this catches some cases but might miss renames outside of Thonny, and requires that students pay attention to the Assistant. I just observed a package install failure due to someone naming a file `types.py`; the Assistant would not be available in that setting. (Perhaps Thonny should execute package installs in some neutral directory anyway, and/or remove the current directory from `sys.path` before doing so.)

What if `sys.path` simply put the current directory at the end? Running a module with a shadowing name would still succeed; import would fail but the Assistant would give a helpful message.

**Comment by aivarannamaa** [comment]
Thank you for the suggestion! Putting the current directory would be an easy solution and might work pretty well. The downside of this approach is that's not what Python normally does -- you don't get the lesson and may still get stuck when venturing outside of Thonny.

I've considered tweaking the import machinery, such that a warning gets printed when a module in stdlib or site-packages (or user site-packages) ends up importing something from currenct directory. I haven't investigated it yet, so I don't know its feasibility or performance penalty.

**Comment by aivarannamaa** [comment]
It now occurred to me that by the time I've tweaked the import machinery, big part of stdlib modules are loaded already, and during this time nothing would guard the interpreter against the trap-modules in current directory.

Maybe the cleanest approach is to start Python in [isolated mode](https://docs.python.org/3/using/cmdline.html#id2) and add current directory (and maybe user site-packages) to the end of `sys.path` later.

Calling `pip` could be definite done in isolated mode, so (unless I'm missing something) it should be easy to fix the install problem you mentioned.

**Comment by kcarnold** [comment]
You have amazingly detailed knowledge of Python!

In case it's helpful to anyone, here's a little script that checks if anything in the current directory tree shadows something importable outside of the current directory. Now that I look at it I should be using `importlib` to search for a module of that name, rather than just using the filename, but it served my purposes of a local audit:

```
import pathlib
import sys

cwd = pathlib.Path('.').resolve()

paths = [
    path for path in sys.path
    if pathlib.Path(path).resolve() != cwd]

importable_modules = {
    p.stem: p
    for d in paths[::-1] if d and d != '.'
    for p in pathlib.Path(d).glob("*.py")}

modules_in_srcdir = {
    p.stem: p
    for p in pathlib.Path('.').rglob('*.py')}

for collision in set(importable_modules.keys()).intersection(modules_in_srcdir.keys()):
    print(modules_in_srcdir[collision],
          "shadows",
          importable_modules[collision])
```

**Comment by aivarannamaa** [comment]
Here is a related case for CircuitPython: https://forum.micropython.org/viewtopic.php?p=59529

I feel that the most general solution would be to give warning for the situation, where at the beginning of the program, two locations of the `sys.path` contain module with the same name. The warning should go both to stderr and Assistant.

Can anyone think of a case when such a warning would be irrelevant?

**Comment by aivarannamaa** [comment]
Another related discussion https://github.com/microsoft/pylance-release/discussions/2619 and https://github.com/microsoft/pyright/pull/4132

A note to myself -- consider outputting a warning before starting the backend process. The backend interpreter may have different set of stdmodules compared to the frontend process, but there would be still a good overlap. Perhaps the frontend should only check its own stdlib vs working directory and the Assistant would make a more comprehensive check inside the backend process.

**Comment by aivarannamaa** [comment]
Thonny 4.1 will have two mechanisms for managing the mess with user modules shadowing library modules.

1. The back-end Python process gets started in an empty directory, which means Python and Thonny's back-end infrastructure can load all the modules they need without being threatened by the user modules. After this the current directory is changed to the desired working directory and Thonny investigates the working directory (or script directory when launching a script) to see if any of the user modules would have had shadowed any of the currently loaded library modules. If yes, then it prints a warning in the shell.
2. In order to detect shadowing of the library modules which are required by the user code, Thonny's back-end adds an audit hook, which notifies of each attempted import operation. If the module would be imported from current dir (or script dir) but is also available in a library dir, Thonny prints a warning. After this the import process continues, and the user code will likely end up with an error later. I'm hoping that when investigating the error, the user notices the warning.

The warnings for both cases can be turned off from Tools => Options => Run & Debug.
