### ISSUE TITLE
auto-complete

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#406]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/406) by Anonymous.**

----------------------------------------

Hi
after press ctrl+space give this error "could not import jedi"

Linux G41-S2 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
![error](https://ibb.co/kMuhOS)

**Comment by TravelTrader** [comment]
Same error for me.
I am using Ubuntu 18.04.
And I am using the default interpreter.
Just tried thonny the first day. No options changed.

Are there any solutions already?
