### ISSUE TITLE
NiceTracer won't step into decorated functions

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#492]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/492) by me.**

----------------------------------------

Example:

```
def string_required ( f ):
    def string_checked ( arg ):
        if type(arg) != str:
            raise ValueError(repr(arg) + "is not a string")
        return f(arg)
    return string_checked

@string_required          
def must_have_s (arg):
    print( len (arg), arg)
```

**Comment by Farcrada** [comment]
Does this issue include Thonny stopping the highlighting function from working when doing:
```
def charify(input: str, output: []) -> []:
    return [x for c in input]
    del output[0]
    return output
```
However, when I remove the argument definitions:
```
def charify(input, output) -> []:
    output = [x for c in input]
    del output[0]
    return output
```
Highlighting works again.

NOTE: With `highlighting` I mean show all occurrences of the variable/method/class. In this instance: putting the carrot on any `output` should highlight all other `output`.

**Comment by aivarannamaa** [comment]
I think these are not related, I created a separate issue #701

**Comment by aivarannamaa** [comment]
Seems to work in master
