### ISSUE TITLE
move dialog to the front...

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#532]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/532) by Jens Diemer (Bitbucket: [jedie](https://bitbucket.org/jedie)
 GitHub: [jedie](https://github.com/jedie)
).**

----------------------------------------

e.g.:

* open thonny
* maximize thonny window
* Open a dialog e.g.: "File/Open..."
* click on thonny main window

Now the "File/Open..." is behind the editor main window... And the main window feels like not to response :(

IMHO every click to the main window should bring a open dialog to the front.

**Comment by jdeisenberg** [comment]
Same problem, using Fedora 29, version 3.0.8

**Comment by aivarannamaa** [comment]
Duplicate of #488
