### ISSUE TITLE
Unable to install packages when behind proxy

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#535]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/535) by Aleksander Szczepanowski (Bitbucket: [alszczep](https://bitbucket.org/alszczep)
 ).**

----------------------------------------

Greetings,
I am new to thonny and python user however I met blocking me issue.
When I try to view packages/modules via GUI(Manages packages...) I get error as attached. ![2018-10-03 11-32-40.jpg](https://bitbucket.org/repo/gXnbod/images/2224175172-2018-10-03%2011-32-40.jpg)

It happens with every package which I try to open/view. Even if I will import new module via system shell, importing it program is unsuccessful. 

I am now using Thonny 3.0.0b6 however the same happend with 2.1.19 to 2.1.22.
I suppose it may be related to some specific Windows 7 settings manage by my employer. Is it possible to change the location of python environment to not use C:\ drive? Or what I can do with described issue?
Thank you in advance for help.

**Comment by rpi4iot** [comment]
about proxy for tools-->manage packages / manage plug-in
some comments(for windows version):

in case 
>>add a separate proxy configuration page to options dialog.
https://github.com/thonny/thonny/issues/535

https://github.com/thonny/thonny/issues/333
>>specify proxy settings in per-user pip.ini 
>>as described here: https://stackoverflow.com/a/22229387/261181


the pip.ini can be created in right path and updated according to this proxy confiugration
or 
pip_gui.py and "thonny\Scripts\pip.bat"  can use this proxy configuration 
to fetch packages info via urllib.request and install packages via "-m pip"


###############################################

```
###PIP GUI : python process -m pip ###
def _create_pip_process(self, args, stderr=subprocess.STDOUT):
    if "--disable-pip-version-check" not in args:
        args.append("--disable-pip-version-check")
    return self._create_python_process(["-m", "pip"] + **_["--proxy", "127.0.0.1:58109"]_** + args, stderr=stderr)
```

###############################################		
		
###PIP GUI : Find packages from PyPI via urllib.request###
```
from urllib.request import urlopen, urlretrieve

def _fetch_url_future(url, timeout=10):
    def load_url():
        with urlopen(url, timeout=timeout) as conn:
            return (conn, conn.read())
			
https://stackoverflow.com/questions/3168171/how-can-i-open-a-website-with-urllib-via-proxy-in-python

#!/usr/bin/env python3
import urllib.request

**proxy_support = urllib.request.ProxyHandler({'http' : 'http://user:pass@server:port', 
                                             'https': 'https://...'})
opener = urllib.request.build_opener(proxy_support)
urllib.request.install_opener(opener)**

urllib.request.urlopen(url
```) 

###############################################

###system shell : PIP CLI###
********************************************************************************
Some Python commands in the PATH of this session:
 - python    == C:\bin\plang\thonny\python.exe
 - **pip       == C:\bin\plang\thonny\Scripts\pip.bat**
 - pip3      == C:\bin\plang\thonny\Scripts\pip3.bat
 - pip3.7    == C:\bin\plang\thonny\Scripts\pip3.7.bat

********************************************************************************

```
thonny\Scripts\pip.bat

@"%~dp0..\python.exe" -m pip **--proxy 127.0.0.158109** %*
```

**Comment by aivarannamaa** [comment]
@rpi4iot, thank you for the input!

In the next major version I plan to refactor configuration dialog and this gives the room for proxy configuration page.

**Comment by aivarannamaa** [comment]
`https_proxy` environment variable is now forwarded to `pip` via `--proxy` argument. Note that, there is also possibility for specifying environment variables in "Tools => Options => General" (#1421)
