### ISSUE TITLE
upload doesn't work with LoBo MicroPython

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#540]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/540) by Jens Diemer (Bitbucket: [jedie](https://bitbucket.org/jedie)
 GitHub: [jedie](https://github.com/jedie)
).**

----------------------------------------

I now use the microPython version from https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo on my Odroid Go and the upload raises a OSError:

```
>>> %upload main.py /main.py
Traceback (most recent call last):
  File "/home/jens/repos/thonny-Env/src/thonny/thonny/plugins/micropython/__init__.py", line 860, in _check_and_upload
    self._upload(source, target)
  File "/home/jens/repos/thonny-Env/src/thonny/thonny/plugins/micropython/__init__.py", line 867, in _upload
    self._upload_via_serial(source, target)
  File "/home/jens/repos/thonny-Env/src/thonny/thonny/plugins/micropython/__init__.py", line 878, in _upload_via_serial
    self._execute_and_expect_empty_response("__upf = open(%r, 'wb')" % target)
  File "/home/jens/repos/thonny-Env/src/thonny/thonny/plugins/micropython/__init__.py", line 503, in _execute_and_expect_empty_response
    assert len(err) == 0, "Error was " + repr(err)
AssertionError: Error was bytearray(b'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nOSError: [Errno 19] ENODEV\r\n')
```

See also: https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/issues/221

How can I better find out where the problem appears?

**Comment by fstengel** [comment]
> 
> 
> **Original comment by Jens Diemer (Bitbucket: [jedie](https://bitbucket.org/jedie) GitHub: [jedie](https://github.com/jedie) ).**
> 
> What's about to add a "base path" into options/interpreter/Details ?
> 
> EDIT: I started https://bitbucket.org/plas/thonny/pull-requests/16/ for this.
I looked at the bitbucket pull request and started playing with it by adding a field in the backend selection panel.

Basically I do the following:
- add an option via ` get_workbench().set_option(self.backend_name + ".pathPrefix", theActualPrefix )` (__init__.py in plugins/micropython)
- add a function to read that option and return an empty string if the option is not set (`__init__.py in `.../plugins/micropython`)
- add a label/entry/textvariable in the definition of the ESP32ConfigPage class within the thonny-esp plugin that sets the option

My problem to date, before I consider sending a pull request, is that these changes impact both thonny/thonny and thonny/thonny-esp

**Comment by aivarannamaa** [comment]
Fixed in master
