### ISSUE TITLE
Editor and Shell Window Arranged Vertically, Side by Side

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#541]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/541) by Anonymous.**

----------------------------------------

Any chance this could be implemented? It would really help me as a teacher and my many students. Thanks.

**Comment by aivarannamaa** [comment]
Covered by #544

**Comment by elliotwoods** [comment]
I'd love this feature also - it's the main thing that's lacking for me within the interface
I'm not sure what the best way is for Thonny to implement this. Either:

1. Split view (code pane can be become 2 panes each with independant tab lists)
2. Tabs can be freely moved around (including Shell, Files, etc)
3. Pop out any tab into its own window
4. Mix of above

I am aware that Thonny puts the word 'beginner' in its tagline, and this maybe isn't particularly a beginners feature. I find Thonny to be an excellent tool (by far the best) for MicroPython development, and it would be great to be able to use it for more advanced workflows.

Is there a strategic design reason why multiple code windows cannot be opened side-by-side within Thonny?

p.s. Thank you for this excellent excellent tool. I love it!
