### ISSUE TITLE
Creating a .exe file

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#553]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/553) by Anonymous.**

----------------------------------------

Hello, I am trying to make an executable program in Thonny so I don't have to run Thonny to use it. I am not very good at this type of stuff and was wondering what the easiest way to do it would be. (Please assume I have nothing I need installed other than Thonny) 
Thanks,
Stlerfn

**Comment by P-Zhu** [comment]
ThonnyRunner310\x64\Release\thonny.exe  是如何构建 的
