### ISSUE TITLE
"Highlight matching names" and "Highlight local variables" makes editor very slow

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#573]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/573) by Anonymous.**

----------------------------------------

in version 3.0.4 it takes about half a second to display a single character in editor workspace
when typing same code in shell workspace it works with no problems 

i'm using windows 10 64-bit

**Comment by Mookiefer** [comment]
I'm running 3.1.0 and I'm experiencing lag again with "Highlight matching names" enabled.

"Highlight local variables" doesn't seem to have a noticeable effect on the UI responsiveness.
