### ISSUE TITLE
Thonny "Convert tabs to spaces" dialog

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#599]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/599) by Anonymous.**

----------------------------------------

I like Thonny as a Python IDE, but you have to give the option to turn this shit off.

Tabs are vastly superior to spaces anyways, and GvR is a fucking douche about that. Having a dialog pop up every linebreak to tell me that I should use spaces is driving me nuts.

**Comment by SiddheshNan** [comment]
Hey, is there any update to turn off this crappy error message every time I open any python files?

**Comment by dinobrasi** [comment]
Dear kind sir, it would be a nice feature to be able to turn off the warning about tabs. Some coders, myself included do not use spaces. After 25 years of coding daily, hitting the tab key is ingrained in my brain and not something I consciously think about. What's that saying about old dogs and new tricks? haha Anyway, I think the editor is really great and thank you for the hard work.

**Comment by aivarannamaa** [comment]
@dinobrasi , it is OK to hit tab key in Thonny -- it simply inserts 4 spaces instead of tab character.

I'll add this issue back to my TODO list.

**Comment by dinobrasi** [comment]
If pressing tab puts in the spaces, I'm totally good. I noticed the warnings when I wrote some Python in Visual Studio, committed to GitHub and pulled it down to a Raspberry Pi. I will follow the advice of the warning and convert the tabs to spaces. Again, thanks for the hard work!

**Comment by open-sky-technologies** [comment]
I don't care about the whole tabs vs spaces thing but I'm afraid I am currently trying to work with a string that includes tabs and having to click no on the dialogue every time I paste it in is beginning to get on my nerves.

Thanks.

**Comment by friscodelrosario** [comment]
Why in the world isn't this in the FAQ?

**Comment by aivarannamaa** [comment]
The dialog will be gone in Thonny 3.3.0.

What I added instead:

* Setting "Tools => Options => Editor => Indent with tab characters" (Tab-key in the beginning of the line inserts single tab char; off by default)
* Setting "Tools => Options => Editor => Highlight tab characters" (gives different background for tabs; on by default)
* Command "Edit => Replace tabs with spaces" (replaces each tab in the beginning of the line with 4 spaces)

Leading tab characters are displayed with same width as 4 spaces.

If you prefer tabs, then you'll probably want to switch on "Indent with tab characters" and switch off "Highlight tab characters".

No automatic conversion or unification of tabs and spaces is attempted anymore. If the user has 4-space indents and she pastes an example with tabs, then she'll have both tabs and spaces in her file. Hopefully she then notices highlighted tabs and/or pylint warning in the "Assistant" view.
