### ISSUE TITLE
Add an option for auto-complete box to pop-up automatically

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#625]
* https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/thonny/mB6nqKm0QQQ/d1S1A9jlBAAJ

**Comment by WaterCountry** [comment]
Add an option for auto-complete box to pop-up automatically,I want too.

**Comment by WaterCountry** [comment]
autocomplete.py
where  can I change Tab to "." , so i type "." to call auto-complete box up

**Comment by WaterCountry** [comment]
the box height is 140, and width is 200 

    def _show_box(self, completions):
        ...
        # place box
        if not self._is_visible():
            # _, _, _, list_box_height = self.bbox(0)
            height = 140  # min(150, list_box_height * len(completions) * 1.15)            
            ...
            width = 200            
            self.place(x=text_box_x, y=y, width=width, height=height)
            self._update_doc()
