### ISSUE TITLE
font and icon size

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#641]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/641) by Anonymous.**

----------------------------------------

Hi,

I wanted the newest thonny on kubuntu 18.10 and installed with curl. My icons and menu font are teeny on a big screen and hardly readable. Adjusting fonts for gtk in system settings dosn't help. Is there a way to get bigger icons and menu fonts?

Thanks

Greetings

**Comment by aivarannamaa** [comment]
See https://www.facebook.com/thonnyide/inbox/10218511032474870/?notif_id=1548364319574681&notif_t=page_message&mailbox_id=1206335882747057&selected_item_id=1467058383

**Comment by MachmaHinne** [comment]
When will the next release containing this bug fix be available?
The small fonts sucks on a 4k screen. Thanks.

**Comment by aivarannamaa** [comment]
It should be fixed in 3.1.0 and later. Which version are you using? Which scaling setting did you use?

**Comment by MachmaHinne** [comment]
I´m using this one offered for download:
https://bitbucket.org/plas/thonny/downloads/thonny-3.0.8-x86_64.tar.gz
Using it with SuSE Tumbleweed. Unpacked at /opt
I tried out different scalings. But it doesn´t influence the UI font size.

**Comment by aivarannamaa** [comment]
It was broken in 3.0.8 indeed. New releases are here: https://github.com/thonny/thonny/releases

**Comment by MachmaHinne** [comment]
Perfect. Thanks a lot!

**Comment by jiri-one** [comment]
Hi, I would like to reopen this issue. I use newest version 3.2.6 from there: https://aur.archlinux.org/packages/thonny/ and you see screenshot. I tried it on Fedora 31 and it is same. I would like, that UI font will be same like in editor or same like in desktop settings or if they are will be adjustable, but not small like nothing in the system.
![Screenshot from 2020-03-08 10-07-09](https://user-images.githubusercontent.com/32774109/76159839-a731d800-6124-11ea-93c6-972affdd62f7.png)

**Comment by aivarannamaa** [comment]
Related to #1113

**Comment by bhcqzf** [comment]
thank you , your Comment is very useful
