### ISSUE TITLE
Show tooltip with function arguments

### ISSUE THREAD

**Issue by jjnilton** [thonny/thonny#662]
Hi, congratulations on the tool, it's really user-friendly!

I was wondering if there's a way to enable a tooltip that show what arguments a function expects, like IDLE does:

![image](https://user-images.githubusercontent.com/228200/51505904-08cf9f80-1dc8-11e9-9363-f43a5c89fe31.png)

I think it could be helpful for those learning the functions. 

Thanks for sharing the project

**Comment by aivarannamaa** [comment]
Hi!

At the moment this is not implemented, but I agree that it is nice thing to have.

**Comment by schellenberg** [comment]
Agreed. This would be a fantastic addition.

**Comment by aivarannamaa** [comment]
Done by now
