### ISSUE TITLE
Interpret escape characters while micropython boots

### ISSUE THREAD

**Issue by fstengel** [thonny/thonny#664]
Using the Lobo port of micropython on an ESP32, I see escape characters during (re)boot. These characters trigger a color change in the printed text. In Thonny they are shown as [0;32m  and [0m. they look like ANSI color escapes (missing the ESC character) and it would seem that Thonny gobbles the \x1b. It would be nice if these were interpreted.

**Comment by aivarannamaa** [comment]
Unfortunately Thonny's shell currently doesn't support color escapes.

About missing ESC... Can you check with another serial tool (eg. Putty, screen), whether the ESC is actually present in the output (or whether they interpret the colors correctly)?

**Comment by fstengel** [comment]
> Unfortunately Thonny's shell currently doesn't support color escapes.
> 
> About missing ESC... Can you check with another serial tool (eg. Putty, screen), whether the ESC is actually present in the output (or whether they interpret the colors correctly)?

The esc is there: when I connect with mpfshell or screen, the escapes are correctly interpreted (some lines are colored green, others stay black). Thonny's shell visually gobbles the ESC and shows the rest of the sequence. For instance Thonny's shell shows:
`[0;32mI (4773) phy: phy_version: 3960, 5211945, Jul 18 2018, 10:40:07, 0, 0[0m`
where this should (and mpfshell shows it) be
`I (4773) phy: phy_version: 3960, 5211945, Jul 18 2018, 10:40:07, 0, 0`
in green... The ESC char is there when copying and pasting, just not interpreted.

**Comment by aivarannamaa** [comment]
In version 3.2 with M5Stack it seems to work properly (now even with proper interpretation of color codes). I assume that refactoring of MicroPython plug-in fixed this problem somehow.

BTW, with some boards it seems to be unavoidable that some part of boot output will be unreadable: https://forum.micropython.org/viewtopic.php?f=16&t=6561&
