### ISSUE TITLE
On OSX Vie→Focus Editor/Shell ⌥-E/⌥-S insert the corresponding chars

### ISSUE THREAD

**Issue by juanfal** [thonny/thonny#675]
On OSX Vie→Focus Editor/Shell ⌥-E/⌥-S insert the corresponding chars, those chars are: €/∫.  For them to work on OSX the keyboard shortcuts should be: ⌘-⌥-E/⌘-⌥-S respectively

**Comment by aivarannamaa** [comment]
Thanks for the report!
