### ISSUE TITLE
On OSX, opening a mathplotlib window gets a hung instance of it when you try to close it

### ISSUE THREAD

**Issue by juanfal** [thonny/thonny#676]
On OSX, opening a mathplotlib window gets a hung instance of it when you try to close it using the red button to close the mathplotlib window.  It did't use to happen

**Comment by aivarannamaa** [comment]
I can reproduce this problem, both with mpl 3.0.2 and 2.2.3.

At the moment I don't have any ideas why it acts like this.

Looks like one workaround is to put exit() after plt.show() or to use TkAgg backend.

It is weird, that when I run a sample script via Thonny in Terminal with "python -i", it can be closed from red button, although the process remains alive ...

**Comment by juanfal** [comment]
It seems that the mathplotlib process depends on the very Thonny process, so it doesn't end until Thonny quits, and if you try to close the mathplotlib manually, it gets stuck not knowing where going back to.

**Comment by aivarannamaa** [comment]
Something like this... It depends on Thonny's backend process, which can be killed with Run => Stop / Restart.

**Comment by juanfal** [comment]
> El 31 ene 2019, a las 0:32, Aivar Annamaa <notifications@github.com> escribió:
> 
> Looks like one workaround is to put exit() after plt.show() or to use TkAgg backend.
> 
> 

done and right! Thanks

-

**Comment by gvwilson** [comment]
I can confirm that switching to the TkAgg backend solves this problem on MacOS. Revising #707:

```
import seaborn as sns
import matplotlib as mpl # Needed so that we can call matplotlib.use later
import matplotlib.pyplot as plt

mpl.use("TkAgg") # This is the new line
sns.scatterplot(x=[1, 2, 3], y=[5, 1, 3])
plt.show()
```

produces the pop-up window, and that window is responsive when asked to close. However, a look at running processes shows that there's still an extra Python process running after the plot window is closed...

**Comment by gvwilson** [comment]
I can confirm that switching to the TkAgg backend solves this problem on MacOS. Revising #707:

```
import matplotlib as mpl
mpl.use("TkAgg")

import seaborn as sns
sns.scatterplot(x=[1, 2, 3], y=[5, 1, 3])

mpl.pyplot.show()
```

produces the pop-up window, and that window is responsive when asked to close. However:

1.  `mpl.use` *must* be called *before* `import seaborn`. If it is called afterward, Thonny crashes.
2.  After the plot window is closed, there appears to be an orphaned process of some kind showing up in the Mac task switcher (command-tab). Its text label is "Python", its icon is a grainy radar chart, but I'm unable to get a screenshot because screen capture won't work in the middle of task switching. `ps` doesn't show anything suspicious, so I'm puzzled.

**Comment by aivarannamaa** [comment]
> there's still an extra Python process running after the plot window is closed

This is expected. Thonny doesn't close the process until next Run, Debug or Stop/Reset in order to allow user to continue interactively in the shell.

**Comment by aivarannamaa** [comment]
I tried hard to get it working with default backend (MacOSX), but failed. Now I added a hack which automatically changes default backend to TkAgg on macOS.

It is still possible to override this hack by setting up matplotlib configuration files or by selecting the backend explicitly in code (eg matplotlib.use("QT5Agg")).

**Comment by chrisfcarroll** [comment]
A simpler workaround for this on macos is to use `pyplot.show(block=False)` instead of just `pyplot.show()`
