### ISSUE TITLE
Debug at 100% CPU lasting very long

### ISSUE THREAD

**Issue by juanfal** [thonny/thonny#686]
On OSX, last 3.1.1, debug takes very very long time when importing not so long imports.  It seems even stuck

**Comment by aivarannamaa** [comment]
Can you provide an example program?

**Comment by juanfal** [comment]
Well, in fact it is the very same one I privately sent to you.  It happens when

	import AE, AE_FILE


-

**Comment by aivarannamaa** [comment]
Thanks! I can confirm that this problem occurs also on Linux. I'll investigate it later.
Meanwhile I recommend to use faster debugger (Shift+F5).

**Comment by juanfal** [comment]
No words.  Thanks!

-

**Comment by aivarannamaa** [comment]
Please check whether it works in 3.1.2 for you: https://github.com/thonny/thonny/releases/download/v3.1.2/thonny-3.1.2.dmg

**Comment by juanfal** [comment]
It now works like a charm!!!!!

The listings now don’t wrap the line numbers and the ⌘-⌥-E and ⌘-⌥-S work nices


Wow!





Thanks Aivar.
If you come to Málaga/Spain consider it done you have free room+beers :)

- Juan F.
