### ISSUE TITLE
Thonny's window title bar does not change to dark mode in macOS Mojave

### ISSUE THREAD

**Issue by phr0gger** [thonny/thonny#695]
This is Thonny 3.1.2:
<img width="201" alt="screen shot 2019-02-17 at 9 17 09 am" src="https://user-images.githubusercontent.com/47429373/52914354-3f98b880-3295-11e9-9f3e-3736758259ba.png">

**Comment by aivarannamaa** [comment]
Do you have IDLE installed? Does it use correct titlebar?

**Comment by phr0gger** [comment]
No, IDLE also keeps the window title bar bright. Ist it possibly a GTK issue?

**Comment by aivarannamaa** [comment]
Not GTK, but Tk (the toolkit used by both Thonny and IDLE via Tkinter).

I'm afraid we need to wait until official Python interpreter (used in Thonny) gets built with current Tk version (8.6.9.1)

**Comment by phr0gger** [comment]
oops, I was confused. Good to know. Thank you!

**Comment by aivarannamaa** [comment]
Fixed by upgrading to Tk 8.6.11. 

Experimental build available in https://github.com/thonny/thonny/releases/download/v3.3.5/thonny-3.3.5_alt.pkg (bundled with Universal 2 binaries of Python 3.9.2)
