### ISSUE TITLE
Use 'Stop/Restart' to restart the backend ...

### ISSUE THREAD

**Issue by DrCai** [thonny/thonny#702]
Thonny 3.1.2:
![ffe 7hh7e h77 6cx](https://user-images.githubusercontent.com/19576322/53619551-a66d8880-3c2a-11e9-8d7e-ec069f70f17d.png)

**Comment by DrCai** [comment]
I know why, because I added PYTHONPATH to my environment variable.

**Comment by aivarannamaa** [comment]
Might be...
Hopefully fixing #639 will help in your case as well.

**Comment by Ilis** [comment]
Using Stop sign for restart is a bit weird. The actual result of "Stop/Restart" action is Restart, so it's better be some sort of Restart icon, not Stop.

**Comment by aivarannamaa** [comment]
> Using Stop sign for restart is a bit weird. The actual result of "Stop/Restart" action is Restart, so it's better be some sort of Restart icon, not Stop.

The main reason for putting this button to the toolbar was to provide quick means for getting out of infinite loops. Just restarting is only required when Thonny does someting bad (or when switching MicroPython devices). Therefore, I would say in most important cases the main action is Stop and Restart is a bonus.

**Comment by victorkolis** [comment]
Whenever I run the pygame module and quit the window I've created this message pops up:

**Backend terminated or disconnected. Use 'Stop/Restart' to restart.**

**Comment by aivarannamaa** [comment]
@victorkolis, can you provide a minimal program that demonstrates this problem?

Which OS, Thonny version and Pygame version are you using?
