### ISSUE TITLE
Suggest current filename when Save As

### ISSUE THREAD

**Issue by Ilis** [thonny/thonny#704]
When we save a copy of a file with Save As dialogue we often just change one or two letters in current name. Now we have empty field for new name, but it's better be selected current filename for quickly replace it with new name or slightly change current name.

**Comment by aivarannamaa** [comment]
Good idea!

TODO: need to check how it behaves with Zenity

**Comment by chpurdy** [comment]
> Good idea!
> 
> TODO: need to check how it behaves with Zenity

I've tested with Zenity and it keeps the current file name when using save as as intended.

**Comment by aivarannamaa** [comment]
Thanks @chpurdy !
