### ISSUE TITLE
Thonny.desktop lacks Categories section

### ISSUE THREAD

**Issue by Ilis** [thonny/thonny#705]
Thonny.desktop in linux distribution lacks Categories section, so when installed it appears in category Others in menu. I've add `Categories=Application;Education;Development;ComputerScience;` as it was made in similar .desktop files and get Thonny in right menu entries.

**Comment by aivarannamaa** [comment]
Weird, I have deleted the Categories line 7 months ago, but I don't remember why...

I guess I just need to restore it.
