### ISSUE TITLE
Finding/changing current working directory

### ISSUE THREAD

**Issue by gvwilson** [thonny/thonny#709]
I am unable to determine how Thonny decides when to change current working directory for the Python session, or how to re-set it: `os.getcwd()` tells me where I am, and `os.chdir()` will change the directory, but there doesn't appear to be a clear relation between what files I open in the editor pane and what my current working directory is. What is the recommended way to find/change this?

**Comment by aivarannamaa** [comment]
At the moment on each run Thonny changes to the directory of the script.

(In the next version there will be an option which allows Files view to control working directory)

**Comment by LGCarmonaS** [comment]
has anything changed?

**Comment by aivarannamaa** [comment]
Thank you for reminding this!

In Thonny 3.2 the active directory in Files view becomes the current directory for the backend process. One can choose from the options (Run & Debug) whether running a file should change that directory automatically.

**Comment by Zandar1958** [comment]
I am getting started and would like to know how I can set up my working directory to point to my "Google Drive" file?  T.

**Comment by aivarannamaa** [comment]
@Zandar1958 you should click on "This computer" in the header of the file browser and then double click on desired drive
