### ISSUE TITLE
OSX Search dialog: ambiguous buttons

### ISSUE THREAD

**Issue by fstengel** [thonny/thonny#719]
When searching the dialog that shows has three buttons labelled replace. I gather they must be for something like: "Replace", "Replace All", "Replace & Find". See the attached file for an idea of the issue.

![thonny-search](https://user-images.githubusercontent.com/4446547/55553120-a2c49a00-56df-11e9-9ac2-4fc792ec96f2.jpeg)

On a side note, there does not seem to be a keyboard shortcut for "find next". without it searching for the next occurence is rather tedious: one has to use the mouse. Ususally on a mac, that shortcut is cmd-G (with cmd-shift-G for a reverse search).

**Comment by aivarannamaa** [comment]
Thank you for the report!
It looks like the buttons are too narrow for this font.
