### ISSUE TITLE
should pygments be on the requirements.txt file?

### ISSUE THREAD

**Issue by badukaire** [thonny/thonny#726]
I have tried running thonny on windows from source with the command line. I have done the pip install of the requirements.txt file (-r option). But it still lacked pygments. I did `python -m pip install pygments` and now it works.

So perhaps this should be added to the `requirements.txt` file.

**Comment by aivarannamaa** [comment]
`from pygments.lexer import include` slipped in accidentally. I [removed it yesterday](from pygments.lexer import include) and it should not be required anymore.

**Comment by badukaire** [comment]
True. I was running it on my fork. Uninnstalled pygments and thonny/thonny works, whereas my fork is back to not-working as expected.
