### ISSUE TITLE
[GUI Issue] [Included Images] Right click menu disappears immediately and executes unwanted Undo action

### ISSUE THREAD

**Issue by vnktsh** [thonny/thonny#731]
Hello,

Thonny right-click menu in editor completely breaks when using any theme other than "Enhanced Calm". The right click menu disappears immediately and unwanted action "undo" is executed.

The following is with theme "Clean Dark". But the issue can be reproduced with any other theme other than default.

UI Theme: Clean Dark  |  Syntax Theme: Default Dark
![Thonny Right-Click issue](https://media.giphy.com/media/iDD75jF3FM3ZJiuE5w/giphy.gif)

In the terminal console I see these logs:
```
ERROR: [_dispatch_tk_operation] operation: edit, args:('undo',)
Traceback (most recent call last):
  File "/home/tmc/.local/lib/python3.5/site-packages/thonny/tktextext.py", line 53, in _dispatch_tk_operation
    return self.tk.call((self._original_widget_name, operation) + args)
_tkinter.TclError: nothing to undo
```

**However there's no issue with default theme:**
UI Theme: Enhanced Calm  |  Syntax Theme: Default Light
![Thonny Right-Click issue](https://media.giphy.com/media/J5k6fyVEmDIKGBvz5v/giphy.gif)

### Steps to reproduce:
1.  Open editor with any file
2.  Goto Menu bar > Tools > Options ; In options windows go to Themes & Font
3. Select "UI Theme: Clean Dark  |  Syntax Theme: Default Dark"
4. Restart thonny
5. Right click anywhere on editor. The pop-up menu is broken and disappears and executes "undo"

### Details:

- Thonny: 3.1.2
- Python: 3.5.2
- Tk 8.6.5
- Linux (64 bit)
- OS: Ubuntu 16.04

**Comment by aivarannamaa** [comment]
Thank you for the report! I'll look into this today

**Comment by vnktsh** [comment]
Thank you for the attention, and thank you in general for developing this awesome IDE.
