### ISSUE TITLE
Old Python-version used by Thonny

### ISSUE THREAD

**Issue by gnossing** [thonny/thonny#732]
Hello 
When I installed Thonny on my Raspian stretch, Python 3.5.3. was the most actual version of Python. After starting Thonny it shows " Python 3.5.3 (/usr/bin/python3)" in the shell window.
I have now installed the new Python 3.7.3. version, but Thonny still uses the old Python-version.
How can I change this or do I have to uninstall/install?
Any help is welcome, Gerd

**Comment by aivarannamaa** [comment]
Thonny's pip / apt package does not include Python interpreter so you are stuck with Python 3.5.3 until Raspberry moves from Debian Stretch to Debian Buster.

The binary bundles, which include Python interpreter, are available only for PC-s
