### ISSUE TITLE
Change Auto Completion

### ISSUE THREAD

**Issue by Remuar** [thonny/thonny#733]
Hi,
I discovered Thonny 
and i am very happy... 
thanks for this good tool.
I would like to change the code issued by auto complete :
I would like to change p.ex print to print(' ') or print() because lot of time you will enter something after print.  I also would like to add some personal auto complete like f => France... 
How can I do that?

**Comment by aivarannamaa** [comment]
Thank you for the idea!

You can't do this in Thonny at the moment. Also, I don't feel it would be too important feature so I'm postponing this for now.

**Comment by aivarannamaa** [comment]
Duplicate of #625
