### ISSUE TITLE
Theme & Font issue

### ISSUE THREAD

**Issue by methedude** [thonny/thonny#747]
When you go to Tools -> Options -> Theme & Font and change from the default UI Theme to a dark theme(any theme that makes the background a different color, you can try "Clean Dark"). After you changed the theme and run a code that outputs to the shell, a white space will be included before the output, every single time.

**Comment by methedude** [comment]
![Capture](https://user-images.githubusercontent.com/37919374/57045983-9b3bd680-6c34-11e9-8539-2f0d01dfdc51.PNG)

**Comment by aivarannamaa** [comment]
Does it appear even after restarting Thonny?

**Comment by aroberge** [comment]
I tested this on my computer (Windows 10) and the white space did not appear after a restart.

**Comment by aivarannamaa** [comment]
Fixed
