### ISSUE TITLE
Never seen before bug

### ISSUE THREAD

**Issue by Andre50501** [thonny/thonny#761]
Thonny 3.?.?  worked perfectly fine on my MacBook Pro running Mojave until yesterday. When I launched it, it looked like this:
<img width="892" alt="Screenshot 2019-05-21 at 08 50 27" src="https://user-images.githubusercontent.com/46201372/58074976-cddb4e00-7ba6-11e9-8e25-532ac671d580.png">

Cant write any code, menus are all greyed out. I can't even quit... I have to Force quit through the Apple menu. I downloaded version 3.1.2 and re-installed it on my machine with exactly the same issue. I have Python 3.7 installed and IDLE and Spyder work fine.

Does anyone have any ideas?

Andre

**Comment by juanfal** [comment]
No problems at all in my Mojave 10.14.6 beta (18G29g), and never had so far, 🤞

**Comment by aivarannamaa** [comment]
@Andre50501, can you please check into `~/Library/Thonny` and send me the log-files and configuration.ini?

**Comment by Andre50501** [comment]
Hi,

Here are the files you’re requested. Thanks for looking into this.

Andre

**Comment by aivarannamaa** [comment]
@Andre50501, did you forget to attach the files?

**Comment by Andre50501** [comment]
Hi,

They were in a folder called “Thonny”. Didn’t you see the folder? Here are the files attached individually.

Andre

**Comment by aivarannamaa** [comment]
No, I don't see the files neither in GitHub nor in my e-mail client.

**Comment by Andre50501** [comment]
Hi, can you see the files now?

Andre

**Comment by aivarannamaa** [comment]
No, I still don't see them.

Trying to attach a file myself:
[test.txt](https://github.com/thonny/thonny/files/3207644/test.txt)

**Comment by Andre50501** [comment]
Very weird. I got your file and I can see my attached files in my Sent Messages. And I also sent the email and attachments to another email address that belongs to me without any problems. 

Maybe your server doesn’t like .ini or log files?

Hi can I send the files to Github?

Andre

**Comment by aivarannamaa** [comment]
> can I send the files to Github?

Sure. If you reply in GitHub, you can drag your files to the comment box.

**Comment by Andre50501** [comment]
OK so here was the problem. I couldn't upload configuration file because Github says: "We don't support that file type. Try again with a GIF, JPG ....XLSX or Zip".  So I saved it as a .txt file and its now attached.

The .log files are all empty and they are not attaching.

Regards,

Andre
[configuration.txt](https://github.com/thonny/thonny/files/3211126/configuration.txt)

**Comment by aivarannamaa** [comment]
Thanks! Unfortunately I don't see anything suspicious in the configuration file. I was hoping to get more information from the logs, but if you had to force quit Thonny, then it might have been unable to save the logs.

Can you please run Thonny from the terminal? It may give some hints into standard output. See here for instructions: https://github.com/thonny/thonny/wiki/Troubleshooting#open-in-terminal-macos

Is it possible that when you open Thonny, it tries to show an information (or error) dialog, but it's hidden behinde the main window? I've seen Tkinter programs occasionally doing this and it would explain why you could not interact with the window.

**Comment by aivarannamaa** [comment]
@Andre50501, Can you please check whether [Thonny 3.2.0](https://github.com/thonny/thonny/releases/download/v3.2.0/thonny-3.2.0.dmg) works for you?

**Comment by aivarannamaa** [comment]
Hoping it is fixed by now
