### ISSUE TITLE
Find & Replace DialogBox: Button's Text / Caption cannot be read as it is longer than the button's width.

### ISSUE THREAD

**Issue by Sakibul** [thonny/thonny#779]
Thonny version = 3.1.2

Menu ==> Edit ==> Find & Replace ==> DialogBox loads

The last button's Text / Caption cannot be read as it is longer than the button's width.

![Find_Replace_DialogBox](https://user-images.githubusercontent.com/11478550/59474803-391ae780-8e16-11e9-8d4a-143256506c4c.gif)

**Comment by Sakibul** [comment]
![Find_Replace_DialogBox](https://user-images.githubusercontent.com/11478550/59474794-2b656200-8e16-11e9-9428-8174fc4041a6.gif)

**Comment by aivarannamaa** [comment]
Thank you for the report. This will be fixed in next version.

Dupicate of #719
