### ISSUE TITLE
No debug commands

### ISSUE THREAD

**Issue by randomhammer** [thonny/thonny#788]
I successfully installed Thonny on Windows 10, and have it connected to MicroPython on an ESP8266. I can run programs, but all options for debugging are greyed out. The test program I have is running on the ESP8266 because it controls the built-in LED, but no debugging. How can I troubleshoot this? 

I am running the latest Windows 10, Thonny 3.1.2 and esp8266-20190529-v1.11.bin for the ESP8266 MicroPython firmware.

**Comment by aivarannamaa** [comment]
Debugging is currently not implemented for MicroPython back-end.
