### ISSUE TITLE
A problem when running script in thonny

### ISSUE THREAD

**Issue by dqs8100** [thonny/thonny#799]
I write a class with "\__del__". Then I run a script in thonny using F5, but when the script ends, the "\__del__" is not called. I run the same script in terminal, when the script ends, the "\__del__" is called.
Another problem is I use 'del *' to destory an object in thonny's shell, the "\__del__" is not called either. But I use 'del *' to destory an object in python shell, the "\__del__" is called.
So how can I make thonny shell the same as python shell, and make the script run in thonny the same as that runs in terminal.
Thank you very much.
Here is the class code:
```
#A.py
class A:
    def __init__(self):
        print("Init an object from A")
    def __del__(self):
        print("Del an object from A")
```
And here is the result using thonny shell and python:
![2019-07-09-115913_1258x729_scrot](https://user-images.githubusercontent.com/52660520/60858936-0f9d8200-a243-11e9-9309-a383cc60e71f.png)
Then I write a script using the class A:
```
#test.py
from A import A
a = A()
```
Here is the result I run the script in thonny and in terminal:
![2019-07-09-120155_1249x715_scrot](https://user-images.githubusercontent.com/52660520/60859022-61460c80-a243-11e9-84bb-4d5df4583086.png)

**Comment by aivarannamaa** [comment]
Please include the code!

**Comment by dqs8100** [comment]
> Please include the code!

`class A:
    def __init__(self):
        print("Init an object from A")
    def __del__(self):
        print("Del an object from A")`
And here is the result:

**Comment by dqs8100** [comment]
> Please include the code!

Hello, I have updated the issue with the code included. Thanks.

**Comment by aivarannamaa** [comment]
Good question!

Here is the background information: https://stackoverflow.com/a/1481512/261181

After each round of interaction with the interpreter, Thonny will gather the reference for each global and local variables in order to allow heap exploration. That's why Python can't garbage collect you `a`.

**Comment by dqs8100** [comment]
> Good question!
> 
> Here is the background information: https://stackoverflow.com/a/1481512/261181
> 
> After each round of interaction with the interpreter, Thonny will gather the reference for each global and local variables in order to allow heap exploration. That's why Python can't garbage collect you `a`.

Thank you very much. It is really helpful.
So I think if I have some cleanup script, I'd better write it into a cleanup method and call it when I need.
Or I can use 'del a' in the end of my program to destroy the object.
