### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by Dleta** [thonny/thonny#812]
could you give me a new release of windows after fixed multiprocess problem?
my email:dqingsh@gmail.com
thanks a lot.

**Comment by aivarannamaa** [comment]
IDLE has problems with even simpler things: https://bugs.python.org/issue11820
When they fix this issue, multiprocessing probably gets fixed as well

**Comment by Dleta** [comment]
ok,i got it

**Comment by Dleta** [comment]
I translated apart into simplied Chinese.
hahhahahhahh..........

**Comment by aivarannamaa** [comment]
Why "hahhahahhahh" ?

**Comment by Dleta** [comment]
I am a student & have little spare time.
but I will do it by heart as I can.
dont worried your project.
hahha
