### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by Dleta** [thonny/thonny#820]
Do you satisfied with my translation or 
have suggestions of it (Simplified Chinese)?
Can I take a piece of translation work.
it is almost completely

**Comment by aivarannamaa** [comment]
I don't speak Chinese myself so I cannot say how good your translation is. 

I recommend you ask the other translator to review your work. If you need to change something then make another pull request

**Comment by Dleta** [comment]
ok,infact I change some details several several times.and I was satisfied with my translation.I have checked
it on my computer.
