### ISSUE TITLE
Thonny pronunciation

### ISSUE THREAD

**Issue by mb720** [thonny/thonny#824]
Hi and thanks a lot for your great software!

I was wondering how you pronounce "Thonny".

Does it rhyme with "sunny"?

Or is pronounced like "Tony", with a "th" at the beginning, like in "thanks"?

**Comment by aivarannamaa** [comment]
Hi!

I've used the latter pronunciation -- "Thon" is taken from Py**thon**.

**Comment by bhuyquang1** [comment]
> Hi!
> 
> I've used the latter pronunciation -- "Thon" is taken from Py**thon**.

That means it's pronounced as /ˈθʌnniː/?

**Comment by aivarannamaa** [comment]
> That means it's pronounced as either /ˈθʌnniː/ or /ˈθɒnniː/?

I tried both on http://ipa-reader.xyz/ and the latter is more accurate
