### ISSUE TITLE
How to check code syntax in Thonny without running code

### ISSUE THREAD

**Issue by MineringGuy** [thonny/thonny#825]

**Comment by aivarannamaa** [comment]
Thonny does not have such feature.

**Comment by MineringGuy** [comment]
Ok
Thanks for the reply

Sent from my mobile phone.
Please ignore typos

On Jul 24, 2019, at 11:47 PM, Aivar Annamaa <notifications@github.com<mailto:notifications@github.com>> wrote:


Thonny does not have such feature.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/17C3Z-vDuNQSdoyXgynJWUyg7Pk8BdorAV-KiMFrtfrNZrGdT4zcrUIFpYAF8iY9loTT2m1RG-Pb8YGnTI4LYgT0s2k6eR0YiILxmPLdlSjXAnV_QK7_S6iISkFxpQhWXrELg1LSXLpBSvWegfV4Xidhglpt4H6nPlraknrWyvKJY_g5v-sAweOgi9qA_Vym4LRq77xxd0IXyf0sjFEiTQzTR_53-A9UB8f16EB_X5GPBuSMuJy6OMQuJ0IJkIi7q8QqQv8FBQAQlWwBiKsof7qza58vVzNyS7ukRmY4NNEn_aF5_2QiWZJ8KlPEfLRkFbmor1x7WqLSiF5Ow7GfhoaqkF4FAAniGz5eZHkKQ4Qa7PRBUAqsJ0bVb6jnlzK6Y7AHJLKwOk66v3-CPhOLve7rLzELJ7OuTyh_GpSBewCZfSkjr84o5EPE0ZvAWAIRo/https%3A%2F%2Fgithub.com%2Fthonny%2Fthonny%2Fissues%2F825%3Femail_source%3Dnotifications%26email_token%3DALRNROI6PTJFV6ADZTXJC7TQBEO45A5CNFSM4IGUPXZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2YIEFA%23issuecomment-514884116>, or mute the thread<https://secure-web.cisco.com/1NfvCIpz13BT02CEGafAQ!
%20I4CVXHd52UiYdCrnTsHau5LoSdRfGeXhsdGWgcc9-iX5nbG0n4SACP9F_RF4tkfuTmX7uQftJaOAsXQn0d56SZVSZO-eYbPCsSDwJkq603vNq4qevUO6j592ZCD8bqKMo9imujYXO4o1NHqfNL4dThRa2j3bhjG56ezsvZHJySG5pAUGmiuwxbUthag__DmbVy9Zt1YnvvwjexN0Ixd1kQB4jx3hoOKogicNvOysxWsle5_TwnY2dY772pHZ6cpk6eZg02T1Gx8D99bjYR8XbRgs-lj-5H3Gy4-9JCdE8gspK1NpVEJvMTvOCBDksJW55FBs3BbX3BQQdwaAUbteAKkO1TIiWd_7__zRc-CFjKGWXQSNFW7ol74QVcVOKJaKLuG0x8xuB1xKcSHYaTL2TGwTfOyxQFyxmRcH0tLJ_x61/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALRNROI2B7QHHWJHWDGMKLTQBEO45ANCNFSM4IGUPXZA>.
