### ISSUE TITLE
Laptop touchpad scroll doesn't work.

### ISSUE THREAD

**Issue by Meta-Cortex** [thonny/thonny#827]
Just a common Synaptics PS/2 port touchpad. It's possible to scroll with finger slide (works like mouse wheel). This works in Windows 7 interface and very very rarely it doesn't work in apps. So this doesn't work in any tab in Thonny.

**Comment by aivarannamaa** [comment]
I used to have same problem when my Thinkpad T20 had Windows 7. It didn't work in IDLE either, so I think it is Tk's problem and I can't do anything about it.

Now My Thinkpad  has Win 10 and touchpad scroll works in Thonny and IDLE, so it seems to be Tk playing nice with some drivers.
