### ISSUE TITLE
Home page: "For the curious: 2.3.0b7"

### ISSUE THREAD

**Issue by kajukenbo** [thonny/thonny#831]
Silly, trivial thing but it might confuse some people...

On the home page, upper right, the Beta is referenced (which is very nice, thank you) but it has a typo:

 "For the curious: _**2.3.0b7**_"
I'd imagine that should be **3.2.0b7**
A minor thing, but I thought I'd mention it, since it has been that way for a while.

![image](https://user-images.githubusercontent.com/34345389/62244744-b50cc700-b3a5-11e9-8dad-d5142dd02761.png)

**Comment by aivarannamaa** [comment]
Thank you for noticing it! It was a typo indeed. Fixed now.
