### ISSUE TITLE
Add option to automatically soft-reboot micropython after uploading scripts

### ISSUE THREAD

**Issue by Ivoz** [thonny/thonny#836]
What it says on the title.

At least for my esp32, it requires a soft-reboot for the newly reloaded code to automatically run. I imagine though there may be cases where you simply want the new file uploaded but no restart, so a configuration option would be nice.

**Comment by aivarannamaa** [comment]
I assume you want it for quick testing. Isn't "Run current script" suitable for this?

**Comment by Ivoz** [comment]
My code is not entirely in one file, so not all files are "scripts" per say

**Comment by aivarannamaa** [comment]
I'll propose a more general solution -- Replace "Run current script" with simply "Run" and add an easy option to specify the main script to be run (eg. as combobox on the toolbar). Default value would be `<current script>`.

BTW. Have you checked out 3.2 beta? It has many changes in MicroPython support.

**Comment by Ivoz** [comment]
ATM I was re-uploading my module file, then rebooting (button or with ctl-D) my esp32 so it ran `main.py` again which would cleanly reimport the new modules with the changes.

If running `main.py` again would also result in a clean re-import of the new code then that would be fine.

I had switched for a little to a new Fedora install, and was running their repo's default 3.1.1 which unfortunately has a stalling / completely locks up on quit issue ATM :/

**Comment by aivarannamaa** [comment]
Will be dealt with under #1087
