### ISSUE TITLE
Files fail to open or save (Mac OS X 10.15)

### ISSUE THREAD

**Issue by troywein** [thonny/thonny#840]
Hello I am encountering a weird issue where I am unable to load or save python scripts.  I recently upgraded to Mac OS X 10.15.  I have tried reinstalling and also have tried running the application from different install locations.  Thanks Troy

**Comment by aivarannamaa** [comment]
Hi!
Do you get some error messages? How does the problem manifest?

**Comment by troywein** [comment]
Upon double clicking any file.py it doesn’t open in the editor.  On save after clicking save the dialog closes and the open file remains as <untitled> *.  I’ve attached a screenshot.  Thanks Troy

[cid:3694E61E-156D-499C-BA07-6403284EE72F]

On Aug 8, 2019, at 2:00 PM, Aivar Annamaa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!
Do you get some error messages? How does the problem manifest?

**Comment by aivarannamaa** [comment]
> Upon double clicking any file.py it doesn’t open in the editor

Do you mean double clicking in Finder or in Thonny's Files view?

Can you try running Thonny from Terminal? It may give some clue. Logs may be useful as well. The instructions are here: https://github.com/thonny/thonny/wiki/Troubleshooting#open-in-terminal-macos

**Comment by troywein** [comment]
This issue only happens on my machine running the latest beta of Mac OS X.  I was able to test on an older version of Mac OS and the issue isn’t there.  Do you have access to a machine with the latest beta?   I can check the log files and send them to you if you are interested?   We could also wait and see if the issue persists in the next release.

You are correct a double clicked file will not open.

Thx Troy

Sent from my iPhone

On Aug 9, 2019, at 1:21 AM, Aivar Annamaa <notifications@github.com<mailto:notifications@github.com>> wrote:


Upon double clicking any file.py it doesn’t open in the editor

Do you mean double clicking in Finder or in Thonny's Files view?

Can you try running Thonny from Terminal? It may give some clue. Logs may be useful as well. The instructions are here: https://github.com/thonny/thonny/wiki/Troubleshooting#open-in-terminal-macos

**Comment by aivarannamaa** [comment]
> I can check the log files and send them to you if you are interested?

Yes, this could be helpful!

> Do you have access to a machine with the latest beta?

My Mac isn't compatible, but I'll try to install it in a VM.

**Comment by troywein** [comment]
Aivar,

I’ve attached a screenshot of the terminal window output when running Thonny from Terminal.  I first attempted to double click a dot.py file and then attempted to save.  The logs are also attached.  Thx Troy
[cid:0869ea4c-bc31-4041-ae7f-9b93d3bc3f4d@namprd17.prod.outlook.com]

On Aug 9, 2019, at 1:20 AM, Aivar Annamaa <notifications@github.com<mailto:notifications@github.com>> wrote:


Upon double clicking any file.py it doesn’t open in the editor

Do you mean double clicking in Finder or in Thonny's Files view?

Can you try running Thonny from Terminal? It may give some clue. Logs may be useful as well. The instructions are here: https://github.com/thonny/thonny/wiki/Troubleshooting#open-in-terminal-macos

**Comment by aivarannamaa** [comment]
Unfortunately I didn't receive the attachments. It seems to be usual problem of GitHub that the attachments sent by e-mail get lost. Please open this issue in the browser and upload the attachments via GitHub interface!

**Comment by troywein** [comment]
Here are the files.
<img width="787" alt="Screen Shot 2019-08-12 at 3 09 41 PM" src="https://user-images.githubusercontent.com/45960380/63033275-982bc580-be74-11e9-9e3b-d076d04c4410.png">
[Thonny.zip](https://github.com/thonny/thonny/files/3502052/Thonny.zip)

**Comment by aivarannamaa** [comment]
Do you happen to have separate Python + IDLE installed?

If yes, then please check whether following program works for you:

```
import tkinter as tk
from tkinter import filedialog

def doit(event):
    print(filedialog.askopenfilename(master=root))

root = tk.Tk()
root.bind("<1>", doit, True)

root.mainloop()
```

When you run it then you should see an empty window.  If you click on it, you should see File Open dialog. Please test whether deleting `master=root` from the code changes anything.

**Comment by aivarannamaa** [comment]
Can you open other Thonny's dialogs (eg. Tools => Options or Help => About) ?

**Comment by troywein** [comment]
I can open the dialogs.

**Comment by troywein** [comment]
> Do you happen to have separate Python + IDLE installed?
> 
> If yes, then please check whether following program works for you:
> 
> ```
> import tkinter as tk
> from tkinter import filedialog
> 
> def doit(event):
>     print(filedialog.askopenfilename(master=root))
> 
> root = tk.Tk()
> root.bind("<1>", doit, True)
> 
> root.mainloop()
> ```
> 
> When you run it then you should see an empty window. If you click on it, you should see File Open dialog. Please test whether deleting `master=root` from the code changes anything.

**Comment by troywein** [comment]
I do have a separate Python and Idle installed.  I get the following error message when running the program you have above:

<img width="556" alt="Screen Shot 2019-08-14 at 11 15 27 AM" src="https://user-images.githubusercontent.com/45960380/63041333-d7faa900-be84-11e9-8466-96e789989378.png">

**Comment by aivarannamaa** [comment]
Most likely `python` command invokes Python 2 bundled with the OS. Can you try same program with `python3`?

**Comment by troywein** [comment]
Works fine in python3 with and without master=root

**Comment by aivarannamaa** [comment]
Problem was created in 4db8c4846793b66eaa473e9f4bdf6f9b180ab165
