### ISSUE TITLE
No link to find easily the install materials

### ISSUE THREAD

**Issue by fa201** [thonny/thonny#846]
I could not manage to easily find the linux material for installation.
I had to go to thonny.org to access the [release page](https://github.com/thonny/thonny/releases/).
I suggest to add a link in the Wiki to access to all OS installation materials, whether they are stable release or release candidate. Note that the download link in https://github.com/thonny/thonny/wiki/Linux direct to old versions hosted in bitbucket.
Thanks anyway for the tool. I hope it will help me to learn Python programming :-)

**Comment by aivarannamaa** [comment]
Thanks for noticing the old link in wiki! I fixed it now.
