### ISSUE TITLE
Open system shell... not opening some Windows environments

### ISSUE THREAD

**Issue by villares** [thonny/thonny#853]
My Thonny 3.1.2 install on Windows 10 (64-bit)
[Python 3.7.2 (32 bit) Tk 8.6.8] does not open the shell window from the tools menu.

Please advise if I can provide any further information to reproduce this.

**Comment by aivarannamaa** [comment]
Please check whether 3.2.0 works better in this respect (https://github.com/thonny/thonny/releases/tag/v3.2.0)

**Comment by villares** [comment]
I tried on a portable 3.20 and it worked!
