### ISSUE TITLE
how to clear recent file

### ISSUE THREAD

**Issue by LGCarmonaS** [thonny/thonny#863]
I have been unable to clear the recent file list, is there a way to do this? Thanks

**Comment by aivarannamaa** [comment]
Nope.

Why do you want to clear it?

**Comment by LGCarmonaS** [comment]
Thank you for your quick responce. The reson is simple, it has become very long. I only work on  the last few files thus, as it becomes crowded, I wanted to clear and start fresh as I move along my learnibg. Thank you again. Something to consider in the future. Great IDE!!!


LGCarmona


----- Mensaje original -----
De: Aivar Annamaa <notifications@github.com>
Fecha: Sábado, 17 de Agosto de 2019, 22:51
Asunto: Re: [thonny/thonny] how to clear recent file (#863)
A: thonny/thonny <thonny@noreply.github.com>
CC: LGCarmonaS <luis.carmona@costarricense.cr>, Author <author@noreply.github.com>


> Nope.



> Why do you want to clear it?


> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
   ,,
  ( ">    LGCarmona
,(> )>
(  ^^    luis.carmona@costarricense.cr
Todos tenemos opiniones y creencias y las expresamos todo el tiempo, pero, ¿serán realmente ciertas o sólo es nuestro ego el que habla? ~ Anónimo

**Comment by aivarannamaa** [comment]
I'd rather not clutter the interface with another command. The recent files list starts removing older entries automatically once it sees more than 15 files.
