### ISSUE TITLE
suggestion about thonny

### ISSUE THREAD

**Issue by Dleta** [thonny/thonny#866]
![thonny](https://user-images.githubusercontent.com/52340898/63503170-91025880-c501-11e9-9fd1-5535bd5ac60d.png)
How do you think about it?
(ಥ_ಥ)

**Comment by Dleta** [comment]
Another problem:
Simplied Chinese translation can't be used since 3.2.0 released,but
it can work in 3.2.0 rc1.

**Comment by aivarannamaa** [comment]
For some reason, Babel compiler, which I was using for recompiling po files, truncated the mo file for Chinese. I now replaced this mo file with the one created by POEditor

**Comment by aivarannamaa** [comment]
For other suggestions, it's better if you add them as separate issues.

**Comment by Dleta** [comment]
yeah~ I will
