### ISSUE TITLE
Make toolbar buttons larger

### ISSUE THREAD

**Issue by pdalet** [thonny/thonny#880]
Can you increase the size of the toolbar ?

Thanks a lot (see mu-editor)

Philippe

**Comment by aivarannamaa** [comment]
Do you mean increasing size of the toolbar icons?

**Comment by pdalet** [comment]
Le Tue, 03 Sep 2019 03:18:45 -0700,
Aivar Annamaa <notifications@github.com> a écrit :

> Do you mean increasing size of the toolbar icons?
> 

Yes

Philippe

**Comment by aivarannamaa** [comment]
In Thonny 4.0 the size of the toolbar icons will be dependent on the pixel size of default font. This means on large monitors they most likely will be bigger.

**Comment by lylewh** [comment]
Hi all,
        I found the required settings to change the toolbar and button size in Thonny.
Please see screen shots
They come under Tools\Options\General
![Thonny Settings](https://github.com/user-attachments/assets/d422f9a7-acf0-4072-8249-5b54ebe8fae0)
![Example Thonny Settings](https://github.com/user-attachments/assets/0622f414-9158-424f-8315-21dc8572451a)
Makes using the program far more comfortable
Regards
Lyle
