### ISSUE TITLE
Cmd-backtick and others crash Thonny

### ISSUE THREAD

**Issue by juanfal** [thonny/thonny#886]
It has been happening since first Thonny version I've used.  It seems to be connected more with TkInter…   When you press ⌘-` (and other combinations using Cmd on Macs) it crashes without a simple warning.  Total crash.  This is quite annoying for students used to Windows who don't know the meaning of the basic Command key on Macs and try to write [ wrongly using the ⌘  instead the ⌥  key

**Comment by aivarannamaa** [comment]
Thanks for letting me know! I'll try to reproduce it when I get around my Mac. Which keyboard layout are you using?

**Comment by juanfal** [comment]
Thanks Aivar

Ours is Spanish




--
Juan miPhone

**Comment by fstengel** [comment]
Same thing happens using a French keyboard. The culprit seems to be an uncaught exception. See the exerpt of the crash report:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TKMenu submenuAction:]: unrecognized selector sent to instance 0x7fac6049e1b0'
abort() called
terminating with uncaught exception of type NSException
```
I can send the whole crash report, if you need it...

**Comment by aivarannamaa** [comment]
I could reproduce this, but it looks like the solution is out of my reach: https://bugs.python.org/issue34455

I created a Tk ticket
https://core.tcl-lang.org/tk/tktview/5849df7852c48cb763b11a11d848a68482b0f828 and I'm afraid I can't do more. When it get fixed, it will come to Thonny when Python includes new Tk version
