### ISSUE TITLE
How to connect pip to Thonny?

### ISSUE THREAD

**Issue by prkundan** [thonny/thonny#901]
I have the py installer zip file. To install py installer pip is required. How to install it in Thonny? How to run pip in Thonny? Please guide me?

**Comment by aivarannamaa** [comment]
* Open "Tools => Manage packages"
* search for `pyinstaller`
* press `Install`

**Comment by prkundan** [comment]
Thanks! I Have Installed pyinstaller. Now how to use it in Thonny?

**Comment by aivarannamaa** [comment]
You need to consult PyInstaller's documentation. Thonny does not include any special support for it

**Comment by Ivoz** [comment]
To get a cmd prompt with Thonny's pip packages available for it, you can use *Tools -> Open System Shell...* menu, then use pyinstaller commands there
