### ISSUE TITLE
Weird interaction with the window manager

### ISSUE THREAD

**Issue by fstengel** [thonny/thonny#905]
Using Thonny 3.2.1 (plain or xxl) on a mac running 10.13.6 with a French locale, I see the following:
- Thonny has one (main) window and it can be "seen" using the "application windows" shortcut (on my machine it is F10)
- When I open the preferences window, iether using the relevant menu item or cmd-, soething quickly flashes on the upper left side of the screen and the preference widow appears.
- When I dismiss the preference window eiter by selecting OK or Cancel, the window disappears. However, in the "Thonny" menu, the items "Preferences..." and "Quit Thonny" are greyed out and, while I can still quit using cmd-Q, I cannot access the preference window without restarting Thonny. Furthermore, using the "application windows" shortcut shows no window for thonny.

**Comment by aivarannamaa** [comment]
Thank you for describing this! I'll try to reproduce it when I'm in the "mac phase" of the next release.
