### ISSUE TITLE
Tkinter

### ISSUE THREAD

**Issue by prkundan** [thonny/thonny#908]
``import shutil
import Tkinter
shutil.copy(r"\\Om-pc\e\Office File\Access Original 14-16\Cash MAR.2017 TO APR.2019.accdb", r"C:\Users\KUNDAN\Desktop\Backup\Cash MAR.2017 TO APR.2019.accdb ")
top = Tk()
Lb1 = Listbox(top)
Lb1.insert(1, "COPIED")
Lb1.pack()
top.mainloop()

> The above code is giving the following error in Thonny:
Traceback (most recent call last):
  File "C:\Users\KUNDAN\backup.py", line 2, in <module>
    import Tkinter
  File "C:\Users\KUNDAN\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 305, in _custom_import
    module = self._original_import(*args, **kw)
ModuleNotFoundError: No module named 'Tkinter'

**Comment by aivarannamaa** [comment]
It's what the error message says -- Python 3 doesn't have module `Tkinter`, it should be `tkinter`.

This is not a Thonny specific problem.
