### ISSUE TITLE
Backend Terminated 

### ISSUE THREAD

**Issue by iris37** [thonny/thonny#910]
Getting the following error message every time when I click the Stop/Restart button. My program is supposed to put esp32 in deepsleep mode every 30 seconds and then use external sources to wake it up. I have try to terminate the program when it is awake but the following error message still occur. 
![捕获](https://user-images.githubusercontent.com/19313650/65181624-769e9a80-da2d-11e9-8f18-1e069f28e184.PNG)

**Comment by aivarannamaa** [comment]
Does this error happen when you wake your device up?

**Comment by Gianowo** [comment]
I have the same problem which arose spontaneously,
My source code was empty as I opened up a new file and went to the bathroom.
I came back and i recieved this error message in red
Backend terminated or disconnected. Use 'Stop/Restart' to restart ...
This same problem happened to my work computer to and reinstalling doesnt seem to solve the problem. Any tips?

**Comment by aivarannamaa** [comment]
@Gianowo , were you using MicroPython back-end as well? Which Thonny version, which platform?

**Comment by Gianowo** [comment]
@aivarannamaa I'm not sure if i was using MicroPython or not but it was Version 3.2.1 on WIndows 10

**Comment by aivarannamaa** [comment]
Please try Thonny 3.3 and reopen if the problem is still there
