### ISSUE TITLE
The erase flash and Install MicroPython menu item are disabled?

### ISSUE THREAD

**Issue by codemee** [thonny/thonny#924]
I'm using Thonny 3.2.1 with D1 mini for MicroPython.However, the Erase ESP8266/ESP32 flash and Install MicroPython to ESP8266/ESP32 in the Tools menu are always disabled.

![圖片](https://user-images.githubusercontent.com/1037913/65831154-2951e100-e2e9-11e9-81ef-8af7cfb025f3.png)

**Comment by aivarannamaa** [comment]
Thank you for reporting!

This was fixed under #896 and will be released in the next version.
