### ISSUE TITLE
(Automatic) scaling doesn't work right for Treeviews

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#933]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/thonny/iM5k8OcOnZ8/ZJLrGh5eAQAJ

See also: https://github.com/thonny/thonny/issues/888#issuecomment-532363657

**Comment by aivarannamaa** [comment]
Consider untying Treeview font size from editor font size (for demonstration purposes one can increase scaling).

Measure font pixel height before setting rowheight

**Comment by boardtc** [comment]
I have the same issue on the variable window :-(
