### ISSUE TITLE
package installation problem.

### ISSUE THREAD

**Issue by Bjoux2** [thonny/thonny#942]
Windows system

the Numpy is in C:/python37/lib/package-site, 
while thonny's package site is ../thonny/python/lib/package-site, 
so i got import error when i "import numpy as np", 
how to add the path "C:/python37/lib/package-site" into Thonny.

Thanks!

**Comment by aivarannamaa** [comment]
If you are using Thonny+Python bundle, then you can make it use different backend from Tools => Options => Interpreter

**Comment by Bjoux2** [comment]
> If you are using Thonny+Python bundle, then you can make it use different backend from Tools => Options => Interpreter

Thanks!
