### ISSUE TITLE
raspberry pi4 thonny steals modules from terminal

### ISSUE THREAD

**Issue by irreverentperson** [thonny/thonny#944]
after using thonny, some packages are no longer available in the terminal but they work in thonny.

**Comment by aivarannamaa** [comment]
Can you be more specific -- which modules? Are you using system provided Thonny? Did you change anything in "Tools => Options => Interpreter"? Are you not confusing commands `python` and `python3`?

**Comment by irreverentperson** [comment]
Board, busio, adafruit-gps modules. They all worked in terminal before I installed them in thonny  through its package installer. I have tried python, python3, sudo python and sudo python3. It is system provided thonny. Only thing I did was install the packages on thonny. Now I get errors in the terminal for those modules

**Comment by aivarannamaa** [comment]
> They all worked in terminal before I installed them in thonny through its package installer.

Why did you install them in Thonny if you already had them installed? Did you use a virtual environment?

> Now I get errors in the terminal for those modules

What does the error messages say?

**Comment by irreverentperson** [comment]
I installed them in thonny because I was getting import error no module
named ... now I get that error when I run the same code in terminal.

**Comment by aivarannamaa** [comment]
What do you see when you go to "Tools => Options => Interpreter"?

Did you open terminal from Thonny (Tools => Open system shell) or from System menu?

Which Thonny version are you using?

**Comment by irreverentperson** [comment]
Tools options interpreter says

 "the same interpreter which runs thonny.
Details
 /usr/bin/python3"

I open thonny by saving a .py from the terminal then I click on the file
and it automatically opens thonny.

It is thonny.desktop @29:1

**Comment by aivarannamaa** [comment]
In recent Thonny versions, "Manage packages" dialog displays installation location for each package. Where are the problematic modules installed?

**Comment by irreverentperson** [comment]
Sorry, I wiped the pi and started over. Removed thonny.
