### ISSUE TITLE
An issue of editor

### ISSUE THREAD

**Issue by rnLIKEm** [thonny/thonny#948]
Hey man,see the picture below,is it a bug?
![1](https://user-images.githubusercontent.com/52340898/66993560-57fbf400-f0fe-11e9-997b-4e949d62383b.png)
I really don't like the 'i'have two styles...
but keywords have two styles can be accepted.

**Comment by aivarannamaa** [comment]
Thonny displays local variables in italic (to emphasize that variable `g` at line 1 in your example is different from variable `g` at line 4).

If you don't like it then you can turn it off from Tools => Options => Editor
