### ISSUE TITLE
Request for "Auto Completion" in Thonny

### ISSUE THREAD

**Issue by travelling-north** [thonny/thonny#956]
Please integrate the "Auto-Completion" feature in Thonny, as it'll make the coding experience more convenient and time-efficient.

Problem #2: when we run the code it creates a new space in the shell instead of adding the new edit to the result. please fix it.

![thonny screeen shot](https://user-images.githubusercontent.com/56908016/67361973-a9d1cd80-f587-11e9-8bf1-171a40b519f8.JPG)

**Comment by aivarannamaa** [comment]
Thonny does have code completion feature (invoked by Tab or Ctrl+Space). First invocation may be slow.

I did not understand your second problem.

**Comment by Codes-and-games** [comment]
What the hell is going on here
If you have problem then switch to another IDE like VS code or Pycharm

**Comment by atesin** [comment]
> What the hell is going on here
> If you have problem then switch to another IDE like VS code or Pycharm

that was a very lazy, unkind and angry response...  i think all we are here for enhance thonny, nothing bad with reporting issues or suggesting features humbly

**Comment by dgoadby** [comment]
I agree with atesin. Whilst code completion is not easy to implement and may never be a feature, the response was not in the spirit of open source projects like this. That said, travelling-north's very curt "please fix it." was a bit harsh too. Maybe it was this that triggered the response. Personally I have to use Thonny for my RPi Pico projects as my "heavy-lifting" Wing IDE does not cater for it. But, for small projects I find that Thonny is really good.

**Comment by aivarannamaa** [comment]
Proper code completion is at the top of my TODO list.

(Unfortunately, Thonny's TODO list is currently below my family's TODO list, but I'll get there)

**Comment by WaGi-Coding** [comment]
Any news ony that? Currently switched to pycharm, but it's workflow is not that nice beside the intellisense/autocomplete. Thonny is so much more convinient for working with all that boards, but makes my fingers bleeding on my mechanical keyboard without any autocomplete feature ^^

**Comment by aivarannamaa** [comment]
@WaGi-Coding, the latest betas of Thonny 4.0 now have improved autocompletion support. You'll need to tweak "Tools => Options => Editor" for all the goodies.

**Comment by WaGi-Coding** [comment]
> @WaGi-Coding, the latest betas of Thonny 4.0 now have improved autocompletion support. You'll need to tweak "Tools => Options => Editor" for all the goodies.

I'll check it out later, many thanks for letting me know, really missed that feature

**Comment by star-king-droid** [comment]
je n'arrive pas a utiliser l'auto-complétions pour les fonctions pourriez vous m'aider

**Comment by atesin** [comment]
> je n'arrive pas a utiliser l'auto-complétions pour les fonctions pourriez vous m'aider

WRITE IN ENGLISH YOU DAMN #$&(# FRENCHIE

i am a native spanish speaker, but i am aware not everybody knows spanish so i speak (or write) in english to be BETTER UNDERSTOOD, same with french or any another language, chances are most people knows some english instead the variety of any other lang

**Comment by aivarannamaa** [comment]
@atesin, such impolite outbursts are not acceptable here. Indeed, it is implied (but nowhere explicitly stated) that this issue tracker expects submissions in English, but this does not warrant such a response.

**Comment by atesin** [comment]
ok i will fix that by editing the previous comment... i pretended to be funny but is hard to catch with text only

**Comment by penguintheguy** [comment]
Does autocomplete work on python 3.12.2

**Comment by hellmader** [comment]
![image](https://github.com/user-attachments/assets/286b0f0a-d61d-45cf-864a-84d1f7a694ae)

**Comment by penguintheguy** [comment]
But that doesn't work with other python installed version
