### ISSUE TITLE
Thonny 3.2.1 under Catalina 10.15.1

### ISSUE THREAD

**Issue by tatecapone** [thonny/thonny#961]
First, the application does not start without the `sudo xattr -rd com.apple.quarantine` command in the terminal. Secondly, once thonny is open, it is impossible to close it ... and I have to force the exit through the menu bar-> apple-> force the exit.
Thanks!!

**Comment by aivarannamaa** [comment]
Thank you for the report! This seems to be somewhat related to but different from #813.

Did you install Thonny in Catalina or it was installed under previous OS version?

**Comment by tatecapone** [comment]
Thank you for the response!
I just installed thonny, because I found the command `sudo xattr -rd com.apple.quarantine` since before I couldn't ... so I already had Macos Catalina 10.15.1 running ...

**Comment by tatecapone** [comment]
the shell works perfect..there seems to work very well ... for now ...

**Comment by tatecapone** [comment]
oooops!  Thonny close perfectly with the x button....
I think you can close this issue.
really, really sorry for this wasted time.
Thanks!!

**Comment by aivarannamaa** [comment]
I'll leave it open for now, because it contains useful information.

**Comment by tatecapone** [comment]
So, until now, the only problem is that it does not open without the above-mentioned command via the terminal.
Ok...Thanks aivarannamaa!!
Best regards!

**Comment by aivarannamaa** [comment]
Please try, whether https://github.com/thonny/thonny/releases/download/v3.2.6/thonny-3.2.6.pkg fixes the problem. 

#79

**Comment by aivarannamaa** [comment]
Ouch, it doesn't work in a clean system (ie. without preinstalled Python). I'll deal with it.

**Comment by aivarannamaa** [comment]
Assuming this got fixed after introducing pkg installer
