### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [thonny/thonny#968]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing thonny on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by aivarannamaa** [comment]
I prefer to focus on core development myself, but I welcome anyone else who wants to do this.

**Comment by jwillikers** [comment]
I'll look into this, though I know a Thonny maintainer should make the actual PR to Flathub since that will grant the submitter write-access to the Flathub Thonny repository.

**Comment by aivarannamaa** [comment]
@jwillikers, if you prepare the code, then I can submit the PR if required.

**Comment by jwillikers** [comment]
I've started working on a `Devel` Flatpak manifest for building Flatpaks locally.
The Flathub repository will end up hosting a pretty similar manifest.
There's some issues that need worked out to build the Python dependencies, so I'll start poking upstream / checking back to see if they get resolved when I have time.
