### ISSUE TITLE
Thonny Greek Translation issues

### ISSUE THREAD

**Issue by niplessa** [thonny/thonny#988]
Hello. 
I'm translating Thonny in Greek language as a project for my university.

I have these issues:

1) "**Options**" window is too narrow and doesn't show all the tabs . 
Screenshot:
![options](https://user-images.githubusercontent.com/52243102/68846823-565e2580-06d6-11ea-90c8-f53cc87695c3.PNG)

2) There is a "**Device**" tab that doesn't exist in POeditor and i can't translate it. 
My supervising professor suggested that it is deprecated and won't be used in future versions so it is not on POeditor on purpose.
Screenshot:
![device](https://user-images.githubusercontent.com/52243102/68847002-93c2b300-06d6-11ea-81b8-23a3e3e6190a.PNG)

3) My professor is using Thonny on MAC. In his version of Thonny there is a menu "**Thonny**" left of the "File" Menu. I can't see the "Thonny" menu neither in 3.2.1 or 3.2.3 editions in Windows.
Screenshot:
![MAC](https://user-images.githubusercontent.com/52243102/68847638-a8537b00-06d7-11ea-8a4d-b379cb1b610a.png)

Apart from the above mentioned issues, our translation is ready. Although i don't know how to make a pull request with my .po & .mo files.

Thank you very much,
Nikos Plessas

**Comment by niplessa** [comment]
anyone?

**Comment by aivarannamaa** [comment]
> "Options" window is too narrow and doesn't show all the tabs .

Thanks for reporting, I'll make it wider.

> There is a "Device" tab that doesn't exist in POeditor and i can't translate it.
> My supervising professor suggested that it is deprecated and won't be used in future versions so it is not on POeditor on purpose.

That's correct.

> I can't see the "Thonny" menu neither in 3.2.1 or 3.2.3 editions in Windows.

"Thonny" menu is supposed to exist only on macOS, as all apps on this OS traditionally have this kind of "Application menu".

> Apart from the above mentioned issues, our translation is ready.  Although i don't know how to make a pull request with my .po & .mo files.

I already took the translation from Poeditor and included it in 3.2.3: https://github.com/thonny/thonny/releases/tag/v3.2.3
You don't need to do anything else.

**Comment by aivarannamaa** [comment]
It turned out the dialog becomes too wide when I try to fit all Greek labels. I'll solve this issue later when I refactor the dialog (#730)
