### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by jianyuhe** [thonny/thonny#992]
![image](https://user-images.githubusercontent.com/32126454/68997419-1a75bc80-089e-11ea-9f38-a3b9c721d37e.png)

**Comment by aivarannamaa** [comment]
How did it happen? Please copy the error as text (see the button "Copy to clipboard")

**Comment by jianyuhe** [comment]
when I save file or run file it will show the error, and i was change code in notpad++ when I open thonny it will not update code still shows old code. 
I uninstall thonny and install newest vision, then it is working now.
