### ISSUE TITLE
Installing Git

### ISSUE THREAD

**Issue by prkundan** [thonny/thonny#997]
I want to install Git in Thonny. Please guide me.

**Comment by aivarannamaa** [comment]
I'm afraid you have misunderstood something. Git is not related to Thonny or Python in this way.

**Comment by prkundan** [comment]
I mean Git for version Control.  https://git-scm.com/

**Comment by aivarannamaa** [comment]
I meant the same. I don't see any meaning in "install Git in Thonny"
