### ISSUE TITLE
writing characters over 7 bits makes two characters on disk

### ISSUE THREAD

**Issue by chrisdekort** [thonny/thonny#999]
Hi, I am a newbie in Phyton Thonny an I already have a question.
when writing to a file I encounter following problem: (see print screen)
when writing a char over 127 like  chr(128) etc it writes 2 char to disk?
for instance chr(127) gives a 7F in the file but chr(128) gives a C2 80 in the file?
The 80 I understand but C2 80? What am I doing wrong?
<img width="1865" alt="Schermafbeelding 2019-11-22 om 15 30 37" src="https://user-images.githubusercontent.com/58078358/69434603-41207100-0d3e-11ea-9c61-2b0da7373442.png">

**Comment by aivarannamaa** [comment]
You are probably saving with UTF-8 encoding, and in this encoding only ASCII chars (ie. chars up to code 127) are written with one byte.

BTW. This is not a Thonny specific question.

**Comment by chrisdekort** [comment]
thanks for your quick response. Sorry for not knowing but how do I save the file correctly?

**Comment by aivarannamaa** [comment]
> how do I save the file correctly?

Depends on what you want to achieve. I would say using utf-8 encoding is nowadays the correct way for storing text.

**Comment by chrisdekort** [comment]
if I want to write up to 255 (FF) as one char to the file.

**Comment by aivarannamaa** [comment]
Then you need to write bytes, not chars. For Python 2 these are the same but not for Python 3.

You need to open file in binary mode (`"bw"`) and use `bytes([...])` instead of `chr(...)`:

```
>>> chr(127)+chr(128)
'\x7f\x80'
>>> bytes([127])+bytes([128])
b'\x7f\x80'
```

**Comment by aivarannamaa** [comment]
... the easiest is to collect all numbers to a list before converting to bytes:

```
>>> bytes([127, 128])
b'\x7f\x80'
```

**Comment by chrisdekort** [comment]
Thank you so much 👍😀. life can sometimes be so simple with the right help!
